Перевод Upstream #1002
space-syndicate/space-station-14 pull request #1004
Opened 2023-04-19 12:41 UTC by lapatison

## Описание PR

**Медиа**

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:
- add: Добавлены переводы

2023-04-20 22:39 UTC, Morb0 requested changes

2023-04-20 22:39 UTC, Morb0 commented on Resources/Locale/ru-RU/xenoarchaeology/artifact-analyzer.ftl
> +analysis-console-destroy-button = Извлечь О.И.
ИО звучит так себе

2023-04-20 22:39 UTC, Morb0 commented on Resources/Locale/ru-RU/ninja/ninja-actions.ftl
> +       *[other] кредитов
Тут кажется что-то не так

2023-04-20 23:24 UTC, lapatison commented on Resources/Locale/ru-RU/xenoarchaeology/artifact-analyzer.ftl
> +analysis-console-destroy-button = Извлечь О.И.
А `очки исследований` - длинно

2023-04-21 18:25 UTC, Morb0 commented on Resources/Locale/ru-RU/xenoarchaeology/artifact-analyzer.ftl
> +analysis-console-destroy-button = Извлечь О.И.
Как по мне Разрушить подходит, особенно если есть уточняющее описание, просто `Извлечь` ничего не говорит.

2023-04-21 18:28 UTC, lapatison commented on Resources/Locale/ru-RU/xenoarchaeology/artifact-analyzer.ftl
> +analysis-console-destroy-button = Извлечь О.И.
Только артефакт теперь не разрушается, только обнуляется ценность, нелогично

2023-04-22 07:59 UTC, Morb0 commented on Resources/Locale/ru-RU/xenoarchaeology/artifact-analyzer.ftl
> +analysis-console-destroy-button = Извлечь О.И.
Нужно тогда и в гайде изменить это

2023-04-22 12:01 UTC, lapatison commented on Resources/Locale/ru-RU/xenoarchaeology/artifact-analyzer.ftl
> +analysis-console-destroy-button = Извлечь О.И.
Я могу обновить гайд со следующим переводом апстрима, чтобы не тянуть время.
Ну или этой ночью

2023-04-22 12:21 UTC, Morb0 approved these changes

2023-04-22 12:21 UTC, merged