New tabletop RPG rulebook
space-syndicate/space-station-14 pull request #1008
Opened 2023-04-20 15:14 UTC by lapatison

## Описание PR

Адаптация (перевод, перефразирование, дополнение) книги правил Stations and Syndicates 9th Edition с Goonstation.
Сама SaS основана на системе Quick Quest, с небольшими изменениями.

Исходная игра сделана юзером GiffyGlyph, и может быть найдена по ссылке: https://giffyglyph.com/#giffyglyphs-quick-quest или https://github.com/giffyglyph/giffyglyphs-quick-quest, и распространяется под лицензией [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/).

**Медиа**

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** **этот PR этого не требует.**

**Изменения**

:cl:
- add: торгомат настольных игр пополнился новой настольной ролевой игрой!

2023-04-22 15:04 UTC, Morb0 requested changes
Книгу нужно выделить в папку Corvax

2023-04-22 15:06 UTC, lapatison commented
> Книгу нужно выделить в папку Corvax

Ты про спрайт?

2023-04-22 16:24 UTC, Morb0 commented
> > Книгу нужно выделить в папку Corvax
> 
> Ты про спрайт?

Да

2023-04-23 13:44 UTC, lapatison commented
Готово

2023-04-27 21:18 UTC, Morb0 requested changes

2023-04-27 21:18 UTC, Morb0 commented on Resources/Textures/Objects/Misc/books.rsi/meta.json
> +  "copyright": "Taken from tgstation at commit https://github.com/tgstation/tgstation/commit/856e0a784abd19d20618aa36b26b73d471adf613, book_stationsagents taken from goonstation at commit https://git
Откатить нужно все изменения в этом файле, если перенесли в новый

2023-04-27 21:20 UTC, lapatison commented on Resources/Textures/Objects/Misc/books.rsi/meta.json
> +  "copyright": "Taken from tgstation at commit https://github.com/tgstation/tgstation/commit/856e0a784abd19d20618aa36b26b73d471adf613, book_stationsagents taken from goonstation at commit https://git
Готово

2023-04-27 21:28 UTC, Morb0 approved these changes

2023-04-27 21:28 UTC, merged