[Items] Pins (lore moment)
space-syndicate/space-station-14 pull request #1037
Opened 2023-04-30 12:25 UTC by nomad0260

## Описание PR

Добавляет значки корпораций и государств из лора
**Медиа**

![Untitled_04-30-2023_06-42-04_11](https://user-images.githubusercontent.com/110369449/235352866-6817ebeb-3ce8-492c-a0ec-8ad5be0ca658.png)
![Untitled_04-30-2023_06-42-04_9](https://user-images.githubusercontent.com/110369449/235352867-0ef70e13-fb4e-4d17-a445-64a683a14622.png)
![Untitled_04-30-2023_06-42-04_8](https://user-images.githubusercontent.com/110369449/235352868-e5d64e62-699e-43b0-9f49-7d5653dc30c4.png)
![Untitled_04-30-2023_06-42-04_6](https://user-images.githubusercontent.com/110369449/235352870-1fd227b6-f0b9-42fc-aa22-6c7d6129c12b.png)

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: no_mad
- add: Добавлены значки корпораций и государств

2023-04-30 16:56 UTC, Morb0 requested changes
Все в отдельные папки Corvax

2023-05-01 02:12 UTC, nomad0260 commented
> Все в отдельные папки Corvax

Даже спавнеры?
Тогда и толку от этого особо не будет, если их никто кроме как ивентов не увидит

2023-05-10 16:01 UTC, Morb0 commented on Resources/Prototypes/Entities/Markers/Spawners/Random/maintenance.yml
> +        - ClothingNeckVitezstviPin #Corvax-Pins
```suggestion
        # Corvax-Pins-Start
        - ClothingNeckUSSPPin
        - ClothingNeckDonkPin
        - ClothingNeckEarthPin
        - ClothingNeckLogistikaPin
        - ClothingNeckDeForestPin
        - ClothingNeckNakamuraPin
        - ClothingNeckNanoTrasenPin
        - ClothingNeckSyndicakePin
        - ClothingNeckVitezstviPin
        # Corvax-Pins-End
```

2023-05-20 19:18 UTC, Morb0 approved these changes

2023-05-20 20:15 UTC, merged