Крутящиеся лампы
space-syndicate/space-station-14 pull request #1047
Opened 2023-05-04 06:24 UTC by SonicHDC

## Описание PR

Возвращает кручение лампам. Они теперь снова стоят на ножке, что чинит визуальные баги на картах. Также мапперы смогут устанавливать лампы в стороны и это будет смотреться красиво.
**Медиа**

![image](https://user-images.githubusercontent.com/100022571/236123071-842da34b-eda4-42f6-b8a0-93ba014596e0.png)
**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: SonicDC
- add: Лампы теперь крутятся через ПКМ!
- tweak: Лампы снова крутятся!

2023-05-06 07:51 UTC, Morb0 requested changes

2023-05-06 07:51 UTC, Morb0 commented on Resources/Textures/Objects/Misc/Lights/lamp.rsi/meta.json
> +  "copyright": "Taken from tgstation at https://github.com/tgstation/tgstation/commit/fb020482a6737372d5b8f2b603d58737b22b0270",
Добавь и в другие файлы
```suggestion
  "copyright": "Taken from tgstation at https://github.com/tgstation/tgstation/commit/fb020482a6737372d5b8f2b603d58737b22b0270, directional sprites by SonicDC#9046",

```

2023-05-06 08:20 UTC, SonicHDC commented
Готово

2023-05-09 06:28 UTC, SonicHDC commented
Обновление ПРа.
Лампы будут смотреться нормально в руках.
Теперь лампы на картах будут направлены в задуманную мапперами сторону.

2023-05-11 22:43 UTC, ficcialfaint approved these changes

2023-05-12 08:05 UTC, ficcialfaint approved these changes

2023-05-12 08:06 UTC, Morb0 approved these changes

2023-05-12 08:08 UTC, merged