Update health-examinable-carbon.ftl
space-syndicate/space-station-14 pull request #109
Opened 2022-02-23 11:08 UTC by lapatison

## Описание PR 
Добавлена часть перевода.

**Скриншоты**

**Изменения**

:cl: lapatison
- add: Добавлен частичный перевод.

2022-02-23 13:06 UTC, Morb0 commented
Нужно удалить функции `SUBJECT`, `CONJUGATE-HAVE` и `POSS-ADJ`. Они для расставления приставок на английском.

2022-02-24 05:32 UTC, Morb0 approved these changes

2022-02-24 07:58 UTC, Morb0 requested changes

2022-02-24 07:58 UTC, Morb0 commented on Resources/Locale/ru-RU/health-examinable/health-examinable-carbon.ftl
> +health-examinable-carbon-Slash-50 = [color=crimson]{ CAPITALIZE($target) } имеет множествво сильных порезов![/color]
```suggestion
health-examinable-carbon-Slash-50 = [color=crimson]{ CAPITALIZE($target) } имеет множество сильных порезов![/color]
```

2022-02-24 07:58 UTC, Morb0 commented on Resources/Locale/ru-RU/health-examinable/health-examinable-carbon.ftl
> +health-examinable-carbon-Slash-75 = [color=crimson]Тело { CAPITALIZE($target) } сильно изрезано![/color]
Было бы неплохо привести к одному формату все сообщения.
Мое предложение, например:
`{ CAPITALIZE($target) } имеет множество глубоких порезов на теле!`

2022-02-24 12:59 UTC, lapatison commented
Поправил 8 + переделал 9

2022-02-24 16:36 UTC, Morb0 approved these changes

2022-02-24 16:38 UTC, merged