[Resprite] Better tanks
space-syndicate/space-station-14 pull request #1095
Opened 2023-05-25 06:40 UTC by SonicHDC

## Описание PR

Добавляет мелкое окошко для жидкостных хранилищ.
**Медиа**

![watercooler](https://github.com/space-syndicate/space-station-14/assets/100022571/490bf2a2-1458-4695-967b-067006c1aa21)
![watertank](https://github.com/space-syndicate/space-station-14/assets/100022571/bc5f960c-169a-4d52-9fcc-732c979e30e0)
![highwatertank](https://github.com/space-syndicate/space-station-14/assets/100022571/1e10a4bd-4a1e-471c-80b9-0c99cf972835)
![fueltank](https://github.com/space-syndicate/space-station-14/assets/100022571/8971540b-32e4-47d4-8f2d-d1eda09d9e53)
![highfueltank](https://github.com/space-syndicate/space-station-14/assets/100022571/cc66801b-7550-4734-868a-950c8fe2b696)

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [-] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: SonicDC
- add: Добавлено окошко в жидкостных танках!

2023-05-25 07:37 UTC, lzk228 commented
![image](https://github.com/space-syndicate/space-station-14/assets/124214523/f20771df-ac45-4ff4-9ed4-9e080f3ba32a)
собственно как и предполагалось

2023-05-25 10:25 UTC, KIBORG04 commented
Где дифф с изменённым авторством

2023-05-25 10:33 UTC, PuroSlavKing commented
> Где дифф с изменённым авторством

Он впринцепе никогда его и не меняет :trollface:

2023-05-25 11:15 UTC, KIBORG04 commented
Он же новые спрайты добавляет, а не меняет тгшные.. Там другой билд автор...

2023-05-25 18:05 UTC, Morb0 commented
Я не думаю, что вода должна быть зелёной, а топливо краснее.

2023-05-27 07:20 UTC, ficcialfaint commented
> > Я не думаю, что вода должна быть зелёной, а топливо краснее.
> > Возможно стоит попробовать оригинальные цвета жидкости для продвинутых версий.
> 
> Это лишь пример, теперь пофикшино под цвет жидкости.

Так они вообще не должны быть цветные, они красятся в зависимости от реагента автоматически

2023-05-27 07:26 UTC, SonicHDC commented
> > > Я не думаю, что вода должна быть зелёной, а топливо краснее.
> > > Возможно стоит попробовать оригинальные цвета жидкости для продвинутых версий.
> > 
> > Это лишь пример, теперь пофикшино под цвет жидкости.
> 
> Так они вообще не должны быть цветные, они красятся в зависимости от реагента автоматически

Они и так уже серые и должны краситься. В медиа лишь старый пример с случайными цветами.

2023-05-27 07:31 UTC, ficcialfaint commented
> > > > Я не думаю, что вода должна быть зелёной, а топливо краснее.
> > > > Возможно стоит попробовать оригинальные цвета жидкости для продвинутых версий.
> > > 
> > > Это лишь пример, теперь пофикшино под цвет жидкости.
> > 
> > Так они вообще не должны быть цветные, они красятся в зависимости от реагента автоматически
> 
> Они и так уже серые и должны краситься. В медиа лишь старый пример с случайными цветами.

У тебя даже RSI Diff Bot показывает, что большая часть спрайтов осталась цветная

2023-05-27 07:35 UTC, SonicHDC commented
> > > > > Я не думаю, что вода должна быть зелёной, а топливо краснее.
> > > > > Возможно стоит попробовать оригинальные цвета жидкости для продвинутых версий.
> > > > 
> > > > Это лишь пример, теперь пофикшино под цвет жидкости.
> > > 
> > > Так они вообще не должны быть цветные, они красятся в зависимости от реагента автоматически
> > 
> > Они и так уже серые и должны краситься. В медиа лишь старый пример с случайными цветами.
> 
> У тебя даже RSI Diff Bot показывает, что большая часть спрайтов осталась цветная  

Они серые, просто значки жидкостей остались на баках, поэтому кажется что они цветные, но это не так. Да и если это многим не понравиться, то я могу потом удалить или обесцветить эти логотипы.

2023-05-27 07:44 UTC, ficcialfaint commented
> > > > > > Я не думаю, что вода должна быть зелёной, а топливо краснее.
> > > > > > Возможно стоит попробовать оригинальные цвета жидкости для продвинутых версий.
> > > > > 
> > > > > Это лишь пример, теперь пофикшино под цвет жидкости.
> > > > 
> > > > Так они вообще не должны быть цветные, они красятся в зависимости от реагента автоматически
> > > 
> > > Они и так уже серые и должны краситься. В медиа лишь старый пример с случайными цветами.
> > 
> > У тебя даже RSI Diff Bot показывает, что большая часть спрайтов осталась цветная  
> 
> Они серые, просто значки жидкостей остались на баках, поэтому кажется что они цветные, но это не так. Да и если это многим не понравиться, то я могу потом удалить или обесцветить эти логотипы.

А, всё, понял

2023-05-29 05:07 UTC, lzk228 commented
теперь должно хорошо выглядеть

2023-05-29 17:24 UTC, lzk228 commented
![image](https://github.com/space-syndicate/space-station-14/assets/124214523/1e13fd0e-799b-4214-a52e-b8b21d21a80b)

2023-06-13 20:19 UTC, ficcialfaint commented on Resources/Textures/Structures/Storage/tanks.rsi/meta.json
> +  "copyright": "Taken from tgstation at commit https://github.com/tgstation/tgstation/commit/8442af39ee82b813194f71db82edd2923d97818d, watercooler Taken from paradise at https://github.com/ParadiseSS
```suggestion
  "copyright": "Taken from tgstation at commit https://github.com/tgstation/tgstation/commit/8442af39ee82b813194f71db82edd2923d97818d, watercooler Taken from paradise at https://github.com/ParadiseSS13/Paradise/commit/ae2258d9235752ac6d80ec11e36553fe3b6ae59e. Degree of fullness made by SonicHDC (GitHub)",
```

2023-06-13 20:56 UTC, ficcialfaint commented on Resources/Textures/Structures/Storage/tanks.rsi/meta.json
> -  "copyright": "Taken from tgstation at commit https://github.com/tgstation/tgstation/commit/8442af39ee82b813194f71db82edd2923d97818d, watercooler Taken from paradise at https://github.com/ParadiseSS
а почему мета старая?

2023-06-14 02:01 UTC, SonicHDC commented on Resources/Textures/Structures/Storage/tanks.rsi/meta.json
> -  "copyright": "Taken from tgstation at commit https://github.com/tgstation/tgstation/commit/8442af39ee82b813194f71db82edd2923d97818d, watercooler Taken from paradise at https://github.com/ParadiseSS
Слегка напутал, уже поправил

2023-06-14 02:36 UTC, ficcialfaint requested changes

2023-06-14 02:36 UTC, ficcialfaint commented on Resources/Textures/Structures/Storage/tanks.rsi/meta.json
> +        "y": 32
а куда пропала фигурная скобка вторая?

2023-06-14 02:36 UTC, ficcialfaint commented on Resources/Textures/Structures/Storage/tanks.rsi/meta.json
> +  "version": 2,
я бы не стал менять на 2, нигде не видел, чтобы использовали что-то, кроме 1

2023-06-14 23:42 UTC, SonicHDC commented on Resources/Textures/Structures/Storage/tanks.rsi/meta.json
> +	  "delays": [
Напутал немного

2023-06-15 11:41 UTC, SonicHDC commented
> Много тестов фейлятся, исправь.

Исправленно

2023-06-20 08:47 UTC, SonicHDC commented on Resources/Textures/Structures/Storage/tanks.rsi/meta.json
> +      ]
Спрайт кулера самого мигает в 2 кадра

2023-06-24 07:31 UTC, lzk228 approved these changes

2023-06-25 03:26 UTC, SonicHDC commented
Удивительно, но ошибки пропали все сразу

2023-06-28 14:54 UTC, ficcialfaint commented on Resources/Textures/Structures/Storage/tanks.rsi/meta.json
> +  "copyright": "Taken from tgstation at commit https://github.com/Skyrat-SS13/Skyrat-tg/commit/44cfb65dece652f7e1b200f5774732d5555ce82f, hightwattertank recolored by Morty. Degree of fullness made by
Первая ссылка неправильная, почему она ведет на `Automatic changelog compile`?

2023-06-28 22:42 UTC, SonicHDC commented on Resources/Textures/Structures/Storage/tanks.rsi/meta.json
> +  "copyright": "Taken from tgstation at commit https://github.com/Skyrat-SS13/Skyrat-tg/commit/44cfb65dece652f7e1b200f5774732d5555ce82f, hightwattertank recolored by Morty. Degree of fullness made by
Нет, просто первая это ссылка на оффициальные спрайты. А это наша ссылка на корвакские спрайты.

2023-06-29 23:24 UTC, ficcialfaint commented on Resources/Textures/Structures/Storage/tanks.rsi/meta.json
> +  "copyright": "Taken from tgstation at commit https://github.com/Skyrat-SS13/Skyrat-tg/commit/44cfb65dece652f7e1b200f5774732d5555ce82f, hightwattertank recolored by Morty. Degree of fullness made by
а, я походу криво скопировал или что-то, но щас у меня нужный коммит открылся

2023-06-29 23:24 UTC, ficcialfaint approved these changes

2023-06-29 23:28 UTC, merged