Перевод Upstream #1094
space-syndicate/space-station-14 pull request #1096
Opened 2023-05-25 19:00 UTC by lapatison

## Описание PR

**Медиа**

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:
- add: Добавлены переводы

2023-05-25 19:09 UTC, lapatison commented
Лучше мержить после #1091

2023-05-26 04:30 UTC, ficcialfaint commented
> Лучше мержить после #1091

pro tip: в описании ПРа можно указать `Requires #1091`, таким образом тесты будут проходить вместе с указанным ПРом

2023-05-26 12:00 UTC, lapatison commented
> > Лучше мержить после #1091
> 
> pro tip: в описании ПРа можно указать `Requires #1091`, таким образом тесты будут проходить вместе с указанным ПРом

Спасибо, я только про resolves знал

2023-05-27 14:18 UTC, Morb0 requested changes

2023-05-27 14:18 UTC, Morb0 commented on Resources/Locale/ru-RU/station-events/events/cargo-gifts.ftl
> +cargo-gifts-event-announcement = Поздравляем! { $sender } решили отправить { $description } { $dest } станции. Look for it in your next cargo shipment.
Не переведено: `Look for it in your next cargo shipment.`

2023-05-27 17:10 UTC, lapatison commented
![image](https://github.com/space-syndicate/space-station-14/assets/100279397/4111a0cb-037b-4fe9-86c0-98a3c6eb5748)
без капитализации лучше

2023-05-27 17:17 UTC, ficcialfaint commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/weapons/melee/knife.ftl
> +    .desc = Грубое оружие, сделанное из куска ткани и осколка уранового стекла.
Здесь же просто `осколок плазмы` и `осколок урана`

2023-05-27 17:17 UTC, ficcialfaint commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/machines/vending_machines.ftl
> +    .desc = Лучшее место чтобы насладиться холодом!
```suggestion
    .desc = Лучшее место, чтобы насладиться холодом!
```

2023-05-27 18:48 UTC, lapatison commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/weapons/melee/knife.ftl
> +    .desc = Грубое оружие, сделанное из куска ткани и осколка уранового стекла.
Ошибка в оригинале

2023-05-27 18:49 UTC, lapatison commented on Resources/Locale/ru-RU/advertisements/vending/chefvend.ftl
> +advertisement-chefvend-4 = Стоите ли вы своих денег? Мы да.
Совсем не русская идиома, но пускай

2023-05-28 05:57 UTC, ficcialfaint approved these changes

2023-05-28 05:59 UTC, merged