Перевод подсказок
space-syndicate/space-station-14 pull request #1108
Opened 2023-05-31 19:38 UTC by lzk228

## Описание PR

**Медиа**

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: lzk
- add: Добавлены переводы!
- fix: Исправлены переводы!

2023-06-02 10:25 UTC, ficcialfaint commented
Почему здесь помимо подсказок что-то ещё переведено?

2023-06-02 11:13 UTC, lzk228 commented
> Почему здесь помимо подсказок что-то ещё переведено?

поправил

2023-06-02 11:33 UTC, ficcialfaint requested changes

2023-06-02 11:33 UTC, ficcialfaint commented on Resources/Prototypes/Datasets/tips.yml
> +    - "Будучи предателем, помните о силе разрушения телекоммуникаций. Людям будет гораздо сложнее обвинить вас, если они не смогут общатся с другими на больших расстояниях!"
```suggestion
    - "Будучи предателем, помните о силе разрушения телекоммуникаций. Людям будет гораздо достать вас, если они не смогут общатся с другими на больших расстояниях!"
```

2023-06-02 11:33 UTC, ficcialfaint commented on Resources/Prototypes/Datasets/tips.yml
> +    - "Будучи предателем, плазма в газообразном виде - отличный способ создать хаос. Её можно поджечь, чтобы сделать область непригодной для жизни, и может вызвать отравление токсинами тем, кто её вд
```suggestion
    - "Будучи предателем, плазма в газообразном виде - отличный способ навести хаос. Её можно поджечь, чтобы сделать область непригодной для жизни, плазма также может отравлять токсинами тех, кто её вдыхает."
```

2023-06-02 11:33 UTC, ficcialfaint commented on Resources/Prototypes/Datasets/tips.yml
> +    - "Будучи ядерным оперативником, помните о скрытном варианте. Капитану будет сложнее отбится, если его застанет врасплох тот, кого он считает обычным пассажиром."
```suggestion
    - "Будучи ядерным оперативником, помните о скрытном варианте. Капитану будет сложнее отбиться, если его застанет врасплох тот, кого он считает обычным пассажиром."
```

2023-06-02 11:33 UTC, ficcialfaint commented on Resources/Prototypes/Datasets/tips.yml
> +    - "Будучи грузчиком, помните, что вы можете заказать оружие в экстренной ситуации! The extra firepower can often be the difference between you and your fellow crewmembers living or dying."
```suggestion
    - "Будучи грузчиком, помните, что вы можете заказывать оружие в экстренных ситуациях! Дополнительная огневая мощь часто может быть разницей между вами и другими членами экипажа, живущими или умирающими."
```

2023-06-02 11:33 UTC, ficcialfaint commented on Resources/Prototypes/Datasets/tips.yml
> +    - "Будучи грузчиком, старайтесь сохранять некоторое количество материалов. Это чрезвычайно полезно, когда они немедленно потребуются Учёным или Инженерам."
```suggestion
    - "Будучи грузчиком, старайтесь поддерживать избыток материалов. Это чрезвычайно полезно, когда они срочно потребуются учёным или инженерам."
```

2023-06-02 11:33 UTC, ficcialfaint commented on Resources/Prototypes/Datasets/tips.yml
> +    - "Будучи утилизатором, учитывайте сотрудничество с Грузчиками. Они могут заказать вам самые разные полезные предметы, в том числе те, которые может быть трудно получить другим способом, такие ка
```suggestion
    - "Будучи утилизатором, сотрудничайте с грузчиками. Они могут заказать вам самые разные полезные предметы, в том числе те, которые будет трудно получить другим способом, такие как лазерные пушки и строительные материалы для шаттлов."
```

2023-06-02 11:33 UTC, ficcialfaint commented on Resources/Prototypes/Datasets/tips.yml
> +    - "Будучи утилизатором, не забывайте копать руду! Руда может быть продана в карго за неплохие деньги, использована для строительства, а также использоваться Учёными для причудливых технологий."
```suggestion
    - "Будучи утилизатором, не забывайте копать руду! Руда может быть продана в карго за неплохие деньги, использована для строительства, а также учёными для причудливых технологий."
```

2023-06-02 11:33 UTC, ficcialfaint commented on Resources/Prototypes/Datasets/tips.yml
> +    - "Будучи утилизатором, вы можете использовать протокинетический ускоритель для передвижения в космосе. Просто знайте, что это не очень эффективно."
```suggestion
    - "Будучи утилизатором, в крайнем случае вы можете использовать протокинетический ускоритель для передвижения в космосе. Просто знайте, что это не очень эффективно."
```

2023-06-02 11:33 UTC, ficcialfaint commented on Resources/Prototypes/Datasets/tips.yml
> +    - "Будучи инженером, вы можете использовать плазменное стекло для для укрепления местности и предотвращения радиации. Урановое стекло так же может быть использовано для защиты от радиации."
```suggestion
    - "Будучи инженером, вы можете использовать плазменное стекло для укрепления местности и защиты от радиации. Урановое стекло может быть тоже использовано для защиты от радиации."
```

2023-06-02 11:33 UTC, ficcialfaint commented on Resources/Prototypes/Datasets/tips.yml
> +    - "Будучи атмосферным техником, постарайтесь сопротивлятся искушению сделать канистровые бомбы против ядерных оперативников, до тех пор, пока у вас не будет другого выхода. Этим вы можете нанести
```suggestion
    - "Будучи атмосферным техником, постарайтесь сопротивлятся искушению использовать канистровые бомбы против ядерных оперативников, до тех пор, пока у вас не будет другого выхода. Этим вы можете нанести много ненужного урона по союзникам."
```

2023-06-02 11:33 UTC, ficcialfaint commented on Resources/Prototypes/Datasets/tips.yml
> +    - "Вместо поднятия, вы можете альт-кликнуть по еде, чтобы кушать её. Это так же работает для мышей и других существ без рук."
```suggestion
    - "Вместо поднятия, вы можете альт-кликнуть по еде, чтобы скушать её. Это так же работает для мышей и других существ без рук."
```

2023-06-02 11:33 UTC, ficcialfaint commented on Resources/Prototypes/Datasets/tips.yml
> +    - "Обезьяны имеют малый шанс быть разумными. УУК!"
Что за УУК?

2023-06-02 11:33 UTC, ficcialfaint commented on Resources/Prototypes/Datasets/tips.yml
> +    - "Вы можете сплавить осколки стекла в стеклянные листы, а плитку в сталь."
```suggestion
    - "Вы можете сплавить осколки стекла в стеклянные листы, а плитки в сталь."
```

2023-06-02 11:33 UTC, ficcialfaint commented on Resources/Prototypes/Datasets/tips.yml
> +    - "Использование сварки без соответствующей защиты, может вызвать повреждение глаз, которое можно вылечить окулином."
```suggestion
    - "Использование сварки без соответствующей защиты для глаз, может вызвать нарушение зрения, которое можно вылечить окулином."
```

2023-06-02 11:33 UTC, ficcialfaint commented on Resources/Prototypes/Datasets/tips.yml
> +    - "В крайнем случае, вы моежете бросать напитки или ёмкости с реагентами позади себя, для создания луж на которых подскользутся ваши преследователи."
```suggestion
    - "В крайнем случае вы можете бросать напитки или другие ёмкости с реагентами позади себя для создания луж, на которых поскользнутся ваши преследователи."
```

2023-06-02 11:33 UTC, ficcialfaint commented on Resources/Prototypes/Datasets/tips.yml
> +    - "Космическая Станция 14 это игра с открытым кодом! Если вы хотите что-то изменить или добавить простой предмет, попробуйте внести вклад в игру. Это не так сложно как вы думаете."
```suggestion
    - "Космическая Станция 14 - это игра с открытым кодом! Если вы хотите что-то изменить или добавить простой предмет, попробуйте внести вклад в игру. Это не так сложно, как вы думаете."
```

2023-06-02 11:33 UTC, ficcialfaint commented on Resources/Prototypes/Datasets/tips.yml
> +    - "Большинство взрывчатки имеет таймер, который вы можете установить через ПКМ меню. В том числе пингвин гренадёр!"
```suggestion
    - "Большинство взрывчаток имеют таймер, который вы можете установить через ПКМ меню. В том числе пингвин гренадёр!"
```

2023-06-02 11:33 UTC, ficcialfaint commented on Resources/Prototypes/Datasets/tips.yml
> +    - "Кровотечение это не шутка! Если вас посдтрелили или вы получили другую серьёзную травму, позаботьтесь о том, чтобы вылечить быстро её вылечить."
```suggestion
    - "Кровотечение не шутка! Если вас посдтрелили или вы получили другую серьёзную травму, позаботьтесь о том, чтобы быстро её вылечить."
```

2023-06-02 11:33 UTC, ficcialfaint commented on Resources/Prototypes/Datasets/tips.yml
> +    - "Пробоины в корпусе требуют несколько секунд для полной разгерметизации. Вы можете использовать это время, чтобы заделать дыру, если достаточно уверены в своих способностях, или просто убежать.
```suggestion
    - "Пробоины в корпусе требуют несколько секунд для полной разгерметизации местности. Вы можете использовать это время, чтобы заделать дыру, если достаточно уверены в своих способностях, или просто убежать."
```

2023-06-02 11:33 UTC, ficcialfaint commented on Resources/Prototypes/Datasets/tips.yml
> +    - "Имея дело с службой безопасности, вы часто можете полностью отменить свой приговор за счет сотрудничества и обмана."
```suggestion
    - "Имея дело со службой безопасности, вы часто можете избежать своего приговора за счёт сотрудничества или обмана."
```

2023-06-02 11:52 UTC, lzk228 commented on Resources/Prototypes/Datasets/tips.yml
> +    - "Будучи предателем, помните о силе разрушения телекоммуникаций. Людям будет гораздо сложнее обвинить вас, если они не смогут общатся с другими на больших расстояниях!"
прочти ещё раз что ты предложил

2023-06-02 12:09 UTC, lzk228 commented on Resources/Prototypes/Datasets/tips.yml
> +    - "Обезьяны имеют малый шанс быть разумными. УУК!"
звук обезьяны, смотри оригинальную строку

2023-06-02 12:12 UTC, lzk228 commented on Resources/Prototypes/Datasets/tips.yml
> +    - "Будучи предателем, помните силу подозрительного ящика для инструментов. Всего за 4 телекристалла, вы можете получить полный набор инструментов, которые помогут вам в экстренной ситуации, наряд
чёрный тулбокс, называется "подозрительный ящик для инструментов"

2023-06-04 20:27 UTC, ficcialfaint requested changes

2023-06-04 20:27 UTC, ficcialfaint commented on Resources/Prototypes/Datasets/tips.yml
> +    - "Вы можете пшикать огнетушителем, бросать вещи или стрелять с оружия, когда летаете в космосе, чтобы получить незначительное ускорение. Просто стреляйте в противоположную сторону, от той куда в
```suggestion
    - "Вы можете пшикать огнетушителем, бросать вещи или стрелять из оружия, когда летаете в космосе, чтобы получить незначительное ускорение. Просто стреляйте в противоположную сторону от той, куда вам нужно попасть."
```

2023-06-04 20:27 UTC, ficcialfaint commented on Resources/Prototypes/Datasets/tips.yml
> +    - "Противогаз синдиката блокирует свет от вспышек, это означает, что Ядерные Оперативники и другие сомнительные личности, которые носят его, не могут быть ослеплены."
```suggestion
    - "Противогаз Синдиката блокирует свет от вспышек, что означает, что Ядерные Оперативники и другие сомнительные личности, которые носят его, не могут быть ослеплены."
```

2023-06-04 20:27 UTC, ficcialfaint commented on Resources/Prototypes/Datasets/tips.yml
> +    - "Как и в любой другой работе, кроме утилизаторво, обычно разумно избегать использование скафандров, если они вам не нужны, поскольку замедленние, которое они вызывают, часто гораздо более вредн
```suggestion
    - "Как и в любой другой работе, кроме утилизатора, обычно разумно избегать использование скафандров, если они вам не нужны, поскольку замедленние, которое они вызывают, часто гораздо более вредно, чем любое сопротивление или защита от космоса, которое вы можете получить."
```

2023-06-04 20:27 UTC, ficcialfaint commented on Resources/Prototypes/Datasets/tips.yml
> +    - "Большинство работ имеют альтернативную униформу в шкаф-автоматах. Не бойтесь попробовать новый стиль!"
```suggestion
    - "Большинство работ имеют альтернативную униформу в шкаф-автоматах. Не бойтесь опробовать новый стиль!"
```

2023-06-04 20:27 UTC, ficcialfaint commented on Resources/Prototypes/Datasets/tips.yml
> +    - "Вы можете наполнить ранцевый резервуар напалмом, для создания огнемёта."
```suggestion
    - "Вы можете наполнить ранцевый водяной резервуар напалмом для создания огнемёта."
```

2023-06-04 20:27 UTC, ficcialfaint commented on Resources/Prototypes/Datasets/tips.yml
> +    - "Заточки и копья сделанны с уранового стекла, могут наносить радиационный урон, который требует лекарства для правильного лечения."
```suggestion
    - "Заточки и копья, сделанные с уранового стекла, могут наносить радиационный урон, который требует лекарства для правильного лечения."
```

2023-06-04 20:27 UTC, ficcialfaint commented on Resources/Prototypes/Datasets/tips.yml
> +    - "Бросайте копья для нанесения дополнительного урона! Однако, будьте осторожны, так как если вы будете бросать их слишком часто, они могут сломатся."
```suggestion
    - "Бросайте копья для нанесения дополнительного урона! Однако, будьте осторожны, так как, если вы будете бросать их слишком часто, они могут сломаться."
```

2023-06-04 20:27 UTC, ficcialfaint commented on Resources/Prototypes/Datasets/tips.yml
> +    - "Вы можете создать копья с осколков армированного, плазменного и уранового стекла для увеличения урона."
```suggestion
    - "Вы можете создать копья с осколков броне-, плазменного и уранового стекла для увеличения урона."
```

2023-06-04 20:27 UTC, ficcialfaint commented on Resources/Prototypes/Datasets/tips.yml
> +    - "Копья могут быть обработаны химикатами, и будут вводить несколько юнитов каждый раз, когда вы бьёте кого-то напрямую."
```suggestion
    - "Копья могут быть обработаны химикатами и будут вводить несколько юнитов каждый раз, когда вы бьёте кого-то напрямую."
```

2023-06-04 20:27 UTC, ficcialfaint commented on Resources/Prototypes/Datasets/tips.yml
> +    - "В экстренной ситуации, помните, что вы можете создать импровизированое оружие! Бейсбольная бита или копьё могут легко стать решающим фактором между отпугиванием нападающего и гибелью от его ру
```suggestion
    - "В экстренной ситуации помните, что вы можете создать импровизированое оружие! Бейсбольная бита или копьё могут легко стать решающим фактором между отпугиванием нападающего и гибелью от его рук."
```

2023-06-04 20:27 UTC, ficcialfaint commented on Resources/Prototypes/Datasets/tips.yml
> +    - "В экстренной ситуации, не забывайте что пожарные и экстренные ЕВА скафандры всегда находятся в соответствующих шкафчиках. В них может быть неудобно передвигаться, но они могут легко спасти вам
```suggestion
    - "В экстренной ситуации не забывайте, что пожарные и экстренные EVA скафандры всегда находятся в соответствующих шкафчиках. В них может быть неудобно передвигаться, но они могут легко спасти вам жизнь в плохой ситуации!"
```

2023-06-04 20:27 UTC, ficcialfaint commented on Resources/Prototypes/Datasets/tips.yml
> +    - "Технические помещения полны снаряжения, которое будет случайным каждый раунд. Оглянитесь вокруг и посмотрите, стоит ли что-то использовать."
```suggestion
    - "Технические помещения полны снаряжения, которое будет случайным каждый раунд. Оглядывайтесь вокруг и смотрите, стоит ли что-то использовать."
```

2023-06-04 20:27 UTC, ficcialfaint commented on Resources/Prototypes/Datasets/tips.yml
> +    - "Будучи врачом, химиком или главным врачом, Вы можете использовать хлоральгидрат для нелетального успокоения непослушных пациентов."
```suggestion
    - "Будучи врачом, химиком или главным врачом, вы можете использовать хлоральгидрат для нелетального успокоения непослушных пациентов."
```

2023-06-04 20:28 UTC, lzk228 commented on Resources/Prototypes/Datasets/tips.yml
> +    - "Противогаз синдиката блокирует свет от вспышек, это означает, что Ядерные Оперативники и другие сомнительные личности, которые носят его, не могут быть ослеплены."
два раза идёт "что", не красиво

2023-06-04 20:33 UTC, lzk228 commented on Resources/Prototypes/Datasets/tips.yml
> +    - "Вы можете создать копья с осколков армированного, плазменного и уранового стекла для увеличения урона."
![image](https://github.com/space-syndicate/space-station-14/assets/124214523/9902e303-3c6f-43e9-9efe-5a0ad5b56878)

2023-06-05 13:05 UTC, ficcialfaint requested changes

2023-06-05 13:05 UTC, ficcialfaint commented on Resources/Prototypes/Datasets/tips.yml
> +    - "Будучи врачом, помните, что в вашем анализаторе здоровья есть сменная батарея. Если, на ваш взгляд, батарея разряжается слишком быстро, вы можете попросить ученых напечатать для вас лучшую бат
```suggestion
    - "Будучи врачом, помните, что в вашем анализаторе здоровья есть сменная батарея. Если, на ваш взгляд, батарея разряжается слишком быстро, вы можете попросить ученых напечатать для вас батарею получше!"
```

2023-06-05 13:05 UTC, ficcialfaint commented on Resources/Prototypes/Datasets/tips.yml
> +    - "Будучи учёным, вы можете попытатся угадать, что делает улучшение машины, исходя их того какой компонент вы обновляете. Ёмкости материи увеличивают возможности хранения, конденсаторы увеличиваю
```suggestion
    - "Будучи учёным, вы можете попытаться угадать, что делает улучшение машины, исходя их того, какой компонент вы улучшаете. Ёмкости материи увеличивают возможности хранения, конденсаторы увеличивают эффективность, и манипуляторы увеличивают мощность."
```

2023-06-05 13:05 UTC, ficcialfaint commented on Resources/Prototypes/Datasets/tips.yml
> +    - "Будучи учёным, вы можете использовать лучшие детали машин для повышения эффективности машин. Это может сделать некоторые машины, такие как переработчик биомассы, значительно лучше!"
```suggestion
    - "Будучи учёным, вы можете использовать детали машин получше для повышения эффективности машин. Это может сделать некоторые машины, такие как переработчик биомассы, значительно лучше!"
```

2023-06-05 13:05 UTC, ficcialfaint commented on Resources/Prototypes/Datasets/tips.yml
> +    - "Будучи атмосферным техником, постарайтесь сопротивлятся искушению использовать канистровые бомбы против ядерных оперативников, до тех пор, пока у вас не будет другого выхода. Этим вы можете на
```suggestion
    - "Будучи атмосферным техником, постарайтесь сопротивляться искушению использовать канистровые бомбы против ядерных оперативников, до тех пор, пока у вас не будет другого выхода. Этим вы можете нанести много ненужного урона по союзникам."
```

2023-06-05 13:22 UTC, ficcialfaint requested changes

2023-06-05 13:22 UTC, ficcialfaint commented on Resources/Prototypes/Datasets/tips.yml
>      - "As the Chief Medical Officer, your hypospray starts with omnizine, which can heal almost every type of damage at once, but can't be synthesized. Use it wisely!"
```suggestion
    - "Будучи СМО, вы стартуете с омнизином в гипоспрее, который может вылечить практически любой вид урона за раз, но не может быть синтерзирован. Используйте его с умом!"
```

2023-06-05 13:22 UTC, ficcialfaint commented on Resources/Prototypes/Datasets/tips.yml
>      - "The station's self-destruct terminal is invincible. Go find the disk instead of trying to destroy it."
```suggestion
    - "Механизм самоуничтожение станции непобедим. Найдите диск вместо того, чтобы уничтожать его."
```

2023-06-05 13:22 UTC, ficcialfaint commented on Resources/Prototypes/Datasets/tips.yml
>      - "Just because a job can't be a traitor at the beginning of a round doesn't mean that they'll never be a traitor."
```suggestion
    - "Просто потому что человек такой профессии не может стать предателем в начале раунда, не значит, что он не станет им больше никогда."
```

2023-06-05 13:22 UTC, ficcialfaint commented on Resources/Prototypes/Datasets/tips.yml
>      - "You can click on the names of items to pick them up in the right click menu, instead of hovering over the item and then selecting pick up."
```suggestion
    - "Вы можете кликнуть на имена предметов в ПКМ меню, чтобы подобрать их, вместо того, чтобы наводиться на предмет, а затем подбирать его."
```

2023-06-05 13:22 UTC, ficcialfaint commented on Resources/Prototypes/Datasets/tips.yml
>      - "You can tell if an area with firelocks up is spaced by looking to see if the firelocks have lights besides them."
```suggestion
    - "Вы можете определить, разгерметизирована ли область с противопожарными замками, посмотря, есть ли у пожарных замков кроме них огни."
```

2023-06-05 13:34 UTC, lzk228 commented on Resources/Prototypes/Datasets/tips.yml
>      - "As the Chief Medical Officer, your hypospray starts with omnizine, which can heal almost every type of damage at once, but can't be synthesized. Use it wisely!"
апстрим уберёт эту строку, но всё же

2023-06-05 13:36 UTC, lzk228 commented on Resources/Prototypes/Datasets/tips.yml
>      - "You can tell if an area with firelocks up is spaced by looking to see if the firelocks have lights besides them."
пожарные замки

2023-06-05 13:38 UTC, ficcialfaint approved these changes

2023-06-05 13:39 UTC, merged