QM mantle recipe to uniform printer
space-syndicate/space-station-14 pull request #1112
Opened 2023-06-02 07:09 UTC by lzk228

## Описание PR

забыл в #979 

**Медиа**

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:
- add: Накидку квартирмейстера можно распечатать на принтере униформы

2023-06-03 06:33 UTC, Morb0 requested changes

2023-06-03 06:33 UTC, Morb0 commented on Resources/Prototypes/Entities/Structures/Machines/lathe.yml
> +      - ClothingNeckMantleQM # Corvax Mantle
Под Resprite попадают как изменения спрайтов так и новые спрайты
И формат комментария должен быть такой:
`# Corvax-Тема: Опциональное описание`
```suggestion
      - ClothingNeckMantleQM # Corvax-Resprite
```

2023-06-07 21:49 UTC, ficcialfaint approved these changes

2023-06-08 05:08 UTC, Morb0 approved these changes

2023-06-08 05:08 UTC, merged