Замена руководителей профессий
space-syndicate/space-station-14 pull request #1132
Opened 2023-06-13 12:14 UTC by Myakot

## Описание PR
Несмотря на все разработки своего лора, вики, и подобного, у нас всё это время оставалось описание работок официального сервера. Из-за чего у нас:
- Квартирмейстер не был полноценным главой, а подчинялся ГП; (теперь подчиняется кэпу и глава)
- Весь состав карго подчинялся КМу И ГП; (теперь подчиняются только КМу)
- Представитель Центрального Командования непонятно почему подчинялся Главе Службы Безопасности станции; (Теперь подчиняется только ЦК)
- Музыкант не находился в сервисе по подчинённости, хотя по всем признакам именно там и находился; (теперь в сервисе, глава - ГП)
- Пассажир подчинялся всем на станции (теперь глава ГП)

**Проверки**

- [х] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [х] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [х] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [х] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:
- Изменено: Центральное Командование исправило ошибку в манифесте и перестало указывать Квартирмейстера подчинённым Главе Персонала. Всем работникам карго на станциях НТ было решено увеличить зарплату в качестве репараций за подобное допущение, однако увидев сколько денег за последние месяцы ЦК спустило на бесполезные платы пожарных шлюзов подобные инициативы сошли на нет.

2023-06-13 12:25 UTC, lzk228 commented on Resources/Locale/ru-RU/job/job-supervisors.ftl
> +job-supervisors-qm = квартирмейстеру
насколько я понимаю, эти строки должны находится в папке `Corvax`, впрочем, фейнт поправит при ревью

2023-06-14 02:43 UTC, ficcialfaint commented on Resources/Locale/ru-RU/job/job-supervisors.ftl
> +job-supervisors-qm = квартирмейстеру
> Для чего?

Все нововведения, сделанные исключительно для билда Корвакса мы выносим в отдельную папку Corvax, а если не получается, то помечаем комментариями. В твоем случае, флуент строки могут находиться где угодно, так что тебе просто надо в каталоге `Resources/Locale/ru-RU/Corvax` создать папку `job/`, если такой ещё нет и создать файлик `job-supervisors.ftl`, в который ты поместишь эту новую строку

2023-06-14 02:46 UTC, ficcialfaint requested changes

2023-06-14 02:46 UTC, ficcialfaint commented on Resources/Prototypes/Roles/Jobs/Cargo/cargo_technician.yml
> +  supervisors: job-supervisors-qm
```suggestion
  supervisors: job-supervisors-qm # Corvax-JobSupervisors
```

2023-06-14 02:46 UTC, ficcialfaint commented on Resources/Prototypes/Roles/Jobs/Cargo/quartermaster.yml
> +  supervisors: job-supervisors-captain
```suggestion
  supervisors: job-supervisors-captain # Corvax-JobSupervisors
```

2023-06-14 02:46 UTC, ficcialfaint commented on Resources/Prototypes/Roles/Jobs/Cargo/salvage_specialist.yml
> +  supervisors: job-supervisors-qm
```suggestion
  supervisors: job-supervisors-qm # Corvax-JobSupervisors
```

2023-06-14 02:46 UTC, ficcialfaint commented on Resources/Prototypes/Roles/Jobs/Civilian/assistant.yml
> +  supervisors: job-supervisors-hop
```suggestion
  supervisors: job-supervisors-hop # Corvax-JobSupervisors
```

2023-06-14 02:46 UTC, ficcialfaint commented on Resources/Prototypes/Roles/Jobs/Civilian/musician.yml
> +  supervisors: job-supervisors-hop
```suggestion
  supervisors: job-supervisors-hop # Corvax-JobSupervisors
```

2023-06-14 02:46 UTC, ficcialfaint commented on Resources/Prototypes/Roles/Jobs/Command/centcom_official.yml
> +  supervisors: job-supervisors-centcom
```suggestion
  supervisors: job-supervisors-centcom # Corvax-JobSupervisors
```

2023-06-14 02:46 UTC, ficcialfaint commented on Resources/Locale/en-US/job/job-supervisors.ftl
> +job-supervisors-qm = the quartermaster
то же самое как и в https://github.com/space-syndicate/space-station-14/pull/1132#discussion_r1228905969, только в папке `en-US/`

2023-06-14 02:48 UTC, ficcialfaint commented
И я бы убрал из ченджлога часть про зарплату, чтобы на вводить игроков в заблуждение

2023-06-14 15:40 UTC, Morb0 requested changes

2023-06-14 15:40 UTC, Morb0 commented on Resources/Locale/en-US/job/job-supervisors.ftl
> +job-supervisors-qm = the quartermaster
Нужно удалить эту строку, если было вынесено в папку

2023-06-18 10:01 UTC, closed without merging