Some more tts sanitize
space-syndicate/space-station-14 pull request #1136
Opened 2023-06-14 10:18 UTC by lzk228

## Описание PR

МК - пистолет МК 58
ВТ - пп WT550

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

2023-06-14 15:22 UTC, ficcialfaint requested changes

2023-06-14 15:22 UTC, ficcialfaint commented on Content.Server/Corvax/TTS/TTSSystem.Sanitize.cs
> +            {"с4", "Си 4"},
Я бы ещё продублировал это, но чтобы в слове `c4` С была английской

2023-06-14 21:40 UTC, lzk228 commented on Content.Server/Corvax/TTS/TTSSystem.Sanitize.cs
> +            {"вт", "Вэ Тэ"},
нету

2023-06-16 04:01 UTC, ficcialfaint commented on Content.Server/Corvax/TTS/TTSSystem.Sanitize.cs
> +            {"вт", "Вэ Тэ"},
Всмысле "нету"? Есть. Ты хоть когда-нибудь читаешь ошибки тестов?

2023-06-16 05:03 UTC, lzk228 commented on Content.Server/Corvax/TTS/TTSSystem.Sanitize.cs
> +            {"вт", "Вэ Тэ"},
Ctrl+F ввожу, там только одна строка

2023-06-16 14:10 UTC, ficcialfaint commented on Content.Server/Corvax/TTS/TTSSystem.Sanitize.cs
> +            {"вт", "Вэ Тэ"},
76 строке

2023-06-20 07:25 UTC, ficcialfaint approved these changes

2023-06-22 19:09 UTC, merged