resprite aghost icons
space-syndicate/space-station-14 pull request #1138
Opened 2023-06-14 15:39 UTC by kxvvv

## Описание PR

Меняет кнопки в AGhost'e на разные, дабы они были различаемые

**Медиа**

![image](https://github.com/space-syndicate/space-station-14/assets/136233650/5fa76f5b-fb69-425b-bc5c-e1efe84e7312)

**Проверки**

- [✓] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [✓] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [✓] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [✓] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

:cl:
- tweak: Респрайт админских действий.

2023-06-14 15:44 UTC, Morb0 requested changes
Нужно вынести новы спрайты в `Corvax/Interface/AdminActions`
И думаю даже не в RSI, будет работать если заменить на:
`icon: Corvax/Interface/AdminActions/solar.png`
И в конце каждой изменённой строки нужно добавить ` # Corvax-Resprite`
А так же почему не на русском текст на спрайтах?

2023-06-18 01:12 UTC, ficcialfaint requested changes
Иконкам нужен `attributions.yml`, как пример можешь найти такие файлы в `Resources/Audio`

2023-06-19 15:31 UTC, lzk228 commented
а почему бы не сделать просто иконки консолей?

2023-06-29 23:24 UTC, kxvvv commented
> 

![image](https://github.com/space-syndicate/space-station-14/assets/136233650/ed73a87d-9d8f-4240-a070-a34fba552a7b)
![image](https://github.com/space-syndicate/space-station-14/assets/136233650/d9ace364-5288-44e1-bb53-0fcf7920189e)

2023-06-29 23:38 UTC, ficcialfaint requested changes
- Вместо галочек поставь X
- И может сделать, чтобы ченджлог звучал получше?

2023-06-29 23:38 UTC, ficcialfaint commented on RobustToolbox
ПР не должен изменять сабмодули

2023-06-30 02:43 UTC, kxvvv commented
сломал окончательно случайно, легче пересоздать

2023-06-30 02:43 UTC, closed without merging