Update butcherable-component.ftl
space-syndicate/space-station-14 pull request #114
Opened 2022-02-24 20:03 UTC by lapatison

## Описание PR 
Добавлена часть перевода.

**Скриншоты**

**Изменения**

:cl: lapatison
- add: Мелкий перевод.

2022-02-24 21:14 UTC, Morb0 requested changes

2022-02-24 21:14 UTC, Morb0 commented on Resources/Locale/ru-RU/kitchen/components/butcherable-component.ftl
> +butcherable-knife-butchered-success = Вы разделываете { THE($target) } с помощью { THE($knife) }.
функции `THE` добавляют приставку `the`переед словами, нам такое не нужно

2022-02-25 09:38 UTC, lapatison commented on Resources/Locale/ru-RU/kitchen/components/butcherable-component.ftl
> +butcherable-knife-butchered-success = Вы разделываете { THE($target) } с помощью { THE($knife) }.
поправил

2022-02-25 11:26 UTC, Morb0 approved these changes

2022-02-25 11:27 UTC, merged