Emote and twitchbanword
space-syndicate/space-station-14 pull request #1140
Opened 2023-06-15 14:38 UTC by Krosus777

## Описание PR
 Добавил быстрые эмоции как смайлики.
Добавил автозамену слов, за которые банит Twitch. Уменьшает шансы получить бан стримерам.

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:
- add: Добавлены быстрые эмоции "!с", "!в", "!х", "!щ".
- add: Добавлены слова для автозамены.

2023-06-15 18:23 UTC, lapatison commented on Content.Server/Chat/Managers/ChatSanitizationManager.cs
> +        { "лол", "chatsan-laughs" },
`лол` не добавляй. Слишком много слов содержат в себе часть `лол`.

2023-06-15 18:55 UTC, Krosus777 commented on Content.Server/Chat/Managers/ChatSanitizationManager.cs
> +        { "лол", "chatsan-laughs" },
Исправил

2023-06-18 01:33 UTC, ficcialfaint requested changes

2023-06-18 01:33 UTC, ficcialfaint commented on Resources/Locale/ru-RU/chat/sanitizer-replacements.ftl
> +chatsan-snap = щёлкает
Добавь то же самое по пути `Resources/Locale/en-US/chat/sanitizer-replacements.ftl`

2023-06-18 11:07 UTC, Krosus777 commented on Resources/Locale/ru-RU/chat/sanitizer-replacements.ftl
> +chatsan-snap = щёлкает
Готово

2023-06-20 00:41 UTC, closed without merging