Замена руководителей профессий v2
space-syndicate/space-station-14 pull request #1145
Opened 2023-06-18 10:25 UTC by Myakot

## Описание PR
Несмотря на все разработки своего лора, вики, и подобного, у нас всё это время оставалось описание профессий официального сервера. Из-за чего у нас:
- Квартирмейстер не был полноценным главой, а подчинялся ГП; (теперь подчиняется кэпу и глава)
- Весь состав карго подчинялся КМу И ГП; (теперь подчиняются только КМу)
- Представитель Центрального Командования непонятно почему подчинялся Главе Службы Безопасности станции; (Теперь подчиняется только ЦК)
- Музыкант не находился в сервисе по подчинённости, хотя по всем признакам именно там и находился; (теперь в сервисе, глава - ГП)
- Пассажир подчинялся всем на станции (теперь глава ГП)

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:
- tweak: Центральное Командование исправило ошибку в манифесте и перестало указывать Квартирмейстера в подчинении Главе Персонала.

2023-06-18 10:26 UTC, Myakot commented
Извиняюсь за закрытие предыдущей ветки и создание новой, если это хоть как-то мешает гиту. Сообщите мне. Просто я подумал, что вырезать всё на корню и начать заново, зная все правки, затратит меньше усилий, чем если я буду долбить местных мейнтейнеров о том, как же мне сделать откат всех правок, не вызывая миллион ошибок.

2023-06-18 16:58 UTC, ficcialfaint requested changes

2023-06-18 16:58 UTC, ficcialfaint commented on Resources/Locale/en-US/corvax/job/job-supervisors.ftl
> +job-supervisors-everyone = absolutely everyone
Это всё не надо было переносить в `/corvax/...`, только то, что новое ты добавил. Остальное оставь где было

2023-06-19 11:29 UTC, Myakot commented on Resources/Locale/en-US/corvax/job/job-supervisors.ftl
> +job-supervisors-everyone = absolutely everyone
> Это всё не надо было переносить в `/corvax/...`, только то, что новое ты добавил. Остальное оставь где было

Кинул коммит, когда-нибудь привыкну.

2023-06-19 15:17 UTC, ficcialfaint approved these changes

2023-06-19 15:18 UTC, merged

2025-06-16 20:23 UTC, lzk228 commented
что это за говно? почему фиксы не были отправлены на визарды? ну и даже то что осталось реально хуйня
![image](https://github.com/user-attachments/assets/9076dad7-4157-4a70-9623-65c2f0e571f5)

- центком офишиал: скорее всего баг, ну или действительно задумка, которая просто не впихивается в корваксный "лор"
- музыкант: может тоже баг, но оправдать можно тем что он вольный артист (который кстати в будущем реально может и будет именно артистом, а не музыкантом)

2025-06-16 21:00 UTC, ArZarLordOfMango commented
лазика закорежило на пр 2 летней давности.