Перевод акцента крыс
space-syndicate/space-station-14 pull request #1151
Opened 2023-06-20 01:16 UTC by Nimfar11

## Описание PR

Переведены все слава акцента крыс.

**Проверки**

- [Х] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [Х] Я внимательно просмотрел все свои изменения и багов в них не нашёл.

:cl: Nimfar11

- add: Добавлен перевод акцента крыс.

2023-06-20 07:20 UTC, ficcialfaint requested changes
половина замен смотрятся глупо, и редко, когда будет тригернуты

2023-06-20 07:20 UTC, ficcialfaint commented on Resources/Locale/ru-RU/accent/mobster.ftl
> +accent-mobster-words-replace-2 = огхта
и что это значит?

2023-06-20 07:20 UTC, ficcialfaint commented on Resources/Locale/ru-RU/accent/mobster.ftl
> +accent-mobster-words-replace-3 = это вот
```suggestion
accent-mobster-words-replace-3 = эт
```

2023-06-20 07:20 UTC, ficcialfaint commented on Resources/Locale/ru-RU/accent/mobster.ftl
> +accent-mobster-words-replace-4 = эти вот
глупо выглядит

2023-06-20 12:51 UTC, Nimfar11 commented on Resources/Locale/ru-RU/accent/mobster.ftl
> +accent-mobster-words-replace-2 = огхта
дайя это дай я, просто вместе. А огхта не смог придумать нормальный перевод. Думаю сейчас слово вообще заменю.

2023-06-20 12:58 UTC, Nimfar11 commented on Resources/Locale/ru-RU/accent/mobster.ftl
> +accent-mobster-words-replace-3 = это вот
поправил

2023-10-12 13:25 UTC, Nimfar11 commented
Ладно, удаляю ПР, смысла в нем нет как я понял.

2023-10-12 13:25 UTC, closed without merging