New lobby music
space-syndicate/space-station-14 pull request #1160
Opened 2023-06-22 07:52 UTC by lzk228

## Описание PR

**Медиа**

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:
- add: Добавлена новая музыка в лобби

2023-06-22 10:58 UTC, Morb0 commented
трки pilotpriest мне не кажутся интересными или подходящими и не сравнится уж точно с существующими треками
Title2 можно добавить, но только оформи правильно, вот информация о происхождении и авторстве - https://github.com/tgstation/tgstation/pull/43461 но тогда добавь и клоун версию - https://github.com/tgstation/tgstation/blob/master/sound/ambience/clown.ogg

2023-06-23 22:17 UTC, lzk228 commented
> вот информация о происхождении и авторстве

не смог найти информацию о копирайте

> но тогда добавь и клоун версию

в коде ТГ она играет только на 1 апреля, точно стоит добавлять её в обычный список музыки?

2023-06-24 14:15 UTC, Morb0 commented
> не смог найти информацию о копирайте
ссылайся на тг, то есть прямую перманентную ссылку на файл в их репозитории и соответственно лицензию CC-BY-SA-3.0

> в коде ТГ она играет только на 1 апреля, точно стоит добавлять её в обычный список музыки?
можно и не добавлять, помню она играла как эмбиент в космосе

2023-06-28 18:29 UTC, lzk228 commented
Какие изменения ожидаются? Везде копирайт и соурс проставил.

2023-06-29 23:38 UTC, Morb0 commented
Одобрен только трек title2

2023-07-02 15:35 UTC, ficcialfaint commented on Resources/Audio/Corvax/Lobby/attributions.yml
> +  copyright: "https://github.com/tgstation/tgstation/blob/44db038c2cf7c6dade4300bea54cff06e98caf6a/sound/ambience/title2.ogg"
зачем в копирайте ссылка?

2023-07-02 18:54 UTC, lzk228 commented on Resources/Audio/Corvax/Lobby/attributions.yml
> +  copyright: "https://github.com/tgstation/tgstation/blob/44db038c2cf7c6dade4300bea54cff06e98caf6a/sound/ambience/title2.ogg"
> ссылайся на тг, то есть прямую перманентную ссылку на файл в их репозитории и соответственно лицензию CC-BY-SA-3.0

2023-07-09 10:53 UTC, lzk228 commented
обновил

2023-07-19 10:45 UTC, Morb0 requested changes

2023-07-19 10:45 UTC, Morb0 commented on Resources/Prototypes/SoundCollections/lobby.yml
> +# Corvax lobby music end
```suggestion
    - /Audio/Corvax/Lobby/title2.ogg # Corvax-LobbyMusic
```

2023-07-19 10:47 UTC, merged