Перевод Upstream #1148
space-syndicate/space-station-14 pull request #1164
Opened 2023-06-22 11:31 UTC by lapatison

## Описание PR

**Медиа**

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:
- add: Добавлены переводы

2023-06-22 11:39 UTC, lzk228 commented on Resources/Locale/ru-RU/apc/components/apc-component.ftl
> +apc-component-breaker-popped = Рубильник ЛКП переключился!
Может `Сработал предохранитель ЛКП!"?

2023-06-22 11:42 UTC, lzk228 commented on Resources/Locale/ru-RU/machine-linking/receiver_ports.ftl
> +signal-port-description-doorbolt = Bolts door when HIGH.
?

2023-06-22 11:43 UTC, lzk228 commented on Resources/Locale/ru-RU/machine-linking/transmitter_ports.ftl
> +signal-port-description-doorstatus = This port is invoked with HIGH when the door opens and LOW when the door closes.
?

2023-06-22 11:43 UTC, lzk228 commented on Resources/Locale/ru-RU/power/components/charger.ftl
> +charger-component-charge-rate = скорость зарядки
```suggestion
charger-component-charge-rate = Скорость зарядки
```

2023-06-22 11:46 UTC, lapatison commented on Resources/Locale/ru-RU/machine-linking/receiver_ports.ftl
> +signal-port-description-doorbolt = Bolts door when HIGH.
https://github.com/space-wizards/space-station-14/pull/17198
Machine linking усложнился. Я не так разбираюсь в этом вопросе, чтобы перевести. Оригинал строки изменился, скрипт её пропустил. Я заменил на en версию.
https://github.com/space-syndicate/space-station-14/blob/bbcdb154c91a513a178b3f74b0ef3be2052f953c/Resources/Locale/en-US/machine-linking/receiver_ports.ftl#L26

2023-06-22 11:46 UTC, lapatison commented on Resources/Locale/ru-RU/machine-linking/transmitter_ports.ftl
> +signal-port-description-doorstatus = This port is invoked with HIGH when the door opens and LOW when the door closes.
См выше

2023-06-22 11:47 UTC, lapatison commented on Resources/Locale/ru-RU/power/components/charger.ftl
> +charger-component-charge-rate = скорость зарядки
С маленькой, потому что предложение описания уже начинается с большой буквы
https://github.com/space-syndicate/space-station-14/blob/bd1ecfa14a81cc6a9f8f15c6109faab0a1012e27/Resources/Locale/ru-RU/machine/machine.ftl#L4

2023-06-22 11:48 UTC, lzk228 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/markers/spawners/mobs.ftl
> +ent-SpawnMobBehonker = спавнер Бехонкер
```suggestion
ent-SpawnMobBehonker = спавнер бехонкер
```

2023-06-22 12:43 UTC, lzk228 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/specific/mech/mechs.ftl
> +    .desc = Экспериментальная меха, использующая нейролинк для прямого подключения к мозгу хомяка.
```suggestion
    .desc = Экспериментальный мех, использующая нейролинк для прямого подключения к мозгу хомяка.
```

2023-06-22 12:45 UTC, lzk228 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/weapons/guns/basic/wands.ftl
> +ent-WeaponWandPolymorphBread =  волшебная палочка хлеба
```suggestion
ent-WeaponWandPolymorphBread = волшебная палочка полиморфа хлеба
```

2023-06-22 12:45 UTC, lzk228 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/weapons/guns/basic/wands.ftl
>  ent-WeaponWandCluwne = волшебная палочка клувеня
```suggestion
ent-WeaponWandCluwne = волшебная палочка полиморфа клувеня
```

2023-06-22 14:34 UTC, lapatison commented on Resources/Locale/ru-RU/apc/components/apc-component.ftl
> +apc-component-breaker-popped = Рубильник ЛКП переключился!
Зачем? В ориге ни слова про предохранитель

2023-06-24 16:21 UTC, ficcialfaint requested changes

2023-06-24 16:21 UTC, ficcialfaint commented on Resources/Locale/ru-RU/guidebook/chemistry/effects.ftl
>         *[other] { $amount } { MAKEPLURAL($entname) }
https://github.com/space-syndicate/space-station-14/pull/1164#discussion_r1240077314 только с MAKEPLURAL

2023-06-24 16:21 UTC, ficcialfaint commented on Resources/Locale/ru-RU/guidebook/chemistry/effects.ftl
>      } vomiting
перевод нужен

2023-06-24 16:21 UTC, ficcialfaint commented on Resources/Locale/ru-RU/guidebook/chemistry/effects.ftl
>      } of { $gas }
тоже

2023-06-24 16:21 UTC, ficcialfaint commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/specific/mech/mech_construction.ftl
> +    .desc = Ядро меха ХАМЯК.
```suggestion
    .desc = Ядро меха ХАМЯК.
```

2023-06-24 17:11 UTC, lapatison commented on Resources/Locale/ru-RU/power/components/charger.ftl
> +charger-component-charge-rate = скорость зарядки
Жёлтого цвета вполне достаточно имхо

2023-06-25 12:34 UTC, lapatison commented on Resources/Locale/ru-RU/xenoarchaeology/artifact-analyzer.ftl
> +analysis-console-extract-button = Извлечь О.И.
Нет, малопонятно

2023-06-25 12:42 UTC, lapatison commented on Resources/Locale/ru-RU/guidebook/chemistry/conditions.ftl
> +       *[false] это не
имхо лучше как сейчас, конкретнее

2023-06-25 12:44 UTC, lapatison commented on Resources/Locale/ru-RU/guidebook/chemistry/core.ftl
> +guidebook-reagent-recipes-mix = Смешайте
![image](https://github.com/space-syndicate/space-station-14/assets/100279397/86b96859-b555-41e9-b670-095a8577d273)

2023-06-25 12:56 UTC, lapatison commented on Resources/Locale/ru-RU/guidebook/chemistry/effects.ftl
>         *[other] { $amount } { MAKEPLURAL($entname) }
Недопонима

2023-06-25 19:33 UTC, ficcialfaint commented on Resources/Locale/ru-RU/guidebook/chemistry/effects.ftl
>         *[other] { $amount } { MAKEPLURAL($entname) }
Надо так же как и `MANY()` удалить `MAKEPLURAL()`, потому что оно используется только для английского языка

2023-06-26 01:21 UTC, merged