Janitorial guidebook locale
space-syndicate/space-station-14 pull request #1168
Opened 2023-06-22 16:28 UTC by lapatison

## Описание PR

**Медиа**

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:
- add: Добавлен перевод руководства уборщика

2023-06-24 05:03 UTC, ficcialfaint commented on Resources/ServerInfo/Guidebook/Service/Janitorial.xml
> +- Чтобы опорожнить тележку, перетащите её (курсором) на дренаж в полу. Обычно дренажи можно найти в медицинском отделе, в морозильной камере на кухне и, конечно же, в кладовке уборщика.
Может найти замену слову "drain" ~~(gang)~~ получше? Осушить, например

2023-06-24 05:03 UTC, ficcialfaint commented on Resources/ServerInfo/Guidebook/Service/Janitorial.xml
> +- Больше очистителя вы можете получить от химиков.
```suggestion
- Побольше очистителя вы можете получить у химиков.
```

2023-06-24 05:04 UTC, ficcialfaint requested changes

2023-06-24 05:04 UTC, ficcialfaint commented on Resources/ServerInfo/Guidebook/Service/Janitorial.xml
> +</Document>
```suggestion
```

2023-06-24 05:04 UTC, ficcialfaint commented on Resources/ServerInfo/Guidebook/Service/Janitorial.xml
> +</Document>
```suggestion
```

2023-06-24 09:05 UTC, lapatison commented on Resources/ServerInfo/Guidebook/Service/Janitorial.xml
> +- Чтобы опорожнить тележку, перетащите её (курсором) на дренаж в полу. Обычно дренажи можно найти в медицинском отделе, в морозильной камере на кухне и, конечно же, в кладовке уборщика.
А что не так с `опорожнить` ?

2023-06-24 16:29 UTC, ficcialfaint commented on Resources/ServerInfo/Guidebook/Service/Janitorial.xml
> +- Чтобы опорожнить тележку, перетащите её (курсором) на дренаж в полу. Обычно дренажи можно найти в медицинском отделе, в морозильной камере на кухне и, конечно же, в кладовке уборщика.
имхо оно слишком... сложное что ли. Ну вот если бы я в первый раз увидел гайд на английском и увидел там глагол `drain`, мне бы было куда понятнее чем, если бы я увидел `опорожнить`

2023-06-24 17:10 UTC, lapatison commented on Resources/ServerInfo/Guidebook/Service/Janitorial.xml
> +- Чтобы опорожнить тележку, перетащите её (курсором) на дренаж в полу. Обычно дренажи можно найти в медицинском отделе, в морозильной камере на кухне и, конечно же, в кладовке уборщика.
`Чтобы вылить содержимое тележки` ?

2023-07-07 16:13 UTC, ficcialfaint approved these changes

2023-07-07 16:13 UTC, merged