Guidebook translations
space-syndicate/space-station-14 pull request #1171
Opened 2023-06-23 11:42 UTC by Myakot

## Описание PR
Коммит нескольких гайдбуков
Повар, Бармен, рецепты повара - перевод "lzk", остальное моё

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:
- add: Переводы статей гайдбука

2023-06-23 12:35 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Engineering/NetworkConfigurator.xml
> +## Режим список
Как-то не очень выглядит, написать либо `Режим списка`, либо `Режим "Список"`

2023-06-23 12:38 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Engineering/NetworkConfigurator.xml
> +При нажатии на прибор из примера, откроется интерфейс, отображающий список сохраненных сетевых устройств, также присутствуют кнопки для управления этим списком.
```suggestion
При нажатии на устройство (напр. воздушная сигнализация), откроется интерфейс, отображающий список сохраненных сетевых устройств и кнопки для управления этим списком.
```

2023-06-23 12:41 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Engineering/NetworkConfigurator.xml
> +К примеру, если вы нажмёте на "источник" по типу [color=#a4885c]signal button[/color] а затем на "получателя" сигнала вроде [color=#a4885c]small light[/color] то откроется интерфейс, показывающий пор
```suggestion
К примеру, если вы нажмёте на "источник" по типу [color=#a4885c]кнопки сигнала[/color], а затем на "получателя" сигнала вроде [color=#a4885c]светильника[/color] то откроется интерфейс, показывающий порты "источника" слева, а порты "получателя" справа.
```

2023-06-23 12:42 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Engineering/NetworkConfigurator.xml
> +Теперь вы можете нажать [color=gray]link defaults[/color] чтобы соединить стандартные для этих устройств порты, или же сделать это вручную.
```suggestion
Теперь вы можете нажать [color=gray]соединить по умолчанию[/color] чтобы соединить стандартные для этих устройств порты, или же сделать это вручную.
```

2023-06-23 12:42 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Engineering/NetworkConfigurator.xml
>    [color=cyan]Pressed 🠒 Toggle[/color]
```suggestion
  [color=cyan]Нажато 🠒 Переключить[/color]
```

2023-06-23 12:43 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Engineering/NetworkConfigurator.xml
> +Когда вы закончили соединять желаемые порты, нажмите на [color=gray]ok[/color] чтобы закрыть интерфейс.
```suggestion
Когда вы закончили соединять желаемые порты, нажмите на [color=gray]Готово[/color] чтобы закрыть интерфейс.
```

2023-06-23 12:46 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Engineering/Networking.xml
> +К примеру воздушным тревогам обязательно нужно указывать с какими вентиляциями, скрубберами, сенсорами и пожарными шлюзами им взаимодействовать.
```suggestion
К примеру воздушным сигнализациям обязательно нужно указывать с какими вентиляциями, скрубберами, сенсорами и пожарными шлюзами им взаимодействовать.
```

2023-06-23 12:48 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Engineering/Networking.xml
> +В обычных условиях большинство устройств соединяются друг с другом таким образом:
Не знаю, может смысл сохранён, но перевод кажется вовсе неверным

2023-06-23 12:52 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Engineering/Networking.xml
> +С помощью связей вы можете соединить вывод информации [color=gray]On[/color] или [color=gray]Off[/color] ввод информации в какое-либо устройство, в этом случае пожарный шлюз.
```suggestion
С помощью связей вы можете соединить вывод информации [color=gray]Вкл[/color] или [color=gray]Выкл[/color] ввод информации в какое-либо устройство, в этом случае пожарный шлюз.
```
И ещё мне кажется тут тоже что-то не так

2023-06-23 12:54 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Medical/Chemist.xml
> +В то время как химики в основном занимаются изготовлением медицины, существует огромный список химикатов, которые можно изготовить. Все эти химикаты показаны в секции Химикаты этой книги.
```suggestion
В то время как химики занимаются в основном изготовлением медикаментов, существует огромный список химикатов, которые можно изготовить. Все эти химикаты показаны в секции Химикаты этой книги.
```

2023-06-23 12:56 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Medical/Chemist.xml
> +- Альт-кликом по Раздатчику вытащите мензурку и переместите её в Хим Мастер.
```suggestion
- Альт-кликом по Раздатчику вытащите мензурку и переместите её в ХимМастер.
```

2023-06-23 12:56 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Medical/Chemist.xml
> +- Откройте интерфейс Хим Мастера. На вкладке Ввод, переместите всё, что вы сварили в буффер.
```suggestion
- Откройте интерфейс ХимМастера. На вкладке Ввод, переместите всё, что вы сварили в буффер.
```

2023-06-23 12:57 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Medical/Chemist.xml
> +Вы также можете использовать этикетировщик, чтобы упростить процесс хранения и использования бутылочек, таблетниц или целых сумок, не используя систему Хим Мастера.
```suggestion
Вы также можете использовать этикетировщик, чтобы упростить процесс хранения и использования бутылочек, таблетниц или целых сумок, не используя систему ХимМастера.
```

2023-06-23 12:59 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Medical/Chemist.xml
>  Speaking of experimentation, there are a few more toy you can use when it comes to chemistry. This job requires a lot of trial and error, but it was worth mentioning that these things exist! It's up
Удалить строку + непереведено выше

2023-06-23 13:00 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Medical/Cloning.xml
>  <Box>
Выше что-то намешано со строками

2023-06-23 19:37 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Medical/Cryogenics.xml
> +- Холодильник: Охлаждает смесь газа, и, с помощью этого, и пациента, чтобы он мог правильно метаболизировать Криоксадон
По моему запятые неправильно стоят...

2023-06-23 19:37 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Medical/Cryogenics.xml
> +- Вывод воздуха: Здесь фильтруются лишние газы, которые либо выходят в специальную канистру, либо в трубу отходов (красную)
```suggestion
- Вывод воздуха: Здесь фильтруются лишние газы, которые либо выходят в специальную канистру, либо в трубу отходов (красную).
```

2023-06-23 19:39 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Medical/Cryogenics.xml
> +Не все сети конфигурации должны выглядеть так, но надеемся, что этот пример объяснит вам базовый функционал всей системы.
```suggestion
Не все системы должны выглядеть так, но надеемся, что этого хватит для объяснения базового функционала.
```

2023-06-23 19:41 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Medical/Cryogenics.xml
> +Закончив с настройкой системы, можно переходить к следующему шагу - Криоксадону.
```suggestion
Закончив с настройкой системы, вам потребуется специальный медикамент - Криоксадон. 
```

2023-06-23 19:42 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Medical/Cryogenics.xml
> +Стандартное давление газового насоса 1.325 Кпа. Криоксадон работает при температуре ниже 170К, но обычно параметры охладителя ставят на 100К для ускорения процесса охлаждения.
```suggestion
Стандартное давление газового насоса 1.325 кПа. Криоксадон работает при температуре ниже 170К, но обычно параметры охладителя ставят на 100К для ускорения процесса охлаждения.
```

2023-06-23 19:46 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Engineering/NetworkConfigurator.xml
> +В этом режиме вы можете нажать на любые сетевые устройства, чтобы сохранить их на конфигуратор, а затем все их разом связать с устройством, имеющим компонент сетевого прибора, как [color=#a4885c]Air
```suggestion
В этом режиме вы можете нажать на любые сетевые устройства, чтобы сохранить их на конфигуратор, а затем все их разом связать с устройством, имеющим компонент сетевого прибора, как [color=#a4885c]воздушная сигнализация[/color].
```

2023-06-23 19:47 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Medical/Botanicals.xml
> +Ботаника и Химия часто работают над задачами вместе. Создать более эффективную натуральную медицину (или рекреационные коктейли) не составит никакого труда, покуда оба отдела гармонично работают друг
отсебятина?

2023-06-23 19:47 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Medical/Cloning.xml
> +Когда вы перепробовали всё, что могли, но пациент всё равно испустил дух - в дело вступает клонирование. Обычно используется только в самых крайних случаях, когда восстановление иными путями невозмож
отсебятина

2023-06-23 19:48 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Medical/Cloning.xml
> +Создание клона из ничего требует биомасса, запас которой, к сожалению, можно стабильно пополнять в адекватных количествах только с помощью переработки умерщвлённых тел. Будь то ваши погибшие товарищи
отсебятина

2023-06-23 19:49 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Medical/MedicalDoctor.xml
> +Время лечить. Ну, по крайней мере время попытаться вылечить побитого беднягу перед вами. Врачи заботятся о каждой мелкой болячке, порезе, и отпадающей от некроза плоти - сотрудники станции в надежных
отсебятина?

2023-06-23 19:50 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Medical/MedicalDoctor.xml
> +Эта книга даст вам фундаментальное понимание возможностей обработки ран, перевязок и иных способов заботы о нашей физической оболочке.
```suggestion
Это руководство даст вам фундаментальное понимание возможностей обработки ран, перевязок и иных способов заботы о нашей физической оболочке.
```

2023-06-23 19:51 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Medical/MedicalDoctor.xml
> +Лучше всего использовать оба способа, если есть возможность, так как некоторые повреждения (к примеру радиация или яд) не заметить поверхностным осмотром, в то время как такие, как анемия (недостаток
```suggestion
Лучше всего использовать оба способа, если есть возможность, так как некоторые повреждения (к примеру радиация или яд) не заметить поверхностным осмотром, в то время как другие (низкий уровень крови) не показываются на медицинском анализаторе.
```

2023-06-23 19:52 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Medical/MedicalDoctor.xml
> +Перед тем как продолжить, хорошей идеей будет разобраться в разных типах урона и как их лечить. Вики имеет больше информации, но нам ничего не мешает узнать самые азы.
отсебятина?

2023-06-23 19:54 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Medical/MedicalDoctor.xml
> +Важный момент: У большей части лекарств существует передозировка, которая начнёт наносить вред вашему пациенту, вместо того, чтобы лечить его. Также, химикатам нужно время, чтобы полностью впитаться
```suggestion
Важный момент: У большей части лекарств существует передозировка, которая начнёт наносить вред вашему пациенту, вместо того, чтобы лечить его. Также, химикатам нужно время для метаболизма, если вы даёте их в виде таблеток или жидкости. Если необходимо использовать медикаменты срочно - воспользуйтесь шприцом.
```

2023-06-23 19:55 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Medical/MedicalDoctor.xml
> +- Ожоги: Дермалин или Мазь
```suggestion
- Ожоги: Дермалин или мазь
```

2023-06-23 19:57 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Medical/MedicalDoctor.xml
> +- Кровопотеря: Дексалин (проведите внешний осмотр, если пациент бледен - ему необходимо дать чистого железа, чтобы восстановить запасы крови)
```suggestion
- Кровопотеря: Дексалин (проведите внешний осмотр, если пациент бледен - ему необходимо дать чистого железа или влить крови из пакетов)
```

2023-06-23 19:57 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Medical/MedicalDoctor.xml
> +- Кровотечение: Транексамовая кислота или бинты (Кровотечение также можно остановить прижиганием любым оружием с ожоговым уроном)
```suggestion
- Кровотечение: Транексамовая кислота или бинты (кровотечение также можно остановить прижиганием любым оружием с ожоговым уроном)
```

2023-06-23 20:02 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Medical/MedicalDoctor.xml
> +Если они живы - приложите все усилия, чтобы восстановить их. Пациенты падают в бессознательное критическое состояние при получении 100 общего урона и погибают при достижении в 200 урона. Всегда испол
```suggestion
Если они живы - приложите все усилия, чтобы восстановить их. Критическое состояние наступает при получении 100 общего урона и смерть при достижении в 200 урона. Имейте это в виду, выбирая, как вам следует поступить дальше. Экстренные медипены и эпинефрин часто используются для временной стабилизации критических пациентов.
```

2023-06-23 20:10 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Medical/MedicalDoctor.xml
> +Если есть возможность - уложите пациента на медицинскую кровать. Если пациент вот-вот откинет ноги - быстрей кладите его на стазисную кровать. Стазис замедлит все процессы в теле персонажа, в том чис
отсебятина

2023-06-23 20:13 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Medical/MedicalDoctor.xml
> +Не всегда удаётся спасти всех, иногда, смерть всё же берёт свой. В зависимости от статуса тела, наличия души и того, гниёт тело или нет, есть несколько способов вернуть персонажа с того света.
```suggestion
Не всегда удаётся спасти всех, иногда, смерть всё же берёт своё. В зависимости от статуса тела, наличия души и того, гниёт тело или нет, есть несколько способов вернуть пациента с того света.
```

2023-06-23 20:14 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Medical/MedicalDoctor.xml
> +1. У тела осталась привязанная душа? Это можно понять, проведя внешний осмотр и увидев фразу в красном цвете: "Душа покинула тело." Если видите эту надпись - сохраните тело в морге или разденьте его
```suggestion
1. У тела осталась привязанная душа? Это можно понять, проведя внешний осмотр и увидев фразу в красном цвете: "Душа покинула тело." Если этой надписи нет - сохраните тело в морге или используйте для биомассы.
```

2023-06-23 20:15 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Medical/MedicalDoctor.xml
> +2. Тело гниёт? Если да, к сожалению - единственный вариант спасения это клонирование. Гниющее тело нельзя дефибриллировать. (смотреть раздел Клонирование)
```suggestion
2. Тело гниёт? Если да, к сожалению - единственный вариант спасения это клонирование. Гниющее тело нельзя реанимировать. (См. раздел Клонирование)
```

2023-06-23 20:17 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Medical/MedicalDoctor.xml
> +3. Если у тела есть душа, оно не гниёт, тогда его можно воскресить на месте. Не считая урон от удушья, вы можете вернуть к жизни пациента с общим уроном в <200. Химия не будет метаболизироваться в мё
отсебятина

2023-06-23 20:18 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Medical/Medicine.xml
> +Лекарства из списка ниже практически всегда полезны медбею, они никогда не будут лишними.
```suggestion
Лекарства из списка ниже почти всегда так или иначе полезны медбею.

2023-06-23 20:19 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Medical/Medicine.xml
> +Это список -все- доступных лекарств, включая упомянутые ранее.
```suggestion
Это список -всех- доступных лекарств, включая упомянутые ранее.
```

2023-06-23 20:20 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Service/Chef.xml
> +# Повар
```suggestion
# Шеф-повар
```

2023-06-23 20:21 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Service/Chef.xml
> +- Посмотрите в справочнике Wiki (или "Рецепты еды"), что можно приготовить, и положите все перечисленные ингредиенты в микроволновую печь, чтобы приготовить еду.
```suggestion
- Посмотрите в справочнике Вики (или в разделе Рецепты еды), что можно приготовить, и положите все перечисленные ингредиенты в микроволновую печь, чтобы приготовить еду.
```

2023-06-23 20:22 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Service/FoodRecipes.xml
> +- Кукурузное тесто= 1 яйцо (6u), 10 молока, 15 кукурузной муки
```suggestion
- Кукурузное тесто= 1 яйцо (6 ед.), 10 молока, 15 кукурузной муки
```

2023-06-23 20:22 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Service/FoodRecipes.xml
> +- Тесто для пирога = 2 яйца (12u), 15 муки, 5 с
```suggestion
- Тесто для пирога = 2 яйца (12 ед.), 15 муки, 5 с
```

2023-06-23 20:23 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Service/FoodRecipes.xml
> +- Тесто для торта = 2 Eggs(12u), 15 flour, 5 Sugar
```suggestion
- Тесто для торта = 2 яйца(12 ед.), 15 муки, 5 сахара
```

2023-06-23 20:23 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Service/FoodRecipes.xml
> +- Фрикаделька = 1 яйцо (6u), 5 муки, 5 непрожаренные животные протеины
```suggestion
- Фрикаделька = 1 яйцо (6 ед.), 5 муки, 5 непрожаренные животные протеины
```

2023-06-23 20:23 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Service/FoodRecipes.xml
> +- Томатный суп: 10u воды, 1 пустая миска и 2 помидора на 10 секунд
```suggestion
- Томатный суп: 10 ед. воды, 1 пустая миска и 2 помидора на 10 секунд
```

2023-06-24 04:17 UTC, Myakot commented on Resources/ServerInfo/Guidebook/Engineering/NetworkConfigurator.xml
> +К примеру, если вы нажмёте на "источник" по типу [color=#a4885c]signal button[/color] а затем на "получателя" сигнала вроде [color=#a4885c]small light[/color] то откроется интерфейс, показывающий пор
У нас **не переведены** эти вещи в окне строительства. Подобное будет путать людей, но, впрочем, я думаю ты мне ещё десяток комментариев вдогонку кинешь.

2023-06-24 04:19 UTC, Myakot commented on Resources/ServerInfo/Guidebook/Engineering/Networking.xml
> +В обычных условиях большинство устройств соединяются друг с другом таким образом:
А знаешь почему? Потому что оригинальный текст грамматически неверен, как и большая часть текста в этих гайдбуках, а ты их ИИ переводил.
Первая часть предложения вообще вся построена не правильно.

2023-06-24 04:20 UTC, Myakot commented on Resources/ServerInfo/Guidebook/Medical/Botanicals.xml
> +Ботаника и Химия часто работают над задачами вместе. Создать более эффективную натуральную медицину (или рекреационные коктейли) не составит никакого труда, покуда оба отдела гармонично работают друг
Что, где.

2023-06-24 04:25 UTC, Myakot commented on Resources/ServerInfo/Guidebook/Medical/Cryogenics.xml
> +- Холодильник: Охлаждает смесь газа, и, с помощью этого, и пациента, чтобы он мог правильно метаболизировать Криоксадон
Специально для проверки сейчас прогнал тест для text.ru и advego - нет ни единой ошибки.

2023-06-24 04:26 UTC, Myakot commented on Resources/ServerInfo/Guidebook/Medical/MedicalDoctor.xml
> +Эта книга даст вам фундаментальное понимание возможностей обработки ран, перевязок и иных способов заботы о нашей физической оболочке.
Это планируют в ближайший месяц сделать физической книгой-предметом, которую нужно будет в руках держать. Так что в каждой статье книгу на "руководство" не спеши заменять.

2023-06-24 04:27 UTC, Myakot commented on Resources/ServerInfo/Guidebook/Medical/MedicalDoctor.xml
> +Перед тем как продолжить, хорошей идеей будет разобраться в разных типах урона и как их лечить. Вики имеет больше информации, но нам ничего не мешает узнать самые азы.
Практически прямой перевод, как и везде.

2023-06-24 04:28 UTC, Myakot commented on Resources/ServerInfo/Guidebook/Medical/MedicalDoctor.xml
> +- Ожоги: Дермалин или Мазь
Мазь это не название лекарства, почему она с большой буквы.

2023-06-24 04:28 UTC, Myakot commented on Resources/ServerInfo/Guidebook/Medical/MedicalDoctor.xml
> +- Кровопотеря: Дексалин (проведите внешний осмотр, если пациент бледен - ему необходимо дать чистого железа, чтобы восстановить запасы крови)
Опа, отсебятина. Этого нет в гайдбуке.

2023-06-24 04:29 UTC, Myakot commented on Resources/ServerInfo/Guidebook/Medical/MedicalDoctor.xml
> +- Кровотечение: Транексамовая кислота или бинты (Кровотечение также можно остановить прижиганием любым оружием с ожоговым уроном)
А как нам лучше, в каждой строке про урон делать: "Оружие с уроном "Ожог"" ?

2023-06-24 04:31 UTC, Myakot commented on Resources/ServerInfo/Guidebook/Medical/MedicalDoctor.xml
> +Если есть возможность - уложите пациента на медицинскую кровать. Если пациент вот-вот откинет ноги - быстрей кладите его на стазисную кровать. Стазис замедлит все процессы в теле персонажа, в том чис
Ну это - наполнение гайдбука реальными советами, оно же нам не надо. Пусть будет меньше советов, в руководстве, наполненном советами.

2023-06-24 04:33 UTC, Myakot commented on Resources/ServerInfo/Guidebook/Medical/MedicalDoctor.xml
> +3. Если у тела есть душа, оно не гниёт, тогда его можно воскресить на месте. Не считая урон от удушья, вы можете вернуть к жизни пациента с общим уроном в <200. Химия не будет метаболизироваться в мё
Опять же, практически прямой перевод. Если твой переводчик переводит не так, это не значит, что все иные варианты - отсебятина.

2023-06-24 04:33 UTC, Myakot commented on Resources/ServerInfo/Guidebook/Medical/Medicine.xml
> +Лекарства из списка ниже практически всегда полезны медбею, они никогда не будут лишними.
Запятые неправильно в твоём варианте стоят.

2023-06-24 06:00 UTC, Myakot commented on Resources/ServerInfo/Guidebook/Medical/MedicalDoctor.xml
> +Если они живы - приложите все усилия, чтобы восстановить их. Пациенты падают в бессознательное критическое состояние при получении 100 общего урона и погибают при достижении в 200 урона. Всегда испол
Этот коммит сломал файл

2023-06-24 06:34 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Medical/MedicalDoctor.xml
> +3. Если у тела есть душа, оно не гниёт, тогда его можно воскресить на месте. Не считая урон от удушья, вы можете вернуть к жизни пациента с общим уроном до <200>. Химия не будет метаболизироваться в
![image](https://github.com/space-syndicate/space-station-14/assets/124214523/1840f6a6-884d-47be-a6ce-9b2349f7f199)

2023-06-24 06:37 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Engineering/NetworkConfigurator.xml
> +Теперь вы можете нажать [color=gray]link defaults[/color] чтобы соединить стандартные для этих устройств порты, или же сделать это вручную.
эти строки, в отличии от крафт-меню, у нас переведены в интерфейсе

2023-06-24 06:37 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Engineering/NetworkConfigurator.xml
>    [color=cyan]Pressed 🠒 Toggle[/color]
и эти тоже

2023-06-24 06:37 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Engineering/NetworkConfigurator.xml
> +Когда вы закончили соединять желаемые порты, нажмите на [color=gray]ok[/color] чтобы закрыть интерфейс.
+

2023-06-24 06:38 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Engineering/Networking.xml
> +К примеру воздушным тревогам обязательно нужно указывать с какими вентиляциями, скрубберами, сенсорами и пожарными шлюзами им взаимодействовать.
у нас нет тревог

2023-06-24 06:40 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Medical/MedicalDoctor.xml
> +Эта книга даст вам фундаментальное понимание возможностей обработки ран, перевязок и иных способов заботы о нашей физической оболочке.
они уже так, но разве руководство не может быть написано в книге?

2023-06-24 06:41 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Medical/MedicalDoctor.xml
> +- Ожоги: Дермалин или Мазь
кхм.. у тебя она с большой буквы, предложение идёт на исправление на маленькую

2023-06-24 06:44 UTC, Myakot commented on Resources/ServerInfo/Guidebook/Medical/MedicalDoctor.xml
> +3. Если у тела есть душа, оно не гниёт, тогда его можно воскресить на месте. Не считая урон от удушья, вы можете вернуть к жизни пациента с общим уроном до <200>. Химия не будет метаболизироваться в
![image](https://github.com/space-syndicate/space-station-14/assets/30875116/ba3b4228-e672-473a-b2e7-838d2b83ae9d)

2023-06-24 07:05 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Medical/Cloning.xml
>  <GuideEntityEmbed Entity="ComputerCloningConsole" Caption="cloning console"/>
```suggestion
<GuideEntityEmbed Entity="ComputerCloningConsole" Caption="консоль клонирования"/>
```

2023-06-24 07:05 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Medical/MedicalDoctor.xml
>  <GuideEntityEmbed Entity="SignExamroom" Caption="examine patient"/>
```suggestion
<GuideEntityEmbed Entity="SignExamroom" Caption="осмотрите пациента"/>
```

2023-06-24 07:06 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Medical/MedicalDoctor.xml
>  <GuideEntityEmbed Entity="MedicalInternPDA" Caption="intern PDA"/>
```suggestion
<GuideEntityEmbed Entity="MedicalInternPDA" Caption="КПК интерна"/>
```

2023-06-24 08:21 UTC, ficcialfaint requested changes

2023-06-24 08:21 UTC, ficcialfaint commented on Resources/ServerInfo/Guidebook/Medical/MedicalDoctor.xml
> +Время лечить. Ну, по крайней мере время попытаться вылечить побитого беднягу перед вами. Врачи заботятся о каждой мелкой болячке, порезе, и отпадающей от некроза плоти - сотрудники станции в надежных
```suggestion
Время лечить. Ну, по крайней мере время попытаться вылечить побитого беднягу перед вами. Врачи заботятся о каждой мелкой болячке, порезе и отпадающей от некроза плоти - сотрудники станции в надежных руках.
```

2023-06-24 08:21 UTC, ficcialfaint commented on Resources/ServerInfo/Guidebook/Medical/MedicalDoctor.xml
> +Есть два способа понять, что не так с товарищем перед вами: Просканировать их анализатором здоровья (или вашим медицинским КПК), или провести визуальный осмотр, используя шифт+клик -> символ сердца н
```suggestion
Есть два способа понять, что не так с товарищем перед вами: Просканировать их анализатором здоровья (или вашим медицинским КПК) или провести визуальный осмотр, используя шифт-клик -> символ сердца на персонаже.
```

2023-06-24 08:21 UTC, ficcialfaint commented on Resources/ServerInfo/Guidebook/Medical/MedicalDoctor.xml
> +Осмотрите пациента и обратите внимание на основные детали: Они живы? Кровоточат? Какой тип урона угрожает их жизни?
```suggestion
Осмотрите пациента и обратите внимание на основные детали: Он жив? Кровоточит? Какой тип урона угрожает его жизни?
```
\- почему используется they в оригинале?
\- they используют, когда не знают род/гендер человека

2023-06-24 08:21 UTC, ficcialfaint commented on Resources/ServerInfo/Guidebook/Medical/MedicalDoctor.xml
> +Если они живы - приложите все усилия, чтобы восстановить их. Критическое состояние наступает при получении 100 общего урона и смерть при достижении в 200 урона. Имейте это в виду, выбирая, как вам сл
```suggestion
Если они живы - приложите все усилия, чтобы восстановить их. Критическое состояние наступает при получении 100 общего урона, и смерть при достижении в 200 урона. Имейте это в виду, выбирая, как вам следует поступить дальше. Экстренные медипены и эпинефрин часто используются для временной стабилизации критических пациентов.
```

2023-06-24 08:21 UTC, ficcialfaint commented on Resources/ServerInfo/Guidebook/Medical/MedicalDoctor.xml
> +Если есть возможность - уложите пациента на медицинскую кровать. Если пациент вот-вот откинет ноги - быстрей кладите его на стазисную кровать. Стазис замедлит все процессы в теле персонажа, в том чис
```suggestion
Если есть возможность - уложите пациента на медицинскую кровать. Если пациент вот-вот откинет ноги - быстрей кладите его на стазисную кровать. Стазис замедлит все процессы в теле персонажа, в том числе и процесс лечения. Как только вы выяснили чем лечить пациента, ввели ему необходимые лекарства шприцом - нужно снять его со стазис кровати, чтобы процесс лечения начался. (А вот предметы первой помощи, вроде мазей, наборов и мешков с кровью будут работать, игнорируя свойства стазисной кровати)
```
чтобы не повторялось

2023-06-24 08:21 UTC, ficcialfaint commented on Resources/ServerInfo/Guidebook/Medical/MedicalDoctor.xml
> +Не всегда удаётся спасти всех, иногда, смерть всё же берёт своё. В зависимости от статуса тела, наличия души и того, гниёт тело или нет, есть несколько способов вернуть персонажа с того света.
```suggestion
Не всегда удаётся спасти всех, иногда смерть всё же берёт своё. В зависимости от статуса тела, наличия души и того, гниёт тело или нет, есть несколько способов вернуть персонажа с того света.
```

2023-06-24 08:21 UTC, ficcialfaint commented on Resources/ServerInfo/Guidebook/Medical/MedicalDoctor.xml
> +1. У тела осталась привязанная душа? Это можно понять, проведя внешний осмотр и увидев фразу в красном цвете: "Душа покинула тело." Если этой надписи нет - сохраните тело в морге или используйте для
```suggestion
1. У тела осталась привязанная душа? Это можно понять, проведя внешний осмотр и увидев фразу красного цвета: "Душа покинула тело." Если этой надписи нет - сохраните тело в морге или используйте для биомассы.
```

2023-06-24 08:21 UTC, ficcialfaint commented on Resources/ServerInfo/Guidebook/Service/FoodRecipes.xml
> +- Кукурузное тесто= 1 яйцо (6u), 10 молока, 15 кукурузной муки
```suggestion
- Кукурузное тесто = 1 яйцо (6 ед.), 10 молока, 15 кукурузной муки
```

2023-06-24 09:54 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Engineering/NetworkConfigurator.xml
> +Когда вы закончили соединять желаемые порты, нажмите на [color=gray]ok[/color] чтобы закрыть интерфейс.
![image](https://github.com/space-syndicate/space-station-14/assets/124214523/f1d5c4f5-6dd4-4269-aa8a-b3387295faa6)

2023-07-01 15:30 UTC, closed without merging