Убрать некоторое дерьмо со списка наград экспедиций
space-syndicate/space-station-14 pull request #1173
Opened 2023-06-25 08:31 UTC by lzk228

## Описание PR

Убрано: семена гатфрукта, с20-r, РПГ

**Медиа**

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

no cl?

2023-06-25 08:52 UTC, Myakot commented
cl то может написать?

2023-06-25 09:16 UTC, Anzarot121 commented
Эм, но ведь контрабанда тут только гатфрукт.

2023-06-25 09:19 UTC, lzk228 commented
> Эм, но ведь контрабанда тут только гатфрукт.

Это награды от НТ, представь, как на научную станцию присылают вражеское снаряжение и ебучий РПГ

2023-06-25 09:22 UTC, Anzarot121 commented
Тогда уж и лазерки с Христовым убирать надо.

2023-06-25 09:25 UTC, Myakot commented
> Тогда уж и лазерки с Христовым убирать надо.

Лазерки крафтятся на техфабах НТ
Христов мапперами сделан в оружейках

А вот у C20-r прямо в описании сказано, что это визитка ЯО, РПГ это просто бредятина (и взрывчатка - на нашем сервере подобное подходит под статью КЗ)

2023-06-26 01:20 UTC, Morb0 requested changes
комменты к изменениям, ex `# Corvax-MRP`

2023-06-28 13:19 UTC, Morb0 approved these changes

2023-06-28 14:59 UTC, merged