Перевод Upstream #1174
space-syndicate/space-station-14 pull request #1180
Opened 2023-06-28 14:53 UTC by lzk228

## Описание PR

**Медиа**

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:
- add: Добавлены переводы!

2023-06-28 15:58 UTC, ficcialfaint requested changes

2023-06-28 15:58 UTC, ficcialfaint commented on Resources/Locale/ru-RU/lube/lube.ftl
> +lubed-name-prefix = смазаный { $target }
```suggestion
lubed-name-prefix = смазанный { $target }
```

2023-06-28 15:58 UTC, ficcialfaint commented on Resources/Locale/ru-RU/lube/lube.ftl
> +lube-slip = { $target } выскальзывает с ваших рук!
```suggestion
lube-slip = { $target } выскальзывает из ваших рук!
```

2023-06-28 15:58 UTC, ficcialfaint commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/hands/gloves.ftl
> +    .desc = Высококачественные боевые перчатки, для защиты рук во время боя.
```suggestion
    .desc = Высококачественные боевые перчатки для защиты рук во время боя.
```

2023-06-28 15:58 UTC, ficcialfaint commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/walls/asteroid.ftl
> +    .suffix = серебро
```suggestion
    .suffix = Серебро
```

2023-06-28 15:58 UTC, ficcialfaint commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/power/generation/ame.ftl
> +ent-AMEController = Контроллер ДАМ
нет.
```yaml
- type: entity
  id: AmeController
```
А зачем с большой буквы я вообще понять не могу

2023-06-28 15:58 UTC, ficcialfaint commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/machines/computers/computers.ftl
> +    .desc = Используется для управления текущими активными запросами.>>>>>>> Stashed changes
```suggestion
    .desc = Используется для управления текущими активными запросами.
```

2023-06-28 15:58 UTC, ficcialfaint commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/specific/medical/healing.ftl
> +ent-PillBicaridine = таблетка бикаридина (10u)
```suggestion
ent-PillBicaridine = таблетка бикаридина (10ед)
```

2023-06-28 15:58 UTC, ficcialfaint commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/power/antimatter_jar.ftl
> +ent-AMEJar = топливный бак ДАМ
![image](https://github.com/space-syndicate/space-station-14/assets/46868845/793111ef-5334-4960-a8e7-68749845fe10)

2023-06-28 15:58 UTC, ficcialfaint commented on Resources/Locale/ru-RU/cargo/bounties.ftl
> +bounty-item-clown-mask = Маска и парик клоуна
```suggestion
bounty-item-clown-mask = Клоунская маска
```

2023-06-28 15:58 UTC, ficcialfaint commented on Resources/Locale/ru-RU/cargo/bounties.ftl
> +bounty-item-cuban-carp = Кубинский карп
```suggestion
bounty-item-cuban-carp = Карп по-Кубински
```

2023-06-28 15:58 UTC, ficcialfaint commented on Resources/Locale/ru-RU/cargo/bounties.ftl
> +bounty-description-artifact = Nanotrasen находится в затруднительном положении из-за кражи артефактов с не космических планет. Верните один, и мы выплатим за него компенсацию.
```suggestion
bounty-description-artifact = Nanotrasen находится в затруднительном положении из-за кражи артефактов с некосмических планет. Верните один, и мы выплатим за него компенсацию.
```

2023-06-28 15:58 UTC, ficcialfaint commented on Resources/Locale/ru-RU/cargo/bounties.ftl
> +bounty-description-box-hugs = Несколько главных чиновников получили серьезные ушибы. Для их выздоровления срочно требуется коробка с объятиями.
```suggestion
bounty-description-box-hugs = Несколько главных чиновников получили серьезные ушибы. Для их выздоровления срочно требуется коробка обнимашек
```

2023-06-28 15:58 UTC, ficcialfaint commented on Resources/Locale/ru-RU/cargo/bounties.ftl
> +bounty-description-brain = Коммандер Колдуэлл лишилась мозга в результате недавней аварии с космической смазкой. К сожалению, мы не можем нанять замену, поэтому просто пришлите нам новый мозг, чтобы
```suggestion
bounty-description-brain = Командир Колдуэлл лишилась мозга в результате недавней аварии с космической смазкой. К сожалению, мы не можем нанять замену, поэтому просто пришлите нам новый мозг, чтобы вставить его в неё.
```

2023-06-28 15:58 UTC, ficcialfaint commented on Resources/Locale/ru-RU/cargo/bounties.ftl
> +bounty-description-cuban-carp = В честь рождения Кастро XXVII отправьте одного кубинского карпа в Центком.
```suggestion
bounty-description-cuban-carp = В честь рождения Кастро XXVII отправьте одного карпа по-Кубински в Центком.
```

2023-06-28 18:04 UTC, lapatison commented on Resources/Locale/ru-RU/lube/lube.ftl
> +lubed-name-prefix = смазаный { $target }
Лучше `скользкий` чем `смазанный`. Не интуитивно. Смазанный чем? Клеем?

2023-06-28 18:11 UTC, lapatison commented on Resources/Locale/ru-RU/cargo/bounties.ftl
> +bounty-item-cuban-carp = Кубинский карп
по-кубински

2023-06-28 18:15 UTC, lapatison commented on Resources/Locale/ru-RU/cargo/bounties.ftl
> +bounty-description-cuban-carp = В честь рождения Кастро XXVII отправьте одного кубинского карпа в Центком.
по-кубински

2023-06-28 18:19 UTC, lapatison commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/uniforms/jumpsuits.ftl
> +    .desc = Униформа для оперативных LARPеров, выполняющих тактические кражи утепленных перчаток в глубоком космосе.
```suggestion
    .desc = Униформа для оперативных LARPеров, выполняющих тактические кражи изолированных 
 перчаток в глубоком космосе.
```

2023-06-28 18:19 UTC, lapatison commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/uniforms/jumpsuits.ftl
> +    .desc = Униформа для оперативных LARPеров, выполняющих тактические кражи утепленных перчаток в глубоком космосе.
```suggestion
    .desc = Униформа для оперативных LARPеров, выполняющих тактические кражи изолированных перчаток в глубоком космосе.
```

2023-06-28 18:20 UTC, lapatison commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/devices/circuitboards/computer.ftl
> +ent-CargoBountyComputerCircuitboard = косноль запросов (консольная плата)
```suggestion
ent-CargoBountyComputerCircuitboard = консоль запросов (консольная плата)
```

2023-06-28 18:21 UTC, lapatison commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/shields/shields.ftl
> +ent-EnergyShield = энерго-щит
без дефиса

2023-06-28 18:21 UTC, lzk228 commented on Resources/Locale/ru-RU/cargo/bounties.ftl
> +bounty-description-cuban-carp = В честь рождения Кастро XXVII отправьте одного кубинского карпа в Центком.
с большой

2023-06-28 18:23 UTC, lapatison commented on Resources/Locale/ru-RU/store/uplink-catalog.ftl
> +uplink-eshield-desc = Экзотический энерго-щит, отражающий почти все лазерные лучи, а также немного защищающий от пуль и других физических атак.
```suggestion
uplink-eshield-name = Энергощит
uplink-eshield-desc = Экзотический энергощит, отражающий почти все лазерные лучи, а также немного защищающий от пуль и других физических атак.
```

2023-06-28 18:41 UTC, lapatison commented on Resources/Locale/ru-RU/cargo/bounties.ftl
> +bounty-description-cuban-carp = В честь рождения Кастро XXVII отправьте одного кубинского карпа в Центком.
[не совсем то правило, но `по-русски, по-немецки` ты там увидишь
](https://orfogrammka.ru/%D0%BE%D1%80%D1%84%D0%BE%D0%B3%D1%80%D0%B0%D1%84%D0%B8%D1%8F/%D0%BD%D0%B0%D1%80%D0%B5%D1%87%D0%B8%D1%8F_%D1%81_%D0%BF%D1%80%D0%B8%D1%81%D1%82%D0%B0%D0%B2%D0%BA%D0%BE%D0%B9_%D0%BF%D0%BE_%D0%BE%D0%BA%D0%B0%D0%BD%D1%87%D0%B8%D0%B2%D0%B0%D1%8E%D1%89%D0%B8%D0%B5%D1%81%D1%8F_%D0%BD%D0%B0_%D0%BE%D0%BC%D1%83_%D0%B5%D0%BC%D1%83_%D1%81%D0%BA%D0%B8_%D1%86%D0%BA%D0%B8_%D1%8C%D0%B8/)

2023-06-28 18:44 UTC, lzk228 commented on Resources/Locale/ru-RU/cargo/bounties.ftl
> +bounty-description-cuban-carp = В честь рождения Кастро XXVII отправьте одного кубинского карпа в Центком.
в игре он с большой

2023-06-28 18:46 UTC, lapatison commented on Resources/Locale/ru-RU/cargo/bounties.ftl
> +bounty-description-cuban-carp = В честь рождения Кастро XXVII отправьте одного кубинского карпа в Центком.
Моя старая ошибка, хорошо что заметил, исправишь? И начос

2023-06-29 23:21 UTC, ficcialfaint approved these changes
LGTM

2023-06-30 22:42 UTC, Morb0 approved these changes

2023-06-30 22:42 UTC, merged