aghost icons resprite
space-syndicate/space-station-14 pull request #1181
Opened 2023-06-30 02:57 UTC by kxvvv

## Описание PR

**Медиа**

![image](https://github.com/space-syndicate/space-station-14/assets/136233650/15a0be1d-97a6-455c-92aa-23de58492cbf)
![image](https://github.com/space-syndicate/space-station-14/assets/136233650/042b4bc3-6e7c-4692-8557-da09e74a06f0)

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:
- tweak: Изменено веселье админов!

2023-06-30 07:16 UTC, Krosus777 commented
Может не солнце, а панели?

2023-06-30 18:06 UTC, kxvvv commented
> Может не солнце, а панели?

завтра залью

2023-07-02 03:54 UTC, kxvvv commented
![image](https://github.com/space-syndicate/space-station-14/assets/136233650/1c9d6f17-879d-48fd-84d8-253f092e84e7)

2023-07-02 14:16 UTC, ficcialfaint requested changes

2023-07-02 14:16 UTC, ficcialfaint commented on Resources/Textures/Corvax/Interface/AdminActions/meta.json
Мета здесь не нужна, т.к. это не RSI

2023-07-04 00:31 UTC, ficcialfaint approved these changes

2023-07-04 00:31 UTC, merged

2023-07-04 00:31 UTC, ficcialfaint commented
Спасибо!