Перевод Upstream #1186, Upstream #1187
space-syndicate/space-station-14 pull request #1188
Opened 2023-07-04 18:13 UTC by lapatison

## Описание PR

**Медиа**

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:
- add: Добавлены переводы

2023-07-04 18:40 UTC, lzk228 commented on Resources/Locale/ru-RU/fluids/components/drain-component.ftl
> +drain-component-empty-verb-using-is-empty-message = { CAPITALIZE(THE($object)) } пуста!
```suggestion
drain-component-empty-verb-using-is-empty-message = { CAPITALIZE($object) } пуста!
```

2023-07-04 18:40 UTC, lzk228 commented on Resources/Locale/ru-RU/fluids/components/drain-component.ftl
> +drain-component-empty-verb-target-is-full-message = { CAPITALIZE(THE($object)) } полна!
```suggestion
drain-component-empty-verb-target-is-full-message = { CAPITALIZE($object) } полна!
```

2023-07-04 18:40 UTC, lzk228 commented on Resources/Locale/ru-RU/fluids/components/drain-component.ftl
> +drain-component-examine-hint-full = [color="blue"]Она заполнена до краёв. Может, вантуз поможет?[/color]
```suggestion
drain-component-examine-hint-full = [color="blue"]Он заполнен до краёв. Может, вантуз поможет?[/color]
```
Так звучит логичнее, так как это применяется только к дренажу, а дренаж - он.

2023-07-04 18:40 UTC, lzk228 commented on Resources/Locale/ru-RU/fluids/components/drain-component.ftl
> +drain-component-unclog-notapplicable = { CAPITALIZE(THE($object)) } не заполнена.
```suggestion
drain-component-unclog-notapplicable = { CAPITALIZE($object) } не заполнена.
```

2023-07-04 18:40 UTC, lzk228 commented on Resources/Locale/ru-RU/fluids/components/drain-component.ftl
> +drain-component-examine-hint-full = [color="blue"]Она заполнена до краёв. Может, вантуз поможет?[/color]
Ниже такое же

2023-07-04 18:40 UTC, lzk228 commented on Resources/Locale/ru-RU/glue/glue.ftl
>  glue-success = Вы покрыли { $target } клеем.
```suggestion
glue-success = Вы покрыли { $target } клеем!
```
![зображення](https://github.com/space-syndicate/space-station-14/assets/124214523/75eabb4b-9cce-4380-9e6a-e86ddce334e1)

2023-07-04 20:14 UTC, lapatison commented on Resources/Locale/ru-RU/fluids/components/drain-component.ftl
> +drain-component-examine-hint-full = [color="blue"]Она заполнена до краёв. Может, вантуз поможет?[/color]
С недавнего ПРа к раковинам тоже. Сделаю нейтрально.

2023-07-05 10:53 UTC, lzk228 commented on Resources/Locale/ru-RU/fluids/components/drain-component.ftl
> +drain-component-empty-verb-inhand = Вылить { $object }
Опустошить?

2023-07-05 10:54 UTC, lapatison commented on Resources/Locale/ru-RU/fluids/components/drain-component.ftl
> +drain-component-empty-verb-inhand = Вылить { $object }
Вылить - конкретнее

2023-07-05 16:56 UTC, lzk228 commented on Resources/Locale/ru-RU/fluids/components/drain-component.ftl
> +drain-component-empty-verb-inhand = Вылить { $object }
всё же, "Вылить мензурка" звучит хуже чем "Опустошить мензурка"
https://user-images.githubusercontent.com/29918611/224519454-aea6adf3-012e-4a13-a3e7-051e8f972e34.mp4

2023-07-05 17:02 UTC, lapatison commented on Resources/Locale/ru-RU/fluids/components/drain-component.ftl
> +drain-component-empty-verb-inhand = Вылить { $object }
Мензурка - хуже
А стакан, ведро - лучше

2023-07-06 02:11 UTC, ficcialfaint requested changes

2023-07-06 02:11 UTC, ficcialfaint commented on Resources/Locale/ru-RU/construction/conditions/no-unstackable-in-tile.ftl
> +construction-step-condition-no-unstackable-in-tile = Вы не можете поместить несколько одинаковых устройств в одну клетку.
```suggestion
construction-step-condition-no-unstackable-in-tile = Вы не можете поместить несколько устройств в стопку.
```

2023-07-06 02:11 UTC, ficcialfaint commented on Resources/Locale/ru-RU/fluids/components/drain-component.ftl
> +drain-component-empty-verb-target-is-full-message = Устройство { $object } переполнилось!
```suggestion
drain-component-empty-verb-target-is-full-message = { $object } полно!
```

2023-07-06 02:11 UTC, ficcialfaint commented on Resources/Locale/ru-RU/fluids/components/drain-component.ftl
> +drain-component-empty-verb-inhand = Вылить { $object }
соглашусь, что лучше наверное «опустошить»

2023-07-06 02:11 UTC, ficcialfaint commented on Resources/Locale/ru-RU/fluids/components/drain-component.ftl
> +drain-component-examine-volume = [color=cyan]Доступный объём - { $volume } ед.[/color]
а почему цвет другой?

2023-07-06 02:11 UTC, ficcialfaint commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/uniforms/ship_vs_ship.ftl
> +    .desc = Злодейского вида комбинезон со светоотражающим жилетом и красной рубашкой.
А зачем в названии везде указывать Nanotrasen?

2023-07-06 05:42 UTC, lapatison commented on Resources/Locale/ru-RU/construction/conditions/no-unstackable-in-tile.ftl
> +construction-step-condition-no-unstackable-in-tile = Вы не можете поместить несколько одинаковых устройств в одну клетку.
Стопка устройств оч странно звучит

2023-07-06 05:43 UTC, lapatison commented on Resources/Locale/ru-RU/fluids/components/drain-component.ftl
> +drain-component-examine-volume = [color=cyan]Доступный объём - { $volume } ед.[/color]
Не так вырвиглазно

2023-07-06 05:46 UTC, lapatison commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/uniforms/ship_vs_ship.ftl
> +    .desc = Злодейского вида комбинезон со светоотражающим жилетом и красной рубашкой.
Сначала я дописал к комбинезону СИ, чтобы он отличался от дефолтного комбинезона СИ, потом дописал к остальным чтобы соблюсти стилистику Синдикат vs НТ.

Вернуть обратно и указать для комбинезона СИ в суффиксе?

2023-07-06 07:32 UTC, ficcialfaint commented on Resources/Locale/ru-RU/construction/conditions/no-unstackable-in-tile.ftl
> +construction-step-condition-no-unstackable-in-tile = Вы не можете поместить несколько одинаковых устройств в одну клетку.
да вроде бы в контексте игры звучит нормально

2023-07-06 07:33 UTC, ficcialfaint commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/uniforms/ship_vs_ship.ftl
> +    .desc = Злодейского вида комбинезон со светоотражающим жилетом и красной рубашкой.
Учитывая, что, как я понял, эта одежда для какого-то вообще другого режима, то думаю, там будет неважно, обычный костюм это или НТ, так что я бы не указывал это нигде, а оставил все как у оффов (естснственно, с переводом)

2023-07-06 18:08 UTC, lapatison commented on Resources/Locale/ru-RU/fluids/components/drain-component.ftl
> +drain-component-empty-verb-inhand = Вылить { $object }
И всё же я настаиваю на `вылить`

2023-07-07 16:12 UTC, merged