hamlet
space-syndicate/space-station-14 pull request #1192
Opened 2023-07-07 20:51 UTC by kxvvv

## Описание PR

Милорд, люди очень просят убрать то чудище что добавили оффы.

**Медиа**

![image](https://github.com/space-syndicate/space-station-14/assets/136233650/c7e34440-c604-413a-9593-ca145f5d3260)  ![image](https://github.com/space-syndicate/space-station-14/assets/136233650/182aaae7-c3aa-4478-808e-66560d76f7ce)

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:
- tweak: Гамлет сходил к косметологу!

2023-07-07 21:26 UTC, lzk228 commented
респрайт должен быть в `Textures/Mobs/Pets/hamlet.rsi`, в прототипе указать этот путь, оставив комментарий

2023-07-08 07:48 UTC, lzk228 requested changes
копирайт поменяй

2023-07-08 16:04 UTC, kxvvv commented
> копирайт поменяй

а еще чего

2023-07-08 16:13 UTC, lzk228 commented
стоп, чел, нахуя ты делаешь пр с респрайтом, если респрайт будет в апстриме?

2023-07-11 11:53 UTC, lzk228 approved these changes

2023-07-13 10:13 UTC, lzk228 requested changes

2023-07-13 10:13 UTC, lzk228 commented on Resources/Prototypes/Entities/Mobs/NPCs/pets.yml
>    - type: Sprite
ты можешь удалить новый респрайт и просто вынести под коменты этот компонент в прототипе гамлета, тогда он будет использоваться от хомяка

2023-07-26 18:23 UTC, closed without merging