Перевод Upstream #1191
space-syndicate/space-station-14 pull request #1193
Opened 2023-07-10 12:53 UTC by lzk228

## Описание PR

**Медиа**

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:
- add: Добавлены переводы!

2023-07-10 17:18 UTC, lapatison commented on Resources/Locale/ru-RU/nutrition/components/animal-husbandry.ftl
> +infant-name-prefix = ребёнок { $name }
```suggestion
infant-name-prefix = детёныш{ $name }
```

2023-07-10 17:19 UTC, lapatison commented on Resources/Locale/ru-RU/objectives/conditions/kill-head-condition.ftl
> +objective-condition-kill-head-description = Нам нужно, чтобы этот начальник умер, и вы, вероятно, знаете, почему. Удачи, агент.
```suggestion
objective-condition-kill-head-description = Нам нужно, чтобы этот глава исчёз, и вы, вероятно, знаете, почему. Удачи, агент.
```

2023-07-10 17:20 UTC, lapatison commented on Resources/Locale/ru-RU/objectives/conditions/kill-person-condition.ftl
> +objective-condition-kill-person-title = Убейте {$targetName} или не дайте ему покинуть станцию.
```suggestion
objective-condition-kill-person-title = Убейте или не дайте покинуть станцию { $targetName }.
```

2023-07-10 17:22 UTC, lapatison commented on Resources/Locale/ru-RU/prototypes/catalog/fills/crates/fun-crates.ftl
> +    .desc = Тысяча гудков в день отпугивает сотрудников службы безопасности!
Может можно сохранить рифму?

2023-07-10 17:23 UTC, lapatison commented on Resources/Locale/ru-RU/reagents/meta/medicine.ftl
> +reagent-desc-ambuzol = Высокотехнологичное средство, способное остановить развитие зомби-инфекции.
```suggestion
reagent-desc-ambuzol = Высокотехнологичный препарат, способный остановить развитие зомби-вируса.
```

2023-07-10 17:25 UTC, lapatison commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/head/hats.ftl
> +ent-ClothingHeadHatTacticalMaidHeadband = тактическая повязка на голову горничной
```suggestion
ent-ClothingHeadHatTacticalMaidHeadband = тактическая головная повязка горничной
```

2023-07-10 17:28 UTC, PuroSlavKing commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/head/hats.ftl
> +    .desc = Сувенирная шапка от "Синдиленда", производство которой уже закрыто.
**из** "Синдиленда"

2023-07-10 17:28 UTC, PuroSlavKing commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/head/hats.ftl
> +ent-ClothingHeadHatTacticalMaidHeadband = тактическая повязка на голову горничной
тактическая повязка горничной

2023-07-10 17:29 UTC, lapatison commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/specific/medical/healing.ftl
> +    .desc = Применяется для лечения даже самых неприятных ожогов. Эффективен также при кислотных ожогах.
Эффективна

2023-07-10 17:29 UTC, PuroSlavKing commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/masks/masks.ftl
> +ent-ClothingMaskNeckGaiter = шарф-труба
гетр = гетр

2023-07-10 17:30 UTC, PuroSlavKing commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/masks/masks.ftl
> +    .desc = Стильный шарф-труба, способный защитить от космического ветра?...
Стильный шарф-труба, моя твоя уважать

2023-07-10 17:31 UTC, PuroSlavKing commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/outerclothing/coats.ftl
> +    .desc = Плащ Синдиката, изготовлен из прочной ткани, украшен позолоченными узорами.
Так всё-таки плащ, или тренч?

2023-07-10 17:33 UTC, lapatison commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/decoration/banners.ftl
> +    .desc = Знамя, с которого, по мнению синдиката, следует испытывать ненависть к NT.
странно звучит

2023-07-10 17:34 UTC, lapatison commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/wallmounts/signs/paintings.ftl
> +    .desc = Эта картина - грустный клоун! Он вызывает радость.
```suggestion
    .desc = На этой картине изображен грустный клоун! Она вызывает радость.
```
+ я бы заменил грустного на печального

2023-07-10 17:35 UTC, lapatison commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/head/hats.ftl
> +    .desc = Сувенирная шапка от "Синдиленда", производство которой уже закрыто.
Да и кавычки я бы убрал. Диснейленд же мы без кавычек пишем

2023-07-10 17:54 UTC, lzk228 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/decoration/banners.ftl
> +    .desc = Знамя, с которого, по мнению синдиката, следует испытывать ненависть к NT.
@PuroSlavKing

2023-07-10 17:58 UTC, lzk228 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/outerclothing/coats.ftl
> +    .desc = Плащ Синдиката, изготовлен из прочной ткани, украшен позолоченными узорами.
сделал по примуре тренча гсб
![зображення](https://github.com/space-syndicate/space-station-14/assets/124214523/c2ce9902-567d-45cf-9250-d76e198bd2a2)

2023-07-10 17:59 UTC, lzk228 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/outerclothing/wintercoats.ftl
> +ent-ClothingOuterWinterSyndieCap = зимнее пальто Синдиката
зимнее пальто

2023-07-10 18:17 UTC, PuroSlavKing commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/decoration/banners.ftl
> +    .desc = Знамя, с которого, по мнению синдиката, следует испытывать ненависть к NT.
Знамя, из-за которого по мнению синдиката, вы должны возненавидеть NT

2023-07-12 10:52 UTC, PuroSlavKing commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/specific/medical/healing.ftl
> +ent-SyringeAmbuzol = шприц амбузолв
Ошибк

2023-07-17 16:34 UTC, ficcialfaint requested changes

2023-07-17 16:34 UTC, ficcialfaint commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/masks/masks.ftl
> +ent-ClothingMaskNeckGaiter = гетр
гетр — это одежда на ноги

2023-07-17 16:34 UTC, ficcialfaint commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/outerclothing/armor.ftl
>  ent-ClothingOuterArmorBasicSlim = armor vest
а где перевод?

2023-07-17 16:34 UTC, ficcialfaint commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/outerclothing/armor.ftl
> -    .desc = Бронежилет с тяжелыми пластинами для защиты от баллистических снарядов.
зачем местами поменял?

2023-07-17 16:34 UTC, ficcialfaint commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/wallmounts/signs/posters.ftl
> +    .desc = Плакат с изображением тех деталей, которые делают вас... вами!
```suggestion
    .desc = Плакат с изображением тех. деталей, которые делают вас... вами!
```

2023-07-17 16:34 UTC, ficcialfaint commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/misc/fluff_lights.ftl
> +    .desc = Сверхъяркая лампа для плохого полицейского.
```suggestion
    .desc = Сверхъяркая лампа для плохого копа.
```

2023-07-17 16:34 UTC, ficcialfaint commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/outerclothing/vests.ftl
> +    .desc = Высококачественный бронежилет из прочного синтетического материала. Он удивительно гибкий и легкий, несмотря на внушительную броню.
зачем

2023-07-17 16:37 UTC, PuroSlavKing commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/masks/masks.ftl
> +ent-ClothingMaskNeckGaiter = гетр
> гетр — это одежда на ноги

Лайфхак, теперь загугли шейный гетр

2023-07-17 16:37 UTC, PuroSlavKing commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/wallmounts/signs/posters.ftl
> +    .desc = Плакат с изображением тех деталей, которые делают вас... вами!
> 

После "." Слово начинается с большой буквы

2023-07-17 16:39 UTC, ficcialfaint commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/masks/masks.ftl
> +ent-ClothingMaskNeckGaiter = гетр
ну так в этом и проеб что в оригинале указано, что это шейное, а в переводе - нет

2023-07-17 16:39 UTC, ficcialfaint commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/wallmounts/signs/posters.ftl
> +    .desc = Плакат с изображением тех деталей, которые делают вас... вами!
впервые слышишь про сокращения слов с точкой на конце?

2023-07-17 16:41 UTC, PuroSlavKing commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/wallmounts/signs/posters.ftl
> +    .desc = Плакат с изображением тех деталей, которые делают вас... вами!
> впервые слышишь про сокращения слов с точкой на конце?

А как звучит не сокращённо "тех"? Впервые слышу, что это слово сокращение

2023-07-17 16:45 UTC, ficcialfaint commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/wallmounts/signs/posters.ftl
> +    .desc = Плакат с изображением тех деталей, которые делают вас... вами!
![image](https://github.com/space-syndicate/space-station-14/assets/46868845/f4dd79f6-5464-417a-b722-c065c548c087)

2023-07-17 17:29 UTC, lzk228 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/outerclothing/armor.ftl
> -    .desc = Бронежилет с тяжелыми пластинами для защиты от баллистических снарядов.
так как в английском файле локали

2023-07-17 17:29 UTC, lzk228 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/outerclothing/vests.ftl
> +    .desc = Высококачественный бронежилет из прочного синтетического материала. Он удивительно гибкий и легкий, несмотря на внушительную броню.
так как в английском файле локали

2023-07-19 10:49 UTC, ficcialfaint approved these changes

2023-07-19 11:25 UTC, merged