Перевод ивента с пауками из вентиляции
space-syndicate/space-station-14 pull request #122
Opened 2022-02-27 11:15 UTC by lapatison

## Описание PR 

**Скриншоты**

**Изменения**

:cl: lapatison
- add: Частичный перевод.

2022-02-27 16:50 UTC, Morb0 commented on Resources/Locale/ru-RU/station-events/events/vent-critters.ftl
> +station-event-vent-spiders-start-announcement = Опираясь на { $data }, мы полагаем, что небольшая колония неизвестных организмов обосновалась внутри вентиляции станции, и предприняли меры по их изгна
Звучит странно последняя часть после запятой. Похоже, что там должно говориться что бы приняли меры по их устранению.

2022-02-27 16:57 UTC, lapatison commented on Resources/Locale/ru-RU/station-events/events/vent-critters.ftl
> +station-event-vent-spiders-start-announcement = Опираясь на { $data }, мы полагаем, что небольшая колония неизвестных организмов обосновалась внутри вентиляции станции, и предприняли меры по их изгна
Мне кажется что речь об освобождении труб\выселении пауков из труб. Думаю "изгнание" и правда стоит заменить.

2022-02-27 21:28 UTC, Morb0 commented on Resources/Locale/ru-RU/station-events/events/vent-critters.ftl
> +station-event-vent-spiders-start-announcement = Опираясь на { $data }, мы полагаем, что небольшая колония неизвестных организмов обосновалась внутри вентиляции станции, и предприняли меры по их изгна
Но они и не устранили их

2022-02-27 22:12 UTC, lapatison commented on Resources/Locale/ru-RU/station-events/events/vent-critters.ftl
> +station-event-vent-spiders-start-announcement = Опираясь на { $data }, мы полагаем, что небольшая колония неизвестных организмов обосновалась внутри вентиляции станции, и предприняли меры по их изгна
А такой вариант?

2022-02-27 22:31 UTC, Morb0 requested changes

2022-02-27 22:31 UTC, Morb0 commented on Resources/Locale/ru-RU/station-events/events/vent-critters.ftl
> +station-event-vent-spiders-start-announcement = Опираясь на { $data }, мы полагаем, что небольшая колония неизвестных организмов обосновалась внутри вентиляции станции, и предприняли меры по их выдво
```suggestion
station-event-vent-spiders-start-announcement = Опираясь на { $data }, мы полагаем, что небольшая колония неизвестных организмов обосновалась внутри вентиляции станции, и мы предприняли меры по выдворению их оттуда.
```

2022-02-28 07:56 UTC, Morb0 approved these changes

2022-02-28 08:02 UTC, merged