Перевод Upstream #1227
space-syndicate/space-station-14 pull request #1232
Opened 2023-07-28 21:58 UTC by lapatison

## Описание PR

**Медиа**

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:
- add: Добавлены переводы

2023-07-28 22:10 UTC, lzk228 commented on Resources/Locale/ru-RU/job/job-description.ftl
> +job-description-boxer = Пробейтесь на вершину! Бросьте вызов главе персонала и будьте арестованы когда выиграете. Эта должность доступна на станциях Core и Origin.
```suggestion
job-description-boxer = Пробейтесь на вершину! Бросьте вызов главе персонала и будьте арестованы когда выиграете. Эта должность доступна на станциях Core, Origin и Avrite.
```

2023-07-28 22:10 UTC, lzk228 commented on Resources/Locale/ru-RU/job/job-description.ftl
> +job-description-psychologist = Оказывайте эмоциональную поддержку психологически травмированному экипажу. Эта должность доступна на станциях Box, Marathon, и Origin.
```suggestion
job-description-psychologist = Оказывайте эмоциональную поддержку психологически травмированному экипажу. Эта должность доступна на станциях Box, Marathon, Origin, Avrite и Delta.
```

2023-07-28 22:10 UTC, lzk228 commented on Resources/Locale/ru-RU/job/job-description.ftl
> +job-description-reporter = Развлекайте и информируйте экипаж своей журналистской деятельностью посредством беспроводных камер и радио. Эта должность доступна на станциях Bagel и Core.
```suggestion
job-description-reporter = Развлекайте и информируйте экипаж своей журналистской деятельностью посредством беспроводных камер и радио. Эта должность доступна на станциях Bagel, Core, Avrite и Delta.
```

2023-07-28 22:10 UTC, lzk228 commented on Resources/Locale/ru-RU/job/job-description.ftl
> +job-description-zookeeper = Устройте веселое шоу с милыми животными и космическими карпами, чтобы все члены экипажа могли ими полюбоваться. Эта должность доступна на станции Kettle Station.
```suggestion
job-description-zookeeper = Устройте веселое шоу с милыми животными и космическими карпами, чтобы все члены экипажа могли ими полюбоваться. Эта должность доступна на станциях Kettle и Avrite.
```

2023-07-28 22:10 UTC, lzk228 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/head/hats.ftl
> +ent-ClothingHeadHatCapcap = кепи кепа
может лучше фуражка?

2023-07-28 22:10 UTC, lzk228 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/machines/computers/computers.ftl
> +    .desc = Отправьте свое послание миру!
```suggestion
    .desc = Отправьте своё послание миру!
```

2023-07-28 22:10 UTC, lzk228 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/storage/crates/crates.ftl
>  ent-CrateStoneGrave = grave
```suggestion
ent-CrateStoneGrave = могила
```

2023-07-28 22:11 UTC, lapatison commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/head/hats.ftl
> +ent-ClothingHeadHatCapcap = кепи кепа
и испортить такой каламбур?

2023-07-28 22:16 UTC, lzk228 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/head/hats.ftl
> +ent-ClothingHeadHatCapcap = кепи кепа
с такой стороны да, кепи лучше

2023-07-28 22:48 UTC, Morb0 requested changes

2023-07-28 22:48 UTC, Morb0 commented on Resources/Locale/ru-RU/game-ticking/game-presets/preset-zombies.ftl
> +zombie-shuttle-call = Мы зафиксировали, что зомби захватили станцию. Аварийный шаттл был отправлен для подбора оставшегося персонала.
В оригинале мне тоже не нравиться `collect`, это не такси.
```suggestion
zombie-shuttle-call = Мы зафиксировали, что зомби захватили станцию. Аварийный шаттл был отправлен для эвакуации оставшегося персонала.
```

2023-07-29 11:23 UTC, Morb0 requested changes

2023-07-29 11:23 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/outerclothing/hardsuits.ftl
> +ent-ClothingOuterHardsuitSalvage = скафандр шахтёра
Почему?

2023-07-29 11:26 UTC, lapatison commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/outerclothing/hardsuits.ftl
> +ent-ClothingOuterHardsuitSalvage = скафандр шахтёра
Оффы
https://github.com/space-syndicate/space-station-14/blob/2b5c72d1da5a3b4d00175beeaccdda64e41a3129/Resources/Locale/en-US/ss14-ru/prototypes/entities/clothing/outerclothing/hardsuits.ftl#L9

2023-07-29 16:10 UTC, merged