Респрайт командного ящика
space-syndicate/space-station-14 pull request #1258
Opened 2023-08-04 09:18 UTC by LinkUyx

## Описание PR

**Медиа**

![Content Client_GG7Or64goc](https://github.com/space-syndicate/space-station-14/assets/131011403/5d4704b5-212f-4c90-8085-58569cf3a098)
![Content Client_Kq5ekkLADD](https://github.com/space-syndicate/space-station-14/assets/131011403/ad85278e-9bc1-4b3e-b64c-9582acd5d9e6)
![Content Client_1afwJ9T4V8](https://github.com/space-syndicate/space-station-14/assets/131011403/7f43ffc8-dd02-4a11-a63e-3868e611a660)

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: mureixlol
- tweak: Изменен спрайт командного ящика

2023-08-04 10:32 UTC, lzk228 approved these changes

2023-08-04 14:40 UTC, Morb0 requested changes

2023-08-04 14:40 UTC, Morb0 commented on Resources/Textures/Structures/Storage/Crates/command.rsi/meta.json
> +  "copyright": "Taken from Citadelstation at commit https://github.com/Citadel-Station-13/Citadel-Station-13/commit/85186a971453b0653bacfb3fae88f978dc1be689, resprite by mureixlol",
От оригинала ничего не осталось, просто укажи:
```suggestion
  "copyright": Made by Discord: @mureixlol",
```

2023-08-04 14:41 UTC, Morb0 submitted a review, later dismissed

2023-08-05 15:44 UTC, Morb0 approved these changes

2023-08-05 15:45 UTC, merged