Replace black shoes in janidrobe with galoshes
space-syndicate/space-station-14 pull request #1269
Opened 2023-08-05 15:47 UTC by mhamsterr

На самом деле это revert 13602
Based on https://discord.com/channels/919301044784226385/1137384282122362910

## Описание PR

Причина проста: Нанятые главой персонала уборщики могли получить свои галоши (как-бы самый важный элемент их униформы, который в несколько раз упрощал их работу) только через: щитспавн, аплинк (при условии что они являлись синдикатовцами) или в качестве подарка от раундстарт уборщиков. Этот пр должен исправить это недоразумение.

13602 был принят только потому, что на Wizden серверах происходили раундстартовые взломы каморки уборщиков ради этого аналога ноуслипов. У нас же такие действия караются (должны) модерацией как минимум по правилам 3 и 3.1, так что такой проблемы не возникает (возникать не должно). 
**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: mhamster
- tweak: Галоши уборщика снова доступны в УборШкафе.

2023-08-05 15:49 UTC, lzk228 commented on Resources/Prototypes/Catalog/VendingMachines/Inventories/janidrobe.yml
> +    ClothingShoesGaloshes: 2 # Corvax-Revert
```suggestion
    ClothingShoesGaloshes: 2 # Corvax-MRP
```
и я бы поместил на строку выше, чтобы они были под туфлями

2023-08-05 15:52 UTC, mhamsterr commented on Resources/Prototypes/Catalog/VendingMachines/Inventories/janidrobe.yml
> +    ClothingShoesGaloshes: 2 # Corvax-Revert
<img width="443" alt="Снимок экрана 2023-08-05 в 22 50 10" src="https://github.com/space-syndicate/space-station-14/assets/81412348/c69d15d8-6f11-4743-bbe7-0b0310051cb9">
Точно под туфлями?

2023-08-05 16:00 UTC, lzk228 commented on Resources/Prototypes/Catalog/VendingMachines/Inventories/janidrobe.yml
> +    ClothingShoesGaloshes: 2 # Corvax-Revert
если ты их поместишь на строку выше, то они в интерфейсе будут под туфлями, а это куда лучше, когда элементы одежды категоризированы

2023-08-05 16:09 UTC, mhamsterr commented on Resources/Prototypes/Catalog/VendingMachines/Inventories/janidrobe.yml
> +    ClothingShoesGaloshes: 2 # Corvax-Revert
Справедливо.
И Я кажется скипнул слово "чтобы" когда читал...

2023-08-05 16:22 UTC, Myakot commented
Я правильно понимаю - добавим больше работы модерации, но зато упростим жизнь лейтджойнерным уборщикам? :)

2023-08-05 16:33 UTC, mhamsterr commented
> Я правильно понимаю - добавим больше работы модерации, но зато упростим жизнь лейтджойнерным уборщикам? :)

Не совсем понимаю, как простой вопрос в ахелп "Зачем вы взламываете чулан уборщиков?" добавляет работы модерации? Это скорее выглядит как ежедневная рутина, хз.
К тому же, кто в здравом уме будет вместо работы и выполнения своих обязанностей заниматься взломом, на секундочку, шлюза на космической станции ради пары резиновых сапог? По моему скромному мнению (я никогда не был модератором кстати), тут ну вот как-бы явное нарушение какой-либо логики персонажа...

2023-08-05 20:45 UTC, Morb0 commented
Просто добавь им замедления и они никому не будут нужны кроме уборщиков.

2023-08-07 10:41 UTC, lzk228 commented
сначала попробуй закинуть визардам замедление галошей

2023-08-09 02:57 UTC, Morb0 commented
> сначала попробуй закинуть визардам замедление галошей

https://github.com/space-wizards/space-station-14/pull/7793

2023-08-09 03:00 UTC, Morb0 requested changes

2023-08-09 03:00 UTC, Morb0 commented on Resources/Prototypes/Entities/Clothing/Shoes/specific.yml
> +    sprintModifier: 0.875 # Try to run fast in big rubber boots, lol
```suggestion
  - type: ClothingSpeedModifier # Corvax-MRP
    walkModifier: 0.8
    sprintModifier: 0.75 # Try to run fast in big rubber boots, lol
```

2023-08-09 05:07 UTC, lzk228 commented
> > сначала попробуй закинуть визардам замедление галошей
> 
> [space-wizards/space-station-14#7793](https://github.com/space-wizards/space-station-14/pull/7793)

ну, уже больше года прошло, может выйдет сейчас это протолкнуть

2023-08-09 14:57 UTC, Morb0 commented
> > > сначала попробуй закинуть визардам замедление галошей
> > 
> > 
> > [space-wizards/space-station-14#7793](https://github.com/space-wizards/space-station-14/pull/7793)
> 
> ну, уже больше года прошло, может выйдет сейчас это протолкнуть

Можешь попробовать

2023-08-15 08:58 UTC, mhamsterr commented
> > > > сначала попробуй закинуть визардам замедление галошей
> > > 
> > > 
> > > [space-wizards/space-station-14#7793](https://github.com/space-wizards/space-station-14/pull/7793)
> > 
> > 
> > ну, уже больше года прошло, может выйдет сейчас это протолкнуть
> 
> Можешь попробовать

Что-то мне подсказывает, что они не оценят...
И что мне тогда с этим пр-ом делать? Закрывать, или пусть дальше лежит?

2023-08-15 09:00 UTC, LightVillet commented
> > > > > сначала попробуй закинуть визардам замедление галошей
> > > > 
> > > > 
> > > > [space-wizards/space-station-14#7793](https://github.com/space-wizards/space-station-14/pull/7793)
> > > 
> > > 
> > > ну, уже больше года прошло, может выйдет сейчас это протолкнуть
> > 
> > Можешь попробовать
> 
> Что-то мне подсказывает, что они не оценят...
> И что мне тогда с этим пр-ом делать? Закрывать, или пусть дальше лежит?

А может залить всё-таки пр оффам, при этом указать зачем сделано замедление (для того, чтобы галоши в убормате были)? Или одним пром это сделать

2023-08-15 15:58 UTC, Morb0 approved these changes

2023-08-15 15:58 UTC, merged