Респрайт одежды на обезьянах
space-syndicate/space-station-14 pull request #1286
Opened 2023-08-09 03:08 UTC by SonicHDC

## Описание PR

Перерисовывает одежду на макаках.
**Медиа**

![equipped-INNERCLOTHING-monkey](https://github.com/space-syndicate/space-station-14/assets/100022571/f0ec4079-c5ba-4071-a180-ed4cfa119a66)
![equipped-INNERCLOTHING-monkey](https://github.com/space-syndicate/space-station-14/assets/100022571/70289834-9cf9-41da-b518-8993d7b79f16)

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:
- tweak: Изменены спрайты одежды на мортышках!

2023-08-09 05:08 UTC, lzk228 commented
файнали

2023-09-09 02:40 UTC, SonicHDC commented
Наконец-то готово. Больше без таких задержек, наверное.

2023-09-09 06:23 UTC, Morb0 reviewed
Так ты в meta.json файлах замени автора monkey спрайтов на своё

2023-09-09 09:00 UTC, lzk228 requested changes
нужны респрайты для юбок комбинезонов
нужны спрайты для одежды в папке корвакс, потому что их вообще нет

2023-09-09 09:14 UTC, Morb0 approved these changes

2023-09-09 09:26 UTC, merged