Adding new parallaxes for Delta Station and Avrite Station maps
space-syndicate/space-station-14 pull request #1297
Opened 2023-08-10 23:31 UTC by Ewerall

## Описание PR

Добавление новых параллаксов для карт Дельта и Аврит

**Медиа**

![2023-8-11_00 53 30](https://github.com/space-syndicate/space-station-14/assets/136239523/b41475a7-6c63-443d-8a9f-3f83368f9331)
![2023-8-11_01 26 23](https://github.com/space-syndicate/space-station-14/assets/136239523/0862488e-b2ad-4874-a5ea-00c1c42e5529)

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:
- add: Добавлен новый параллакс для Дельты
- add: Добавлен новый параллакс для Аврита

2023-08-10 23:32 UTC, lzk228 commented
я бы процитировал великого сухапика

2023-08-10 23:33 UTC, Ewerall commented
> я бы процитировал великого сухапика

Мы с ним обсуждали это)

2023-08-10 23:33 UTC, Syxapik commented
> я бы процитировал великого сухапика

Подтверждаю, с ним я это обсудил и одобрил

2023-08-11 00:42 UTC, Ewerall commented
Исправил файлы карт, так как случайно изменил старые версии

2023-08-11 00:48 UTC, Morb0 requested changes

2023-08-11 00:48 UTC, Morb0 commented on Resources/Prototypes/Parallaxes/avrite.yml
В подпапку Corvax

2023-08-11 00:48 UTC, Morb0 commented on Resources/Prototypes/Parallaxes/delta.yml
В подпапку Corvax

2023-08-11 00:48 UTC, Morb0 commented on Resources/Textures/Corvax/Parallax/attributions.yml
Новую строку в конце добавь

2023-08-11 01:48 UTC, Morb0 approved these changes

2023-08-11 01:48 UTC, merged