New library book, "Busido"
space-syndicate/space-station-14 pull request #1306
Opened 2023-08-12 00:00 UTC by lapatison

## Описание PR

**Медиа**

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:
- add: В библиотеку добавлена новая книга: "Бусидо. Избранные главы"

2023-08-12 00:42 UTC, Morb0 requested changes

2023-08-12 00:42 UTC, Morb0 commented on Resources/Prototypes/Catalog/Fills/Books/bookshelf.yml
> +      - id: BookBusido
```suggestion
      - id: BookBusido # Corvax-Books
```

2023-08-13 21:49 UTC, lzk228 requested changes

2023-08-13 21:49 UTC, lzk228 commented on Resources/Locale/ru-RU/corvax/paper/book-busido.ftl
> +ent-BookBusido = Бусидо. Избранные главы
это явно не тут должно быть

2023-08-13 21:49 UTC, lzk228 commented on Resources/Locale/ru-RU/corvax/paper/book-busido.ftl
> +    Самурай должен прежде всего постоянно помнить — помнить днем и ночью, с того утра, когда он берет в руки палочки, чтобы вкусить новогоднюю трапезу, до последней ночи старого года, когда он платит
```suggestion
    Самурай должен прежде всего постоянно помнить — помнить днём и ночью, с того утра, когда он берёт в руки палочки, чтобы вкусить новогоднюю трапезу, до последней ночи старого года, когда он платит свои долги — что он должен умереть. Вот его главное дело.
```

2023-08-13 21:49 UTC, lzk228 commented on Resources/Locale/ru-RU/corvax/paper/book-busido.ftl
> +    Если он всегда помнит об этом, он сможет прожить жизнь в соответствии с верностью и сыновней почтительностью, избегнуть мириада зол и несчастий, уберечь себя от болезней и бед, и насладиться долг
```suggestion
    Если он всегда помнит об этом, он сможет прожить жизнь в соответствии с верностью и сыновней почтительностью, избегнуть мириада зол и несчастий, уберечь себя от болезней и бед и насладиться долгой жизнью.
```
я не уверен, но вроде так должно быть

2023-08-13 21:49 UTC, lzk228 commented on Resources/Locale/ru-RU/corvax/paper/book-busido.ftl
> +    Он будет исключительной личностью, наделенной прекрасными качествами. Ибо жизнь мимолетна, подобно капле вечерней росы и утреннему инею, и тем более такова жизнь воина.
```suggestion
    Он будет исключительной личностью, наделенной прекрасными качествами. Ибо жизнь мимолётна, подобно капле вечерней росы и утреннему инею, и тем более такова жизнь воина.
```

2023-08-13 21:49 UTC, lzk228 commented on Resources/Locale/ru-RU/corvax/paper/book-busido.ftl
> +    Воин должен глубоко понимать эти два качества. Если он знает, как делать одно и избегать другого, он обрел бусидо.
```suggestion
    Воин должен глубоко понимать эти два качества. Если он знает, как делать одно и избегать другого, он обрёл бусидо.
```

2023-08-13 21:49 UTC, lzk228 commented on Resources/Locale/ru-RU/corvax/paper/book-busido.ftl
> +    Правильное и неправильное — это не что иное, как добро и зло, и хотя я не отрицаю, что различие между словами незначительно, поступать правильно и делать добро считается утомительным, а поступать
```suggestion
    Правильное и неправильное — это не что иное, как добро и зло, и хотя я не отрицаю, что различие между словами незначительно, поступать правильно и делать добро считается утомительным, а поступать неправильно и делать зло — лёгким и приятным, поэтому естественно, что многие склоняются к неправильному или злому и не любят правильное и доброе.
```

2023-08-13 21:49 UTC, lzk228 commented on Resources/Locale/ru-RU/corvax/paper/book-busido.ftl
> +    Причина тому — неумение управлять собой. Само по себе это может и не звучит так плохо, но если посмотреть глубже, мы увидим, что все идет от трусости. Поэтому я утверждаю, что самураю необходимо
```suggestion
    Причина тому — неумение управлять собой. Само по себе это может и не звучит так плохо, но если посмотреть глубже, мы увидим, что всё идёт от трусости. Поэтому я утверждаю, что самураю необходимо воздерживаться от неправильного и стремиться к правильному.
```

2023-08-13 21:49 UTC, lzk228 commented on Resources/Locale/ru-RU/corvax/paper/book-busido.ftl
> +    Но поскольку таких людей немного, следует среди многих друзей выбрать одного, на которого в случае необходимости можно полностью положиться.
```suggestion
    Но поскольку таких людей немного, следует среди многих друзей выбрать одного, на которого, в случае необходимости, можно полностью положиться.
```

2023-08-13 21:49 UTC, lzk228 commented on Resources/Locale/ru-RU/corvax/paper/book-busido.ftl
> +    Надежность — одно из качеств Пути воина, необходимых самураю, но ни в коем случае не желательно оказывать помощь без веских причин, ввязываться в дела, которые не имеют значения или принимать на
```suggestion
    Надёжность — одно из качеств Пути воина, необходимых самураю, но ни в коем случае не желательно оказывать помощь без веских причин, ввязываться в дела, которые не имеют значения или принимать на себя обязательства в том, что не касается тебя самого, только ради того, чтобы сделать так-то или дать совет.
```

2023-08-13 21:49 UTC, lzk228 commented on Resources/Locale/ru-RU/corvax/paper/book-busido.ftl
> +    Я лично люблю спать. Со временем я собираюсь все чаще уединяться у себя в доме и проводить остаток жизни во сне.
```suggestion
    Я лично люблю спать. Со временем я собираюсь всё чаще уединяться у себя в доме и проводить остаток жизни во сне.
```

2023-08-13 21:49 UTC, lzk228 commented on Resources/Locale/ru-RU/corvax/paper/book-busido.ftl
> +    Если человек вел себя перед смертью достойно, это воистину смелый человек. Мы знаем много примеров таких людей. Тот же, кто похваляется своим удальством, а перед смертью приходит в замешательство
```suggestion
    Если человек вёл себя перед смертью достойно, это воистину смелый человек. Мы знаем много примеров таких людей. Тот же, кто похваляется своим удальством, а перед смертью приходит в замешательство, не может быть назван воистину смелым.
```

2023-08-13 21:49 UTC, lzk228 commented on Resources/Locale/ru-RU/corvax/paper/book-busido.ftl
> +    Как бы ни был он умен и талантлив, если он беспечен и недостаточно хладнокровен, а потому, оказавшись лицом к лицу со смертью, выглядит растерянным, все его предыдущие добрые дела потеряют свой с
```suggestion
    Как бы ни был он умён и талантлив, если он беспечен и недостаточно хладнокровен, а потому, оказавшись лицом к лицу со смертью, выглядит растерянным, все его предыдущие добрые дела потеряют свой смысл, а все порядочные люди будут презирать его, и на него ляжет несмываемое пятно позора.
```

2023-08-13 21:49 UTC, lzk228 commented on Resources/Locale/ru-RU/corvax/paper/book-busido.ftl
> +    Ибо если самурай идет в битву, совершает отважные и величественные поступки и покрывает славой свое имя, то это только потому, что он настроил свое сердце на смерть.
```suggestion
    Ибо если самурай идёт в битву, совершает отважные и величественные поступки и покрывает славой свое имя, то это только потому, что он настроил свое сердце на смерть.
```

2023-08-13 21:49 UTC, lzk228 commented on Resources/Locale/ru-RU/corvax/paper/book-busido.ftl
> +    Если случается худшее, и ему суждено расстаться с жизнью, то, когда его противник спрашивает его имя, он должен громко и четко ответить и проститься с жизнью с улыбкой на губах, не выказывая ни м
```suggestion
    Если случается худшее, и ему суждено расстаться с жизнью, то, когда его противник спрашивает его имя, он должен громко и чётко ответить и проститься с жизнью с улыбкой на губах, не выказывая ни малейшего признака страха. 
```

2023-08-13 21:49 UTC, lzk228 commented on Resources/Locale/ru-RU/corvax/paper/book-busido.ftl
> +    Хотя самурай должен прежде всего чтить Путь Самурая, не вызывает сомнений, что все мы небрежительны. Поэтому, если в наши дни спросить: "В чем подлинный смысл Пути Самурая?", лишь немногие ответя
```suggestion
    Хотя самурай должен прежде всего чтить Путь Самурая, не вызывает сомнений, что все мы небрежительны. Поэтому, если в наши дни спросить: "В чём подлинный смысл Пути Самурая?", лишь немногие ответят без промедления.
```

2023-08-13 21:49 UTC, lzk228 commented on Resources/Locale/ru-RU/corvax/paper/book-busido.ftl
> +    В ситуации "или — или" без колебаний выбирай смерть. Это нетрудно. Исполнись решимости и  действуй.
```suggestion
    В ситуации "или — или" без колебаний выбирай смерть. Это нетрудно. Исполнись решимости и действуй.
```

2023-08-13 21:49 UTC, lzk228 commented on Resources/Locale/ru-RU/corvax/paper/book-busido.ftl
> +    Только  малодушные оправдывают себя рассуждениями о том, что умереть, не достигнув цели, означает умереть собачьей смертью.
```suggestion
    Только малодушные оправдывают себя рассуждениями о том, что умереть, не достигнув цели, означает умереть собачьей смертью.
```

2023-08-13 21:49 UTC, lzk228 commented on Resources/Prototypes/Catalog/Fills/Lockers/heads.yml
> +      - id: BookBusido # Corvax-Books
я бы добавил шанс спавна в 0.25 к примеру

2023-08-13 21:49 UTC, lzk228 commented on Resources/Prototypes/Catalog/Fills/Lockers/security.yml
> +      - id: BookBusido # Corvax-Books
тут тоже с шансом, но значительно меньшим, например 0.01
а ещё добавил бы в обычный локер сб

2023-08-13 21:49 UTC, lzk228 commented on Resources/Textures/Corvax/Objects/Misc/books.rsi/meta.json
> +  "copyright": "book_stationsagents taken from goonstation at commit https://github.com/goonstation/goonstation/commit/666034ca1da626e832c66980d7c28c5b8de72640 and edited by github:lapatison; book_bu
```suggestion
  "copyright": "book_stationsagents taken from goonstation at commit https://github.com/goonstation/goonstation/commit/666034ca1da626e832c66980d7c28c5b8de72640 and edited by github:lapatison; book_busido is taken from tgstation at commit https://github.com/tgstation/tgstation/commit/856e0a784abd19d20618aa36b26b73d471adf613 and respited by github:lapatison",
```

2023-08-13 21:52 UTC, lapatison commented on Resources/Locale/ru-RU/corvax/paper/book-busido.ftl
> +ent-BookBusido = Бусидо. Избранные главы
Незачем плодить лишние файлы, ящитаю. Всё в одном месте

2023-08-13 22:03 UTC, lzk228 commented on Resources/Locale/ru-RU/corvax/paper/book-busido.ftl
> +ent-BookBusido = Бусидо. Избранные главы
тогда запуск конфига локали скажет привет и создаст этот файл сам

2023-08-13 22:07 UTC, lapatison commented on Resources/Locale/ru-RU/corvax/paper/book-busido.ftl
> +ent-BookBusido = Бусидо. Избранные главы
Прав, исправлю

2023-08-13 22:12 UTC, lapatison commented on Resources/Locale/ru-RU/corvax/paper/book-busido.ftl
> +ent-BookBusido = Бусидо. Избранные главы
Убрал, переместил, и то же сделал для рулбука раз так

2023-08-13 22:13 UTC, lapatison commented on Resources/Prototypes/Catalog/Fills/Lockers/heads.yml
> +      - id: BookBusido # Corvax-Books
По обоим - пускай так, а то много книг будет, пусть в библиотеке ищут

2023-08-25 09:39 UTC, lapatison commented
![image](https://github.com/space-syndicate/space-station-14/assets/100279397/71148388-db4c-4a48-a331-6c9a0fc22681)

2023-08-25 10:17 UTC, lzk228 commented
![20230825_121716](https://github.com/space-syndicate/space-station-14/assets/124214523/c1700238-6445-4292-9033-9ff303b84857)

2023-08-30 18:25 UTC, Morb0 commented on Resources/Locale/ru-RU/corvax/paper/book-rulebook.ftl
> -    .desc = Книга с подробным описанием правил для настольной ролевой игры «Станции и агенты». Неизвестно, что случилось с предыдущими 13 редакциями, но искать их, наверное, не стоит.
Это и должно удаляться тут?

2023-08-30 18:27 UTC, lapatison commented on Resources/Locale/ru-RU/corvax/paper/book-rulebook.ftl
> -    .desc = Книга с подробным описанием правил для настольной ролевой игры «Станции и агенты». Неизвестно, что случилось с предыдущими 13 редакциями, но искать их, наверное, не стоит.
да, дубль
https://github.com/space-syndicate/space-station-14/blob/920fd567fef8c7adf6d150df0beaeb086ce7f777/Resources/Locale/ru-RU/ss14-ru/prototypes/corvax/catalog/fills/books/rulebook.ftl#L1

2023-08-30 18:30 UTC, Morb0 approved these changes

2023-08-30 18:32 UTC, merged