Перевод шкафов, ящиков, постеров, цистерн, и разной мелочёвки.
space-syndicate/space-station-14 pull request #131
Opened 2022-03-03 14:50 UTC by lapatison

## Описание PR 

**Скриншоты**

**Изменения**

:cl: lapatison
- add: Добавлены переводы шкафов, ящиков, постеров, цистерн, и разной мелочёвки.

2022-03-04 12:41 UTC, Morb0 requested changes

2022-03-04 12:41 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/lighting_ground.ftl
> +    .suffix = Пустой запитанный
Лучше сохранить форматирование как в оригинале, это по сути теги для поиска админам.
```suggestion
    .suffix = Пустой, Запитанный
```

2022-03-04 12:41 UTC, Morb0 commented on Resources/Locale/ru-RU/power-cell/components/power-cell-slot-component.ftl
> +power-cell-slot-component-slot-name-default = Энергоячейка
Думаю лучше назвать их `батареями`.
Даже `cell recharger` переведен как `зарядник для батарей`.

2022-03-04 12:41 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/power/smes.ftl
> +    .desc = Сверхпроводящее Магнитное ЭнергоХранилище (СМЭХ) большой емкости.
Аббревиатура не очень. Под `СМЕС` никак не получиться адаптировать?

2022-03-04 12:41 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/storage/closets/wardrobe.ftl
> +ent-WardrobeSalvage = гардероб шахтёра-утилизатора
До этого использовалось просто слово `утилизатор` в названии ящика - `снаряжение специалиста по утилизации`. Думаю стоит тогда везде использовать просто `утилизаторы` как название профессии.

2022-03-04 12:41 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/storage/tanks/tanks.ftl
>      .desc = A storage tank containing welding fuel.
Не переведено

2022-03-04 12:41 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/wallmounts/extinguisher_cabinet.ftl
> +    .suffix = Открытый наполненный
Как уже раньше описывал.
```suggestion
    .suffix = Открытый, Наполненный
```

2022-03-04 12:41 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/wallmounts/fireaxe_cabinet.ftl
> +    .suffix = Открытый наполненный
```suggestion
    .suffix = Открытый, Наполненный
```

2022-03-04 12:41 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/wallmounts/signs/posters.ftl
>      .desc = This poster looks like an advertisement for tools, but is in fact a subliminal jab at the tools at CentCom.
Перевод пропущен?

2022-03-04 12:41 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/wallmounts/signs/posters.ftl
>      .desc = Ignorant of Nature's Harmonic 6 Side Space Cube Creation, the Spacemen are Dumb, Educated Singularity Stupid and Evil.
Перевод пропущен?

2022-03-04 12:41 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/wallmounts/signs/posters.ftl
> +    .desc = Плакат, высмеивающий отрицание ЦентКомом существования заброшенной станции около с Космической станции 13.
```suggestion
    .desc = Плакат, высмеивающий отрицание ЦентКомом существования заброшенной станции около Космической станции 13.
```
И так же это не имеет смысла так как весь юмор был в том, что речь шла про русскую станцию - `Kosmicheskaya Stantsiya 13`. Даже не знаю, что с этим делать....

2022-03-04 12:41 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/wallmounts/signs/posters.ftl
> +    .desc = Плакат, рекламирующий пистолеты Синдиката как "чертовски классные". Он покрыт выцветшими логотипами банд.
```suggestion
    .desc = Плакат, рекламирующий пистолеты Синдиката как "чертовски классные". Он покрыт выцветшими тэгами банд.
```
Тэги есть и в русском и означают немного другое.

2022-03-04 12:41 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/wallmounts/signs/posters.ftl
>      .desc = Get a load, or give, of these all natural Exos!
Перевод пропущен?

2022-03-04 12:41 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/wallmounts/signs/posters.ftl
> +    .desc = Я сказал тебе взболтать, не смешивать.
```suggestion
    .desc = Я сказал тебе взболтать, но не смешивать.
```
Это важно 😎

2022-03-04 12:42 UTC, Morb0 commented
И что думаешь насчет перевода названия постеров?

2022-03-05 19:29 UTC, lapatison commented on Resources/Locale/ru-RU/magboot/actions.ftl
> +action-decription-magboot-toggle = Включает и выключает магнитные ботинки.
Прав

2022-03-05 19:31 UTC, lapatison commented on Resources/Locale/ru-RU/power-cell/components/power-cell-slot-component.ftl
> +power-cell-slot-component-slot-name-default = Энергоячейка
Прав.

2022-03-05 20:41 UTC, lapatison commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/wallmounts/signs/posters.ftl
> +    .desc = Плакат, высмеивающий отрицание ЦентКомом существования заброшенной станции около с Космической станции 13.
Переделал чуть иначе. У нас же Космическая станция 14, как никак.

2022-03-05 20:42 UTC, lapatison commented
> И что думаешь насчет перевода названия постеров?

Поскольку при осмотре плаката они видны - они нужны. Сделал.

2022-03-05 21:45 UTC, Morb0 requested changes

2022-03-05 21:45 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/wallmounts/signs/posters.ftl
> +ent-PosterContrabandSmoke = Курение
```suggestion
ent-PosterContrabandSmoke = Кури
```

2022-03-05 21:45 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/wallmounts/signs/posters.ftl
> +ent-PosterContrabandGreyTide = Серая волна
```suggestion
ent-PosterContrabandGreyTide = Грейтайд
```
Это уже нарицательное

2022-03-05 21:45 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/wallmounts/signs/posters.ftl
> +    .desc = Модные борги, Теперь только самый модные.
Если в тексте речь про модных то и названия лучше сделать `Модные борги` и слово `борги` можно с маленькой буквы.

2022-03-06 03:41 UTC, lapatison commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/wallmounts/signs/posters.ftl
> +    .desc = Модные борги, Теперь только самый модные.
В принципе, да. Не помню почему я решил сделать аллитеративное имя.

2022-03-06 09:46 UTC, Morb0 approved these changes
Отличная работа

2022-03-06 09:46 UTC, merged