фикс ё в имени персонажа
space-syndicate/space-station-14 pull request #1353
Opened 2023-08-20 20:21 UTC by lzk228

## Описание PR

разрешает использование `ё` в имени персонажа
бонусом добавил апостроф для очень ролеплейных имён унатхов
**Медиа**

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:
- fix: В именах персонажей теперь доступна буква Ё

2023-08-20 23:46 UTC, KIBORG04 commented on Content.Shared/Preferences/HumanoidCharacterProfile.cs
> +                name = Regex.Replace(name, @"[^А-Я,а-я,ё,Ё,0-9,', -]", string.Empty); // Corvax: Only cyrillic names
```suggestion
                name = Regex.Replace(name, @"[^\u0430-\u04510-9'-]", string.Empty); // Corvax: Only cyrillic names
```
Может тогда просто использовать юнидод рендж? еще и запятые какие-то непонятные были

2023-08-20 23:46 UTC, KIBORG04 commented on Content.Shared/Preferences/HumanoidCharacterProfile.cs
> +                name = Regex.Replace(name, @"[^А-Я,а-я,ё,Ё,0-9,', -]", string.Empty); // Corvax: Only cyrillic names
Если меня закоммитишь, то в ченджлоге напиши, что ТЕПЕРЬ ЗАПЯТУЮ ИСПОЛЬЗОВАТЬ ЗАПРЕЩЕНО

2023-09-10 06:03 UTC, Morb0 approved these changes

2023-09-10 06:24 UTC, Morb0 requested changes

2023-09-10 06:24 UTC, Morb0 commented on Content.Shared/Preferences/HumanoidCharacterProfile.cs
> +                name = Regex.Replace(name, @"[^А-Я,а-я,ё,Ё,0-9,', -]", string.Empty); // Corvax: Only cyrillic names
```suggestion
                name = Regex.Replace(name, @"[^А-Яа-яёЁ0-9' -]", string.Empty); // Corvax: Only cyrillic names
```

2023-09-10 06:26 UTC, merged