Перевод Upstream #1373
space-syndicate/space-station-14 pull request #1374
Opened 2023-08-29 19:42 UTC by lapatison

## Описание PR

**Медиа**

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:
- add: Добавлены переводы

2023-08-29 20:43 UTC, lzk228 commented on Resources/Locale/ru-RU/wires/wire-names.ftl
> +wires-board-name-dawinstrument = Цифровая звуковая рабочая станция
а оно влезет в ui?

2023-08-30 10:20 UTC, lzk228 approved these changes

2023-08-30 12:27 UTC, Morb0 requested changes

2023-08-30 12:27 UTC, Morb0 commented on Resources/Locale/ru-RU/wires/wire-names.ftl
> +wires-board-name-dawinstrument = Цифровая звуковая рабочая станция
По идеи нет, но у неё вроде и UI нельзя открыть
![image](https://github.com/space-syndicate/space-station-14/assets/14136326/64013c01-ea15-4899-a6ad-c9b69a18f3a1)

2023-08-30 17:38 UTC, merged