Перевод Upstream #1376
space-syndicate/space-station-14 pull request #1378
Opened 2023-08-30 19:54 UTC by lapatison

## Описание PR

**Медиа**

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:
- add: Добавлены переводы

2023-08-30 20:02 UTC, lzk228 requested changes

2023-08-30 20:02 UTC, lzk228 commented on Resources/Locale/ru-RU/nukeops/war-declarator.ftl
> +war-declarator-boost-declared = Объявлена война!
я бы сделал `Война объявлена`, ьак больше внимания пойдёт на слово война

2023-08-31 04:35 UTC, Morb0 requested changes

2023-08-31 04:35 UTC, Morb0 commented on Resources/Locale/ru-RU/nukeops/war-declarator.ftl
> +war-declarator-default-message = Пограничный отряд Синдиката объявил о своем намерении уничтожить станцию при помощи ядерного устройства и бросает вызов экипажу, пытающемуся их остановить.
В оригинале экипажу предлагается попытаться остановить их, а в текущем тексте они уже заведомо пытающиеся.

2023-08-31 04:35 UTC, Morb0 commented on Resources/Locale/ru-RU/nukeops/war-declarator.ftl
> +war-declarator-message-placeholder = Введите сюда текст объявления войны...
Звучит интереснее?
```suggestion
war-declarator-message-placeholder = Введите текст деклорации...
```

2023-08-31 04:35 UTC, Morb0 commented on Resources/Locale/ru-RU/chat/managers/chat-manager.ftl
> +[font size=12]{ $message }[/bold][/font]
```suggestion
chat-manager-sender-announcement-wrap-message = [font size=14][bold]Объявление { $sender }:[/font]
                                                                                          [font size=12]{ $message }[/bold][/font]
```

2023-08-31 07:51 UTC, lzk228 commented on Resources/Locale/ru-RU/nukeops/war-declarator.ftl
> +war-declarator-message-placeholder = Введите сюда текст объявления войны...
деклорации

2023-08-31 11:08 UTC, lapatison commented on Resources/Locale/ru-RU/nukeops/war-declarator.ftl
> +war-declarator-message-placeholder = Введите сюда текст объявления войны...
Думаю, не стоит
Везде `объявление`, а тут в одном месте будет `декларация`
Можно конечно и в другие места добавить, но `декларация войны` (именно со вторым словом) имхо не звучит

2023-08-31 11:51 UTC, Morb0 requested changes

2023-08-31 11:51 UTC, Morb0 commented on Resources/Locale/ru-RU/nukeops/war-declarator.ftl
> +war-declarator-default-message = Пограничный отряд Синдиката объявляет о своем намерении уничтожить станцию при помощи ядерного устройства и предлагает экипажу попробовать их остановить.
Это слишком прямолинейно и как-то не атмосферно тогда

2023-08-31 17:17 UTC, lapatison commented on Resources/Locale/ru-RU/nukeops/war-declarator.ftl
> +war-declarator-default-message = Пограничный отряд Синдиката объявляет о своем намерении уничтожить станцию при помощи ядерного устройства и предлагает экипажу попробовать их остановить.
Есть идеи?

2023-08-31 17:47 UTC, lapatison commented on Resources/Locale/ru-RU/nukeops/war-declarator.ftl
> +war-declarator-default-message = Пограничный отряд Синдиката объявляет о своем намерении уничтожить станцию при помощи ядерного устройства и предлагает экипажу попробовать их остановить.
ничё так, добавил

2023-08-31 17:51 UTC, Morb0 approved these changes

2023-08-31 17:51 UTC, merged