Изменен MapPool для Атара, Мейн и Элизиум
space-syndicate/space-station-14 pull request #1388
Opened 2023-09-05 09:30 UTC by Krosus777

## Описание PR

**Медиа**

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

У Атара, Мейн и Элизиум расширен мап пул, он стал как у Солярис, Нова и Эхо.
В связи с тем, с тем что на Атаре был убран бункер, время для прочтения правил был увеличен до 180 секунд.

:cl: Krosus777
- tweak: Увеличен список станций из голосования для серверов: Атара, Мейн и Элизиум

2023-09-05 10:41 UTC, lzk228 requested changes
Название пра должно по крайней мере описывать изменения

В чейнжлоге не фикс, а `tweak`

2023-09-05 10:41 UTC, lzk228 commented on Resources/ConfigPresets/Corvax/elysium.toml
>  map_rotation = false
в таком случае и тут включить
```suggestion
map_rotation = true
```

2023-09-05 10:47 UTC, Krosus777 commented
> Название пра должно по крайней мере описывать изменения
> 
> В чейнжлоге не фикс, а `tweak`

Исправил, ты кстати не знаешь почему мап пул такой обрезанный был у этих серверов?

2023-09-05 19:52 UTC, SonicHDC commented
Лрп сервера походу)

2023-09-07 13:36 UTC, Morb0 approved these changes

2023-09-07 13:37 UTC, merged