Новая станция Gate.
space-syndicate/space-station-14 pull request #1408
Opened 2023-09-12 14:06 UTC by TheShuEd

## Описание PR

Добавление новой станции Gate.
Представляем новую карту, где каждый отдел имеет уникальную атмосферу и визуальный стиль. Где каждый отдел расположен на отдельном астероиде, и связан между собой портальной сетью.

Каждый отдел на этой станции идеет свои уникальные и отличительные особенности:
* **Медицинский отдел** представляет из себя снежный биокупол, где поддерживается температура -60 градусов. Это заставляет игрокам носить теплую одежду, а так же не дает гнить трупам. Дополнительный шаттл парамедиков будет доступен медперсоналу, если те пройдут обучение у Карго.
* **Научный отдел** после неудачных экспериментов с растениями, частично зарос растительностью. И в его недрах можно найти странные биологические формы жизни, и даже Кудзу.
* **Инженерный отдел** окопался в центре лавового астероида, и отстроил там чуть ли не крепость. Бывшая клетка сингулярности разбита странным магическим астероидом, и больше не функционирует.
* **Карго отдел** выкупил самый богатый на руду астероид, и получил в свое распоряжение целых 4 шаттла. Помимо двух стандартных, каргония получила продвинутый утилизационный шаттл, а так же шаттл маршрутного такси для обеспечения коммуникации отделов в случае отключения порталов.
* **Отдел службы безопасности** получил в свое распоряжение каторгу, расположенную в километре от станции на обломках шахтерского поселка. А так же он активно старается игнорировать ныне заброшенную комнату бригмедика.
* **Центральный отдел**, смешение сервисного отдела и мостика командования, балует пассажиров банным комплексом и космическим МакДаком. 

Помимо этого, как внутри отделов, так и на их обшивке можно найти много интересных секретов и историй.

**Медиа**

![Gate-Render](https://github.com/space-syndicate/space-station-14/assets/96445749/83921463-4abc-42f1-b309-70acde970a4e)
<img width="891" alt="Screenshot2" src="https://github.com/space-syndicate/space-station-14/assets/96445749/6d0116c0-2011-453d-8069-3587f9e5ca77">
<img width="817" alt="Screenshot1" src="https://github.com/space-syndicate/space-station-14/assets/96445749/de03b587-143c-4935-bbe4-582308e00b37">
<img width="743" alt="Screenshot3" src="https://github.com/space-syndicate/space-station-14/assets/96445749/7034b059-733d-4fa1-a554-cfd648f78e51">
<img width="864" alt="Screenshot4" src="https://github.com/space-syndicate/space-station-14/assets/96445749/e7177f45-f827-4b96-91e0-428c07f0f10d">
<img width="912" alt="Screenshot5" src="https://github.com/space-syndicate/space-station-14/assets/96445749/b30924e8-f96d-40cb-ac20-577abc8cbcec">
<img width="916" alt="Screenshot6" src="https://github.com/space-syndicate/space-station-14/assets/96445749/bf7c3a88-1a2a-4ff0-8447-70ac7b581472">
<img width="917" alt="Screenshot7" src="https://github.com/space-syndicate/space-station-14/assets/96445749/780cf186-6b5f-449c-b6cc-b10746012c0f">
<img width="888" alt="Screenshot8" src="https://github.com/space-syndicate/space-station-14/assets/96445749/6b15db9f-9b09-4404-9878-c25994e43a83">
<img width="911" alt="Screenshot9" src="https://github.com/space-syndicate/space-station-14/assets/96445749/c6bf38e6-ea66-47de-b938-d04be8fd6119">
<img width="918" alt="Screenshot10" src="https://github.com/space-syndicate/space-station-14/assets/96445749/968d3b0b-f78c-4330-8253-a4168a0217df">
<img width="921" alt="Screenshot11" src="https://github.com/space-syndicate/space-station-14/assets/96445749/8cf936df-c390-4b37-a143-4ede85ecdbd2">
<img width="912" alt="Screenshot12" src="https://github.com/space-syndicate/space-station-14/assets/96445749/9522aa89-7c22-41a6-b76b-47c658f79279">
<img width="886" alt="Screenshot13" src="https://github.com/space-syndicate/space-station-14/assets/96445749/5143da39-02f2-4d54-9494-f3a0311a21f5">
<img width="689" alt="Screenshot14" src="https://github.com/space-syndicate/space-station-14/assets/96445749/29e99e05-6c93-4d03-aefa-bd09c1ca70e0">
<img width="730" alt="Screenshot15" src="https://github.com/space-syndicate/space-station-14/assets/96445749/4f8c94ad-537f-4764-84ae-b41dc8dc3388">

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:
- add: Добавлена новая карта Gate.

2023-09-12 16:49 UTC, MureixloI commented
А не слишком ли имбовая карта?

2023-09-12 16:57 UTC, NikaVichy commented
> А не слишком ли имбовая карта?

Сначала игроки ругались, что на карте нет геймлута, теперь ругаются, что имбалансно.. We live in society.

2023-09-12 17:02 UTC, Verslebas commented
> > А не слишком ли имбовая карта?
> 
> Сначала игроки ругались, что на карте нет геймлута, теперь ругаются, что имбалансно.. We live in society.

всем не угодить

2023-09-12 17:07 UTC, BolloTea commented
Именно по этому мапперы и проводят тестирования. Проведя пару раундов на станции, можно обнаружить множество ошибок, недочётов с балансом и тд. Я думаю тут будет так-же, пара раундов и отзывы тестеров покажут где и что нуждается в исправлении. А по хорошему, до окончательного выпуска, Вам бы посоветовать с ведущим маппером, для уточнения некоторых деталей.

2023-09-12 17:12 UTC, NikaVichy commented
> Именно по этому мапперы и проводят тестирования. Проведя пару раундов на станции, можно обнаружить множество ошибок, недочётов с балансом и тд. Я думаю тут будет так-же, пара раундов и отзывы тестеров покажут где и что нуждается в исправлении. А по хорошему, до окончательного выпуска, Вам бы посоветовать с ведущим маппером, для уточнения некоторых деталей.

Плейтесты производились на многих серверах Корвакса, пожелания игроков были учтены, исправлено большое количество мелких недочетов, карта уже получила свой примерный баланс. С вед. маппером тоже связывались, спасибо за советы.

2023-09-12 17:13 UTC, BolloTea commented
Приятно слышать. В целом карта очень красивая и сразу видно, что было вложено много творческих сил.

2023-09-12 20:11 UTC, Morb0 approved these changes
Looks cool

2023-09-12 20:13 UTC, Morb0 requested changes
Нужно добавить префикс `corvax_` к карте файлу и id
И
добавить сюда:
https://github.com/space-syndicate/space-station-14/blob/92bbc86b868433aadc92b11cecf630171c3fdaa0/Content.IntegrationTests/Tests/PostMapInitTest.cs#L47-L52

2023-09-12 22:08 UTC, TheShuEd commented
> Нужно добавить префикс `corvax_` к карте файлу и id И добавить сюда:
> 
> https://github.com/space-syndicate/space-station-14/blob/92bbc86b868433aadc92b11cecf630171c3fdaa0/Content.IntegrationTests/Tests/PostMapInitTest.cs#L47-L52

Исправил, в иниттесты добавил

2023-09-13 05:56 UTC, Jackal298 commented
В целом неплохо, карта неплохая, единственные два вопроса:
1. Можешь добавить плащ шахтера где кирка и шлем с фонариком
2. Если Декард находится в хранилище докину один спидлоудер

2023-09-13 13:35 UTC, merged

2023-09-14 15:17 UTC, deltanedas commented
Это очень классная карта, никогда не думал, что увижу что-то подобное.