[TRANSLATE] Добавил переводы и пофиксил слетевшие
space-syndicate/space-station-14 pull request #1415
Opened 2023-09-14 10:47 UTC by MrFippik

## Описание PR

Добавил переводы

**Медиа**

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:
- add: Добавлены переводы

2023-09-14 11:03 UTC, lzk228 commented
это перевод апстрима? если да, то назови соответствующе

2023-09-14 11:29 UTC, lzk228 requested changes

2023-09-14 11:29 UTC, lzk228 commented on Resources/Locale/ru-RU/communications/terror.ftl
> +terror-dragon = Внимание экипажу, похоже, что кто-то с вашей станции неожиданно вышел на связь со странной рыбой в ближнем космосе
```suggestion
terror-dragon = Внимание экипажу, похоже, что кто-то с вашей станции неожиданно вышел на связь со странной рыбой в ближнем космосе.
```

2023-09-14 11:29 UTC, lzk228 commented on Resources/Locale/ru-RU/ninja/gloves.ftl
> +ninja-gloves-examine-on = Все способности доступны.
```suggestion
ninja-gloves-examine-on = Все способности включены.
```

2023-09-14 11:29 UTC, lzk228 commented on Resources/Locale/ru-RU/ninja/katana.ftl
> +ninja-hands-full = У вас заняты руки!
```suggestion
ninja-hands-full = Ваши руки заняты!
```

2023-09-14 11:29 UTC, lzk228 commented on Resources/Locale/ru-RU/ninja/ninja-actions.ftl
> +ninja-research-steal-fail = Никакие новые исследовательские узлы украдены не были...
странно выглядит

2023-09-14 11:29 UTC, lzk228 commented on Resources/Locale/ru-RU/ninja/ninja-actions.ftl
> +ninja-research-steal-success = Украдено { $count } новых технологий из { ($server) }.
```suggestion
ninja-research-steal-success = Украдено { $count } новых технологий из { $server }.
```

2023-09-14 11:29 UTC, lzk228 commented on Resources/Locale/ru-RU/ninja/role.ftl
> +ninja-round-end-agent-name = Космический ниндзя
```suggestion
ninja-round-end-agent-name = Ниндзя
```

2023-09-14 11:29 UTC, lzk228 commented on Resources/Locale/ru-RU/objectives/conditions/steal-research-condition.ftl
> +objective-condition-steal-research-description = Ваши перчатки могут быть использованы для взлома научного сервера и кражи его ценных данных. Если наука дает слабину, вам придется взяться за работу.
```suggestion
objective-condition-steal-research-description = Ваши перчатки могут быть использованы для взлома научного сервера и кражи его ценных данных. Если учёные дают слабину, вам придется взяться за работу.
```

2023-09-14 11:29 UTC, lzk228 commented on Resources/Locale/ru-RU/prototypes/roles/antags.ftl
> +roles-antag-space-ninja-objective = Используй свою скрытность, чтобы устроить диверсию на станции, nom on electrical wires.
не переведено

2023-09-14 11:29 UTC, lzk228 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/actions/crit.ftl
> +    .desc = Прошепчите свои последние слова всем, кто находится поблизости, а затем сдайтесь на милость судьбы. Вам доступно только 30 символов.
в прелыдущих описаниях `смириться`, `притвориться` (сделать), а тут `прошепчите` (сделайте)

2023-09-14 11:29 UTC, lzk228 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/actions/ninja.ftl
> +    .desc = Включает все возможности перчаток. При щелчке ЛКП может: взломать дверь, впитать энергию, оглушить врага, загрузить данные и вызвать угрозу.
лкп

2023-09-14 11:29 UTC, lzk228 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/actions/ninja.ftl
> +ent-ActionNinjaEmp = электромагнитный импульс
```suggestion
ent-ActionNinjaEmp = Электромагнитный импульс
```

2023-09-14 11:29 UTC, lzk228 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/actions/revenant.ftl
не переведены 3 5 и 7 строчки

2023-09-14 11:29 UTC, lzk228 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/consumable/food/baked/misc.ftl
>      .suffix = Fresh
```suggestion
    .suffix = Свежий
```

2023-09-14 11:41 UTC, MrFippik commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/uniforms/jumpsuits.ftl
> +ent-ClothingUniformJumpsuitNinja = комбинезон космического ниндзя
Не склоняется

2023-09-14 11:44 UTC, lzk228 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/uniforms/jumpsuits.ftl
> +ent-ClothingUniformJumpsuitNinja = комбинезон космического ниндзя
поправил

2023-09-14 14:09 UTC, lapatison commented on Resources/Locale/ru-RU/administration/antag.ftl
>  admin-verb-text-make-traitor = Make Traitor
Остальное не переведено

2023-09-14 14:11 UTC, MrFippik commented
Сейчас исправлю, а так-же остальную часть апстрима переведу

2023-09-14 16:31 UTC, lapatison commented on Resources/Locale/ru-RU/wires/wire-names.ftl
> +wire-name-bomb-bolt = БОЛТ
LIVE - АКТВ

2023-09-14 16:42 UTC, MrFippik commented on Resources/Locale/ru-RU/ninja/role.ftl
> +ninja-round-end-agent-name = Космический ниндзя
Ну он же космический

2023-09-14 16:45 UTC, MrFippik commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/uniforms/jumpsuits.ftl
> +ent-ClothingUniformJumpsuitNinja = комбинезон космического ниндзя
Ну у него всё снаряжение называется как то-то или это космического ниндзя, а тут комбинезон будет просто ниндзя

2023-09-14 17:18 UTC, MrFippik commented on Resources/Locale/ru-RU/wires/wire-names.ftl
> +wire-name-bomb-bolt = БОЛТ
Исправил

2023-09-14 17:19 UTC, MrFippik commented on Resources/Locale/ru-RU/administration/antag.ftl
>  admin-verb-text-make-traitor = Make Traitor
Исправлено

2023-09-14 17:29 UTC, lapatison commented on Resources/Locale/ru-RU/materials/units.ftl
>  # sheets of steel
Сделай тут всё во множественном числе
листы, слитки, т.д

2023-09-14 17:58 UTC, lzk228 requested changes

2023-09-14 17:58 UTC, lzk228 commented on Resources/Locale/ru-RU/research/technologies.ftl
34 39 строки

2023-09-14 17:58 UTC, lzk228 commented on Resources/Locale/ru-RU/research/technologies.ftl
> +research-technology-weaponized-laser-manipulation = Weaponized Laser Manipulation              //
```suggestion
research-technology-weaponized-laser-manipulation = Оружейная манипуляция лазерами
```

2023-09-14 17:58 UTC, lzk228 commented on Resources/Locale/ru-RU/research/technologies.ftl
> +research-technology-portable-microfusion-weaponry = Portable Microfusion Weaponry                 //
не переведено

2023-09-14 17:58 UTC, lzk228 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/actions/ninja.ftl
> +ent-ActionTogglePhaseCloak = Невидимость
```suggestion
ent-ActionTogglePhaseCloak = Фазовый покров
```

2023-09-14 17:58 UTC, lzk228 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/actions/ninja.ftl
> +    .desc = Переключает невидимость вашего костюма. Помните, что если в вас попадут, все способности будут отключены на 5 секунд, включая невидимость!
```suggestion
    .desc = Переключает невидимость вашего костюма. Помните, что если в вас попадут, все способности будут отключены на 5 секунд, включая покров!
```

2023-09-14 17:58 UTC, lzk228 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/actions/revenant.ftl
>  ent-ActionRevenantOverloadLights = Overload Lights
```suggestion
ent-ActionRevenantOverloadLights = Перегрузка ламп
```

2023-09-14 17:58 UTC, lzk228 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/actions/revenant.ftl
>  ent-ActionRevenantDefile = Defile
не переведено

2023-09-14 17:58 UTC, lzk228 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/actions/revenant.ftl
>  ent-ActionRevenantMalfunction = Malfunction
-

2023-09-14 17:58 UTC, lzk228 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/actions/spider.ftl
> +ent-ActionSericulture = Ткать шелк
```suggestion
ent-ActionSericulture = Ткать шёлк
```

2023-09-14 17:58 UTC, lzk228 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/actions/spider.ftl
> +    .desc = Соткать немного шелка для использования в декоративно-прикладном искусстве.
```suggestion
    .desc = Соткать немного шёлка для использования в декоративно-прикладном искусстве.
```

2023-09-14 17:58 UTC, lzk228 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/actions/types.ftl
>      .desc = AAAAAAAAAAAAAAAAAAAAAAAAA
```suggestion
    .desc = ААААААААААААААААААААААААА
```

2023-09-14 17:58 UTC, lzk228 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/masks/masks.ftl
> +ent-ClothingMaskNinja = маска космического ниндзя
```suggestion
ent-ClothingMaskNinja = маска ниндзя
```

2023-09-14 17:58 UTC, lzk228 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/outerclothing/hardsuits.ftl
> +    .desc = Отремонтированный шахтерский скафандр, выполненный в цветах квартирмейстера. Графеновая подкладка имеет меньше защиты, но в нем гораздо легче перемещаться.
```suggestion
    .desc = Отремонтированный шахтёрский скафандр, выполненный в цветах квартирмейстера. Графеновая подкладка имеет меньше защиты, но в нём гораздо легче перемещаться.
```

2023-09-14 17:58 UTC, lzk228 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/uniforms/jumpsuits.ftl
> +ent-ClothingUniformJumpsuitNinja = комбинезон космического ниндзя
ну у него в оригинале называется `NINJA SUIT`

2023-09-14 17:58 UTC, lzk228 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/markers/warp_point.ftl
> +    .suffix = Место взрыва у ниндзя
```suggestion
    .suffix = Цель взрыва ниндзя
```

2023-09-14 17:58 UTC, lzk228 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/mobs/player/dragon.ftl
> +    .desc = Попытаться разрушить конструкцию своими челюстями или проглотить существо
```suggestion
    .desc = Попытаться разрушить конструкцию своими челюстями или проглотить существо.
```

2023-09-14 17:58 UTC, lzk228 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/mobs/player/guardian.ftl
> +    .desc = Призывает либо отзывает стража обратно в ваше тело
```suggestion
    .desc = Призывает либо отзывает стража обратно в ваше тело.
```

2023-09-14 17:58 UTC, lzk228 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/consumable/food/baked/misc.ftl
> +    .suffix = Сежий
```suggestion
    .suffix = Свежий
```

2023-09-14 17:58 UTC, lzk228 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/consumable/food/ingredients.ftl
> +ent-FoodCannabisButter = брусок масла с коноплёй
```suggestion
ent-FoodCannabisButter = брусок масла с конопли
```

2023-09-14 17:58 UTC, lzk228 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/materials/materials.ftl
> +    .desc = Роскошная шкура, используемая в самой элитной моде. Ходят слухи, что это случается, когда корги отправляют на ферму в Ницце.
```suggestion
    .desc = Роскошная шкура, используемая в самой элитной моде. Ходят слухи, что это находят, когда корги отправляют на хорошую ферму.
```

2023-09-14 17:58 UTC, lzk228 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/specific/chapel/bibles.ftl
> +    .desc = Призовите фамильяра, который станет помогать вам и обретет человекоподобный интеллект после вселения в него души.
```suggestion
    .desc = Призовите фамильяра, который станет помогать вам и обретёт человекоподобный интеллект после вселения в него души.
```

2023-09-14 17:58 UTC, lzk228 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/specific/salvage/ore_bag.ftl
> +    .desc = Прочная сумка для специалистов по утилизации и шахтеров для переноски больших объемов руды. Намагничивает близлежащие руды, если прикрепить их к ленте.
```suggestion
    .desc = Прочная сумка для специалистов по утилизации и шахтеров для переноски больших объемов руды. Намагничивает близлежащую руду, если закрепить на поясе.
```

2023-09-14 17:58 UTC, lzk228 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/furniture/chairs.ftl
> +    .desc = Длинная скамья, созданная для метро. Реальный стандартный дизайн.
```suggestion
    .desc = Длинная скамья, созданная для метро. Реально стандартный дизайн.
```

2023-09-14 17:58 UTC, lzk228 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/machines/bombs.ftl
> +    .desc = Просто говорите и никто не взорвется.
```suggestion
    .desc = Просто говорите и никто не взорвётся.
```

2023-09-14 17:58 UTC, lzk228 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/machines/bombs.ftl
> +    .desc = Господи, она сейчас взорвется.
```suggestion
    .desc = Господи, она сейчас взорвётся.
```

2023-09-14 17:58 UTC, lzk228 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/magic/forcewall_spells.ftl
> +    .desc = TARCOL MINTI ZHERI
как это вообще тут появилось?

2023-09-14 17:58 UTC, lzk228 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/magic/spawn_spells.ftl
> +    .desc = Это заклинание призывает трех мэджикарпов вам на помощь! Могут напасть на хозяина, а могут и нет.
```suggestion
    .desc = Это заклинание призывает трёх мэджикарпов вам на помощь! Могут напасть на хозяина, а могут и нет.
```

2023-09-14 17:58 UTC, lzk228 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/magic/projectile_spells.ftl
> +    .desc = Выпускает взрывающийся огненный шар в направлении кликнутого места.
```suggestion
    .desc = Выпускает взрывающийся огненный шар в направлении выбранного места.
```

2023-09-14 17:58 UTC, lzk228 commented on Resources/Locale/ru-RU/store/uplink-catalog.ftl
> +uplink-exploding-syndicate-bomb-desc = Надежная бомба, которая может проделать большую дыру в станции. Полезно для отвлечения внимания.
```suggestion
uplink-exploding-syndicate-bomb-desc = Надёжная бомба, которая может проделать большую дыру в станции. Полезно для отвлечения внимания.
```

2023-09-15 08:22 UTC, lapatison commented on Resources/Locale/ru-RU/battery/components/battery-drainer-component.ftl
> +battery-drainer-success = Вы получаете энергию из { $battery }!
```suggestion
battery-drainer-success = Вы вытягиваете энергию из { $battery }!
```

2023-09-15 08:24 UTC, lapatison commented on Resources/Locale/ru-RU/battery/components/battery-drainer-component.ftl
> +battery-drainer-empty = { CAPITALIZE($battery) } не хватает мощности для заряда
```suggestion
battery-drainer-empty = В { CAPITALIZE($battery) } не хватает энергии, которую можно выкинуть
```

2023-09-15 08:26 UTC, lapatison commented on Resources/Locale/ru-RU/defusable/examine.ftl
> +defusable-examine-live-display-off = { CAPITALIZE($name) } [color=red]тикает[/color] и таймер похоже выключен.
```suggestion
defusable-examine-live-display-off = { CAPITALIZE($name) } [color=red]тикает[/color] и таймер, похоже, выключен.
```

2023-09-15 08:30 UTC, lapatison commented on Resources/Locale/ru-RU/defusable/examine.ftl
> +defusable-examine-live = { CAPITALIZE($name) } [color=red]тикает[/color] и осталось [color=red]{ $time }[/color] секунд.
```suggestion
defusable-examine-live =
    { CAPITALIZE($name) } тикает [color=red][/color] и осталось [color=red]{ $time } { $time ->
        [one] секунда
        [few] секунды
       *[other] секунд
    }.
```

2023-09-15 08:34 UTC, lapatison commented on Resources/Locale/ru-RU/job/role-timers.ftl
> +role-timer-department-insufficient = Требуется ещё [color=yellow]{ TOSTRING($time, "0") }[/color] минут игры за [color={$departmentColor}]{$department}[/color].
```suggestion
role-timer-department-insufficient = Требуется ещё [color=yellow]{ TOSTRING( $time, "0" ) }[/color] минут игры за [color={ $departmentColor }]{ $department }[/color].
```
И далее по файлу

2023-09-15 08:37 UTC, lapatison commented on Resources/Locale/ru-RU/ninja/ninja-actions.ftl
> +ninja-no-power = Недостаточно заряда в аккумуляторе костюма!
```suggestion
ninja-no-power = Недостаточно заряда в батарее костюма!
```

2023-09-15 08:39 UTC, lapatison commented on Resources/Locale/ru-RU/ninja/ninja-actions.ftl
> +ninja-research-steal-success = Украдено { $count } новых технологий из { $server }.
```suggestion
ninja-research-steal-success =
    Вы украли { $count } { $count ->
        [one] новую
        [few] новые
       *[other] новых
    } технологий из { $server }.
```

2023-09-15 08:42 UTC, lapatison commented on Resources/Locale/ru-RU/prototypes/catalog/fills/crates/cargo-crates.ftl
> +ent-CrateCargoLuxuryHardsuit = ящик с элитным шахтёрским скафандром
```suggestion
ent-CrateCargoLuxuryHardsuit = ящик элитного шахтёрского скафандра
```

2023-09-15 08:43 UTC, lapatison commented on Resources/Locale/ru-RU/prototypes/roles/antags.ftl
> +roles-antag-space-ninja-objective = Используй свою скрытность, чтобы устроить диверсию на станции, ном на электрических проводах.
```suggestion
roles-antag-space-ninja-objective = Используй свою скрытность, чтобы устроить диверсию на станции, питайтесь от электрических проводов.
```

2023-09-15 08:49 UTC, lapatison commented on Resources/Locale/ru-RU/research/technologies.ftl
> +research-technology-weaponized-laser-manipulation = Оружейная манипуляция лазерами
Манипулирование лазерным оружием?

2023-09-15 08:50 UTC, lapatison commented on Resources/Locale/ru-RU/research/technologies.ftl
> +research-technology-portable-microfusion-weaponry = Портативное микрофузионное оружие
Microfusion - Микросинтез

2023-09-15 08:52 UTC, lapatison commented on Resources/Locale/ru-RU/ss14-ru/prototypes/catalog/fills/boxes/general.ftl
> +ent-BoxLeadLined = свинцовая коробка
```suggestion
ent-BoxLeadLined = освинцованная коробка
```

2023-09-15 08:53 UTC, lapatison commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/eyes/glasses.ftl
> +    .desc = Усовершенствованные очки, защищающие глаза ниндзя от мигающих огней.
```suggestion
    .desc = Усовершенствованные очки, защищающие глаза ниндзя от вспышек света.
```

2023-09-15 08:54 UTC, lapatison commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/head/hardsuit-helmets.ftl
> +    .desc = Отремонтированный шлем шахтёрского скафандра, оснащенный амортизацией и дополнительной (нерабочей) антенной.
```suggestion
    .desc = Отремонтированный шлем шахтёрского скафандра, оснащенный атласной подкладкой и дополнительной (нерабочей) антенной.
```
satin cushioning по идее подчёркивает элитность костюма

2023-09-15 08:56 UTC, lapatison commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/outerclothing/hardsuits.ftl
> +    .desc = Отремонтированный шахтёрский скафандр, выполненный в цветах квартирмейстера. Графеновая подкладка имеет меньше защиты, но в нем гораздо легче перемещаться.
```suggestion
    .desc = Отремонтированный шахтёрский скафандр, выполненный в цветах квартирмейстера. Графеновая подкладка обеспечивает меньшую защиту, но с ней гораздо легче передвигаться.
```

2023-09-15 08:59 UTC, lapatison commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/outerclothing/suits.ftl
> +    .desc = Этот чёрный технологически продвинутый, кибернетически усиленный костюм обеспечивает хорошую защиту и множество способностей, таких как невидимость или телепортация.
```suggestion
    .desc = Этот чёрный, технологически продвинутый, кибернетически усиленный костюм даёт хорошую защиту и множество способностей, таких как невидимость или телепортация.
```

2023-09-15 09:00 UTC, lapatison commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/markers/warp_point.ftl
> +    .suffix = Цель взрыва ниндзя
```suggestion
    .suffix = Цель взрыва бомбы ниндзя
```

2023-09-15 09:02 UTC, lapatison commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/consumable/food/baked/misc.ftl
> +ent-FoodBakedCannabisBrownie = особое брауни
А не `особый`?

2023-09-15 09:04 UTC, lapatison commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/consumable/food/ingredients.ftl
> +ent-FoodCannabisButter = брусок масла с конопли
```suggestion
ent-FoodCannabisButter = брусок конопляного масла
```

2023-09-15 09:05 UTC, lapatison commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/consumable/food/ingredients.ftl
> +    .desc = Добавляйте это в свои любимые блюда.
```suggestion
    .desc = Добавляйте это в свою любимую выпечку для веселого времяпровождения.
```

2023-09-15 09:06 UTC, lapatison commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/consumable/food/snacks.ftl
> +    .suffix = И.Р.П
```suggestion
    .suffix = ИРП
```

2023-09-15 09:08 UTC, lapatison commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/materials/materials.ftl
> +    .desc = Роскошная шкура, используемая в высокой моде. Ходят слухи, что она получается, когда корги отправляют на хорошую ферму.
```suggestion
    .desc = Роскошная шкура, используемая в высокой моде. Ходят слухи, что их находят, когда старые корги отправляются на ферму.
```

2023-09-15 09:08 UTC, lapatison commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/misc/identification_cards.ftl
> +    .suffix = Оперативника
```suggestion
    .suffix = Ядерный оперативник
```

2023-09-15 09:09 UTC, lapatison commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/specific/salvage/ore_bag.ftl
> +.desc = Прочная сумка для специалистов по утилизации и шахтеров для переноски больших объемов руды. Намагничивает близлежащую руду, если закрепить на поясе.
```suggestion
    .desc = Прочная сумка для специалистов по утилизации и шахтеров для переноски больших объемов руды. Примагничивает близлежащую руду, если закрепить на поясе.
```

2023-09-16 12:30 UTC, MrFippik commented on Resources/Locale/ru-RU/materials/units.ftl
>  # sheets of steel
сделал

2023-09-16 17:00 UTC, lzk228 requested changes

2023-09-16 18:04 UTC, lzk228 requested changes

2023-09-16 18:04 UTC, lzk228 commented on Resources/Locale/ru-RU/objectives/conditions/doorjack-condition.ftl
> +objective-condition-doorjack-title = Взломайте { $count } дверей на станции.
```suggestion
objective-condition-doorjack-title = Взломайте { $count } { $count ->
        [one] дверь
        [few] двери
       *[other] дверей
    } на станции.
```

2023-09-16 18:04 UTC, lzk228 commented on Resources/Locale/ru-RU/objectives/conditions/doorjack-condition.ftl
> +objective-condition-doorjack-description = Ваши перчатки могут взламывать шлюзы. Сделайте это с { $count } дверьми.
```suggestion
objective-condition-doorjack-description = Ваши перчатки могут взламывать шлюзы. Сделайте это с { $count } { $count ->
        [one] дверью
        [few] дверьми
       *[other] дверьми
    }.
```

2023-09-16 18:04 UTC, lzk228 commented on Resources/Locale/ru-RU/objectives/conditions/steal-research-condition.ftl
> +objective-condition-steal-research-title = Украдите { $count } технологий.
```suggestion
objective-condition-steal-research-title = Украдите { $count } { $count ->
        [one] технологию
        [few] технологии
       *[other] технологий
    }.
```

2023-09-16 18:39 UTC, lapatison commented on Resources/Locale/ru-RU/objectives/conditions/steal-research-condition.ftl
> +objective-condition-steal-research-title = Украдите { $count } технологий.
ну почти

2023-09-16 18:41 UTC, lapatison commented on Resources/Locale/ru-RU/objectives/conditions/steal-research-condition.ftl
> +objective-condition-steal-research-title = Украдите { $count } технологий.
![image](https://github.com/space-syndicate/space-station-14/assets/100279397/3d53134b-17d1-4716-9398-5fb159dc22a5)
после `=` с новой строки, как в примере

2023-09-16 18:58 UTC, lzk228 commented on Resources/Locale/ru-RU/objectives/conditions/steal-research-condition.ftl
> +objective-condition-steal-research-title = Украдите { $count } технологий.
есть

2023-09-16 19:04 UTC, lzk228 requested changes

2023-09-16 19:04 UTC, lzk228 commented on Resources/Locale/ru-RU/objectives/conditions/steal-research-condition.ftl
> +objective-condition-steal-research-title = Украдите { $count } { $count ->
```suggestion
objective-condition-steal-research-title =
Украдите { $count } { $count ->
```

2023-09-17 08:18 UTC, lzk228 commented on Resources/Locale/ru-RU/objectives/conditions/spider-charge-condition.ftl
> +objective-condition-spider-charge-description = Эта бомба может быть взорвана в определенном месте. Обратите внимание, что бомба не сработает в другом месте!
вот это ещё

2023-09-17 08:43 UTC, lapatison commented on Resources/Locale/ru-RU/objectives/conditions/doorjack-condition.ftl
> +Ваши перчатки могут взламывать шлюзы. Сделайте это с { $count } { $count ->
```suggestion
    Ваши перчатки могут взламывать шлюзы. Сделайте это с { $count } { $count ->
```

2023-09-17 08:44 UTC, lapatison commented on Resources/Locale/ru-RU/objectives/conditions/steal-research-condition.ftl
> +Украдите { $count } { $count ->
```suggestion
    Украдите { $count } { $count ->
```

2023-09-17 11:49 UTC, Morb0 commented
CLIENT: 17.721s [ERRO] loc: /Locale/ru-RU/job/role-timers.ftl:
 2 |role-timer-department-too-high = Требуется на [color=yellow]{ TOSTRING( $time, "0" ) }[/color] меньше минут игры за [color={ $departmentColor }]{$ department }[/color]. (Вы пытаетесь играть за роль для новичков?)
                                                                                                                                                      ^ Expected one of "a-zA-Z"

2023-09-17 11:58 UTC, lapatison commented
> CLIENT: 17.721s [ERRO] loc: /Locale/ru-RU/job/role-timers.ftl: `2 |role-timer-department-too-high = Требуется на [color=yellow]{ TOSTRING( $time, "0" ) }[/color] меньше минут игры за [color={ $departmentColor }]{$ department }[/color]. (Вы пытаетесь играть за роль для новичков?)` ^ Expected one of "a-zA-Z"

Это из-за того, что перед долларом нет пробела?

2023-09-17 12:34 UTC, Morb0 commented
> > CLIENT: 17.721s [ERRO] loc: /Locale/ru-RU/job/role-timers.ftl: `2 |role-timer-department-too-high = Требуется на [color=yellow]{ TOSTRING( $time, "0" ) }[/color] меньше минут игры за [color={ $departmentColor }]{$ department }[/color]. (Вы пытаетесь играть за роль для новичков?)` ^ Expected one of "a-zA-Z"
> 
> Это из-за того, что перед долларом нет пробела?

Скорее всего

2023-09-17 12:59 UTC, MrFippik commented
Вроде исправил

2023-09-17 13:20 UTC, lzk228 commented on Resources/Locale/ru-RU/defusable/popup.ftl
> +defusable-popup-wire-proceed-cut = Цифровой дисплей на { ($name) } выключается.
```suggestion
defusable-popup-wire-proceed-cut = Цифровой дисплей на { $name } выключается.
```

2023-09-17 13:27 UTC, lzk228 approved these changes
мне норм

2023-09-17 14:06 UTC, merged