json autogen fix + react_prototypes.json autogen
space-syndicate/space-station-14 pull request #1441
Opened 2023-09-22 19:55 UTC by mhamsterr

What it says on the title...
Всё это ради вики.

## Описание PR

### Фиксы:
Пофикшена генерация chem_prototypes.json и react_prototypes.json. В большинстве доступных на данный момент логов Github Actions генерация стопорилась из-за того, что какое-то число не могло быть записано в json. Расследование вывело на Leporazine, которому в max по дефолту прописали значение `float.PositiveInfinity`. Теперь вместо ошибки в консоль мы получим "Infinity" в json. А что делать с "Infinity" - на вики уже как-нибудь сами разберёмся.
## Нововведения
Теперь вместе с chem_prototypes.json и react_prototypes.json генерируется entity_prototypes.json, содержащий в себе все энтити с их внутриигровыми названиями и описаниями. Это нужно на вики, поэтому хотелось бы это в автопубликацию как-нибудь засунуть, если можно. 🥺<br>
**Медиа**

<img width="697" alt="Screenshot 2023-09-23 at 00 53 36" src="https://github.com/space-syndicate/space-station-14/assets/81412348/57223af2-97fd-4a35-af9f-dba377fe9040"><br>
Оно честно работает<br>
**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

no cl

2023-09-22 19:57 UTC, lzk228 commented
нихуя он умный

2023-09-22 20:25 UTC, MureixloI commented
Brains 🧠

2023-09-22 21:41 UTC, Morb0 commented
И сколько интересно весит файл со всеми entity

2023-09-22 21:53 UTC, Clostyandr commented
big brain

2023-09-23 02:05 UTC, mhamsterr commented
> И сколько интересно весит файл со всеми entity

<img width="260" alt="Screenshot 2023-09-23 at 09 04 42" src="https://github.com/space-syndicate/space-station-14/assets/81412348/1d418660-16ac-456c-b500-f1bf1e7677c9">

2023-09-24 09:37 UTC, Morb0 requested changes

2023-09-24 09:37 UTC, Morb0 commented on Content.Server/GuideGenerator/ChemistryJsonGenerator.cs
> +            NumberHandling = System.Text.Json.Serialization.JsonNumberHandling.AllowNamedFloatingPointLiterals, // Corvax-fix
Используй один контекст для PR'а
```suggestion
            NumberHandling = System.Text.Json.Serialization.JsonNumberHandling.AllowNamedFloatingPointLiterals, // Corvax-Wiki
```

2023-09-24 09:37 UTC, Morb0 commented on Content.Server/GuideGenerator/ReactionJsonGenerator.cs
> +            NumberHandling = System.Text.Json.Serialization.JsonNumberHandling.AllowNamedFloatingPointLiterals, // Corvax-fix
```suggestion
            NumberHandling = System.Text.Json.Serialization.JsonNumberHandling.AllowNamedFloatingPointLiterals, // Corvax-Wiki
```

2023-09-24 09:37 UTC, Morb0 commented on Content.Server/Entry/EntryPoint.cs
> +                file.Flush(); // Corvax-Wiki
```suggestion
                // Corvax-Wiki-Start
                file = resourceManager.UserData.OpenWriteText(resPath.WithName("entity_" + dest));
                EntityJsonGenerator.PublishJson(file);
                file.Flush();
                // Corvax-Wiki-End
```

2023-09-24 09:37 UTC, Morb0 commented on Content.Server/Corvax/GuideGenerator/EntityEntry.cs
> +        if (proto.Name.Length > 1)
Возможно стоит получать локализацию для названия и описания entity? Я не думаю, что вики нужны английские названия.
А так же я думаю, что викиделы сами могут делать uppsercase для первой буквы.

2023-09-24 09:46 UTC, mhamsterr commented on Content.Server/Corvax/GuideGenerator/EntityEntry.cs
> +        if (proto.Name.Length > 1)
Прямо сейчас он получает локализованную версию названия и описания (на https://station14.ru/wiki/Участник:Mhamster/entity_prototypes.json есть небольшой кусочек, использовавшийся для некоторых тестов) (удалить бы его уже надо, на самом деле...).
А заглавная буква в начале названий была "запросом" куратора вики ( https://discord.com/channels/919301044784226385/1011942047961333814/1154695237709602866 https://discord.com/channels/919301044784226385/1011942047961333814/1154718961770975303 )

2023-09-24 10:00 UTC, Morb0 commented on Content.Server/Corvax/GuideGenerator/EntityEntry.cs
> +        if (proto.Name.Length > 1)
Окей

2023-09-24 14:11 UTC, Morb0 commented on Content.Server/Corvax/GuideGenerator/EntityEntry.cs
> +        }
При каком условии, тут может быть `else`?

2023-09-24 14:21 UTC, mhamsterr commented on Content.Server/Corvax/GuideGenerator/EntityEntry.cs
> +        }
По задумке - когда описание не длиннее одного символа и его длина не равна единице, то есть когда в нём нечего капитализировать.
Такое вот, например, происходит у некоторых заданий некоторых антагонистов (у заданий ниндзя нет названий, но есть описания, а у заданий агента (кроме хайджека) названий и описаний просто нет) и у подобных "энтити", которых игрок видеть не может.

2023-09-24 14:27 UTC, Morb0 commented on Content.Server/Corvax/GuideGenerator/EntityEntry.cs
> +        }
Понятно

2023-09-24 14:28 UTC, Morb0 approved these changes
LGTM

2023-09-24 14:29 UTC, merged