Различные переводы
space-syndicate/space-station-14 pull request #145
Opened 2022-03-12 15:53 UTC by lapatison

Переводы ящиков, шкафчиков, коробок, ботинок, и комбинезонов

## Описание PR 

**Скриншоты**

**Изменения**

:cl: lapatison
- add: Переводы ящиков, шкафчиков, коробок, ботинок, и комбинезонов

2022-03-14 00:15 UTC, Morb0 requested changes

2022-03-14 00:15 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/shoes/specific.ftl
> +    .desc =Удобные, чистые ботинки для длительной работы в напряженном ритме.
Пробел перед равно `.desc`.
Так же эти вещи являются отсылкой на Disco Elysium, поэтому лучше оставить `аэростатические`.

2022-03-14 00:15 UTC, Morb0 commented on Resources/Locale/ru-RU/misc-computers.ftl
> +radar-window-title = Терминал детектора массы
Этот сканер обнаруживает структуры в космосу, может лучше будет сделать в множественном числе - `масс`?

2022-03-14 00:15 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/catalog/fills/backpacks/duffelbag.ftl
> +ent-ClothingBackpackDuffelSurgeryFilled = хирургический вещмешок
Та же тема про наименование `duffel bag`

2022-03-14 05:31 UTC, lapatison commented on Resources/Locale/ru-RU/ss14-ru/prototypes/catalog/fills/lockers/service.ftl
> +    .suffix = Loot (увидите - напишите в чат переводы)
Тогда такой вариант, поскольку "суффикс".

2022-03-15 23:23 UTC, lapatison commented
Я - за вещмешок. Спортивная сумка это всё же большая сумка для удобного переноса спорт инвентаря. А у нас возникают спортивные инженерные сумки, медицинские спортивные сумки, и т.п, что звучит довольно странно. Хотя нельзя не отметить что образ "вещмешка" в сознании жителя СНГ далек от изображения заграничного "даффел бэга", а ближе к "сидору" советских времён, однако современные ВС РФские вещмешки это как раз оно самое, см файл
![image](https://user-images.githubusercontent.com/100279397/158488221-b65cfaa0-8a2d-48f3-8491-8b68ea0d3f79.png)

2022-03-16 19:42 UTC, Morb0 requested changes

2022-03-16 19:48 UTC, Morb0 approved these changes

2022-03-16 19:48 UTC, merged