[Localisation][Resprite] Poster translation
space-syndicate/space-station-14 pull request #1464
Opened 2023-09-26 20:30 UTC by lapatison

## Описание PR

**Медиа**

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:
- add: Переведены плакаты

2023-09-26 21:05 UTC, lapatison commented
> poster25_legit удалён
Вернул

2023-09-27 07:46 UTC, MureixloI commented
А так и должно быть, что у poster5_contraband шлем отличается?

2023-09-27 07:50 UTC, lzk228 commented
poster12_legit - одна буква шириной 5, вторая 3 третья 4, сделай чтобы одинаково было
poster19_legit - чтобы понять что там написано "ТЕХника БЕЗопасности" надо сильно подумать
poster1_legit - откуда там взялся"ЗАКОН"? и почему чел стал шыре?
poster23_contraband - "ВМЕСТЕ" можно сжать и впихнуть "!"
poster26_legit - "У" растяни на один пиксель, чтобы слово доставало до обоих краёв
poster32_contraband - "МОЧИ" сдвинуть на пиксель влево, "И" расширить на пиксель вправо
poster3_contraband - потерялся стиль
poster37_legit - как "FALSE" превратилось в "ЕГО НЕТ"?
poster48_contraband - "REAL" - "ЛОЖЬ"............
poster7_contraband - потерялся стиль

плюс свяжись с ведущим спрайтером

2023-09-27 10:19 UTC, lapatison commented
> poster12_legit - одна буква шириной 5, вторая 3 третья 4, сделай чтобы одинаково было 

Ты предлагаешь сжать И и растянуть А? Чепуха

> poster19_legit - чтобы понять что там написано "ТЕХника БЕЗопасности" надо сильно подумать

Ты о чём? 
![image](https://github.com/space-syndicate/space-station-14/assets/100279397/1736e56b-0b43-4066-a7dd-c5e92516c3e4)

> poster1_legit - откуда там взялся"ЗАКОН"? и почему чел стал шыре?

`Безопасность` не влезла, переделаю под новый шлем, я так понял постеры успели по мелочи обновиться с начала моей работы над ними

> poster23_contraband - "ВМЕСТЕ" можно сжать и впихнуть "!" 

сделаю

> poster26_legit - "У" растяни на один пиксель, чтобы слово доставало до обоих краёв

не стоит

> poster32_contraband - "МОЧИ" сдвинуть на пиксель влево, "И" расширить на пиксель вправо

сделаю

> poster3_contraband - потерялся стиль

жертва, на которую я готов пойти

> poster37_legit - как "FALSE" превратилось в "ЕГО НЕТ"?

потому что газового гиганта НЕТ

 > poster48_contraband - "REAL" - "ЛОЖЬ"............ 

постер обвиняет ЦК во лжи

> poster7_contraband - потерялся стиль

Так? Ну хз
![poster7_contraband](https://github.com/space-syndicate/space-station-14/assets/100279397/9fea3040-26a3-4639-901c-247b5bbdc963)

Плюс пофикшу poster5_contraband

2023-09-27 10:27 UTC, lzk228 commented
> Ты предлагаешь сжать И и растянуть А? Чепуха

оно как-то криво выглядит

> жертва, на которую я готов пойти

ну тогда спрайтерам дай, пусть стиль вернут

2023-10-03 16:01 UTC, KuroTheKutoss requested changes
poster20_contraband.png - мода боргОВ (если не вместится - ладно, но так лучше)
poster21_contraband.png- мода боргОВ (если не вместится - ладно, но так лучше)
postet33_contraband.png - тут была шутка про грифферство.... "Круши ВСЕ"?
postet35_contraband.png - "Свободу попугаям!" Только тут просто "Свободу"

2023-10-04 20:40 UTC, lapatison commented
> poster20_contraband.png - мода боргОВ (если не вместится - ладно, но так лучше)
poster21_contraband.png- мода боргОВ (если не вместится - ладно, но так лучше)

Тут увы, никак

> poster33_contraband.png - тут была шутка про грифферство.... По аналогии с "Береги ВСЕ" - "Круши ВСЕ"? 

Персонаж на постере - суперзлодей грифон Гриффин, имхо `гриффь` лучше обыгрывает и персонажа, и гриферство

> poster35_contraband.png - "Свободу попугаям!" Только тут просто "Свободу"

У меня не выходит вместить Свободу

2023-10-05 20:09 UTC, KuroTheKutoss commented
Короче ведущий спрайтер одобрямс - постеры из-за игры слов и проблем "на английском 4 буквы, а на русском 7" трудно перевести, так что потерявшийся стиль или еще что-то, допустимая жертва.

2023-10-05 22:21 UTC, merged