Изменение заказов щита-разума
space-syndicate/space-station-14 pull request #1490
Opened 2023-10-06 16:16 UTC by LinkUyx

## Описание PR

**Медиа**

![Content Client_g6lNSsjzSO](https://github.com/space-syndicate/space-station-14/assets/131011403/11d34273-4476-4d19-931b-a2a10fb4a21e)
![Content Client_Fz0DPI43TX](https://github.com/space-syndicate/space-station-14/assets/131011403/bef18f27-e8db-4d65-ae65-01f1514450ab)

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:
- tweak: Изменена цена ящика щита-разума в консоли заказа.
- tweak: Изменено наполнение ящика до двух имплантеров.

2023-10-06 16:36 UTC, lzk228 requested changes
# Corvax-MRP

2023-10-06 17:17 UTC, Jackal298 commented
Я бы поднял цену до 12000, но не изменял бы количество

2023-10-07 00:28 UTC, SonicHDC commented
Похоже на лютый хардкор ради хардкора.
Карго и так денег жалко всегда, а так их вообще заказывать не будут вовсе.

2023-10-07 04:33 UTC, LinkUyx commented
> Похоже на лютый хардкор ради хардкора.
> Карго и так денег жалко всегда, а так их вообще заказывать не будут вовсе.

Мне кажется, что такое небольшое изменение - лучше, чем бить людей за метагейминг

2023-10-07 09:24 UTC, Holinka4ever commented
> > Похоже на лютый хардкор ради хардкора.
> > Карго и так денег жалко всегда, а так их вообще заказывать не будут вовсе.
> 
> Мне кажется, что такое небольшое изменение - лучше, чем бить людей за метагейминг

Да, причем тут метагейминг?
Разве этим не должны заниматся модерация?

Фактически, это просто сделает закуп имплантов бессмысленым, ибо люди будут покупать оружие, вместо того что бы спасти экипаж от промывке мозгов.

Так же вовремя ревы будет факт того что карго не будет работать/не будет иметь достаточно денег/карго шаттл могут просто саботировать.

Бтв, в сравнении с лрп сервером из /tg/station, terry, сб хоть и щиткьюр, но они пытаются имплантить майншилд первую очередь обычных людей, что бы не лишать оных геймплей, ибо все же в первую очередь игра, а не глубокий рп проект.

Как я уже говорил, и скажу еще раз, это лишит людей выбора спасти людей, потому что резня для мрп выгоднее.

2023-10-07 10:50 UTC, Myakot commented
Просто лорово ограничьте возможности ставить импланты. Скажите, что у них отвратительная репутация среди непосвященных. Как бы НТ не старалось - идёт молва, что они контролируют разум (хоть это и не так) - но народ не убедить.
Теперь представьте, идёт раундстарт и командование запрашивает карго массово закупать импланты - а потом ставить их в людей без причины - да они там сами реву устроят без РевГлав под страхом того, что их хотят превратить в безвольных рабов насильно.

Это лишь один из вариантов. Не вижу никакого смысла абсолютно повышать цену на импланты, так как у нас получается дешевле убивать революционеров или **вообще всех вокруг, кроме СБ и Ком** - только вот по итогу 80% сервера будет в гостах сидеть и ждать конца раунда.
Имплантирование должно быть в приоритете для Командования станцией, приоритетом над убийством и жестким подавлением революции, хотя бы просто потому, что иначе это призыв СБ РДМить весь экипаж.

2023-10-09 10:47 UTC, Nimfar11 commented
Тоже думаю что не нужно повышать цену. Если СБ будет метагеймить, модеры и так накажут. А делать не подъёмную цену, это перебор.

2023-10-11 17:50 UTC, closed without merging