Принтер документов
space-syndicate/space-station-14 pull request #1510
Opened 2023-10-18 00:17 UTC by Krosus777

## Описание PR

- Добавлен принтер документов на базе системы протолата
- Криминалистические консоли и консоли оповещений заменены на принтер

**Медиа**

![image](https://github.com/space-syndicate/space-station-14/assets/38509947/086c5efe-dd35-4e6c-8292-319681813681)

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: Krosus
- add: Добавлен принтер документов
- tweak: Бесполезные консоли заменены на принтеры документов

2023-10-18 01:21 UTC, SonicHDC commented
Всё круто, но замену консолей удаляй, им функционал могут хоть завтра добавить. Да и не везде принтер на месте консоли будет хорошо выглядить

2023-10-18 10:54 UTC, Nimfar11 commented
> Всё круто, но замену консолей удаляй, им функционал могут хоть завтра добавить. Да и не везде принтер на месте консоли будет хорошо выглядить

Я так понимаю, это сделано чтобы принтеры были на картах оффов. Ну и то что функционал хоть завтра добавят, это конечно загнул. Максимум криминалистическую консоль, хотя она уже несколько месяцев в застое.

2023-10-18 12:17 UTC, Krosus777 commented
Вернуть их не проблема. Можно в принципе принтер в файл компьютера добавить и в случае если у этих консолей добавится функционал, то сразу удалят заменяющие принтеры.

2023-10-18 13:12 UTC, Morb0 requested changes
Для карт есть файл миграция который автоматически заменяет protoId -> protoId на карте при загрузке, поэтому не нужно переделывать консоль.
Пример: https://github.com/space-syndicate/space-station-14/blob/master/Resources/migration.yml#L20

2023-10-18 14:44 UTC, Krosus777 commented
- Убрал замену
- Добавил миграцию

2023-10-18 16:05 UTC, lapatison commented on Resources/Prototypes/Corvax/Entities/Objects/Material/Sheets/other.yml
> +  name: Бумага
```suggestion
  name: бумага
```

2023-10-18 16:06 UTC, lapatison commented on Resources/Prototypes/Corvax/Entities/Structures/Machines/Printer.yml
> +  description: Уникальная разработка на NanoTrasen.
```suggestion
  description: Уникальная разработка Nanotrasen.
```

2023-10-18 21:08 UTC, Morb0 requested changes

2023-10-18 21:08 UTC, Morb0 commented on Resources/Locale/ru-RU/paper/doc-printer.ftl
Перенеси файл в ru-RU/corvax/paper/

2023-10-18 21:08 UTC, Morb0 commented on Resources/Prototypes/Corvax/Entities/Objects/Material/Sheets/other.yml
Путь должен `Materials` а сейчас `Material`

2023-10-18 21:08 UTC, Morb0 commented on Resources/Prototypes/Corvax/Entities/Objects/Material/Sheets/other.yml
> +  id: SheetPrinter
А существующий `SheetPaper` не подойдет?

2023-10-18 21:08 UTC, Morb0 commented on Resources/Prototypes/Corvax/Entities/Structures/Machines/Printer.yml
название файла нужно с маленькой буквы

2023-10-18 21:16 UTC, Krosus777 commented on Resources/Prototypes/Corvax/Entities/Objects/Material/Sheets/other.yml
> +  id: SheetPrinter
> А существующий `SheetPaper` не подойдет?

Нет, так как его только маперы могут добавить, он не спаунится и не заказывается

2023-10-19 10:55 UTC, BolloTea commented
Если вы хотите чтобы его можно было разместить без участия мапперов. То, по возможности сделайте его крафт и платы

2023-10-19 17:32 UTC, Krosus777 commented
> Если вы хотите чтобы его можно было разместить без участия мапперов. То, по возможности сделайте его крафт и платы. Если это уже реализовано, то простите, я немного слепой

Он и так будет появляться без участия маперов, при старте раунда он заменит не работающие консоли. Для офовских карт пока так, для наших маперы сами могут его поставить.

Так как полтикика сервера это поддержание «ванильной» сборки я специально не делал отдельных плат. Мне кажется чем больше механик к нему накручивать, тем сложнее его будет поддерживать в Корвакс сборке, а значит меньше шансов что он к нам попадет.

2023-10-19 19:15 UTC, Morb0 requested changes

2023-10-19 19:15 UTC, Morb0 commented on Resources/migration.yml
> +# 2023-10-18
```suggestion
# 2023-10-18 - Corvax
```

2023-10-20 07:52 UTC, Morb0 requested changes
Исправь тесты:
```
   Multiple failures or warnings in test:
  1)   SheetPrinter 'stack entity' Paper does not have the stack component
  Expected: True
  But was:  False

  2)   SheetPrinter material has no stack prototype
  Expected: True
  But was:  False
  ```

2023-10-22 00:16 UTC, lzk228 requested changes
у ВСЕХ энтити должны быть английские названия, дальше они локализируются через фтл

со спрайтами какая-то хуета, как пример хорошей работы можешь глянуть #1073

2023-10-22 00:16 UTC, lzk228 commented on Resources/migration.yml
> +# 2023-10-18 - Corvax
почему оно в середине файла?
должно же по дате сортироваться

2023-10-22 00:16 UTC, lzk228 commented on Resources/Prototypes/Corvax/Entities/Structures/Machines/printer.yml
> +  description: Уникальная разработка Nanotrasen.
слишком уныло

2023-10-22 00:16 UTC, lzk228 commented on Resources/Prototypes/Corvax/Entities/Structures/Machines/printer.yml
> +  parent: BaseLathe
не проще за основу взять автолат? так как это сделано с принтером одежды

2023-10-22 00:16 UTC, lzk228 commented on Resources/Textures/Corvax/Structures/Machines/printer.rsi/meta.json
> +          2.0
почему финальный кадр целые две секунды?

2023-10-22 00:16 UTC, lzk228 commented on Resources/Textures/Corvax/Structures/Machines/printer.rsi/meta.json
> +      "delays": [
у тебя каждый рецепт 1 секунду, а стейт идёт 1.8секунд

2023-10-22 00:16 UTC, lzk228 commented on Resources/Prototypes/Corvax/Entities/Objects/Materials/Sheets/other.yml
> +  name: бумага
а разве названия материалов не должно быть в фтл файле?

2023-10-22 00:16 UTC, lzk228 commented on Resources/Prototypes/Corvax/Catalog/Fills/Paper/document.yml
> +  id: NOTICEOFLIQUIDATION
почему все буквы заглавные?

2023-10-22 00:16 UTC, lzk228 commented on Resources/Textures/Corvax/Structures/Machines/printer.rsi/building.png
почему тут накладывается фулловый спрайт, можно де накладывать только то, что меняется

2023-10-22 12:04 UTC, Krosus777 commented on Resources/Prototypes/Corvax/Catalog/Fills/Paper/document.yml
> +  id: NOTICEOFLIQUIDATION
Так надо

2023-10-22 12:05 UTC, Krosus777 commented on Resources/Textures/Corvax/Structures/Machines/printer.rsi/building.png
Такой спрайт

2023-10-22 12:05 UTC, Krosus777 commented on Resources/Textures/Corvax/Structures/Machines/printer.rsi/meta.json
> +          2.0
Так необходимо

2023-10-22 12:05 UTC, Krosus777 commented on Resources/Prototypes/Corvax/Entities/Structures/Machines/printer.yml
> +  parent: BaseLathe
Нет не проще

2023-10-22 12:05 UTC, Krosus777 commented on Resources/Prototypes/Corvax/Entities/Structures/Machines/printer.yml
> +  description: Уникальная разработка Nanotrasen.
Даже не буду комментировать

2023-10-22 12:05 UTC, Krosus777 commented on Resources/migration.yml
> +# 2023-10-18 - Corvax
Исправлю

2023-10-22 12:07 UTC, Krosus777 commented on Resources/Prototypes/Corvax/Entities/Objects/Materials/Sheets/other.yml
> +  name: бумага
Зачем если это для корвакса?

2023-10-22 12:23 UTC, Morb0 commented on Resources/Prototypes/Corvax/Entities/Objects/Materials/Sheets/other.yml
> +  name: бумага
В .yml используй английское название, я потом сгенерирую ftl
или сам можешь с помощью `python .\Tools\ss14_ru\yamlextractor.py`, только  там мусор нагенерит, нужно будет закомитить только новые ftl

2023-10-22 12:45 UTC, lzk228 commented on Resources/Prototypes/Corvax/Catalog/Fills/Paper/document.yml
> +  id: NOTICEOFLIQUIDATION
надо? это называется стандартизация, все айди должны быть в `PascalCase`

2023-10-22 12:49 UTC, lzk228 commented on Resources/Prototypes/Corvax/Entities/Structures/Machines/printer.yml
> +  parent: BaseLathe
проще, так как ты будешь использовать в принтере меньше компонентов

2023-10-26 08:48 UTC, Morb0 reviewed
Failed MaterialPrototypeSpawnsStackMaterial [333 ms]
  Error Message:
     Expected: "SheetPrinter1"
  But was:  SheetPrinter

2023-11-27 14:15 UTC, lzk228 commented
@Krosus777 are you coming back to this? :trollface:

2024-01-10 15:05 UTC, closed without merging