Перевод болезней, мед оборудования, и прочего разного.
space-syndicate/space-station-14 pull request #153
Opened 2022-03-17 00:37 UTC by lapatison

## Описание PR 

**Скриншоты**

**Изменения**

:cl: lapatison
- add: Различные переводы, по большей части медицинской направленности (вирусы)

2022-03-17 21:01 UTC, Morb0 requested changes

2022-03-17 21:37 UTC, lapatison commented on Resources/Locale/ru-RU/disease/swab.ftl
> +swab-swabbed = Вы зондируете рот { $target }.
заменил на ватные палочки, но если в игре будет слишком длинно - вернёмся к моему варианту, идёт?

2022-03-19 01:24 UTC, Morb0 requested changes

2022-03-19 01:24 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/specific/janitorial/spray.ftl
> +ent-SprayBottleWater = бутылка-спрей
```suggestion
ent-SprayBottle = распылитель
    .desc = Распылитель с отвинчивающимся верхом.
    .suffix = Пустая
ent-SprayBottleWater = распылитель
```

2022-03-19 01:24 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/specific/janitorial/spray.ftl
> +    .desc = Непенящийся очиститель пространства бренда BLAM!
```suggestion
ent-SprayBottleSpaceCleaner = очиститель
    .desc = Непенящийся очиститель бренда BLAM!
```

2022-03-19 01:24 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/specific/medical/surgery.ftl
> +    .desc = Ужасный зазубренный клинок, сделанный из любых неприятных острых предметов, которые вы только можете найти.
```suggestion
    .desc = Ужасный зазубренный клинок, сделанный из любых неприятно острых предметов, которые вы только можете найти.
```

2022-03-19 01:24 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/specific/medical/surgery.ftl
> +    .desc =Для интенсивной резки.
```suggestion
    .desc = Для интенсивной резки.
```

2022-03-19 01:49 UTC, lapatison commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/specific/janitorial/spray.ftl
> +    .desc = Непенящийся очиститель пространства бренда BLAM!
не согласен, но предлагаю заменить на пространственный очиститель.
пространственный очиститель - очищает пространство, а также очиститель, который применяется в [космическом] пространстве

или более прямолинейный вариант - космический очиститель. Так на вики станции Chaotic Onyx

2022-03-19 02:08 UTC, lapatison commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/fun/instruments.ftl
> +ent-GunpetInstrument = гунпет
Есть варианты:
- шумострел
- канонада - как звуки которые она издает
- звукобой
- шумонада - как канонада + шум, а так же мем про корейца с очками - шума-нннадо?
- пушкозвон - как пушка+звон, ну и пустозвон как ненастоящий пистолет
- писольлет - пистолет + нота соль

2022-03-19 02:08 UTC, lapatison commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/fun/instruments.ftl
> +ent-GunpetInstrument = гунпет
![image](https://user-images.githubusercontent.com/100279397/159102729-60108241-5b66-4229-801d-1b3dd42a1b07.png)
> шумонада

2022-03-19 10:12 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/specific/janitorial/spray.ftl
> +    .desc = Непенящийся очиститель пространства бренда BLAM!
Этот вариант был взят из вики 220. Тогда лучше `космический очиститель`.

2022-03-19 10:15 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/fun/instruments.ftl
> +ent-GunpetInstrument = гунпет
Мне `писольлет` нравится, так как больше всего передает оригинал.

2022-03-19 14:44 UTC, Morb0 approved these changes

2022-03-19 14:44 UTC, merged