Service worker antag
space-syndicate/space-station-14 pull request #1565
Opened 2023-11-13 15:33 UTC by kerisargit

## Описание PR
Сервисный работник может быть антагонистом - по результату предложения. Причина - у нас это полноценная роль без ограничения по часам, а согласно официальному репозиторию роли новичков не могут быть антагами.
https://discord.com/channels/919301044784226385/1172948442008518656

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**
- tweak:  Сервисный работник может быть антагонистом

2023-11-13 15:35 UTC, lzk228 requested changes
измени на `canBeAntag: true # Corvax-MRP`

2023-11-13 15:37 UTC, kerisargit commented
Проблема в том, что этой строки как раз нету, если антагом может быть роль. Могу просто комментарий

2023-11-13 15:40 UTC, lzk228 commented
так напиши true чтобы мог
если строки нет, то значит что дефолтное значение в коде true

2023-11-13 15:42 UTC, kerisargit commented
Написала ( ˘▽˘)っ

2023-11-13 15:44 UTC, kerisargit commented
Написала (•‿•)

2023-11-17 14:24 UTC, Morb0 requested changes

2023-11-17 14:24 UTC, Morb0 commented on Resources/Prototypes/Roles/Jobs/Civilian/service_worker.yml
> +  canBeAntag: true #Corvax-MRP
```suggestion
  canBeAntag: true # Corvax-MRP: Available not only for newbies
```

2023-11-17 14:25 UTC, merged