New CentComm Station
space-syndicate/space-station-14 pull request #1573
Opened 2023-11-15 13:04 UTC by poeMota

## Описание PR

**Медиа**

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:
- add: Добавлена новая станция ЦентКом

2023-11-15 13:18 UTC, Deserty0 commented
Скрин можно?

2023-11-15 13:50 UTC, poeMota commented
> Скрин можно?

Только если скринами, рендер не фурычит.

![image](https://github.com/space-syndicate/space-station-14/assets/142114334/894643b8-ced1-47f3-927b-3cef98183a87)
![image](https://github.com/space-syndicate/space-station-14/assets/142114334/a8ce323f-353b-4233-a6c7-d9f30f6c4867)
![image](https://github.com/space-syndicate/space-station-14/assets/142114334/fc68c75f-6288-4efe-aebd-a7837571555a)
![image](https://github.com/space-syndicate/space-station-14/assets/142114334/ae2e8ba0-1854-485a-aef3-c90753d49b5e)
![image](https://github.com/space-syndicate/space-station-14/assets/142114334/c0976b0a-b22d-464f-aeec-4b68638eaa25)
![image](https://github.com/space-syndicate/space-station-14/assets/142114334/11a87ea5-7c22-4eee-9014-4ac747135565)
![image](https://github.com/space-syndicate/space-station-14/assets/142114334/d4c0d274-03e3-415b-acb6-ed8179454d8b)

2023-11-15 13:52 UTC, Deserty0 commented
красота 🐢

2023-11-15 15:09 UTC, MureixloI commented
Ура, ура! Теперь это не пустышка!

2023-11-17 14:13 UTC, Morb0 requested changes

2023-11-17 14:13 UTC, Morb0 commented on Resources/Prototypes/Entities/Stations/base.yml
> +      map: "/Maps/corvax_centcomm.yml" # Corvax mapping
```suggestion
      map: "/Maps/corvax_centcomm.yml" # Corvax-Mapping
```

2023-11-17 14:14 UTC, merged