Протокол 1984/лазiк [MAPs]
space-syndicate/space-station-14 pull request #1578
Opened 2023-11-20 14:07 UTC by Bloodcanis

## Описание PR

С предложениями убрать "оверлут", приравнять карты корвакса к офовским и ставить больше полезных вещей в самые популярные места, запускается "ивент" "Протокол 1984/лазiк".
Убраны практически все ресурсы раундстартом, урезаны практически все секретки, убрано большинство вещей и тд.
Длительность мероприятия будет от 1 до 2 недель, в зависимости от отзывов игроков.
Замечательная возможность почувствовать старую политику мапперов, что игроки должны страдать. 

**Медиа**

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

2023-11-20 14:17 UTC, Deserty0 commented
Объявляю процедуру "36 и 6 молитв" игроков и "76 и 9 отзывов"

2023-11-20 14:28 UTC, Hiucko commented
_Finally_

2023-11-21 12:05 UTC, Morb0 requested changes
Loading Map: /Maps/corvax_gate.yml
 SERVER: 9,317s [ERRO] map: Error in map file: found local entity UID '0' which does not exist.

2023-11-22 12:27 UTC, Bloodcanis commented
Да откуда эти инвалиды берутся, едридь их в корень.

2023-11-22 13:02 UTC, Bloodcanis commented
Убрал инвалид у гейта остаточны, а вот откуда ещё идёт UID 0 не понимяу, фолловедов нет, инвалидов нет, что там ещё на спектруме может его вызывать, учитывая, что мы опустошали,  а не добавляли я хз. Карта на локалке грузится и работает.

2023-11-22 13:54 UTC, Morb0 requested changes
Found no latejoin spawn points on CorvaxAvrite

2023-11-22 15:01 UTC, lzk228 commented
не упоминайте меня в своих шизо-высерах.

2023-11-22 16:37 UTC, merged