Update salvage-system.ftl
space-syndicate/space-station-14 pull request #158
Opened 2022-03-23 13:56 UTC by fineks

## Описание PR 

**Скриншоты**

**Изменения**

:cl: fineks
- add: Перевод оповещений магнита

2022-03-23 15:24 UTC, Morb0 requested changes

2022-03-23 15:24 UTC, Morb0 commented on Resources/Locale/ru-RU/salvage/salvage-system.ftl
> +salvage-system-magnet-examined-pulling-in = Магнит пытается притянуть перерабатываемые обломки.
Может лучше просто обломки? без перерабатываемые.

2022-03-23 15:24 UTC, Morb0 commented on Resources/Locale/ru-RU/salvage/salvage-system.ftl
> +salvage-system-magnet-examined-active = МАгнит удерживает обломки. Время удержания { $timeLeft } секунд.
```suggestion
salvage-system-magnet-examined-active = Магнит удерживает обломки. Время удержания { $timeLeft } секунд.
```

2022-03-23 15:24 UTC, Morb0 commented on Resources/Locale/ru-RU/salvage/salvage-system.ftl
> +salvage-system-magnet-examined-cooling-down = Магнит на перезарядке.
Почему бы не оставить как в оригинале информацию, что он именно `остывает.`

2022-03-24 06:14 UTC, fineks commented on Resources/Locale/ru-RU/salvage/salvage-system.ftl
> +salvage-system-announcement-losing = Магнит больш не может удерживать обломки. Время удержания: { $timeLeft } секунд.
Исправлю.

2022-03-24 06:19 UTC, fineks commented on Resources/Locale/ru-RU/salvage/salvage-system.ftl
> +salvage-system-magnet-examined-cooling-down = Магнит на перезарядке.
Я думал об этом, но cooling down перевести и как охлаждение, как и перезарядка.

2022-03-26 13:53 UTC, Morb0 approved these changes
Исправил сам.

2022-03-26 14:04 UTC, merged