fix
space-syndicate/space-station-14 pull request #1581
Opened 2023-11-22 21:01 UTC by VigersRay

## Описание PR

Заметил что нихуя не работает злой двойник, после входа на роль тебя бросает в госты, + цель на убийство не отображалась.
Почему бросало в госты? В душе не ебу, почему mind оставалось просле переноса на спавнере и после его удаления игрок обратно бросается в госты. Перекинул удаление перед переносом mind и сделал его без очереди.
Еще что забавно - если проверять спавн двойника в дебаг версии - такого бага не будет.

**Медиа**

**Проверки**

- [X] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [X] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [X] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

2023-11-23 00:42 UTC, SonicHDC commented
Лучше сразу кидать оффам, теперь двойник и у них.
P.S. Рад что ты живой и с нами (:

2023-11-23 01:33 UTC, VigersRay commented
> Лучше сразу кидать оффам, теперь двойник и у них. P.S. Рад что ты живой и с нами (:

нее, я с оффами не дружу, раз у них то наверное он должен быть рабочий?.. Или нет?

2023-11-23 03:22 UTC, SonicHDC commented
> > Лучше сразу кидать оффам, теперь двойник и у них. P.S. Рад что ты живой и с нами (:
> 
> нее, я с оффами не дружу, раз у них то наверное он должен быть рабочий?.. Или нет?

нет, у них тоже самое что и у нас

2023-11-23 08:54 UTC, lzk228 commented
> Лучше сразу кидать оффам, теперь двойник и у них. P.S. Рад что ты живой и с нами (:

чекни какие файлы изменены в этом пре

2023-11-23 16:45 UTC, Morb0 requested changes

2023-11-23 16:45 UTC, Morb0 commented on Content.Server/Corvax/EvilTwin/EvilTwinSystem.cs
>                  _mindSystem.TransferTo(mindId, spawnedTwin);
Удаление должно быть последним шагом, используя QueueDel

2023-11-23 18:43 UTC, VigersRay commented on Content.Server/Corvax/EvilTwin/EvilTwinSystem.cs
>                  _mindSystem.TransferTo(mindId, spawnedTwin);
В таком случае при удалении спавнера игрок будет кинут в госты. Почему я в душе не чаю, очень странная штука, с аналогичным спавнером допустим беглеца у меня всё работает. Тут или оффы опять поломали что-то, или волшебство.
Почему-то даже после _mindSystem.TransferTo(mindId, spawnedTwin); внутри MindComponent спавнера остается записано mindId игрока. 
Если еще вариант не удалять спавнер а просто убрать у него компоненты призрак роли, чтобы новые игроки не заходили.
Впрочем я много вариантов пробывал и это пожалуй эдиный рабочий, удалить спавнер перед переносом сознания.
Кстати попытаться просто выкинуть создание через _mindSystem.TransferTo(mindId, null); тоже ничего не дает.

2023-11-23 23:13 UTC, Morb0 commented on Content.Server/Corvax/EvilTwin/EvilTwinSystem.cs
>                  _mindSystem.TransferTo(mindId, spawnedTwin);
> В таком случае при удалении спавнера игрок будет кинут в госты.
Я не разбирался, но предположу, что возможно uid указывает на `session.AttachedEntity` и вызов `QueueDel` ставит удаление в очередь на следующий тик, в котором  `session.AttachedEntity` уже будет тело двойника.

2024-04-12 00:26 UTC, SoulFN commented
Если оффам надо, тогда может закроете ПР? Он все равно не обновляется давно

2024-05-20 19:31 UTC, closed without merging