Различные переводы
space-syndicate/space-station-14 pull request #160
Opened 2022-03-25 11:32 UTC by lapatison

## Описание PR 

**Скриншоты**

**Изменения**

:cl: lapatison
- add: переводы компьютеров, машин, торговых автоматов, раздатчиков одежды, их рекламы, подсказок при строительстве, атмосферного оборудования

2022-03-25 13:54 UTC, Morb0 requested changes

2022-03-25 13:54 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/machines/lathe.ftl
> +    .desc = Печатает снаряжение для службы безопасности, и немного базового.
```suggestion
    .desc = Печатает снаряжение для службы безопасности и некоторые базовые вещи.
```

2022-03-25 13:54 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/machines/computers/computers.ftl
> +ent-ComputerCriminalRecords = компьютер для криминальных записей
Можно ли обойтись без `для`?
так же относится и к переводам ниже

2022-03-25 13:54 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/machines/computers/computers.ftl
> +    .desc = Компьютер, используемый для взаимодействия с оборудованием для НИОКР.
Не уверен готовы ли люди сейчас переименовать R&D в НИОКР. Думаю пока стоит оставить Р&Д.

2022-03-25 13:54 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/machines/recycler.ftl
> +    .desc = Большая дробящая машина, используемая для неэффективной переработки мелких предметов. На боковой стороне есть огни.
```suggestion
    .desc = Большая дробящая машина, используемая для неэффективной переработки мелких предметов. На боковой стороне есть лампочки.
```

2022-03-25 13:54 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/machines/computers/arcades.ftl
> +ent-BlockGameArcade = НТ тетрис
Тут шутка именно в том, что это не тетрис а block game, даже по описанию видно.

2022-03-25 13:54 UTC, Morb0 commented on Resources/Locale/ru-RU/cuffs/components/cuffable-component.ftl
> +cuffable-component-remove-cuffs-partial-success-message = Вы успешно снимаете наручники. { $cuffedHandCount } ваших рук остаются в наручниках.
Нужно добавлять fluent конструкцию для изменения склонения слова рук в зависимости от количества рук в переменной, примеры такого уже были с руками.

2022-03-25 13:54 UTC, Morb0 commented on Resources/Locale/ru-RU/cuffs/components/cuffable-component.ftl
>  cuffable-component-remove-cuffs-fail-message = You fail to remove the cuffs.
Не переведено.

2022-03-25 13:54 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/machines/research.ftl
> +ent-BaseResearchAndDevelopmentPointSource = базовый источник очков НИОКР
Не думаю, что готовы переименовывать, поэтому лучше пока Р&Д.

2022-03-25 13:54 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/machines/vending_machines.ftl
> +    .desc = Автомат прохладительных напитков, предоставленный компанией Робаст Индастриз, LLC.
```suggestion
    .desc = Автомат прохладительных напитков, предоставленный компанией Робаст Индастриз, OOO.
```

2022-03-25 13:54 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/machines/vending_machines.ftl
> +ent-VendingMachineSec = ОхрТех
Так получше звучит
```suggestion
ent-VendingMachineSec = СБТех
```

2022-03-25 13:54 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/machines/vending_machines.ftl
> +ent-VendingMachineSnack = Ешьбольш Шоколад Корп
Возможно названия типа ShadyCigs Deluxe и Getmore Chocolate Corp, не стоит переводить? Выглядит как то не очень.

2022-03-25 13:54 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/machines/vending_machines.ftl
>  ent-VendingMachineGames = Good Clean Fun
Пропущен перевод

2022-03-25 13:54 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/machines/vending_machines.ftl
> +    .desc = Протест! Этот шкаф обеспечивает верховенство закона... и адвокатской одежды...
Хм, может так?
`Протест! Этот шкаф обеспечивает верховенство закона... и адвоката одеждой...`

2022-03-25 13:54 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/machines/vending_machines.ftl
> +    .desc = Этот относительно безызвестный торговый автомат выдаёт одежду для атмосферных техников, на редкость безызвестный должности.
```suggestion
    .desc = Этот относительно безызвестный торговый автомат выдаёт одежду для атмосферных техников, на столько же безызвестной должности.
```

2022-03-25 13:54 UTC, Morb0 commented on Resources/Locale/ru-RU/station-events/events/meteor-swarm.ftl
> +station-event-meteor-swarm-ebd-announcement = Метеоритный поток миновал. Пожалуйста, вернитесь на свои рабочие места.
Может все таки роя?
```
Метео́рный пото́к — совокупность метеоров, порождённых вторжением в атмосферу Земли роя метеорных тел.
Wikipedia
```

2022-03-25 18:48 UTC, lapatison commented on Resources/Locale/ru-RU/actions/actions/pai.ftl
> +action-name-pai-play-midi = Включить MIDI
`Проиграть` не очень, как тебе такой вариант?

2022-03-25 18:54 UTC, lapatison commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/machines/vending_machines.ftl
> +ent-VendingMachineSnack = Ешьбольш Шоколад Корп
Окей, эти два были спорными, заменю транслитерацией, как с Робаст

2022-03-25 19:06 UTC, lapatison commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/machines/vending_machines.ftl
> +    .desc = Протест! Этот шкаф обеспечивает верховенство закона... и адвокатской одежды...
Да, упустил из виду

2022-03-25 19:13 UTC, lapatison commented on Resources/Locale/ru-RU/station-events/events/meteor-swarm.ftl
> +station-event-meteor-swarm-ebd-announcement = Метеоритный поток миновал. Пожалуйста, вернитесь на свои рабочие места.
Вернул с фиксами

2022-03-25 22:33 UTC, lapatison commented on Resources/Locale/ru-RU/cuffs/components/cuffable-component.ftl
> +cuffable-component-remove-cuffs-partial-success-message = Вы успешно снимаете наручники. { $cuffedHandCount } ваших рук остаются в наручниках.
Вроде готово.

2022-03-25 23:06 UTC, Morb0 requested changes

2022-03-25 23:06 UTC, Morb0 commented on Resources/Locale/ru-RU/cuffs/components/cuffable-component.ftl
> +     } в наручниках.
```suggestion
cuffable-component-remove-cuffs-to-other-partial-success-message = 
    Вы успешно снимаете наручники. { $cuffedHandCount } { $cuffedHandCount ->
        [one] рука осталась
        [few] руки остались
       *[other] рук остались
    } у { $otherName } в наручниках.
cuffable-component-remove-cuffs-by-other-partial-success-message =
    { $otherName } успешно снимает с вас наручники. { $cuffedHandCount } { $cuffedHandCount ->
        [one] ваша рука осталась
        [few] ваши руки остаются
       *[other] ваши руки остаются
     } в наручниках.
cuffable-component-remove-cuffs-partial-success-message =
    Вы успешно снимаете наручники. { $cuffedHandCount } { $cuffedHandCount ->
        [one] ваша рука осталась
        [few] ваши руки остаются
       *[other] ваши руки остаются
     } в наручниках.
```

2022-03-26 00:17 UTC, Morb0 requested changes

2022-03-26 00:17 UTC, Morb0 commented on Resources/Locale/ru-RU/construction/components/machine-board-component.ftl
> +machine-board-component-required-element-entry-text = [color=yellow]{ $amount }ед.[/color] [color=green]{ $requiredElement }[/color]
Точка сбивает предложение.
```suggestion
machine-board-component-required-element-entry-text = [color=yellow]{ $amount }ед[/color] [color=green]{ $requiredElement }[/color]
```

2022-03-26 00:17 UTC, Morb0 commented on Resources/Locale/ru-RU/construction/conditions/machine-frame-complete.ftl
> +construction-condition-machine-frame-required-element-entry = [color=yellow]{ $amount }ед.[/color] [color=green]{ $elementName }[/color]
```suggestion
construction-condition-machine-frame-required-element-entry = [color=yellow]{ $amount }ед[/color] [color=green]{ $elementName }[/color]
```

2022-03-26 00:17 UTC, Morb0 commented on Resources/Locale/ru-RU/construction/steps/material-construction-graph-step.ftl
> +construction-insert-material-entity = Далее, добавьте [color=yellow]{ $amount }ед.[/color] [color=cyan]{ $materialName }[/color].
```suggestion
construction-insert-material-entity = Далее, добавьте [color=yellow]{ $amount }ед[/color] [color=cyan]{ $materialName }[/color].
```

2022-03-26 00:17 UTC, Morb0 commented on Resources/Locale/ru-RU/construction/ui/construction-menu-presenter.ftl
> +construction-presenter-material-step = Добавьте { $amount }ед. { LOC($material) }.
```suggestion
construction-presenter-material-step = Добавьте { $amount }ед { LOC($material) }.
```

2022-03-26 09:52 UTC, merged