real moth accent locale
space-syndicate/space-station-14 pull request #1610
Opened 2023-12-05 16:58 UTC by lzk228

## Описание PR

**Медиа**

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:
- add: Добавлено веселье!
- remove: Убрано веселье!
- tweak: Изменено веселье!
- fix: Исправлено веселье!

2023-12-05 17:36 UTC, lzk228 commented
фиксанул всё

2023-12-08 13:37 UTC, Morb0 requested changes

2023-12-08 13:37 UTC, Morb0 commented on Content.Server/Speech/EntitySystems/MothAccentSystem.cs
> +        /// Corvax-Localization-End
```suggestion
        // Corvax-Localization-End
```

2023-12-08 13:37 UTC, Morb0 commented on Content.Server/Speech/EntitySystems/LizardAccentSystem.cs
> +using Robust.Shared.Random; // Corvax-Localization
```suggestion
using Robust.Shared.Random;
```

2023-12-08 13:37 UTC, Morb0 commented on Content.Server/Speech/EntitySystems/MothAccentSystem.cs
> +using Robust.Shared.Random; // Corvax-Localization
```suggestion
using Robust.Shared.Random;
```

2023-12-08 13:38 UTC, merged