BarkAccent localisation
space-syndicate/space-station-14 pull request #1652
Opened 2023-12-17 16:37 UTC by TheShuEd

## Описание PR

Заголовок
**Медиа**

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:
- add: Добавлено веселье!
- remove: Убрано веселье!
- tweak: Изменено веселье!
- fix: Исправлено веселье!

2023-12-17 16:53 UTC, lzk228 commented on Content.Server/Speech/EntitySystems/BarkAccentSystem.cs
> +            //Corvax-Localization-End
тут без старт и енд, просто сбоку `// Corvax-Localization` с пробелом(!)

2023-12-17 16:56 UTC, TheShuEd commented on Content.Server/Speech/EntitySystems/BarkAccentSystem.cs
> +            //Corvax-Localization-End
Шо

2023-12-17 16:56 UTC, TheShuEd commented on Content.Server/Speech/EntitySystems/BarkAccentSystem.cs
> +            //Corvax-Localization-End
Куда пробел

2023-12-17 16:56 UTC, lzk228 commented on Content.Server/Speech/EntitySystems/BarkAccentSystem.cs
> +            //Corvax-Localization-End
блять по темплейту сделай в дискорде

2023-12-17 16:58 UTC, TheShuEd commented on Content.Server/Speech/EntitySystems/BarkAccentSystem.cs
> +            //Corvax-Localization-End
Проверяй

2023-12-17 17:34 UTC, JerryImMouse commented
> localisation
localiZation 🤓

2023-12-17 17:46 UTC, JerryImMouse commented on Content.Server/Speech/EntitySystems/BarkAccentSystem.cs
> +                //Corvax-Localization-End
```suggestion
                .Replace("л", "р").Replace("Л", "Р"); // Corvax-Localization     
```

2023-12-17 17:46 UTC, JerryImMouse commented on Content.Server/Speech/EntitySystems/BarkAccentSystem.cs
> +            " Гав!", " ГАВ", " вуф-вуф"
```suggestion
            " Гав!", " ГАВ", " вуф-вуф" // Corvax-Localization
```

2023-12-20 23:39 UTC, Morb0 requested changes

2023-12-20 23:39 UTC, Morb0 commented on Content.Server/Speech/EntitySystems/BarkAccentSystem.cs
> +                //Corvax-Localization-End
Задевается изменением 2 строка
```suggestion
                //Corvax-Localization-Start
                .Replace("l", "r").Replace("L", "R")
                .Replace("л", "р").Replace("Л", "Р");
                //Corvax-Localization-End
```

2023-12-20 23:41 UTC, Morb0 requested changes

2023-12-20 23:41 UTC, Morb0 commented on Content.Server/Speech/EntitySystems/BarkAccentSystem.cs
> +            " Гав!", " ГАВ", " вуф-вуф"
```suggestion
            " Гав!", " ГАВ", " вуф-вуф"  // Corvax-Localization
```

2023-12-20 23:41 UTC, merged