Гайдбук ниндзи
space-syndicate/space-station-14 pull request #1684
Opened 2023-12-25 22:31 UTC by AwareFoxy

## Описание PR
Чуточка https://github.com/space-syndicate/space-station-14/issues/1642

**Медиа**

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

2023-12-25 23:16 UTC, lzk228 requested changes

2023-12-25 23:16 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Antagonist/SpaceNinja.xml
>  <GuideEntityEmbed Entity="ClothingHandsGlovesSpaceNinja" Caption="ninja gloves"/>
кепшн не переведён

2023-12-25 23:16 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Antagonist/SpaceNinja.xml
> +Эти парни - ваш хлеб и масло.
эти плохие парни

2023-12-25 23:16 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Antagonist/SpaceNinja.xml
> +У вас есть действие, чтобы включить перчатки. Когда перчатки включены, они позволяют вам использовать специальные способности, которые срабатывают при взаимодействии с предметами пустой рукой и при о
может дело вкуса но я бы изменил на "... с предметами пустой рукой и отключённым боевым режимом"

2023-12-25 23:16 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Antagonist/SpaceNinja.xml
> +- Зарядка от источников энергии, таких как ЛКП, подстанций или СМЭСов. Чем выше напряжение в источнике, тем эффективнее заряжается ваш костюм.
первое - что делать
второе - действие
я бы изменил на "Взламывание неограниченного..."
чтобы было схоже

2023-12-25 23:16 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Antagonist/SpaceNinja.xml
>  <GuideEntityEmbed Entity="EnergyKatana" Captain="energy katana"/>
кепшн

2023-12-25 23:16 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Antagonist/SpaceNinja.xml
>  <GuideEntityEmbed Entity="SpiderCharge" Caption="spider clan charge"/>
кепшн

2023-12-25 23:16 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Antagonist/SpaceNinja.xml
> +Модифицированная взрывчатка C-4, вы появляетесь с ней в кармане. Она создает большой взрыв, но должна быть установлена в зоне поражения.
```suggestion
Модифицированная взрывчатка C-4, вы появляетесь с ней в кармане. Она создаёт большой взрыв, но должна быть установлена в зоне поражения.
```
+ зона не поражения а таргет т.е. целевая или типа того

2023-12-25 23:16 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Antagonist/SpaceNinja.xml
> +Зона поражения выбирается случайно, она является одной из ваших целей. Эту бомбу нельзя активировать вручную, просто прикрепите её к стене или чему-то еще.
как и выше

2023-12-25 23:16 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Antagonist/SpaceNinja.xml
> +# Ваши цели
просто цели

2023-12-25 23:16 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Antagonist/SpaceNinja.xml
> +- Взломайте несколько дверей на станции: Ваши перчатки могут взламывать шлюзы. Сделайте это с указанным в цели количеством дверей.
я бы оставил Х, вместо нексколько

2023-12-25 23:16 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Antagonist/SpaceNinja.xml
> +- Взорвать бомбу клана Паука в отделе станции: Эта бомба может быть взорвана в указанном в цели месте на станции. Обратите внимание, что бомба не сработает в другом месте!
```suggestion
- Взорвать бомбу клана Паука: Заложите заряд клана Паука в нужном месте и посмотрите, как он взорвётся.
```

2023-12-25 23:16 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Antagonist/SpaceNinja.xml
> +- Призвать угрозу: Используйте свои перчатки на консоли связи, чтобы навлечь на станцию ещё одну угрозу.
так ты определись, тут "Используйте перчатки" а выше "перчатки могут быть использованы"

2023-12-25 23:28 UTC, lapatison commented on Resources/ServerInfo/Guidebook/Antagonist/SpaceNinja.xml
> +# Ваша экипировка
Лучше оставить, не так сухо будет

2023-12-25 23:29 UTC, lapatison commented on Resources/ServerInfo/Guidebook/Antagonist/SpaceNinja.xml
> +Так-же у вас есть джетпак и пинпойнтер, он поможет вам найти станцию.
вместо `он` лучше `который`

2023-12-25 23:30 UTC, lapatison commented on Resources/ServerInfo/Guidebook/Antagonist/SpaceNinja.xml
> +Текущий заряд можно узнать, посмотрев на костюм или в оповещении в правом верхнем углу экрана.
Не стоит буквально переводить

2023-12-25 23:34 UTC, lapatison commented on Resources/ServerInfo/Guidebook/Antagonist/SpaceNinja.xml
> +Эти парни - ваш хлеб и масло.
`your bread and butter` - идиома, и прямой перевод мне не кажется удачным решением

2023-12-25 23:34 UTC, lapatison commented on Resources/ServerInfo/Guidebook/Antagonist/SpaceNinja.xml
> +- Вы можете ударить любого моба током, оглушив и слегка поранив его.
моб - существо

2023-12-26 15:41 UTC, AwareFoxy commented on Resources/ServerInfo/Guidebook/Antagonist/SpaceNinja.xml
> +# Ваша экипировка
> Лучше оставить, не так сухо будет то же мнение и ниже по тексту

так что оставлять? :pleading_face:

2023-12-26 16:26 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Antagonist/SpaceNinja.xml
> +<GuideEntityEmbed Entity="ClothingOuterSuitSpaceNinja" Captain="костюм ниндзя"/>
```suggestion
<GuideEntityEmbed Entity="ClothingOuterSuitSpaceNinja" Caption="костюм ниндзя"/>
```

2023-12-26 16:26 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Antagonist/SpaceNinja.xml
> +<GuideEntityEmbed Entity="EnergyKatana" Captain="энергетическая катана"/>
```suggestion
<GuideEntityEmbed Entity="EnergyKatana" Caption="энергетическая катана"/>
```

2023-12-29 13:36 UTC, merged