Принтер документов
space-syndicate/space-station-14 pull request #1700
Opened 2023-12-29 22:24 UTC by TheShuEd

## Описание PR
По просьбе Бладканиса возвращение принтера, вместе с правками от Морти и Лазика. И еще пара фиксов от меня.

**Медиа**

![image](https://github.com/space-syndicate/space-station-14/assets/96445749/6992233b-8f40-496c-bf55-9b42fed32200)

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**
CL не пишу, потому что его сначала замаппить еще надо. А это отдельные пры.

2023-12-29 22:26 UTC, Bloodcanis commented
Миску риса с порцией говядины данному человеку

2023-12-29 22:29 UTC, TheShuEd commented
Так, я ошибки завтра дочиню

2023-12-29 22:35 UTC, lzk228 commented
только так, НИКАКОГО МАППИНГА, ТОЛЬКО ЧЕРЕЗ МИГРАЦИЮ!
буквально завтра могут добавить функционал консоли оповещений, а на консоль крим записей даже ПР висит.
легче будет именно стереть строчку с одного файла чем менять файлы карт

2023-12-29 22:36 UTC, TheShuEd commented
Я вообще не ебу что это за миграция, копировал тот пр.

Надо, уберу

2023-12-29 22:38 UTC, Bloodcanis commented
Сколько нужно контрибуторов, что бы поставить 1 принтер?=)

2023-12-29 22:39 UTC, TheShuEd commented
4
Один прит
Второй правит
Третий ревьювит
Четвертый маппит

2023-12-29 22:58 UTC, Agoichi commented
Он герой которого мы заслужили, но которого мы имеем и будем иметь

2023-12-29 23:33 UTC, Krosus777 commented
Ошибки так остались, ругается на материал. Хотя в таком написании он идеально работает.

2023-12-30 00:07 UTC, SonicHDC commented
Если подумать, то через миграцию получается странно. Ведь принтеры появятся у сб и в случайных отделах.
Это нормально? Не думаю.
Лучше сделайте плату для автолата и рецепт через каркас.

2023-12-30 21:26 UTC, TheShuEd commented
Добавил крафт через плату и каркас. Плата доступна раундстартом.

2023-12-30 22:12 UTC, lzk228 commented on Resources/Prototypes/Corvax/Entities/Objects/Materials/Sheets/other.yml
разные прототипы в одном файле, нужно разделить

2023-12-30 22:12 UTC, lzk228 commented on Resources/Prototypes/Entities/Structures/Machines/lathe.yml
> +    # Corvax-Printer-End
```suggestion
    - PrinterDocMachineCircuitboard # Corvax-Printer
```

2024-01-19 12:29 UTC, lzk228 commented on Resources/Prototypes/Entities/Objects/Misc/paper.yml
> +# Corvax-Printer-End
вот это закинь оффам сначала, в любом случае мне кажется бумажные листы когда-то будут использоватся для протолата, так почему бы не добавить это сразу? чтобы было меньше изменений в нашей сборке

2024-01-19 12:47 UTC, TheShuEd commented on Resources/Prototypes/Entities/Objects/Misc/paper.yml
> +# Corvax-Printer-End
Потребуют сразу в геймплей встроить

2024-01-19 12:53 UTC, lzk228 requested changes
ещё надо засунуть в migration.yml вместо какой-то неработающей консоли

так вроде вопросов нет, после правок я ещё на локалке протестирую

2024-01-19 12:53 UTC, lzk228 commented on Resources/Prototypes/Corvax/Entities/Structures/Machines/printer.yml
> +  parent: BaseLathe
как и говорил в предыдущем пре, возьми автолат за основу

2024-01-19 12:53 UTC, lzk228 commented on Resources/Prototypes/Corvax/Catalog/Fills/Paper/document.yml
![image](https://github.com/space-syndicate/space-station-14/assets/124214523/f0e789c4-2261-484c-be10-b791b3bb10f8)

2024-01-19 12:55 UTC, lzk228 commented
ещё можно добавит кому-то в шкафчик плату или две, чтобы раундстартом можно было собрать где нужно

2024-01-19 13:10 UTC, TheShuEd commented on Resources/Prototypes/Corvax/Entities/Structures/Machines/printer.yml
> +  parent: BaseLathe
Насколько я помню мне наоборот уже говорили убрать из миграции, можно поискать в фидьеке выше.

Автолат по какой то причине не получилось использовать. Не помню щас почему, но я пробовал, т.к. видел этот фидбек

2024-01-19 13:11 UTC, TheShuEd commented on Resources/Prototypes/Corvax/Entities/Structures/Machines/printer.yml
> +  parent: BaseLathe
А, хм, это ты сказала только через миграцию наоборот... И я после этого миграцию убрал кажись

2024-01-19 13:13 UTC, TheShuEd commented
Ее можно раундстарт собирать, ее плата в рнд раундстартом в принтере схем

2024-01-19 13:31 UTC, lzk228 commented
может в автолат поместить?

2024-01-19 23:11 UTC, SonicHDC commented on Resources/migration.yml
> +ComputerCriminalRecords: PrinterDoc
Думаю, всё же лучше не добавлять консоль криминальных записей в миграцию, ведь она всегда находится лишь у сб.
Это просто ненужная замена, просто во всех патрульных пунктах будут принтеры, а это сьранно.
Консоль оповещений пока лучший вариант, она в командовании чаще всего стоит, поэтому гп может легко её использовать.
Но честно миграция вещь довольно спорная. Появление непредвиденных принтеров непонятно где. Мапперам лишняя работа по удалению ненужных предметов с карт корвакса.
```suggestion
```

2024-01-30 20:04 UTC, lzk228 requested changes
- вот это выглядит странно, в таком случае лучше вовсе убрать миграцию
и вместо этого сделай упакованный принтер, который будет в шкафчике ГП и где-то ещё
![Screenshot_20240130_205500](https://github.com/space-syndicate/space-station-14/assets/124214523/b60e06b9-7888-469e-bb0e-be8c90cbff5f)
![Screenshot_20240130_205518](https://github.com/space-syndicate/space-station-14/assets/124214523/28b02da6-a124-4613-bd7c-05dd9e053e99)


- безымянная бумага
![Screenshot_20240130_205534](https://github.com/space-syndicate/space-station-14/assets/124214523/f982a4e7-bd2c-4d03-8194-9fe715481138)


- максимальный стак 1, иначе можно просто терять написанные текста стакая бумагу
![Screenshot_20240130_205720](https://github.com/space-syndicate/space-station-14/assets/124214523/ebdb5327-e5e4-4315-81e0-96f699470d86)

2024-01-31 22:34 UTC, lzk228 commented on Resources/Prototypes/Corvax/Entities/Structures/Machines/printer.yml
> +  description: Бюрократическое совершенство. Хранит базу данных всех документов Nanotrasen, и дает возможность печатать их, пока у вас есть бумага.
это ещё на английский надо вроде

2024-02-01 14:49 UTC, closed without merging