Added sprites for cyrilic letters
space-syndicate/space-station-14 pull request #1706
Opened 2023-12-30 20:27 UTC by 778b

## Описание PR

Добавлены спрайты для кириллицы, теперь все что имеет компонент TextScreenVisualsComponent (бриг-таймер и сигнал таймер) поддерживают кириллицу, ну и так же любой текст вне UI который будет иметь тот же принцип действия то же будет использовать эти наборы спрайтов.

**Медиа**

![Content Client_iMx83tMYjk](https://github.com/space-syndicate/space-station-14/assets/33431126/714c26be-4260-46f9-a123-657b86804c93)

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: 778b
- add: Добавлена поддержка кириллицы для бриг и сигнал таймеров

2023-12-30 20:29 UTC, 778b commented
ЗЫ. в другую папку спрайты не убрать, тк в коде явно прописан путь до них

2024-01-10 11:42 UTC, Morb0 requested changes
Добавь себя в copyright поле

2024-01-14 22:30 UTC, Morb0 requested changes

2024-01-14 22:30 UTC, Morb0 commented on Resources/Textures/Effects/text.rsi/meta.json
> +  "copyright": "Created by rolfero(English and numbers)(github) for Space Station 14 and 778b(Cyrillic)(github) for Corvax",
```suggestion
  "copyright": "Created by rolfero (github) for Space Station 14 and cyrillic 778b (github) for Corvax",
```

2024-01-14 22:32 UTC, merged