Роль - Магистрат
space-syndicate/space-station-14 pull request #1711
Opened 2024-01-02 18:29 UTC by Agoichi

## Описание PR

**Начну с того почему я сделал Pull Request Корваксу а не Волшебникам**
Это дело принципа.
Волшебники взяли курс и держат его прямиком в пучины лрп. Соответствено любая предложка которая будет нацеленна на улучшение мрп будет откланятся за ненадобностью для них.
Наш проект корвакс позиционирует себя как МРП и следовать во всем лрп проекту я считаю крайне не дальновидным.

Мой ПР добавляет новую роль в пул ролей, элементы одежды, кпк, гарнитуру, ID карту, молот судьи и новый штамп. 
Также вносит изменения в прототип карт для внедрения новой роли
Роль - Магистрат.

**Почему эта наработка может быть внедрена в корвакс и не нарушает логику и атмосферу оного:**
Так как мне много чего есть сказать я приведу ссылку на предложение в канале сервера корвакс которое я создал в поддержку этому пр-у, и в котором приведен почти каждый аргумент который у меня имеется.
Ссылка на предложку на Дискорд сервере корвакс: ⁠https://discord.com/channels/919301044784226385/1190065917518938122

**Медиа**
![image](https://github.com/space-syndicate/space-station-14/assets/92464780/3d85537e-ea7f-4c23-9258-4e2ad8360ff3)

**Проверки**

- [х] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [х] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [х] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [х] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

- add:  Добавлена новая роль - Магистрат 
- add:  Добавлены элементы одежды магистрата (Парик магистрата, мантия магистрата)
- add:  Добавлены девайсы (Гарнитура магистрата, КПК магистрата с ручкой центком + ID карта магистрата )
- add:  Добавлен судейский молот магистрата (добавлены также звуки удара)
- add:  Добавлен штамп магистрата
- tweak:  Изменены прототипы карт (Добавлин магистрат в них. В карты корвакса с возможностью раундстарта, для карт оффов только с поздним подключением из-за политики не маппинга оффовских карт)

:cl:
- add: Добавлен магистрат и его одежда!
- add: Добавлен молот магистрата со встроенным предохранителем!
- add: Добавлен штамп магистрата!

2024-01-02 18:57 UTC, lzk228 requested changes
1. Меня волнует то, что в прототипах и локали разные описания.
2. В описаниях ссылается на другие професии, как-то не очень в целом выглядит.
3. Магистрат, везде в файлах судья почему-то.
4. Пожалуйста, никаких раундстартовых магистратов на картах корвакса. Люди будут выбирать карты потому что они лучше и будет неравновесие в картах.

2024-01-02 18:57 UTC, lzk228 commented on Resources/Locale/ru-RU/job/job-description.ftl
> +job-description-judge = Бдите за соблюдением закона, судите клоуна в начале смены и кричите на вашего АВД.
вашего авд?
плюс эту строку в папку corvax

2024-01-02 18:57 UTC, lzk228 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/corvax/entities/clothing/outerclothing/misc.ftl
> +ent-ClothingUniformMagistrat = Накидка магистрата
с маленькой буквы

2024-01-02 18:57 UTC, lzk228 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/weapons/melee/judge_hammer.ftl
> +ent-MagistratHammer = Молот Магистрата
с маленькой

2024-01-02 19:25 UTC, 778b commented
Ну скорее надо было делать ПР волшебникам, у корваксов все таки парадигма что они АДАПТИРУЮТ контент волшебников для РУ комьюнити, поэтому твой ПР скорее всего побреют

2024-01-02 20:46 UTC, Nimfar11 commented
Я "за" хотябы ради эксперимента, как оно покажет себя в деле, а не виртуальном размышлении. Но проблема размещения Магистрата останется, ведь "своей" комнаты у него не будет. Разве что сидеть в комнате АВД. 
И разве Магистрату нужен "Внешний" доступ?

2024-01-02 20:52 UTC, Agoichi commented on Resources/Locale/ru-RU/job/job-description.ftl
> +job-description-judge = Бдите за соблюдением закона, судите клоуна в начале смены и кричите на вашего АВД.
Сделал.
Что касается приписки "вашего авд" то ничего критического в этом не вижу. Магистрат в реалиях сс13 был главой авд. И даже в наших реалиях срп является его главой. Плюс у магистрата только один работник АВД.
Так что фраза вашего АВД очень даже не плохо смотрится по моему мнению.

2024-01-02 20:52 UTC, Agoichi commented on Resources/Locale/ru-RU/ss14-ru/prototypes/corvax/entities/clothing/outerclothing/misc.ftl
> +ent-ClothingUniformMagistrat = Накидка магистрата
Исправил

2024-01-02 20:53 UTC, Agoichi commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/weapons/melee/judge_hammer.ftl
> +ent-MagistratHammer = Молот Магистрата
Исправил

2024-01-03 18:24 UTC, lapatison commented
Почему магистрат, а не судья?

2024-01-03 18:38 UTC, Agoichi commented
> Почему магистрат, а не судья?

Потому что в нашем срп есть магистрат, магистрат есть и на парадайзе откуда был взят авд.

2024-01-31 06:21 UTC, MureixloI commented
> Почему магистрат, а не судья?

Звучит брутальнее, а также на вики написано как магистрат

2024-01-31 08:48 UTC, Deserty0 commented
> Главное не добавлять его в раундстарт-роли, ибо магистрат это дядечка, который 90% смены сидит и пинает балду, потому что ему попросту нечего делать. Только для ивентов

Так прототипом всегда можно, смысл пра добавление дядечки Магистрата в структуру процедурного ака юридического отдела

2024-01-31 10:47 UTC, MureixloI commented
> > > Главное не добавлять его в раундстарт-роли, ибо магистрат это дядечка, который 90% смены сидит и пинает балду, потому что ему попросту нечего делать. Только для ивентов
> > 
> > 
> > Так прототипом всегда можно, смысл пра добавление дядечки Магистрата в структуру процедурного ака юридического отдела
> 
> Тут не спорю, да и лут его нужная штука, а то пихать в суд резиновый молоток клоуна - такое себе
Да не, круто же молотком клоунским. Обвиняемый будет радоваться

2024-01-31 11:55 UTC, Deserty0 commented
> > > > Главное не добавлять его в раундстарт-роли, ибо магистрат это дядечка, который 90% смены сидит и пинает балду, потому что ему попросту нечего делать. Только для ивентов
> > > 
> > > 
> > > Так прототипом всегда можно, смысл пра добавление дядечки Магистрата в структуру процедурного ака юридического отдела
> > 
> > 
> > Тут не спорю, да и лут его нужная штука, а то пихать в суд резиновый молоток клоуна - такое себе
> > Да не, круто же молотком клоунским. Обвиняемый будет радоваться

по решению суда присяжных, вы приговорены к каторге на клоунской станции *хонк*

2024-02-07 18:54 UTC, closed without merging

2024-04-30 19:45 UTC, Dmitry2777 commented
Круто