Resprite science magboots
space-syndicate/space-station-14 pull request #1719
Opened 2024-01-03 20:50 UTC by lzk228

title

2024-01-03 21:29 UTC, MureixloI commented
Прикольно, но оно будет отличаться от палитры палитры снаряжения

2024-01-31 22:25 UTC, lzk228 commented
@Morb0 merg

2024-02-01 11:55 UTC, Morb0 requested changes
Постфикс не `-digi` теперь а `-reptilian`

2024-02-01 13:56 UTC, lzk228 commented
merg

2024-02-01 13:59 UTC, merged