Duffel resprite
space-syndicate/space-station-14 pull request #1737
Opened 2024-01-08 07:38 UTC by SentryPrimies

## Описание PR
С этим МР-ом рюкзаки, сумки да вещмешки подходят друг к другу по стилистике и качеству исполнения.

**Медиа**
![258610154-f43f7a25-535b-402e-af82-181ba2729475](https://github.com/space-syndicate/space-station-14/assets/126711441/37c8525f-e5c5-482c-8439-c31e3cf99715)

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:
- add: Были портированы новые спрайты вещмешков для соответствия сумкам и рюкзакам
- remove: Душа из спрайтов вещмешков

2024-01-08 07:43 UTC, lzk228 commented
скриншот из сс13 :trollface:

2024-01-08 10:49 UTC, SonicHDC commented
Карго и атмос вещмешки не подходят, увы

2024-01-10 11:47 UTC, Morb0 requested changes
`mime` и `holding` же ещё

2024-01-10 11:48 UTC, Morb0 requested changes

2024-01-10 11:48 UTC, Morb0 commented on Resources/Textures/Clothing/Back/Duffels/atmospherics.rsi/meta.json
> +  "copyright": "Modified from tgstation at commit https://github.com/tgstation/tgstation/commit/eeb99fcbde07bcf2e8bce93383744e3e142839df by SentryPrimies",
Ты что-то модифицировал лично в этих спрайтах? Иначе укажи просто `Taken from tgstation at commit https://github.com/tgstation/tgstation/commit/eeb99fcbde07bcf2e8bce93383744e3e142839df`

2024-01-10 11:50 UTC, MureixloI commented
Надо бы реально заменить карго вещмешок и атмос вещмешок

2024-02-10 23:58 UTC, SentryPrimies commented
Лень

2024-02-10 23:58 UTC, closed without merging

2024-02-11 00:20 UTC, lzk228 commented
ахаххаах база