Recorvax things
space-syndicate/space-station-14 pull request #1740
Opened 2024-01-09 09:24 UTC by SonicHDC

## Описание PR

Восстановление и изменение ресурсов, также респрайты и новые стэйты.
Стилизация некоторых вещей и изменения звука для лучшего сочетания со спрайтами шлюзов.
**Медиа**

![image](https://github.com/space-syndicate/space-station-14/assets/100022571/69c1778c-9b0a-4691-9f53-d3dae970df33)
![image](https://github.com/space-syndicate/space-station-14/assets/100022571/995a2246-3b70-43bd-bf3e-868ddd9278f6)

https://github.com/space-syndicate/space-station-14/assets/100022571/01b10441-815f-4ca5-a5d7-6e579be9e9e8

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: SonicDC
- tweak: Возвращён старый звук шлюза!
- tweak: Изменена текстура пустого резервуара!
- fix: Исправлен стиль мусорок!

2024-01-10 00:06 UTC, Morb0 requested changes

2024-01-10 00:06 UTC, Morb0 commented on Resources/Prototypes/Entities/Structures/Storage/Tanks/tanks.yml
> +      fillBaseName: generictank-1-
Почему так?

2024-01-10 00:06 UTC, Morb0 commented on Resources/Textures/Structures/Storage/tanks.rsi/meta.json
> +    {
В мета себя укажи

2024-01-10 00:26 UTC, SonicHDC commented on Resources/Prototypes/Entities/Structures/Storage/Tanks/tanks.yml
> +      fillBaseName: generictank-1-
У оффов там стандартные спрайты, а тут получается криво. Поэтому заменил на пустве кастомные.

2024-01-14 21:06 UTC, Morb0 requested changes

2024-01-14 21:06 UTC, Morb0 commented on Resources/Prototypes/Entities/Structures/Storage/Tanks/tanks.yml
> +        - state: generictank-1-1
```suggestion
        - state: generictank-1-1 # Corvax-Resprite
```

2024-01-14 21:06 UTC, merged