Добавление даты в кпк
space-syndicate/space-station-14 pull request #1744
Opened 2024-01-10 12:47 UTC by user424242420

Добавление даты в кпк
## Описание PR
https://github.com/space-syndicate/space-station-14/pull/1720

Добавление даты в кпк
**Медиа**

![image](https://github.com/space-syndicate/space-station-14/assets/142989209/a65c2a8b-2866-4dfe-a568-14e7b6736bc5)

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: username
- add: Добавление даты в кпк

2024-01-10 12:56 UTC, Syxapik commented
А к оффам с датой не получилось залезть?

2024-01-18 17:03 UTC, ficcialfaint requested changes

2024-01-18 17:03 UTC, ficcialfaint commented on Content.Client/PDA/PdaMenu.xaml.cs
> +                _clipboard.SetText((stationTime.ToString("hh\\:mm\\:ss")) + " " + (DateTime.Now.ToUniversalTime() + DeltaUtc3).ToString("dd\\.MM\\.\\3\\0yy"));
последний метод выглядит как-то страшно, можно же просто:
`.AddYears(1000).ToString("dd.MM.yyyy")`

2024-01-18 17:03 UTC, ficcialfaint commented on Resources/Locale/ru-RU/pda/pda-component.ftl
> +comp-pda-ui-station-time = Продолжительность смены: [color=white]{ $time } { $date }[/color]
Мне всё еще не нравится решение отображать дату рядодм с временем относительно начала смены, как-то нелогично, как по мне

2024-01-18 17:05 UTC, user424242420 commented on Content.Client/PDA/PdaMenu.xaml.cs
> +                _clipboard.SetText((stationTime.ToString("hh\\:mm\\:ss")) + " " + (DateTime.Now.ToUniversalTime() + DeltaUtc3).ToString("dd\\.MM\\.\\3\\0yy"));
Мем в том что время в c# имеет int64 и соответственно просто ему не хватит значений чтобы добавить 1000 лет (overflow)

2024-01-18 17:06 UTC, user424242420 commented on Resources/Locale/ru-RU/pda/pda-component.ftl
> +comp-pda-ui-station-time = Продолжительность смены: [color=white]{ $time } { $date }[/color]
А где?

2024-01-18 17:06 UTC, Syxapik commented on Resources/Locale/ru-RU/pda/pda-component.ftl
> +comp-pda-ui-station-time = Продолжительность смены: [color=white]{ $time } { $date }[/color]
> Мне всё еще не нравится решение отображать дату рядодм с временем относительно начала смены, как-то нелогично, как по мне

ну для тебя это не логично, но в игре мы так бумажки заполняем. пример тебе вот, страница вики по "бумажным работам" 
![image](https://github.com/space-syndicate/space-station-14/assets/127504249/adc5c109-cf5b-4ef1-8dd8-1bb89fbdac6c)

2024-01-18 17:07 UTC, ficcialfaint commented on Content.Client/PDA/PdaMenu.xaml.cs
> +                _clipboard.SetText((stationTime.ToString("hh\\:mm\\:ss")) + " " + (DateTime.Now.ToUniversalTime() + DeltaUtc3).ToString("dd\\.MM\\.\\3\\0yy"));
ehhh, хз, у меня в #1357 вроде все окей было

2024-06-28 21:32 UTC, lzk228 commented
@user424242420 будешь ещё над этим работать?

2024-06-28 23:38 UTC, user424242420 commented
@lzk228 так это уже добавлено, только в main визардов

2024-06-28 23:38 UTC, closed without merging

2024-06-28 23:39 UTC, user424242420 commented
Даты не будет потому что у визардов нет даты, а здесь мне сказали что именно дату не хотят вводить потому что корвакс билд должен быть чистым

2024-06-28 23:41 UTC, user424242420 commented
А я прочитал выше, может сделаю но попозже, по крайней мере не раньше того момент когда меня разбанят на мейне