Респрайт Swapper'а
space-syndicate/space-station-14 pull request #1746
Opened 2024-01-10 16:38 UTC by xKREKSx

## Описание PR

Респрайт не давно добавленого Swapper'а 
**Медиа**

![image](https://github.com/space-syndicate/space-station-14/assets/132602258/ac98393c-99d5-4b44-b272-8364d87f5d28)
![image](https://github.com/space-syndicate/space-station-14/assets/132602258/6712a4a9-cf5d-49df-b29b-a38e89595e5d)

**Проверки**

- [X] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [X] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: KREKS
- tweak: Респрайт свапера

2024-01-10 16:39 UTC, RumiTiger commented
Старое как-то получше выглядит. 3D не очень вписывается в стиль игры

2024-01-10 21:15 UTC, xKREKSx commented
столько лайков в медиа было, могли бы хотяб комент оставить чоль

2024-01-10 21:19 UTC, SonicHDC commented
Выглядит очень странно, форма стала ну очень цилиндрической и плоской.
Может попробуешь сделать ближе к старому по форме, но только в таком стиле?

2024-01-17 16:56 UTC, Morb0 requested changes

2024-01-17 16:56 UTC, Morb0 commented on Resources/Textures/Objects/Devices/swapper.rsi/meta.json
> +    "copyright": "tgstation at https://github.com/tgstation/tgstation/commit/71a1fee2f13730adee5302d34bfa0f0262314d63 , resprite by KREKS",
ужс
```suggestion
    "copyright": "tgstation at https://github.com/tgstation/tgstation/commit/71a1fee2f13730adee5302d34bfa0f0262314d63, resprite by KREKS",
```

2024-01-17 16:57 UTC, merged