Избавляемся от меты, часть вторая
space-syndicate/space-station-14 pull request #1767
Opened 2024-01-15 23:02 UTC by TheShuEd

## Описание PR
Мы берем https://github.com/space-syndicate/space-station-14/pull/1731
и дополняем общую неметовую информацию новыми пометками, которые показываются только для определенных ролей или антагов.
Вот так: 

https://github.com/space-syndicate/space-station-14/assets/96445749/96d367c2-b5bb-4bfd-b228-427f8fe667ed
*(пока согласия от Морти нет, чисто демонстрация игромехана)*

Я уже ознакомился с критикой, которая упала на вышеуказанный ПР. Вот что я думаю.
Я считаю, что убирание метовых названий это полезно для игровой атмосферы и погружения в роль, и так как Оффы отказались от подобных механик, предлагаю нашу с Александром вариацию. Основное изменение - разные роли и антагонисты могут видеть разную дополнительную информацию о предмете. 

По умолчанию гиппоручка будет описана как обычная ручка. Химики голубым цветом увидят пометку "В эту ручку встроен замаскированный гипоспрей", Антагонисты увидят кроваво-красную надпись "Это орудие химического убийства, способное незаметно впрыскивать в цель снотворное или яды, разработанное синдикатом"

Первый плюс: Увеличение погружения и атмосферы рп.
Разные роли в раунде будут давать разные описания, как бы приоткрывая информацию о предмете с разных сторон.

Второй плюс: более легкая интеграция в игру для новичков. Если новому игроку-ученому примнесут на опознание гипоручку, ему не придется лезть на вики или спрашивать в лоок "чо происходит", он сможет по описнаию понять что это: взрывная ручка, гипоручка, или обычная ручка.

Согласие от морти получено: https://discord.com/channels/919301044784226385/924735650119422032/1196584720994148494

Времять работац

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**
:cl:
- add: Добавлено веселье!
- remove: Убрано веселье!
- tweak: Изменено веселье!
- fix: Исправлено веселье!

2024-01-16 13:43 UTC, TheShuEd commented
https://github.com/space-syndicate/space-station-14/assets/96445749/46ca6f8e-f49b-466d-ad69-eed5303e029a

Обновил видос в описании

2024-01-16 20:32 UTC, TheShuEd commented
@ficcialfaint @JerryImMouse заправшиваю ревью по орфографии

2024-01-16 20:33 UTC, TheShuEd commented
ПР готов. Возможны незамеченные косяки, так как много муторной работы. Но я перенес всю страницу контрабанды в IC-пространство
https://station14.ru/wiki/%D0%9A%D0%BE%D0%BD%D1%82%D1%80%D0%B0%D0%B1%D0%B0%D0%BD%D0%B4%D0%B0

2024-01-16 20:45 UTC, TheShuEd commented
https://github.com/space-syndicate/space-station-14/assets/96445749/7a943c43-0a4f-4b6f-9820-d9f8b6feae4e

Немного примеров работы с имплантами.

2024-01-16 20:49 UTC, Syxapik commented
Как же он хорош :fire:

2024-01-16 21:33 UTC, TheShuEd commented
если заходить еще дальше, то будущими ПРами можно попробовать четко определить границу навыков для использования предметов и оружия. Ну, я не предлагаю блочить, но можно переименовать все консоли в абстрактные "Технологическая консоль отдела НИО", и только для ученых давать в описании конкретные описания предназначений.

Таким образом можно будет для новичков четко определить, чем они пользоваться НЕ МОГУТ на текущей роли.

Тоже самое с баночками реагентов, тоже самое с оружием для неумеющих стрелять, и далее, далее, далее. Но это возможно лишнее))

2024-01-17 04:30 UTC, Deserty0 commented
А разве гв не должен по долгу службы в имплантах разбираться

2024-01-17 07:46 UTC, TheShuEd commented
По таблице навыков у него нету исследований и разработки, значит не может

2024-01-17 07:58 UTC, Deserty0 commented
По этой же таблице навыков у него есть навык хирургии (установка и снятие имплантов) и ОЧЕНЬ странно что он не знает какой имплант ставит

2024-01-17 08:09 UTC, TheShuEd commented
Ну, я на текущий момент просто перенес таблицу навыков. Это стартовая точка.

Вполне вероятно, что такое наглядное отображение таблицы навыков в игре приведет к изменениям в будущем, но пока что я не собираюсь менять гв

2024-01-17 11:02 UTC, Kit0vras requested changes

2024-01-17 11:10 UTC, TheShuEd commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/tools/jaws_of_life.ftl
> +ent-SyndicateJawsOfLife = ало-красные челюсти жизни
согласен, они же черно-красные. Саш, че пишешь)))

2024-01-17 11:28 UTC, Kit0vras commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/tools/jaws_of_life.ftl
> +ent-SyndicateJawsOfLife = ало-красные челюсти жизни
бОльшую часть текста я на 220 отревьюил, так что тут не так много правок нужно

2024-01-17 11:31 UTC, TheShuEd commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/tools/jaws_of_life.ftl
> +ent-SyndicateJawsOfLife = ало-красные челюсти жизни
Супер, спасибо.

2024-01-17 11:32 UTC, Kit0vras requested changes

2024-01-17 11:32 UTC, Kit0vras commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/tools/jaws_of_life.ftl
> +    .desc = Набо стильных челюстей жинзи, скомпонованных при помощи магии науки.
```suggestion
    .desc = Набор стильных челюстей жизни, скомпонованных при помощи магии науки.
```

2024-01-17 11:32 UTC, TheShuEd commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/tools/jaws_of_life.ftl
> +ent-SyndicateJawsOfLife = ало-красные челюсти жизни
Но погоди, я же добавил много нового текста подсказок для отделов)))

2024-01-17 11:33 UTC, Kit0vras commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/tools/jaws_of_life.ftl
> +ent-SyndicateJawsOfLife = ало-красные челюсти жизни
аа, блин.. Туда не смотрел.. Оке, гляну тоже

2024-01-17 12:11 UTC, Kit0vras requested changes

2024-01-17 12:11 UTC, Kit0vras commented on Resources/Locale/ru-RU/corvax/hiddenDescription/hiddenDescription.ftl
> +corvax-hidden-desc-EnergyShield-syndicate = [color=#e31735]Настоящий экзотический энергетический щит, в сложенном состоянии может поместиться даже в кармане.[/color]
```suggestion
corvax-hidden-desc-EnergyShield-syndicate = [color=#e31735]Настоящий экзотический энергетический щит. В сложенном состоянии может поместиться даже в кармане.[/color]
```

2024-01-17 12:11 UTC, Kit0vras commented on Resources/Locale/ru-RU/corvax/hiddenDescription/hiddenDescription.ftl
> +corvax-hidden-desc-IllegalImplants-medical = [color=#52B4E9]Сверив серийные номера, вы понимаете что это несертифицированный имплантер.[/color]
```suggestion
corvax-hidden-desc-IllegalImplants-medical = [color=#52B4E9]Сверив серийные номера, вы понимаете, что это несертифицированный имплантер.[/color]
```

2024-01-17 12:11 UTC, Kit0vras commented on Resources/Locale/ru-RU/corvax/hiddenDescription/hiddenDescription.ftl
> +corvax-hidden-desc-LegalImplants-medical = [color=#52B4E9]Сверив серийные номера, вы понимаете что это легальный, сертифицированный имплантер.[/color]
```suggestion
corvax-hidden-desc-LegalImplants-medical = [color=#52B4E9]Сверив серийные номера, вы понимаете, что это легальный, сертифицированный имплантер.[/color]
```

2024-01-17 12:11 UTC, Kit0vras commented on Resources/Locale/ru-RU/corvax/hiddenDescription/hiddenDescription.ftl
> +corvax-hidden-desc-HoloparasiteInjector-syndicate = [color=#e31735]Сложнейшее произведение искусства, основанное на наномашинах, позволяющее пользователю стать носителем опаснейшнего голопаразита.[/c
```suggestion
corvax-hidden-desc-HoloparasiteInjector-syndicate = [color=#e31735]Сложнейшее произведение искусства, основанное на наномашинах, позволяющее пользователю стать носителем опаснейшего голопаразита.[/color]
```

2024-01-17 12:11 UTC, Kit0vras commented on Resources/Locale/ru-RU/corvax/hiddenDescription/hiddenDescription.ftl
> +corvax-hidden-desc-StorageImplanter-research = [color=#D381C9]Это имплантер подкожного хранилища. Позволяет организовать скрытое хранилище внутри тела, с использованием блюспейс-технологии.[/color]
```suggestion
corvax-hidden-desc-StorageImplanter-research = [color=#D381C9]Это имплантер подкожного хранилища. Позволяет организовать скрытое хранилище внутри тела с использованием блюспейс-технологии.[/color]
```

2024-01-17 12:11 UTC, Kit0vras commented on Resources/Locale/ru-RU/corvax/hiddenDescription/hiddenDescription.ftl
> +corvax-hidden-desc-UplinkImplanter-research = [color=#D381C9]Это имплантер черного рынка. Позволяет владельцу пользоваться черным рынком.[/color]
```suggestion
corvax-hidden-desc-UplinkImplanter-research = [color=#D381C9]Это имплантер чёрного рынка. Позволяет владельцу пользоваться чёрным рынком.[/color]
```

2024-01-17 12:11 UTC, Kit0vras commented on Resources/Locale/ru-RU/corvax/hiddenDescription/hiddenDescription.ftl
> +corvax-hidden-desc-UplinkImplanter-syndicate = [color=#e31735]Это имплантер черного рынка. Позволит пользоваться спрятанным аплинком Синдиката, даже если у меня все заберут.[/color]
```suggestion
corvax-hidden-desc-UplinkImplanter-syndicate = [color=#e31735]Это имплантер чёрного рынка. Позволит пользоваться спрятанным аплинком Синдиката, даже если у меня всё заберут.[/color]
```

2024-01-17 12:11 UTC, Kit0vras commented on Resources/Locale/ru-RU/corvax/hiddenDescription/hiddenDescription.ftl
> +corvax-hidden-desc-Emag-research = [color=#D381C9]Интересная модификация стандартной ID карты, работающая как электронная отмычка.[/color]
```suggestion
corvax-hidden-desc-Emag-research = [color=#D381C9]Интересная модификация стандартной ID карты, работающая, как электронная отмычка.[/color]
```
сравнение, потому запятая

2024-01-17 12:11 UTC, Kit0vras commented on Resources/Locale/ru-RU/corvax/hiddenDescription/hiddenDescription.ftl
> +corvax-hidden-desc-PowerSink-research = [color=#D381C9]Крайне неэффективное использование резисторов и ретрансляторов зацикливает ток с огромными электропотерями. Это устройство создано чтобы поглоща
```suggestion
corvax-hidden-desc-PowerSink-research = [color=#D381C9]Крайне неэффективное использование резисторов и ретрансляторов зацикливает ток с огромными электропотерями. Это устройство создано, чтобы поглощать электроэнергию из сети.[/color]
```

2024-01-20 15:24 UTC, TheShuEd commented
Долбанный конфликт, и как тебя решать без веба?

2024-01-20 15:34 UTC, lzk228 commented
не решать из веба😎

2024-01-20 15:41 UTC, TheShuEd commented
Не умею, класс

2024-01-26 01:57 UTC, JerryImMouse commented
> @ficcialfaint @JerryImMouse заправшиваю ревью по орфографии

То была одноразовая акция :pepe_chill:

2024-02-16 00:39 UTC, TheShuEd commented
В связи с тупым мердж конфликтом который мне было лень чинить и новым положением в котором я теперь крайне занят и не могу позволить кодить для сски, закрываю этот ПР.

2024-02-16 00:39 UTC, TheShuEd commented
Может кто доделает другой, но не я.

2024-02-16 05:53 UTC, Deserty0 commented
> Может кто доделает другой, но не я.

Сколько там ещё работы, для справки

2024-03-20 16:43 UTC, TheShuEd commented
охуеть
![image](https://github.com/space-syndicate/space-station-14/assets/96445749/bd25842e-6e34-4bc3-b4e3-3fbe2141147c)

2024-03-20 18:35 UTC, TheShuEd commented
выхуели обратно, ПР завершен. Если Лазик еще раз решит сломать мне все, я вычислю его айпи адрес, приду домой и задушу

2024-03-20 21:57 UTC, merged

2024-03-21 00:14 UTC, lzk228 commented
НЕЕЕЕЕ

2024-05-08 11:01 UTC, Subversionary commented on Resources/Locale/ru-RU/corvax/hidden-description/hiddenDescription.ftl
> +corvax-hidden-desc-DeathAcidifierImplanter-research = [color=#D381C9]Это имплант предсмертного хрипа. Сообщает в неизвестный радиоканал о жизненных показателях носителя.[/color]
corvax-hidden-desc-DeathRattleImplanter-research и corvax-hidden-desc-DeathAcidifierImplanter-research попутаны местами