Fix tts settings
space-syndicate/space-station-14 pull request #1774
Opened 2024-01-17 20:37 UTC by CrazyCat2048

## Фикс неправильной настройки ТТС в окне "Аудио"

Убрал баг из-за которого нельзя было отключить звук ТТС. 
Перевёл изменение громкости при помощи логарифма (такой же принцип, как у эмбиент звуков).

**Изменения**

:cl:
- fix: Исправлена настройка громкости ТТС.

2024-01-17 20:47 UTC, CrazyCat2048 commented
Мэх, щиткод заметил. Пофикшу сначала

2024-01-17 20:54 UTC, CrazyCat2048 commented
Удалил глобал саунд, так как он не нужен, если нет энтити или компонента ТТС на нём

2024-01-17 23:30 UTC, Morb0 requested changes

2024-01-17 23:30 UTC, Morb0 commented on Content.Client/Corvax/TTS/TTSSystem.cs
> +    public const float MinimalVolume = -10f;
Думаю нет смысла им быть public
```suggestion
    public const float WhisperFade = 4f;

    /// <summary>
    /// The volume at which the TTS sound will not be heard.
    /// </summary>
    public const float MinimalVolume = -10f;
```

2024-01-18 01:19 UTC, CrazyCat2048 commented on Content.Client/Corvax/TTS/TTSSystem.cs
> +    public const float MinimalVolume = -10f;
Оке. Изменил

2024-01-18 10:25 UTC, merged