Перевод Upstream #1792
space-syndicate/space-station-14 pull request #1793
Opened 2024-01-21 15:02 UTC by lapatison

## Описание PR

**Медиа**

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:
- add: Добавлены переводы

2024-01-21 19:17 UTC, lzk228 requested changes

2024-01-21 19:17 UTC, lzk228 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/devices/circuitboards/machine/production.ftl
> +ent-ShuttleGunDusterCircuitboard = EXP-2100g "Дастер" (машинная плата)
ну раз дружбу перевёл, переводи ПЫЛЕВИКА

2024-01-21 19:17 UTC, lzk228 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/power/powercells.ftl
> +    .desc = Перезаряжаемая энергетическая ячейка для больших устройств. Это самая дешевая разновидность, которую вы можете найти.
```suggestion
    .desc = Перезаряжаемая энергетическая ячейка для больших устройств. Это самая дешёвая разновидность, которую вы можете найти.
```

2024-01-22 01:44 UTC, lapatison commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/devices/circuitboards/machine/production.ftl
> +ent-ShuttleGunDusterCircuitboard = EXP-2100g "Дастер" (машинная плата)
Нет, одно дело Дружба, другое - Дастер.
Ну и это нормально, [не переводить это слово](https://ru.wikipedia.org/wiki/M42_(%D0%97%D0%A1%D0%A3 )

2024-01-22 08:52 UTC, Kit0vras commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/devices/circuitboards/machine/production.ftl
> +ent-ShuttleGunDusterCircuitboard = EXP-2100g "Дастер" (машинная плата)
Рено Дастер

2024-01-22 10:41 UTC, lzk228 approved these changes

2024-01-22 14:08 UTC, merged