Resprite brick&riveted walls
space-syndicate/space-station-14 pull request #1826
Opened 2024-01-31 05:16 UTC by Ko4ergaPunk

## Описание PR

Перерисовал кирпичную. Изменил клёпанную под перспективу стен корвакса

**Медиа**

![walls](https://github.com/space-syndicate/space-station-14/assets/62609550/bf743223-dd07-4786-8ddf-5053ca3f1197)

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:

2024-01-31 05:38 UTC, SonicHDC commented
Круто, но клёпанная немного странная. Слишком сильно рябит в глазах.

2024-01-31 12:05 UTC, lzk228 commented
мне не нравится клёпанная стена, она слишком яркая в центре

2024-01-31 12:14 UTC, Morb0 requested changes
Согласен, клёпанную стену нужно пересмотреть. Меньше мелкого паттерна и уменьшить яркость в центре.

2024-01-31 20:15 UTC, Ko4ergaPunk commented
Вроде теперь хайп
![newWalls](https://github.com/space-syndicate/space-station-14/assets/62609550/13522f3c-5009-4a5e-866d-a47443e36f65)

2024-02-01 12:26 UTC, Morb0 requested changes

2024-02-01 12:26 UTC, merged