Перевод животных
space-syndicate/space-station-14 pull request #183
Opened 2022-04-04 19:01 UTC by lapatison

## Описание PR 

**Скриншоты**

**Изменения**

:cl: lapatison
- add: различные переводы животных

2022-04-04 20:39 UTC, Morb0 requested changes

2022-04-04 20:39 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/mobs/npcs/animals.ftl
> +    .desc = Вопреки распространенному заблуждению, на самом деле она сделана не из бабла.
Может как то обыгрывать `бочка`? Не обязательно по оригинальному тексту.

2022-04-04 20:39 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/mobs/npcs/carp.ftl
> +ent-MobCarpMagic = мэджикарп
Может `магикарп` это же сокращение от магического карпа.

2022-04-04 20:39 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/mobs/npcs/dummy_npcs.ftl
> +ent-MobHumanPathDummy = Манекен следопыт
Название лучше не переводить, это технический моб только для тестов и разработки.

2022-04-04 20:39 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/mobs/npcs/pets.ftl
> +ent-MobCorgiNarsi = испорченный корги
Наверное лучше `порченный корги`

2022-04-04 20:39 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/mobs/npcs/pets.ftl
> +ent-MobMcGriff = Харламов
What?

2022-04-04 20:39 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/mobs/npcs/pets.ftl
> +ent-MobPaperwork = Буквоед
`Пэйперворк` как то привычнее звучит и ведь до этого он был в карго и как я понимаю только тут его переместили в библиотеку.

2022-04-04 20:39 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/mobs/species/dwarf.ftl
> +    .desc = Жалкая кучка тайн.
В других местах было `секретов` а не тайн.

2022-04-04 20:39 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/mobs/species/human.ftl
> +    .desc =  Манекен-человек, используемый при создании персонажа.
Лишний пробел перед первой буковой описания.

2022-04-04 20:39 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/mobs/species/reptilian.ftl
> +    .desc =  Манекен-рептилоид, используемый при создании персонажа.
Лишний пробел перед первой буковой описания.

2022-04-04 20:39 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/mobs/species/slime.ftl
> +    .desc =  Манекен-слайм, используемый при создании персонажа.
Лишний пробел перед первой буковой описания.

2022-04-04 20:43 UTC, lapatison commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/mobs/npcs/pets.ftl
> +ent-MobMcGriff = Харламов
#предложения

2022-04-04 20:50 UTC, lapatison commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/mobs/npcs/carp.ftl
> +ent-MobCarpMagic = мэджикарп
С другой стороны, `мэджикарп` это такой покемон

2022-04-05 09:37 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/mobs/npcs/carp.ftl
> +ent-MobCarpMagic = мэджикарп
Тогда окей

2022-04-05 09:44 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/mobs/npcs/pets.ftl
> +ent-MobMcGriff = Харламов
Ничего не нашел в канале.

2022-04-05 09:45 UTC, lapatison commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/mobs/npcs/pets.ftl
> +ent-MobMcGriff = Харламов
![Uploading Screenshot_20220405-124459.png…]()

2022-04-05 09:46 UTC, lapatison commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/mobs/npcs/pets.ftl
> +ent-MobMcGriff = Харламов
![Screenshot_20220405-124459](https://user-images.githubusercontent.com/100279397/161727227-8272e004-3dd6-4e83-b5fa-7a0d7b76bd76.png)

2022-04-05 09:51 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/mobs/npcs/pets.ftl
> +ent-MobMcGriff = Харламов
Не стоит. Лучше просто перевести.

2022-04-05 10:19 UTC, Morb0 requested changes

2022-04-05 10:19 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/mobs/npcs/animals.ftl
> +    .desc = Вопреки распространенному заблуждению, бабки не солят их в бочках.
Ну такое... Может:
```suggestion
    .desc = Имеет привлекательные и яркие крылья.
```
Или
```suggestion
    .desc = Вопреки заблуждениям, это не душа вашей бабушки.
```
(отсылается на истинное название)

2022-04-05 10:20 UTC, lapatison commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/mobs/npcs/animals.ftl
> +    .desc = Вопреки распространенному заблуждению, бабки не солят их в бочках.
Второе хорошо.

2022-04-05 11:21 UTC, Morb0 requested changes

2022-04-05 11:21 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/mobs/npcs/animals.ftl
> +    .desc = Была раньше яйца, динозавром!
Не очень понятно. Тут же скорее:
`Была раньше яйца, и это динозавр!`
хотя я все еще не вижу смысла.

2022-04-05 11:34 UTC, lapatison commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/mobs/npcs/animals.ftl
> +    .desc = Была раньше яйца, динозавром!
Что было раньше, курица или яйцо?
Динозавры тоже несли яйца, потому курица и была раньше яйца - только не курицей а динозавром, эволюция, туда-сюда

2022-04-05 11:35 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/mobs/npcs/animals.ftl
> +    .desc = Была раньше яйца, динозавром!
Хмм, ну ладно...

2022-04-05 11:36 UTC, Morb0 approved these changes

2022-04-05 11:36 UTC, merged