Принтер документов. Дубль 2.
space-syndicate/space-station-14 pull request #1832
Opened 2024-02-01 14:27 UTC by TheShuEd

Сколько контрибуторов нужно для того чтобы сделать принтер? Еще на 2 больше, чем раньше.

2024-02-01 14:30 UTC, lzk228 approved these changes
@Morb0 MERG

2024-02-01 14:35 UTC, lzk228 commented on Resources/Prototypes/Corvax/Entities/Objects/Misc/flatpacks.yml
> +  id: BaseFlatpack
```suggestion
  parent: BaseFlatpack
```

2024-02-01 14:42 UTC, Krosus777 commented
> @Morb0 MERG

Рано, обновляю формы.

2024-02-01 22:04 UTC, Krosus777 commented
> > @Morb0 MERG
> 
> Рано, обновляю формы.

Вот теперь можно. =)

2024-02-02 09:24 UTC, Morb0 requested changes

2024-02-02 09:24 UTC, Morb0 commented on Resources/Locale/en-US/lathe/lathe-categories.ftl
> +# Corvax-Printer-End
Можно же вынести в отдельный файл, в папку `corvax`:
`/Locale/en-US/corvax/lathe/lathe-categories.ftl`
и названия категорий должны быть с маленькой, по примеру выше

2024-02-02 09:53 UTC, Krosus777 commented on Resources/Locale/en-US/lathe/lathe-categories.ftl
> +# Corvax-Printer-End
Могут ли бы заглавные в середине названия?
Например:
lathe-category-ordersAndInstructions

2024-02-02 11:16 UTC, Krosus777 commented
@Morb0 Все исправил. Merge?

2024-02-02 13:47 UTC, Morb0 commented on Resources/Locale/en-US/lathe/lathe-categories.ftl
> +# Corvax-Printer-End
используется kebab-case
должно быть `Inquiries-and-appeals `

2024-02-02 14:49 UTC, merged