новая станция
space-syndicate/space-station-14 pull request #1880
Opened 2024-02-19 02:31 UTC by mofkkol1

## Описание PR

**Медиа**

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

2024-02-19 02:33 UTC, mofkkol1 commented
карта для малого и среднего онлайна. Не знаю как это отметить в ПРе

2024-02-19 02:37 UTC, lzk228 requested changes

2024-02-19 02:37 UTC, lzk228 commented on Resources/Prototypes/Corvax/Maps/paper.yml
отсортируй роли

2024-02-19 02:43 UTC, mofkkol1 commented on Resources/Prototypes/Corvax/Maps/paper.yml
когда нибудь. Я спать

2024-02-19 06:30 UTC, mofkkol1 commented on Resources/Prototypes/Corvax/Maps/paper.yml
> отсортируй роли

Рассортировал

2024-02-21 08:36 UTC, mofkkol1 commented on Resources/Prototypes/Corvax/Maps/paper.yml
![привет](https://github.com/space-syndicate/space-station-14/assets/160409429/6f0342ac-1922-46a8-b60b-c8fd6b46069a)
*машет Морти говоря что теперь всё работает*

2024-02-22 23:39 UTC, merged