Переводы еды
space-syndicate/space-station-14 pull request #190
Opened 2022-04-12 19:07 UTC by lapatison

## Описание PR 

**Скриншоты**

**Изменения**

:cl: lapatison
- add: различные переводы еды

2022-04-12 22:51 UTC, Morb0 requested changes

2022-04-12 22:51 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/consumable/food/baked/donkpocket.ftl
> +    .desc = Разогретый выбор опытного предателя.
Почему не `Еда опытного предателя`?
Если первое еще неплохо, но `Разогретый выбор` как то не очень.

2022-04-12 22:51 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/consumable/food/baked/donkpocket.ftl
> +    .desc = Классическая закуска, теперь, наверное, слишком острая.
Многовато запятых, возможно достаточно так?
`Классическая закуска, теперь наверное слишком острая.`

2022-04-12 22:51 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/consumable/food/baked/donkpocket.ftl
> +    .desc = Классическая закуска, теперь с острым вкусом, который активируется при нагревании.
```suggestion
    .desc = Классическая закуска, теперь активируемым при нагревании острым вкусом.
```

2022-04-12 22:51 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/consumable/food/baked/donkpocket.ftl
> +    .desc = Разогретый выбор опытного ботаника.
Опять же, `Разогретый выбор`?

2022-04-12 22:51 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/consumable/food/baked/donkpocket.ftl
> +ent-FoodDonkpocketHonkWarm = теплый хонк-покет
Лишний пробел в конце.

2022-04-12 22:51 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/consumable/food/baked/donut.ftl
> +    .desc =     .desc = Отлично сочетается с закаточной банкой "Восторга хиппи".
Поломано

2022-04-12 22:51 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/consumable/food/baked/donut.ftl
> +    .desc =     .desc = Отлично сочетается с закаточной банкой "Восторга хиппи".
Поломано

2022-04-12 22:51 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/consumable/food/containers/condiments.ftl
> +    .desc = Соль. Предположительно, из космических океанов.
Шутка портится.
```suggestion
    .desc = Соль. Из космических океанов, предположительно.
```

2022-04-12 22:51 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/consumable/food/produce.ftl
> +    .desc = По ступенькам прикатилось, круглое бревно.
Не соответствует оригинальному описанию. Оригинал из песни на английском, я бы предположил, что это могло бы быть тоже из какого-то стиха, но гугл ничего не находит.

2022-04-12 22:51 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/consumable/food/produce.ftl
> +    .desc = Цветок, экстракты которого часто используются в производстве лекарств
Можно точку поставить.

2022-04-12 22:51 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/consumable/food/noodles.ftl
> +    .desc = Лапша, покрытая соленым маслом. Просто и скользко, но вкусно.
Если это сливочная лапша, то правильно будет масло сливочное.
```suggestion
    .desc = Лапша, покрытая сливочным маслом. Просто и скользко, но вкусно.
```

2022-04-12 23:29 UTC, lapatison commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/consumable/food/baked/cake.ftl
> +    .desc = Полый пирог с настоящей тыквой.
![image](https://user-images.githubusercontent.com/100279397/163070769-2751fd0c-fba1-45eb-89bd-703a36044117.png)
название изменил, отверстие переделал

2022-04-12 23:31 UTC, lapatison commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/consumable/food/baked/donkpocket.ftl
> +    .desc = Классическая закуска, теперь, наверное, слишком острая.
Уберу `наверное`, тут либо обособлять, либо без него.

2022-04-12 23:35 UTC, lapatison commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/consumable/food/baked/donkpocket.ftl
> +    .desc = Разогретый выбор опытного предателя.
Хорошее решение, переделал

2022-04-12 23:49 UTC, lapatison commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/consumable/food/produce.ftl
> +    .desc = По ступенькам прикатилось, круглое бревно.
Можно кардинально поменять тему, например
`Такое заметишь и в своём глазу.`

2022-04-13 11:06 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/consumable/food/produce.ftl
> +    .desc = По ступенькам прикатилось, круглое бревно.
Да, давай лучше пословицу.

2022-04-13 11:16 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/consumable/food/baked/cake.ftl
> +    .desc = Полый пирог с настоящей тыквой.
упс, не так `hollow` перевел.

2022-04-13 12:12 UTC, Morb0 requested changes

2022-04-13 12:12 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/consumable/food/ingredients.ftl
> +ent-FoodCheese = сырная голова
Вроде так это употребляется.
```suggestion
ent-FoodCheese = головка сыра
```

2022-04-13 12:12 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/consumable/food/ingredients.ftl
> +ent-FoodCheeseSlice = сырный клин
А это тогда просто:
```suggestion
ent-FoodCheeseSlice = кусок сыра
```

2022-04-13 12:12 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/consumable/food/ingredients.ftl
> +    .desc = Клин восхитительного Чеддера. Сырная голова, от которой его отрезали, не могла уйти далеко.
```suggestion
    .desc = Клин восхитительного Чеддера. Сырная головка, от которой его отрезали, не могла уйти далеко.
```

2022-04-13 12:12 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/consumable/food/meals.ftl
> +ent-FoodMealFries = космический фри
Лишние пробелы в конце.

2022-04-13 12:12 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/consumable/food/meals.ftl
> +ent-FoodMealFriesCarrot = морковка фри
Лишние пробелы в конце.

2022-04-13 12:12 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/consumable/food/meals.ftl
> +    .desc = Картофель фри. Покрытый сыром. Да.
```suggestion
    .desc = Картофель фри. Покрытый сыром. Вкуснятина.
```

2022-04-13 12:12 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/consumable/food/meals.ftl
> +ent-FoodMealEggplantParm = баклажан пармиджана
```suggestion
ent-FoodMealEggplantParm = баклажан пармиджано
```

2022-04-13 12:12 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/consumable/food/meals.ftl
> +ent-FoodMealPigblanket = свинка в тесте
Вики говорит - `Сосиска в тесте (Pigs in a blanket)`

2022-04-13 12:12 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/consumable/food/meals.ftl
> +ent-FoodMealMemoryleek = лук-течка памяти
Может уточнить?
```suggestion
ent-FoodMealMemoryleek = лук-утечка памяти
```

2022-04-14 07:37 UTC, lapatison commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/consumable/food/meals.ftl
> +ent-FoodMealMemoryleek = лук-течка памяти
`беспамятный лук` \ `лук беспамятства`
`утечка луковой памяти`
`утечка луковая` (горе луковое)
`мемори-лук` (уверен, можно не переводить `мемори`)

2022-04-14 11:11 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/consumable/food/meals.ftl
> +ent-FoodMealMemoryleek = лук-течка памяти
Вся шутка в том, что это созвучно с ошибкой программирования - `memory leak`.

2022-04-14 11:25 UTC, lapatison commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/consumable/food/meals.ftl
> +ent-FoodMealMemoryleek = лук-течка памяти
Шутка то понятная, вопрос в адаптации.
Подумал что хочу заменить слова `-течка` из-за неблагозвучности
`лукотечка`?

2022-04-14 12:17 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/consumable/food/meals.ftl
> +ent-FoodMealMemoryleek = лук-течка памяти
Можно и так

2022-04-14 12:17 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/consumable/food/meals.ftl
> +ent-FoodMealPigblanket = свинка в тесте
Так что с этим?

2022-04-14 12:37 UTC, lapatison commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/consumable/food/meals.ftl
> +ent-FoodMealPigblanket = свинка в тесте
Вернул `сосиска...` с последним апдейтом, плюс актуализировал описание.

2022-04-14 12:39 UTC, Morb0 approved these changes

2022-04-14 12:40 UTC, merged