Возврат хайджека
space-syndicate/space-station-14 pull request #1903
Opened 2024-02-28 18:00 UTC by kerisargit

Возврат хайджека

## Описание PR
Возврат цели на угон эвакуационного шаттла. Цель была закомментирована Wizard и перестала выдаваться агентам. Кроме того, она стала и более сложной к выполнению, поскольку емаг эвака теперь сделать нельзя и хайджекеру нужно приложить больше усилий. Шанс выпадения также, как и был - 0.02, ниже, чем у славной смерти. Переводы цели не были удалены.

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.

**Изменения**
- tweak: Цель на хайджек снова выдаётся агентам Синдиката.

2024-02-28 19:00 UTC, lzk228 reviewed
можем в таком случае вместо декоментирования лучше перенести в папку Corvax?

2024-02-28 19:09 UTC, Morb0 requested changes
Вынести в папку Corvax, а так же необходимо вернуть возможность емага шаттла

2024-02-29 10:00 UTC, kerisargit commented
> Вынести в папку Corvax, а так же необходимо вернуть возможность емага шаттла

Хорошо, вынесу, а про емаг это скорее фича. Он угоняется сейчас 3 доступами командования, если обратно вернуть возможность емаг-а, этим могут воспользоваться не хайджекеры. Но в целом можно и емаг вернуть...

2024-02-29 10:45 UTC, lzk228 commented
не хайджекеров будут банить

2024-02-29 10:51 UTC, mhamsterr commented
1984

2024-02-29 16:01 UTC, kerisargit reviewed
Перенесла всё что нужно, вернула ЕМАГ. Протестировала на локалке, цель выдалась успешно, также получилось емагнуть консоль. Гринтекст засчитан.

2024-03-08 09:55 UTC, Morb0 requested changes

2024-03-08 09:55 UTC, Morb0 commented on Resources/Prototypes/Objectives/objectiveGroups.yml
> +    HijackShuttleObjective: 0.02 #Corvax-MRP
```suggestion
    HijackShuttleObjective: 0.02 #Corvax-Hijack
```

2024-03-08 09:55 UTC, Morb0 commented on Content.Server/Shuttles/Systems/EmergencyShuttleSystem.Console.cs
> +    }
```suggestion
    // Corvax-Hijack-Start
    private void OnEmagged(EntityUid uid, EmergencyShuttleConsoleComponent component, ref GotEmaggedEvent args)
    {
        _logger.Add(LogType.EmergencyShuttle, LogImpact.Extreme, $"{ToPrettyString(args.UserUid):player} emagged shuttle console for early launch");
        EarlyLaunch();
    }
    // Corvax-Hijack-End
```

2024-03-08 09:55 UTC, Morb0 commented on Content.Server/Shuttles/Systems/EmergencyShuttleSystem.Console.cs
> +        SubscribeLocalEvent<EmergencyShuttleConsoleComponent, GotEmaggedEvent>(OnEmagged);
```suggestion
        SubscribeLocalEvent<EmergencyShuttleConsoleComponent, GotEmaggedEvent>(OnEmagged); // Corvax-Hijack
```

2024-03-08 10:14 UTC, merged