Species guidebook translation
space-syndicate/space-station-14 pull request #1955
Opened 2024-03-12 20:34 UTC by ficcialfaint

2024-03-12 23:27 UTC, lzk228 requested changes

2024-03-12 23:27 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Mobs/Arachnid.xml
> +  Они задыхаются на 50% быстрее, и их голубая кровь не может метаболизироваться из железа, будучи основанной на меди.
```suggestion
  Они задыхаются на 50% быстрее, и их голубая кровь не может метаболизироваться из железа, вместо этого она основана на меди.
```

2024-03-12 23:27 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Mobs/Arachnid.xml
> +  Их безоружные атаки наносят колющий урон, а не ударный.
blunt - ушибы

2024-03-12 23:27 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Mobs/Arachnid.xml
> +  Арханиды могут создавать шёлк, становлясь при этом более голодными. Они (и только они) могут создавать из наборов шёлека различные предметы, начиная одеждой и щитами, заканчивая целыми стенами.
```suggestion
  Арханиды могут создавать шёлк, ценой своей сытости. Они (и только они) могут создавать из наборов шёлека различные предметы, начиная одеждой и щитами, заканчивая целыми стенами.
```

2024-03-12 23:27 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Mobs/Diona.xml
> +  Будучи растениями, гербициды отравляют их, а робаст харвест наоборот лечит их (но не без риска при чрезмерном использовании!)
у нас реагент робаст харвест не переведён
```suggestion
  Будучи растениями, гербициды отравляют их, а robust harvest наоборот лечит их (но не без риска при чрезмерном использовании!)
```

2024-03-12 23:27 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Mobs/Diona.xml
> +  Они получают [color=#1e90ff]на 30% меньше ударного урона и на 20% меньше режущего урона[/color];
всё тот же blunt

2024-03-12 23:27 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Mobs/Diona.xml
> +  Чрезмерное использование робуст харвестера может привести к выходу дионы из под контроля и её превращению в неподвижной дерево (выбрасывая всю экипировку).
robust harvest

2024-03-12 23:27 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Mobs/Diona.xml
> +  Чрезмерное использование робуст харвестера может привести к выходу дионы из под контроля и её превращению в неподвижной дерево (выбрасывая всю экипировку).
```suggestion
  Чрезмерное использование робуст харвестера может привести к выходу дионы из под контроля и её превращению в неподвижное дерево (сбрасывая всю свою экипировку).
```

2024-03-12 23:27 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Mobs/Diona.xml
> +  Срубливание дерева "восстановит" диону к её прежнему подвижному состоянию.
срубливание это что-то связано со срублями?
```suggestion
  Срубив дерево, вы "восстановите" диону к её прежнему подвижному состоянию.
```

2024-03-12 23:27 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Mobs/Diona.xml
> +  После смерти диона может добровольно уничтожить своё собственное тело, освобождая свои "внутренние органы" - три нимфы -
```suggestion
  После смерти диона может добровольно уничтожить своё собственное тело, освобождая свои "внутренние органы" в виде трёх нимф -
```

2024-03-12 23:27 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Mobs/Diona.xml
> +  включая мозг, взять управление которого может игрок.
это тоже сменил бы
```suggestion
  включая мозг, взять управление которого может игрок.
```

2024-03-12 23:27 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Mobs/Diona.xml
> +  и не будет почти никаких доказательств, кем они были, кроме её собственных слов..
```suggestion
  и не будет почти никаких доказательств, кем они были, кроме её собственных слов.
```

2024-03-12 23:27 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Mobs/Human.xml
> +  У них нет специальныъ механик или примечательных способностей.
```suggestion
  У них нет специальных механик или примечательных способностей.
```

2024-03-12 23:27 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Mobs/Moth.xml
> +  Они могут есть хлопок, ткани и одежду, но практически ничего из еды, считаемой другими "съедобной". Они предпочитают более низкие температуры, чем люди.
```suggestion
  Они могут есть хлопок, текстиль и одежду, но практически ничего из еды, которую другие считают "съедобной". Они предпочитают более низкие температуры, чем люди.
```

2024-03-12 23:27 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Mobs/Reptilian.xml
> +  Их безоружные аттаки когтями наносят режущий урон, а не ударный.
ударный
![image](https://github.com/space-syndicate/space-station-14/assets/124214523/146823bb-ee1b-47c3-bbf2-ec03deeefa20)

2024-03-12 23:27 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Mobs/SlimePerson.xml
> +  Они получают [color=#1e90ff]на 80% меньше клеточного урона, на 40% меньше ударного урона и на 20% меньше ядовитого урона[/color], но [color=#ffa500]на 50% больше низкотемпературного урона, на 20% б
ты сегодня в ударе (ещё одна глупая шутка про ударный урон)

2024-03-13 17:50 UTC, lapatison commented on Resources/ServerInfo/Guidebook/Mobs/Diona.xml
> +  Чрезмерное использование робуст харвестера может привести к выходу дионы из под контроля и её превращению в неподвижной дерево (выбрасывая всю экипировку).
робаст харвеста*

2024-06-01 07:59 UTC, lzk228 commented
suppressed by #dunno

2024-06-01 07:59 UTC, closed without merging