Locale Guidebook for Revolution.
space-syndicate/space-station-14 pull request #1985
Opened 2024-03-22 14:21 UTC by BongoCatGamer

## Описание PR

Я тут решил помочь с переводом гайдбука, так что вот. Держите локализацию для Революции. А ещё этот PR является частью данной задачи https://github.com/space-syndicate/space-station-14/issues/1642.

**Проверки**

- [ ]  PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: Cat
- tweak: Теперь есть локализация на Революцию!

2024-03-22 17:21 UTC, lzk228 requested changes

2024-03-22 17:21 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Antagonist/Revolutionaries.xml
> +  [color=#5e9cff]Главы революционеров[/color] выбираются в начале смены, и им поручено захватить станцию, убив или изгнав весь командный состав. Главам революционеров было выдано: [color=#a4885c]Вспы
```suggestion
  [color=#5e9cff]Главы революционеров[/color] выбираются в начале смены, и им поручено захватить станцию, убив или изгнав весь командный состав. Для помощи в этом, главам революционеров была выдана [color=#a4885c]Вспышка[/color] и пара [color=#a4885c]Солнцезащитных очков[/color].
```

2024-03-22 17:21 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Antagonist/Revolutionaries.xml
> +  Вы можете конвертировать членов экипажа, используя [color=#a4885c]Вспышку[/color] в [color=#ff0000]Боевом режиме[/color] и атакуя кого-нибудь с ее помощью. Для конвертации можно использовать любую
```suggestion
  Вы можете конвертировать членов экипажа, используя [color=#a4885c]Вспышку[/color] в [color=#ff0000]Боевом режиме[/color] и атакуя кого-нибудь с её помощью. Для конвертации можно использовать любую вспышку, но помните, что у них ограниченный заряд.
```

2024-03-22 17:21 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Antagonist/Revolutionaries.xml
> +  Однако такие вещи, как [color=#a4885c]Солнцезащитные очки[/color] и [color=#a4885c]Сварочная маска[/color] обеспечивают защиту от вспышки, и люди, носящие их, не смогут быть конвертированы в револю
```suggestion
  Однако такие вещи, как [color=#a4885c]Солнцезащитные очки[/color] и [color=#a4885c]Сварочная маска[/color] защищают от вспышек, и люди, носящие их, не смогут быть конвертированы в революционеров.
```

2024-03-22 17:21 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Antagonist/Revolutionaries.xml
> +  Несмотря на отсутствие защиты от вспышки, [color=#a4885c]Имплант Щит Разума[/color] предотвратит превращение имплантированного человека в революционера. Assume all of [color=#a4885c]Службы Безопасн
```suggestion
  Несмотря на отсутствие защиты от вспышки, [color=#a4885c]Имплант Щит Разума[/color] предотвратит превращение имплантированного человека в революционера. Предполагается, что все сотрудники [color=#a4885c]Службы Безопасности[/color] и [color=#a4885c]Командование[/color] уже имплантированы.
```

2024-03-22 17:21 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Antagonist/Revolutionaries.xml
> +  [color=#ff0000]Революционеры[/color] это результат конвертации от [color=#5e9cff]Главы Революционеров[/color]. Революционеры являются подчиненными Главы Революционеров и должны следовать их приказа
```suggestion
  [color=#ff0000]Революционеры[/color] это результат конвертации от [color=#5e9cff]Главы Революционеров[/color]. Революционеры являются подчинёнными Главы Революционеров и должны следовать их приказам и ставить их благополучие выше всего остального, потому что, если они умрут, вы проиграете.
```

2024-03-22 17:21 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Antagonist/Revolutionaries.xml
> +  Вы должны уничтожить или изгнать всех следующих командных сотрудников на станции в произвольном порядке.
```suggestion
  Вы должны уничтожить или изгнать всех следующих сотрудников командования, находящихся на станции, в произвольном порядке.
```

2024-03-22 17:21 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Antagonist/Revolutionaries.xml
> +  Помните, ваша цель — захватить станцию, а не разрушить ее, поэтому постарайтесь свести к минимуму ущерб, где это возможно. Viva la revolución!
```suggestion
  Помните, ваша цель — захватить станцию, а не разрушить её, поэтому постарайтесь свести к минимуму ущерб, где это возможно. Viva la revolución!
```

2024-03-22 18:27 UTC, lapatison commented
И не Глава\ы революционеров, а Глава\ы революции

2024-03-23 05:22 UTC, BongoCatGamer commented
Я вас услышал,  и осознал что мой перевод был на троечку. Все правки приняты.

2024-03-23 05:59 UTC, lzk228 approved these changes
мне норм

2024-03-23 09:06 UTC, lapatison commented on Resources/ServerInfo/Guidebook/Antagonist/Revolutionaries.xml
> +  [color=#5e9cff]Главы революционеров[/color] выбираются в начале смены, и им поручено захватить станцию, убив или изгнав весь командный состав. Для помощи в этом, главам революционеров была выдана [
```suggestion
  [color=#5e9cff]Главы революции[/color] выбираются в начале смены, и им поручено захватить станцию, убив или изгнав весь командный состав. Для помощи в этом, главам революции была выдана [color=#a4885c]Вспышка[/color] и пара [color=#a4885c]Солнцезащитных очков[/color].
```

2024-03-23 09:07 UTC, lapatison commented on Resources/ServerInfo/Guidebook/Antagonist/Revolutionaries.xml
> +  Однако такие вещи, как [color=#a4885c]Солнцезащитные очки[/color] и [color=#a4885c]Сварочная маска[/color] защищают от вспышек, и люди, носящие их, не смогут быть конвертированы в революционеров.
```suggestion
  Однако такие вещи, как [color=#a4885c]Солнцезащитные очки[/color] и [color=#a4885c]Сварочная маска[/color] защищают от вспышек, и члены экипажа, носящие их, не смогут быть конвертированы в революционеров.
```

2024-03-23 09:10 UTC, lapatison commented on Resources/ServerInfo/Guidebook/Antagonist/Revolutionaries.xml
> +  [color=#ff0000]Революционеры[/color] это результат конвертации от [color=#5e9cff]Главы Революционеров[/color]. Революционеры являются подчинёнными Главы Революционеров и должны следовать их приказа
```suggestion
  [color=#ff0000]Революционерами[/color] становятся в результате конвертации, осуществляемой [color=#5e9cff]Главами Революции[/color]. Революционеры подчиняются Главам Революции, и должны следовать их приказам и ставить их благополучие выше всего остального, потому что если они умрут, Революционеры проиграют.
```

2024-03-23 09:11 UTC, lapatison commented on Resources/ServerInfo/Guidebook/Antagonist/Revolutionaries.xml
> +  Имейте в виду, что вы не можете конвертировать экипаж, будучи обычным революционером, это может сделать только ваш глава.
```suggestion
  Имейте в виду, что рядовые Революционеры не могут конвертировать экипаж, это могут делать только Главы Революции.
```

2024-03-26 21:32 UTC, merged