Corvax clothes to uniform printer
space-syndicate/space-station-14 pull request #2007
Opened 2024-03-31 20:38 UTC by ArZarLordOfMango

## Описание PR

ПР на добавление парочки одежды(только шляпы но не суть) корвакса в принтер униформы.
Почему? Да красивые они.
Список одежды:

- Фуражка главы службы безопастности
- Капитанская шляпа
- Берет бригмедика
- Полицейская фуражка смотрителя

**Медиа**

![Screenshot 2024-03-31 222815](https://github.com/space-syndicate/space-station-14/assets/96249677/f427ac1b-bba7-4b0b-830e-7e3c3b907d7c)
![Screenshot 2024-03-31 222828](https://github.com/space-syndicate/space-station-14/assets/96249677/44d1a05c-d433-406d-9472-95599642a385)
![Screenshot 2024-03-31 222841](https://github.com/space-syndicate/space-station-14/assets/96249677/2de7fe34-4348-47c4-8d9b-d07510edba04)
![Screenshot 2024-03-31 222853](https://github.com/space-syndicate/space-station-14/assets/96249677/a4f9198e-6d16-47fa-9f7a-e43bfb0ede87)

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:
- add: Добавлены рецепты: Фуражка главы службы безопастности, Капитанская шляпа, Берет бригмедика, Полицейская фуражка смотрителя для принтера униформы

2024-04-26 16:00 UTC, Zna1kin commented
Особая шляпа сделана на заказ (ТОЧНО НЕ НА ПРИНТЕРЕ ДЛЯ 100000 ТАКИХ ЖЕ КАПИТАНОВ СТАНЦИЙ)

2024-04-26 16:01 UTC, Zna1kin commented
Раз она "сделана на заказ" пихать в принтер?

> Особая шляпа сделана на заказ (ТОЧНО НЕ НА ПРИНТЕРЕ ДЛЯ 100000 ТАКИХ ЖЕ КАПИТАНОВ СТАНЦИЙ)

2024-06-01 09:20 UTC, lzk228 requested changes

2024-06-01 09:20 UTC, lzk228 commented on Resources/Prototypes/Entities/Structures/Machines/lathe.yml
тут сгруппируй между комментариями `Corvax-Clothing-Start` & `Corvax-Clothing-End`

2024-06-01 09:20 UTC, lzk228 commented on Resources/Prototypes/Recipes/Lathes/clothing.yml
это вынести в файл `Resources/Prototypes/Corvax/Recipes/Lathes/clothing.yml`

2024-06-03 15:58 UTC, lzk228 approved these changes

2024-06-03 15:59 UTC, merged