Переименовать АлкоМат в БухлоМат
space-syndicate/space-station-14 pull request #2029
Opened 2024-04-08 16:05 UTC by RumiTiger

## Описание PR
Вот код для https://discord.com/channels/919301044784226385/1226588360949239849
Я поменял название "АлкоМат" на "БухлоМат". Я считаю это более красивым переводом "Booze-O-Mat".

**Медиа**
![image](https://github.com/space-syndicate/space-station-14/assets/154005209/d84dbc34-37bb-451f-8ecc-9382ccdfca4e)

**Проверки**
- [X] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [X] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [X] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [X] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: RumiTiger
- tweak: "АлкоМат" переименован в "БухлоМат".

2024-04-09 01:54 UTC, SoulFN commented
Однозначно да

2024-04-09 04:19 UTC, SonicHDC commented
> Однозначно да

Лучше нет 👎🏻

2024-04-09 04:41 UTC, YuiFann commented
> > Однозначно да
> 
> Лучше нет 👎🏻

лучше да 👍

2024-04-09 10:23 UTC, lzk228 requested changes
ты забыл все другие упоминания алкомата
![image](https://github.com/space-syndicate/space-station-14/assets/124214523/db7df8a9-3d19-432c-a0c7-4ba8e4a659f7)

2024-04-09 13:43 UTC, RumiTiger commented
> ты забыл все другие упоминания алкомата ![image](https://private-user-images.githubusercontent.com/124214523/320813636-db7df8a9-3d19-432c-a0c7-4ba8e4a659f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NzAyOTcsIm5iZiI6MTcxMjY2OTk5NywicGF0aCI6Ii8xMjQyMTQ1MjMvMzIwODEzNjM2LWRiN2RmOGE5LTNkMTktNDMyYy1hMGM3LTRiYThlNGE2NTlmNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwOVQxMzM5NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNWUyYTBlZWYzZTkyNDI5MmRjZjg0OGRkODFjMjMxNTk2NTYzZWU5OGI4NzQzNDA2ZDA5N2YxNTFjNGY4NDUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YOfwwBPBfRA5M9urdmkBj_TQAzBQh5_IKo2WqFtpW8c)

Спасибо за подсказку, не заметил. Теперь все нормально

2024-04-18 20:24 UTC, RumiTiger commented
Каков вердикт? Принято или отклонено?

2024-04-19 08:44 UTC, Deserty0 commented
Я ускоряю первую фазу с ннами

2024-05-22 16:58 UTC, NotSoDana commented
Nikogda

2024-06-08 12:54 UTC, Morb0 commented
Серьёзное название больше подходит.

2024-06-08 12:54 UTC, closed without merging