[Resprite] Some bartender clothing
space-syndicate/space-station-14 pull request #2035
Opened 2024-04-11 16:45 UTC by MureixloI

## Описание PR

Изменение некоторых спрайтов одежды бармена/сервисного работника под общий стиль одежды других отделов. 
**Медиа**

![RespriteBartender](https://github.com/space-syndicate/space-station-14/assets/132683811/1d6e123e-9a99-4a50-93a2-276e0661f8ac)

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: MureixloL
- tweak: Изменены спрайты бармена!

2024-04-11 16:48 UTC, MureixloI commented
burh

2024-04-11 18:36 UTC, NotSoDana commented
Нет.. Явно не то. Амбассадор бара недоволен, сносите..

2024-04-11 18:38 UTC, lapatison commented
В целом дизайн нрав, но не думаю, что у барменов должны быть отрисованы жилетки. У барменов есть отдельным айтемом жилеты и бронежилеты, на выбор.

2024-04-11 18:40 UTC, NotSoDana commented
Белоснежность куртки явно преувеличена. У неё и был шарм в том что она желтовата, как реально мех, а теперь.. Теперь не то

2024-04-11 18:52 UTC, MureixloL commented
Ну не говорите, что просто так время потрачено..

2024-04-11 18:58 UTC, NotSoDana commented
> Да и отдельные жилеты так себе

Весь смысл был в том, что белая рубашка и чёрная юбка. Ты мог играться с ними как душе угодно, комбинируя под стиль. Отдельный жилет для того и был сделан. Если его вставить то теряется суть, не говоря уже про.. галстук или бабочку (хз что это), ибо у нас отдельный слот под них.

2024-04-17 05:29 UTC, Morb0 requested changes
Conflict

2024-06-26 19:30 UTC, closed without merging