[Resprite] Some brigmedic clothing
space-syndicate/space-station-14 pull request #2043
Opened 2024-04-14 13:54 UTC by MureixloI

## Описание PR

Изменение спрайтов некоторых элементов одежды роли - бригмедика, под общий стиль других вещей отделов.
**Медиа**

![BrigMedicResprite](https://github.com/space-syndicate/space-station-14/assets/132683811/2c67733c-dfc8-4b8d-85f0-b25cdf2a0736)

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: MureixloL
- tweak: Изменены спрайты бригмедика!

2024-04-14 13:59 UTC, MureixloI commented
Red CrossRed CrossRed CrossRed CrossRed CrossRed CrossRed CrossRed CrossRed CrossRed CrossRed CrossRed CrossRed CrossRed CrossRed CrossRed CrossRed CrossRed CrossRed CrossRed CrossRed CrossRed CrossRed CrossRed CrossRed CrossRed CrossRed CrossRed CrossRed CrossRed CrossRed CrossRed CrossRed CrossRed CrossRed CrossvRed CrossRed CrossRed Cross

2024-04-14 16:18 UTC, Hiucko commented
Опять любители нарушать женевскую конвенцию 🤓

2024-04-17 05:26 UTC, Morb0 requested changes
Geneva Conventions violation is forbidden

2024-04-17 07:16 UTC, MureixloL commented
> Нарушение Женевских конвенций запрещено

А иконка берета????

2024-04-17 07:22 UTC, MureixloL commented
Вернусь домой, уберу всё

2024-04-17 07:47 UTC, MureixloI commented
Готово

> Нарушение Женевских конвенций запрещено

Готово

2024-04-23 03:54 UTC, merged