[Locale] Ё
space-syndicate/space-station-14 pull request #2051
Opened 2024-04-19 16:18 UTC by mhamsterr

Я не шутил.

В канал 🌐│перевод в дс периодически приходят люди, которые указывают на небольшие недочёты, связанные с буквой ё в переводах, точнее тем, что некоторые слова, которые как-ты должны быть написаны через ё, на самом деле написаны через е. В этом пр __потенциально__ пофикшены __почти все__ такие "ляпы".

# Рецепт:
Делалось всё с помощью https://github.com/e2yo/eyo:
```bash
npm install eyo -g
find Resources/Locale/ru-RU -name "*.ftl" >> eyo.txt
eyo -i $(cat eyo.txt)
rm eyo.txt
```
__Способ не идеален.__ Эта утилита, например, пропускает слова, которые возможно написаны правильно (например слова "все" и "всё", "отсек" и "отсёк", "бедрá" и "бёдра", ну вы поняли идею).
**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

# Почему?
1. Некоторые игроки сами указывают на недочёты перевода. Устраивало бы всё всех - не было бы этого ПР'а
2. Использование е и ё с текущим количеством переведённых строк потеряло какую-либо логику (не виню никого, переводы могли делаться разными людьми с разными принципами, клавиатурами и мыслями в разное время (банально вечером мог написать е из-за усталости, а утром продолжить писать ё; или например был один перевод от одного человека, а через время пришёл другой, сделал свою правку и получилась мешанина и т.д. и т.п.), например я увидел в одной строчке слово "шахтёр", а через несколько слов после него шло слово "предпочел" (орфография сохранена). Почему слова были написаны именно в таком порядке? Почему не было е в обоих словах, или ё в обоих словах?
3. Я платил за весь алфавит, так почему я должен использовать только 32/33 букв?
4. Мне было очень смешно с того что я за 2 команды насрал на 290 изменённых файлов. 🤓
5. За 3 часа до этого ПР'а я нашёл https://github.com/e2yo/eyo и я решил его испытать. Ну чего же добру (выводу из команды) пропадать то?

### Дополнения приветствуются
Улыбок тому, кто решит это всё проверить.

2024-04-19 16:19 UTC, mhamsterr commented
Комедия.

2024-04-19 16:26 UTC, Hemomancer commented
> Комедия.

Все люди с ФИО через ё, тебе благодарны.

2024-04-19 16:36 UTC, YuiFann commented
вот кому то делать нехуй

2024-04-19 16:36 UTC, Deserty0 commented
Герой, лазик определённо обрадуется

2024-04-19 16:43 UTC, Hiucko commented on Resources/Locale/ru-RU/paper/book-authorbooks.ftl
> +    Дойдя до конца лабиринта, их ожидало сюрприз. Лабиринт привёл их в скрытую комнату, где ждали их Слизни. Слизни объяснили, что они наблюдали за игрой и были впечатлёны командной работой Чаклза и
впечатлены*

2024-04-19 17:08 UTC, Hiucko commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/furniture/tables/tables.ftl
> +ent-TableReinforcedGlass = стол из бронестёкла
бронестекла*

2024-04-19 17:17 UTC, lzk228 requested changes

2024-04-19 17:17 UTC, lzk228 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/furniture/tables/tables.ftl
> +ent-TableReinforcedGlass = стол из бронестёкла
```suggestion
ent-TableReinforcedGlass = стол из бронестекла
```

2024-04-20 09:57 UTC, lzk228 requested changes

2024-04-20 09:57 UTC, lzk228 commented on Resources/Locale/ru-RU/paper/book-authorbooks.ftl
> +    Чаклз и Снагглз были заинтригованы и решили присоединиться к увлечению. Их парой были Ящеричьи братья и сёстры, Лиззи и Ленни. Лиззи была своенравной, а Ленни был более спокойным и беззаботным.
```suggestion
    Чаклз и Снагглз были заинтригованы и решили присоединиться к увлечению. Их парой были Ящеричьи сестра и брат Лиззи и Ленни. Лиззи была своенравной, а Ленни был более спокойным и беззаботным.
```
siblings

2024-04-20 09:57 UTC, lzk228 commented on Resources/Locale/ru-RU/paper/book-authorbooks.ftl
> +    Но потом облака раздвигаются, и солнце прорывается вперёд, заливая меня светом и жизнью. Я впитываю его, наслаждаюсь его сиянием и чувствую себя живым. Это напоминание о том, зачем я здесь, о чём
```suggestion
    Но потом облака раздвигаются, и солнце прорывается вперёд, заливая меня светом и жизнью. Я впитываю его, наслаждаюсь его сиянием и чувствую себя живым. Это напоминание о том, зачем я здесь, к чему я стремлюсь.
```

2024-04-20 09:57 UTC, lzk228 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/uniforms/jumpskirts.ftl
> +    .desc = На нём есть плюс, это хорошо, верно?
юбка
```suggestion
    .desc = На ней есть плюс, это хорошо, верно?
```

2024-04-20 10:07 UTC, lzk228 approved these changes

2024-04-23 03:56 UTC, merged