Rework races guidebook
space-syndicate/space-station-14 pull request #2060
Opened 2024-04-24 17:30 UTC by fqqf

## Описание PR
Адаптация руководств по расам на русский язык. Добавлен раздел для расы вульпканинов. Некоторые описания рас переписаны в соответствии с лором и добавлено описание расовых особенностей для каждой расы.

**Медиа**

https://github.com/space-syndicate/space-station-14/assets/77983090/0ed36fd0-e6d3-4728-9268-96eddbdb2f34

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: Miracula
- tweak: Руководство по расам адаптировано под лор и переведено на русский язык, добавлены новые разделы.

2024-04-24 17:56 UTC, lzk228 commented
Не одобряю
За разными добавлениями, добро пожаловать к https://github.com/space-wizards/space-station-14
у нас перевод, добавлений нету

2024-04-24 18:08 UTC, fqqf commented
> Не одобряю За разными добавлениями, добро пожаловать к https://github.com/space-wizards/space-station-14 у нас перевод, добавлений нету

У оффов нет расы вульп, тут без добавлений не выйдет. Это не просто перевод, а скорее реворк, так как в изначальном руководстве вообще почти ничего не сказано о расовых особенностях. Плюс у корвакса свой лор, и сделать ПР об этом лоре у оффов, ну, банально не выйдет, понятно почему

2024-04-24 18:13 UTC, lzk228 commented
я говорю не только о вульпах
все реворки и прочее сюда https://github.com/space-wizards/space-station-14
у нас только перевод, естественно с добавлением гайда о вульпах

2024-04-24 18:57 UTC, fqqf commented
Этот пулл реквест просто нацелен на то, чтобы рукводство сделать более лорным по лору корвакса. Типо, в чем смысл лора, если его даже в описание расы нельзя добавить.

В любом случае, напишите о своем решении, как рассмотрите. Можно ли вернуть полную версию руководства, или все же разрешаете оставить только часть про вульп

2024-04-25 06:59 UTC, themanyfaceddemon commented
> Этот пулл реквест просто нацелен на то, чтобы рукводство сделать более лорным по лору корвакса. Типо, в чем смысл лора, если его даже в описание расы нельзя добавить.
> 
> В любом случае, напишите о своем решении, как рассмотрите. Можно ли вернуть полную версию руководства, или все же разрешаете оставить только часть про вульп

Для того чтобы был отдел лороведов и тонна никому не нужного текста

2024-04-27 15:07 UTC, Morb0 requested changes

2024-04-27 15:07 UTC, Morb0 commented on Resources/ServerInfo/Guidebook/Mobs/Vulpkanin.xml
> +  - Видят на клетку дальше.
```suggestion
  - Имеют обзор на один тайл дальше.
```

2024-04-27 15:46 UTC, fqqf commented on Resources/ServerInfo/Guidebook/Mobs/Vulpkanin.xml
> +  - Видят на клетку дальше.
Исправлено в след коммите

2024-04-27 15:56 UTC, lapatison commented on Resources/ServerInfo/Guidebook/Mobs/SlimePerson.xml
> +  - Единственная раса, которая не гниёт.
Гниёт

2024-04-27 15:58 UTC, lapatison commented on Resources/ServerInfo/Guidebook/Mobs/Diona.xml
> +  - Поскольку их ноги всегда голые, мышеловки наносят дионам урон в [color=red]0.66[/color] ушибов. Если они наступят на осколки стекла, то получат урон в [color=red]5[/color] уколов, а если бросить,
Это можно удалить. Все расы получают урон будучи босиком. Не думаю, что нужно весь урон расписывать

2024-04-27 15:58 UTC, lapatison commented on Resources/ServerInfo/Guidebook/Mobs/Diona.xml
> +  - Вместо крови у них вода, при кровотечении истекают ей же.
Сироп же

2024-04-27 16:07 UTC, fqqf commented on Resources/ServerInfo/Guidebook/Mobs/SlimePerson.xml
> +  - Единственная раса, которая не гниёт.
Спасибо, исправила

2024-04-27 16:08 UTC, fqqf commented on Resources/ServerInfo/Guidebook/Mobs/Diona.xml
> +  - Поскольку их ноги всегда голые, мышеловки наносят дионам урон в [color=red]0.66[/color] ушибов. Если они наступят на осколки стекла, то получат урон в [color=red]5[/color] уколов, а если бросить,
Да, удалила

2024-04-27 16:08 UTC, fqqf commented on Resources/ServerInfo/Guidebook/Mobs/Diona.xml
> +  - Вместо крови у них вода, при кровотечении истекают ей же.
Заменила на древесный сок

2024-04-28 17:12 UTC, fqqf commented
Собственно, вроде все)

2024-04-28 17:30 UTC, lzk228 requested changes

2024-04-28 17:30 UTC, lzk228 commented on Resources/Prototypes/Guidebook/species.yml
> +    - Vulpkanin
```suggestion
    - Vulpkanin # Corvax
```

2024-04-28 17:30 UTC, lzk228 commented on Resources/Prototypes/Guidebook/species.yml
> +  text: "/ServerInfo/Guidebook/Mobs/Vulpkanin.xml"
этот отдельный прототип можно вывести в папку корвакс
`Resources/Prototypes/Corvax/Guidebook/species.yml

2024-04-28 17:30 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Mobs/Vulpkanin.xml
на счёт вынесения этого файла в папку корвакс спорно, пусьт морти уточнит

2024-05-10 23:14 UTC, merged