Добавление недостающих данных в выгрузку на wiki
space-syndicate/space-station-14 pull request #2064
Opened 2024-04-25 23:50 UTC by KrasnoshchekovPavel

## Описание PR

На wiki периодически выгружаются данные для составления статей по химии, готовке и т.д.
В это ПР к этим данным была добавлена следующая информация:
1) Мин, макс температура реакции 
2) Описание эффектов реагентов из гайдбука
3) Название устройства для реакции (блендер, центрифуга,, электролизер и другое)
4) Цвет текста для отображения поверх цвета реагента (ранее рассчитывалось на стороне вики)

**Важно**, что ПР нельзя мержить пока не будут подтверждены соответствующие статьи на вики (иначе текущие статьи полетят). Они готовы и ждут одобрения. Это Химия, Состав_продуктов, Готовка, Напитки (раздел "обсуждение"). Проверял, сервер запускается, генерирует файлы, все как нужно, ошибок нет. Ни в каких других системах кроме выгрузки на вики этот блок кода насколько мне известно не участвует
**Медиа**

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

no cl

2024-04-27 14:05 UTC, Morb0 requested changes

2024-04-27 14:05 UTC, Morb0 commented on Content.Server/GuideGenerator/ReactionJsonGenerator.cs
Желательно сделать этот класс `partial` и создать второй `partial class ReactionJsonGenerator` в `Corvax/GuideGenerator/ReactionJsonGenerator.cs` и перенести `DefaultMixingCategory` туда, а добавленный код вынести в метод нового класса и вызывать тут. 

Либо... выделить комментариями:
```csharp
// Corvax-Wiki-Start
...
// Corvax-Wiki-End
```

2024-04-27 14:05 UTC, Morb0 commented on Content.Server/GuideGenerator/ReagentEntry.cs
Все что можно желательно выделить в папку `Corvax`

2024-05-01 15:03 UTC, KrasnoshchekovPavel commented
Можно мержить после ревью, статьи на вики согласованы

2024-05-03 08:06 UTC, merged