[Resprite] Some glasses & huds
space-syndicate/space-station-14 pull request #2095
Opened 2024-05-02 19:44 UTC by MureixloI

## Описание PR

Изменение спрайтов очков & визоров, а также изменение спрайтов некоторых состояний для meson и termal очков.
**Медиа**

![glasses](https://github.com/space-syndicate/space-station-14/assets/132683811/e670dc77-daae-43d1-bb54-deea52aeaa04)

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: MureixloL
- tweak: Изменены спрайты!

2024-05-02 19:46 UTC, Morb0 requested changes
Resources/Textures/Clothing/Head/Hats/beret_hos.rsi: PNG not defined in metadata: equipped-HEAD.png
Resources/Textures/Corvax/Clothing/Eyes/Glasses/kim.rsi: PNG not defined in metadata: equipped-EYES-hamster.png
Resources/Textures/Corvax/Clothing/Eyes/Glasses/salesman.rsi: PNG not defined in metadata: equipped-EYES-hamster.png

2024-05-02 20:02 UTC, MureixloI commented
Исправлю

> Resources/Textures/Clothing/Head/Hats/beret_hos.rsi: PNG not defined in metadata: equipped-HEAD.png Resources/Textures/Corvax/Clothing/Eyes/Glasses/kim.rsi: PNG not defined in metadata: equipped-EYES-hamster.png Resources/Textures/Corvax/Clothing/Eyes/Glasses/salesman.rsi: PNG not defined in metadata: equipped-EYES-hamster.png

исправлю с беретом главы СБ в следующем ПРе, в этом не смогу

2024-05-02 21:53 UTC, KIBORG04 commented on Resources/Textures/Clothing/Eyes/Glasses/glasses.rsi/meta.json
> +  "copyright": "Taken from tgstation at commit https://github.com/tgstation/tgstation/commit/5a73e8f825ff279e82949b9329783a9e3070e2da, tweak by @linkblyat, Resprited by MureixloL",
Мне кажется, copyright должен полностью измениться, а не остаться тем же, но с пометкой тебя

2024-05-03 10:06 UTC, SonicHDC commented
Очки синдиката похожи на обычные. Нужно их заспрайтить под форму начальную

2024-05-03 14:33 UTC, Morb0 requested changes
Согласен, если от изначального спрайта не осталось ничего кроме идем то `copyright` нужно полностью заменить на свой.

2024-05-05 09:04 UTC, merged