Перевод одежды
space-syndicate/space-station-14 pull request #210
Opened 2022-04-28 20:36 UTC by lapatison

## Описание PR 

**Скриншоты**

**Изменения**

:cl: lapatison
- add: различные переводы одежды

2022-04-30 20:43 UTC, Morb0 requested changes

2022-04-30 20:43 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/outerclothing/misc.ftl
> +    .desc = Черная и строгая толстовка капеллана.
Вроде решили называть везде `священник`

2022-04-30 20:43 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/neck/cloaks.ftl
> +    .desc = Помпезный и удобный синий плащ с красивой золотой окантовкой, хотя и не такой ценный, как другие ваши вещи, но, несомненно, красивый.
Много запятых

2022-04-30 20:43 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/neck/cloaks.ftl
> +    .desc =Белый плащ с фиолетовыми полосами, демонстрирующий ваш статус законодателя передовых технологий.
Пробел в начале

2022-04-30 20:43 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/neck/cloaks.ftl
> +    .desc = Вышитый из золота логотип компании НаноТрейзен говорит сам за себя.
NanoTrasen не переводим. (стоит поискать в принятых переводах тоже)

2022-04-30 20:43 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/neck/cloaks.ftl
> +    .desc = Его носят самые опытные шахтеры, те, кто сдвинул горы и засыпал долины.
Лучше или `сдвигал` и `засыпал` или `сдвинул` и `засыпал`

2022-04-30 20:43 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/neck/ties.ftl
> +ent-ClothingNeckHorrific = ужасный галстук
```suggestion
ent-ClothingNeckHorrific = кошмарный галстук
```

2022-04-30 20:43 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/outerclothing/coats.ftl
> +    .desc = Прочный брезентовый плащ, разработка компании TX Fabrication Corp. Плащ устойчив к внешнему воздействию - идеально подходит для вашей следующей автодефенестрации.!
лишняя точка в конце

2022-05-01 02:56 UTC, lapatison commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/eyes/hud.ftl
> +ent-ClothingEyesHudDiagnostic = диагностический окуляр
Они все один имеют
https://github.com/space-syndicate/space-station-14/tree/f2c4d8fb527f5043319293d22ef8b9954525a14d/Resources/Textures/Clothing/Eyes/Hud

2022-05-01 04:27 UTC, lapatison commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/eyes/glasses.ftl
> +    .desc = Зрелищная пара очков с линзами по рецепту.
Как тебе `неприглядная`, `невзрачная`?

2022-05-01 04:56 UTC, lapatison commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/neck/cloaks.ftl
> +    .desc = Его носят самые опытные шахтеры, те, кто сдвинул горы и засыпал долины.
Переиграл на 'способные сдвинуть горы и засыпать долины', как такое?

2022-05-01 09:30 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/neck/cloaks.ftl
> +    .desc = Его носят самые опытные шахтеры, те, кто сдвинул горы и засыпал долины.
Норм

2022-05-01 09:52 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/eyes/glasses.ftl
> +    .desc = Зрелищная пара очков с линзами по рецепту.
`неприглядные` норм

2022-05-01 09:55 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/eyes/hud.ftl
> +ent-ClothingEyesHudDiagnostic = диагностический окуляр
`окуляр` звучит как старомодно для такой технологичной вещи. Можно `визор`.

2022-05-01 10:26 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/eyes/glasses.ftl
> +    .desc = Зрелищная пара очков с линзами по рецепту.
Имел в виду, что вариант с `пара неприглядных очков`.

2022-05-01 10:27 UTC, Morb0 requested changes

2022-05-01 10:27 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/neck/cloaks.ftl
> +    .desc = Помпезный и удобный синий плащ с красивой золотой окантовкой, хотя и не самый ценный ваш предет вашего снарежения, но очень красивый.
```suggestion
    .desc = Помпезный и удобный синий плащ с красивой золотой окантовкой, хотя и не самый ценный предмет вашего снаряжения, но очень красивый.
```

2022-05-01 11:55 UTC, merged