Перевод статей гайдбука по инженерии + фикс перевода панели эмоций
space-syndicate/space-station-14 pull request #2102
Opened 2024-05-05 21:40 UTC by KrasnoshchekovPavel

## Описание PR

**Медиа**

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

2024-05-05 22:13 UTC, lzk228 commented
а разве они не были переведены?

2024-05-05 23:24 UTC, lzk228 requested changes
остальное позже ревьювну

2024-05-05 23:24 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Engineering/Singularity.xml
> +  Когда молния ударяет по катушкам Теслы, они изнашиваются; обязательно [color=#a4885c]время от времени приваривайте их[/color], чтобы продолжать генерировать энергию.
```suggestion
  По мере того как шаровая молния поражает катушки Теслы, они будут разрушаться от износа; чтобы они продолжали генерировать энергию, время от времени подваривайте их [color=#a4885c]сваркой[/color].
```

2024-05-05 23:24 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Engineering/Singularity.xml
> +  [color=red]Не[/color] включайте УЧ, если все остальные подсистемы не работают должным образом и нет достаточной мощности для запуска двигателя.
```suggestion
  [color=red]Не включайте[/color] УЧ, если все остальные подсистемы не работают должным образом и нет достаточной мощности для запуска двигателя.
```

2024-05-05 23:24 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Engineering/Singularity.xml
> +  Включите питание с помощью консоли управления УЧ. Установите мощность на соответствующий уровень. В настоящее время единственным подходящим уровнем является [color=#f0684d]1[/color] все, что выше э
```suggestion
  Включите питание с помощью консоли управления УЧ. Установите мощность на соответствующий уровень. В настоящее время единственным подходящим уровнем является [color=#f0684d]1[/color]; всё, что выше этого, приведёт к тому, что сингулярность станет слишком сильной, чтобы с ней можно было справиться.
```

2024-05-05 23:24 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Engineering/Singularity.xml
> +  В настоящее время выходная мощность не влияет на теслу, за исключением придания тесле дополнительных размеров вокруг нее.
```suggestion
  В настоящее время выходная мощность не влияет на Теслу, кроме того, что она даёт дополнительные шары вокруг себя.
```

2024-05-05 23:24 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Engineering/Singularity.xml
> +  Теперь УЧ будет получать энергию от электросети и начнет обстреливать генераторы частицами.
обстреливать звучит более связанное с оружием
```suggestion
  Теперь УЧ будет получать энергию от электросети и начнёт стрелять частицами в генераторы.
```

2024-05-05 23:24 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Engineering/Singularity.xml
> +  Сингулярность или тесла вскоре появится в месте расположения генератора сингулярности / теслы.
```suggestion
  Сингулярность или шаровая молния вскоре появится в месте расположения генератора сингулярности / теслы.
```

2024-05-05 23:24 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Engineering/Singularity.xml
> +  Если в сингулярность не попадает ни одна частица, сингулярность начнет медленно распадаться, пока не исчезнет.
```suggestion
  Если в сингулярность не попадает ни одна частица, сингулярность начнёт медленно распадаться, пока не исчезнет.
```

2024-05-05 23:24 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Engineering/Singularity.xml
> +  Сингулярность излучает вокруг себя большое количество радиации, поэтому всегда держитесь от нее на расстоянии. Подумайте о том, чтобы заранее приобрести [color=yellow]радиозащитный костюм[/color].
```suggestion
  Сингулярность излучает вокруг себя большое количество радиации, поэтому всегда держитесь от неё на расстоянии. Подумайте о том, чтобы заранее получить [color=yellow]радиозащитный костюм[/color]. Если у вас возникли проблемы со здоровьем, обратитесь к врачу.
```

2024-05-05 23:24 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Engineering/Singularity.xml
> +  Сингулярность может перемещаться, но защитное поле будет ее отталкивать.
```suggestion
  Сингулярность может перемещаться, но защитное поле будет её отталкивать.
```

2024-05-05 23:24 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Engineering/Singularity.xml
> +  Тесла создает вокруг себя большие разряды молний, поэтому, прежде чем приближаться к ней, обязательно наденьте защитные очки. Если это не так, и она поразит вас, молитесь, чтобы тесла не оглушила в
```suggestion
  Тесла создаёт вокруг себя большие разряды молний, поэтому, прежде чем приближаться к ней, обязательно наденьте изоли. Если вы не надели их и она поразила вас, молитесь, чтобы молния не оглушила вас и в конечном итоге не отправила в критическое состояние.
```

2024-05-05 23:24 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Engineering/Singularity.xml
> +  Если сингулярность или тесла вырвутся из своего сдерживающего поля, они будут притягивать, а затем поглощать все на своем пути, увеличиваясь в размерах, или начнут уничтожать все машины на своем пу
```suggestion
  Если сингулярность или тесла вырвутся из своего сдерживающего поля, они будут притягивать, а затем поглощать всё на своем пути, увеличиваясь в размерах, или начнут уничтожать все машины на своем пути и поражать током весь экипаж.
```

2024-05-05 23:24 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Engineering/Singularity.xml
> +  Однако удачи вам с теслой. Она просто слишком мощная, чтобы ее можно было сдержать после прорыва.
```suggestion
  Однако если учёные успели исследовать [color=#D381C9]Портативные замедлители частиц[/color] или если отдел снабжения сможет заказать их вовремя, вы, возможно, сможете помешать сингулярности поглотить всю станцию.
  Однако удачи вам с теслой. Она просто слишком мощная, чтобы ее можно было сдержать после прорыва.
```

2024-05-06 10:10 UTC, KrasnoshchekovPavel commented
> а разве они не были переведены?

Не были. Только статья про сингу/теслу была переведена, но она устарела. Поэтому заного подтянул. Остальное - тэг, ритэги, консоль криминальных записей были на английском

2024-05-07 08:20 UTC, lzk228 requested changes
Это пиздец.

2024-05-07 08:20 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Engineering/TEG.xml
> +  Проще говоря, система охлаждения состоит из 3 основных частей: входного разъема, нескольких насосов и системы теплообменников, размещенных в открытом пространстве. Ее можно настроить следующим обра
```suggestion
  Проще говоря, охлаждающий массив состоит из трёх основных частей: Входной порт, несколько насосов и массив теплообменников в космосе. Его можно расположить следующим образом:
```

2024-05-07 08:20 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Engineering/TEG.xml
> +  - Насосы ввода/вывода: используются для обеспечения постоянного прохождения газа как через циркуляционный насос, так и через теплообменник. По мере того как газ охлаждается и нагревается (и проходи
```suggestion
  - Насосы ввода/вывода: используются для обеспечения постоянного прохождения газа через циркуляционный насос и через теплообменный массив. По мере того как газ охлаждается и нагревается (и проходит через теплообменник), необходимо создавать давление, чтобы он продолжал поступать.
```

2024-05-07 08:20 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Engineering/TEG.xml
> +  ## Цикл замораживания
```suggestion
  ## Морозильный контур
```

2024-05-07 08:20 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Engineering/TEG.xml
> +  Просто следуйте инструкциям для системы охлаждения, но вместо теплообменников используйте морозильную камеру. Как же так:
```suggestion
  Просто следуйте инструкциям для охлаждающего массива, но вместо теплообменников используйте охладители. Вот так:
```

2024-05-07 08:20 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Security/CriminalRecords.xml
> +  Консоль криминальных записей доступна в отделе безопасности каждой станции, она служит для отслеживания и управления криминальной историей и статусом любого лица, включенного в манифест экипажа.
```suggestion
  Консоль криминальных записей доступна в отделе безопасности каждой станции, она служит для отслеживания и управления криминальной историей и статусом любого лица, включённого в манифест экипажа.
```

2024-05-07 08:20 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Security/CriminalRecords.xml
> +  Любой желающий может открыть пользовательский интерфейс консоли, но только те, у кого есть доступ к системе безопасности, могут что-либо изменять.
```suggestion
  Любой желающий может открыть интерфейс консоли, но только те, у кого есть доступ службы безопасности, могут что-либо изменять.
```

2024-05-07 08:20 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Security/CriminalRecords.xml
> +  Пользовательский интерфейс состоит из следующих элементов:
```suggestion
  Интерфейс состоит из следующих элементов:
```

2024-05-07 08:20 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Security/CriminalRecords.xml
> +  - Как только кто-то будет арестован, обновить его статус на консоли, чтобы все знали, что его больше не нужно арестовывать.
```suggestion
  - Как только кто-то будет арестован, обновить его статус на консоли, чтобы все знали, что его больше не нужно ловить.
```

2024-05-07 08:20 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Security/CriminalRecords.xml
> +  - Открыть окно "История преступлений", чтобы проверить или изменить ее.
```suggestion
  - Открыть окно "История преступлений", чтобы проверить или изменить её.
```

2024-05-07 08:20 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Security/CriminalRecords.xml
> +  - Выберите строку нежелательной истории и нажмите "Удалить", чтобы удалить ее.
```suggestion
  - Выберите строку нежелательной истории и нажмите "Удалить", чтобы удалить её.
```

2024-05-07 08:20 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Survival.xml
> +
```suggestion
## Определение вашего положения
Ваш КПК содержит название станции и список членов экипажа, работающих в данный момент на вашей станции, напоминание вашего имени в случае необходимости, а также назначенное задание на смену, что позволит вам быстро оценить ситуацию.
```

2024-05-07 08:20 UTC, lzk228 requested changes
Это пиздец.

2024-05-07 08:20 UTC, lzk228 commented
@Morb0 если автор не примет мои правки, то просто закрой ПР.
Он просто провёл всё через переводчик, даже не посмотрев, что делает.
Тут буквально потраченный перевод сс14.

2024-05-07 08:54 UTC, NotSoDana commented
Птздец, машинный перевод, зачем а главное нахуя? Походу пора взяться за эту хуйню..

2024-05-07 09:42 UTC, YuiFann commented
жду первоапрельский патч с полным переводом игры через промт

2024-05-07 15:31 UTC, lzk228 commented
> жду первоапрельский патч с полным переводом игры через промт

гении мыслят одинаково

2024-05-07 15:53 UTC, NotSoDana commented
Ещё раз перечитала переводы и ужаснулась. Такой пиздец в гайдбук совать - грех. Закрывай нахуй, сегодня ночью переведу по-человечески.

2024-05-07 16:10 UTC, NotSoDana commented
> Оно даже тесты валит. ПР который мы заслужили

Тесты валятся сейчас у всего подряд. Лейблер хуйню творит последнее время.

2024-05-10 22:59 UTC, closed without merging