Chemistry bottle resprite
space-syndicate/space-station-14 pull request #2118
Opened 2024-05-12 05:47 UTC by Ko4ergaPunk

**Медиа**

![Без имени](https://github.com/space-syndicate/space-station-14/assets/62609550/f7fa1036-63a6-4b4f-a743-2202c06c4463)

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:
- add: Добавлено веселье!
- remove: Убрано веселье!
- tweak: Изменено веселье!
- fix: Исправлено веселье!

2024-05-12 05:55 UTC, Ko4ergaPunk commented
Возрадуйтесь, перфекционисты

2024-05-24 13:36 UTC, Morb0 requested changes
Укажи в meta.json, что зареспрайтил

2024-05-24 13:36 UTC, Morb0 commented on Resources/Textures/Objects/Consumable/Food/bowl.rsi/aesir.png
А с этим что?

2024-05-24 14:26 UTC, Ko4ergaPunk commented on Resources/Textures/Objects/Consumable/Food/bowl.rsi/aesir.png
В коммите написал, что изменение без изменений. Тупа для запуска речеков

2024-05-24 20:44 UTC, Morb0 commented on Resources/Textures/Objects/Consumable/Food/bowl.rsi/aesir.png
Если оно отображается в изменениях, значит оно изменено и такого быть не должно. Сделай реверт `Empty recheck`

2024-05-25 00:07 UTC, Ko4ergaPunk commented on Resources/Textures/Objects/Consumable/Food/bowl.rsi/aesir.png
Да не изменено. Я в фотошопе двигаю на один пиксель, сохраняю. Потом двигаю как было, и снова сохраняю. И вот уже файл как измененный считается. Я всегда так делаю, если речек нужен

2024-05-25 00:14 UTC, Ko4ergaPunk commented on Resources/Textures/Objects/Consumable/Food/bowl.rsi/aesir.png
![image](https://github.com/space-syndicate/space-station-14/assets/62609550/87f3484f-e7ce-4a5c-9e7a-1f4321740818)

2024-05-25 00:15 UTC, Ko4ergaPunk commented on Resources/Textures/Objects/Consumable/Food/bowl.rsi/aesir.png
че это такое вообще

2024-06-11 00:55 UTC, Ko4ergaPunk commented
@SonicHDC

2024-06-11 01:06 UTC, merged