HatchAirlock Resprite + Fix
space-syndicate/space-station-14 pull request #2124
Opened 2024-05-12 19:25 UTC by xKREKS

## Описание PR

Респрайт "Герметичнных Шлюзов" а так же фикс ЕРРОР'ок

**Медиа**

https://github.com/space-syndicate/space-station-14/assets/169612430/71dec159-7246-4b84-8444-9f093abb1abc

![image](https://github.com/space-syndicate/space-station-14/assets/169612430/132defa9-3e25-4176-9047-b81786d298c0)

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: KREKS
- tweak: Респрайт герметичных шлюзов!
- fix: Исправленны ЕРРОРки при открытии герметичных шлюзов!

2024-05-12 19:25 UTC, xKREKS commented
Хоть бы всё было нормально в этот раз

2024-05-12 21:20 UTC, SonicHDC commented
Простой герметичный шлюз что-то довольно светлый и деталей у него нет совсем.
Может добавить тёмных пластин(ну или как это ещё назвать...) или скосов похожих на плоской части.

2024-05-18 22:45 UTC, xKREKS commented
Пока не мерджнули жоско пофикшу всякое

2024-05-18 22:55 UTC, xKREKS commented
акакредактировать

2024-05-19 04:59 UTC, DreamlyJack commented
Меняй файлы в ветке, и оно автоматически сюда будет переносится

2024-05-19 18:52 UTC, xKREKS commented
Ну вроде всё

2024-05-20 11:04 UTC, Morb0 requested changes

2024-05-20 11:04 UTC, Morb0 commented on Resources/Textures/Structures/Doors/Airlocks/Standard/hatch_maint.rsi/meta.json
> +  "copyright": "Taken from paradise station at commit https://github.com/ParadiseSS13/Paradise/commit/9312f1fb7dcdf1c195e255a528f31092613fb60d" Resprite by KREKS,
```suggestion
  "copyright": "Taken from paradise station at commit https://github.com/ParadiseSS13/Paradise/commit/9312f1fb7dcdf1c195e255a528f31092613fb60d, Resprite by KREKS",
```

2024-05-20 11:33 UTC, merged