Fix desert tile params
space-syndicate/space-station-14 pull request #2128
Opened 2024-05-14 05:23 UTC by Ko4ergaPunk

## Описание PR
Мапплю пляжик для Пилигрима. Настолько засранный песок выглядит просто ужасно

**Медиа**

![image](https://github.com/space-syndicate/space-station-14/assets/62609550/ef7871ea-807c-45eb-b55b-033a636e447f)

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:
- add: Добавлено веселье!
- remove: Убрано веселье!
- tweak: Изменено веселье!
- fix: Исправлено веселье!

2024-05-14 05:24 UTC, Ko4ergaPunk commented
![image](https://github.com/space-syndicate/space-station-14/assets/62609550/a6d842fb-04d3-47c3-a5c4-2163a33b68bd)

2024-05-14 05:24 UTC, lzk228 commented
оффам

2024-05-14 05:25 UTC, mhamsterr commented
cute

2024-05-14 05:26 UTC, Ko4ergaPunk commented
> оффам

Я хотел бы залить им чуть позже. Просто я быстрее карту закончу, чем они примут

2024-05-17 13:49 UTC, Morb0 requested changes

2024-05-17 13:49 UTC, Morb0 commented on Resources/Prototypes/Tiles/planet.yml
> +  - 0.01
```suggestion
# Corvax-Mapping-Start: Better visual look
  - 0.75
  - 0.06
  - 0.06
  - 0.06
  - 0.06
  - 0.01
# Corvax-Mapping-End
```

2024-05-17 13:50 UTC, merged