Сигареты и алкоголь
space-syndicate/space-station-14 pull request #215
Opened 2022-05-04 23:19 UTC by lapatison

## Описание PR 

**Изменения**

:cl: lapatison
- add: переводы и стилистические правки алкоголя, напитков, и сигарет
- remove: устаревшие файлы

2022-05-10 01:52 UTC, Morb0 requested changes

2022-05-10 01:52 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/consumable/drinks/drinks_cans.ftl
> +    .desc = Проходит сквозь словно космический ветер.
```suggestion
    .desc = Проходит сквозь, словно космический ветер.
```

2022-05-10 01:52 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/consumable/drinks/drinks_cans.ftl
> +ent-DrinkSpaceMountainWindCan = банка космогорного ветра
F отсылка на `mountendew`

2022-05-10 01:52 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/consumable/drinks/drinks_cans.ftl
> +    .desc = У хинина смешной вкус, но, по крайней мере, он убережет от космической малярии.
```suggestion
    .desc = У хинина смешной вкус, но по крайней мере он убережет от космической малярии.
```

2022-05-10 01:52 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/consumable/drinks/drinks_cans.ftl
> +ent-DrinkFourteenLokoCan = банка Четырнадцать Локо
как то не очень название такое смотрится переведенное

2022-05-10 01:54 UTC, lapatison commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/consumable/drinks/drinks_bottles.ftl
> +ent-DrinkBlueCuracaoBottleFull = кюрасао Мисс Синева
Заменю, провтыкал.

2022-05-10 01:57 UTC, lapatison commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/consumable/drinks/drinks_cans.ftl
> +ent-DrinkFourteenLokoCan = банка Четырнадцать Локо
Верну.

2022-05-10 02:00 UTC, lapatison commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/consumable/drinks/drinks_cans.ftl
> +ent-DrinkSpaceMountainWindCan = банка космогорного ветра
Может тогда, `космического маунтин винда'?
У нас же есть 'космическая кола'.

2022-05-10 04:33 UTC, lapatison commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/consumable/drinks/drinks_cans.ftl
> +ent-DrinkFourteenLokoCan = банка Четырнадцать Локо
Не хочу извращаться с транслитерацией fourteen, цифрой пойдет?

2022-05-10 10:59 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/consumable/drinks/drinks_cans.ftl
> +ent-DrinkSpaceMountainWindCan = банка космогорного ветра
Можно так

2022-05-10 11:05 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/consumable/drinks/drinks_cans.ftl
> +ent-DrinkFourteenLokoCan = банка Четырнадцать Локо
Это просто вообще не звучит как название напитка, если произносить цифры. Можно - `Фоуртин Локо`

2022-05-10 11:18 UTC, lapatison commented
Готово

2022-05-11 11:29 UTC, Morb0 requested changes

2022-05-11 11:29 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/consumable/smokeables/cigarettes/cigarette.ftl
> +    .suffix = синдиката
просто `синдикат`

2022-05-11 11:31 UTC, Morb0 commented
Так же нужно пройтись по файлам в `ss14-ru\prototypes\entities\objects\comsimable\drinks` и проверить, что у всех блоков есть свойство `.suffix = { "" }`.

2022-05-11 11:56 UTC, lapatison commented
> Так же нужно пройтись по файлам в `ss14-ru\prototypes\entities\objects\comsimable\drinks` и проверить, что у всех блоков есть свойство `.suffix = { "" }`.

Везде есть.

2022-05-11 11:58 UTC, merged