Респрайт Пластитановых Стен
space-syndicate/space-station-14 pull request #2151
Opened 2024-05-21 18:14 UTC by xKREKS

## Описание PR

 
Респрайт пластитановых стен под наш стиль (Tau Ceti)

**Медиа**

![image](https://github.com/space-syndicate/space-station-14/assets/169612430/0c61674d-2d71-4a4c-895f-dc8fdaab6759)

![image](https://github.com/space-syndicate/space-station-14/assets/169612430/73adad1d-a10f-4eb3-b408-35e6620250f3)

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: KREKS
- tweak: Респрайт пластитановых стен!

2024-05-21 18:15 UTC, xKREKS commented
Я наконец-то смог сделать ПР за 5 минут, а не за 5 часов🎉🎉🎉

2024-05-21 21:41 UTC, Morb0 requested changes

2024-05-21 21:41 UTC, Morb0 commented on Resources/Textures/Structures/Walls/plastitanium.rsi/meta.json
> +    "copyright": "Taken from https://github.com/tgstation/tgstation/tree/dfb73d28e68aa56c34c7c539448f713b78b6d4d5 and modified. Resprite by KREKS",
```suggestion
    "copyright": "Made by KREKS",
```

2024-05-21 21:41 UTC, Morb0 commented on Resources/Textures/Structures/Walls/plastitanium_diagonal.rsi/meta.json
> +    "copyright": "Taken from: https://github.com/tgstation/tgstation/commit/847e50af31a6c2b797c0de213e725f24b6175e17#diff-d887f4300e059d5fba9576e24bf1e6268a2fd25791f3d13f2636402492f6d917 Resprite by
```suggestion
    "copyright": "Made by KREKS",
```

2024-05-21 21:43 UTC, merged

2024-05-22 12:39 UTC, NULL882 commented
![image](https://github.com/space-syndicate/space-station-14/assets/104377798/a1142580-e377-44a9-8fba-198494a479d5)
:Pepe_Point:

2024-05-22 14:47 UTC, xKREKS commented
> ![image](https://private-user-images.githubusercontent.com/104377798/332798418-a1142580-e377-44a9-8fba-198494a479d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzODk0OTksIm5iZiI6MTcxNjM4OTE5OSwicGF0aCI6Ii8xMDQzNzc3OTgvMzMyNzk4NDE4LWExMTQyNTgwLWUzNzctNDRhOS04ZmJhLTE5ODQ5NGE0NzlkNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMlQxNDQ2MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MmVmOGFhN2M3OWMxNTdmOWIyYjczOWFlMzM0MWQ0OTQxNzdiYWIwZDUxM2MwYjNlOWIzMjRiMDg5YTk5ZTE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MXWoejuTrNw7yJgLiVqkq4NKwgQYv44zdUvIcb1NU90) :Pepe_Point:

ничё не понял

2024-05-29 07:18 UTC, NULL882 commented
> > ![image](https://private-user-images.githubusercontent.com/104377798/332798418-a1142580-e377-44a9-8fba-198494a479d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzODk0OTksIm5iZiI6MTcxNjM4OTE5OSwicGF0aCI6Ii8xMDQzNzc3OTgvMzMyNzk4NDE4LWExMTQyNTgwLWUzNzctNDRhOS04ZmJhLTE5ODQ5NGE0NzlkNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMlQxNDQ2MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MmVmOGFhN2M3OWMxNTdmOWIyYjczOWFlMzM0MWQ0OTQxNzdiYWIwZDUxM2MwYjNlOWIzMjRiMDg5YTk5ZTE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MXWoejuTrNw7yJgLiVqkq4NKwgQYv44zdUvIcb1NU90) :Pepe_Point:
> 
> ничё не понял
Стейт opening у технического гермолюка не респрайтнут, а остался тем же.