Щиттл апдейт мауса.
space-syndicate/space-station-14 pull request #2262
Opened 2024-06-15 18:22 UTC by Zna1kin

## Описание PR

**Медиа**

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: Zna1kin
- add: Добавлены шаттлы, СБ, РНД, новые карго, Утильский шаттл
- remove: Убрано веселье!
- tweak: Изменен косметически комната казни.
- fix: Исправлены мелкие косяки ввиде атмоса.

2024-06-15 18:28 UTC, Zna1kin commented
Похуй, завтра поломанные чеки сделаю.

2024-06-15 19:41 UTC, poeMota requested changes

2024-06-15 19:41 UTC, poeMota commented on Resources/Prototypes/Corvax/Maps/maus.yml
> +           - type: GridSpawn
Удали копипасту GridSpawn'а

2024-06-16 11:04 UTC, Zna1kin commented on Resources/Prototypes/Corvax/Maps/maus.yml
> +           - type: GridSpawn
ок щас

2024-06-16 11:33 UTC, poeMota approved these changes

2024-06-16 11:44 UTC, merged