Turtlenecks for command
space-syndicate/space-station-14 pull request #2276
Opened 2024-06-17 14:03 UTC by Deenkaide

## Описание PR
ПР на добавление недостающих водолазок глав и респрайт имеющихся.
Водолазки ГСБ и НРа перенесены в папку Корвакса, на их местах респрайты (новые костюмы)

**Медиа**
![ГВ](https://github.com/space-syndicate/space-station-14/assets/91343598/2607de2a-b7f0-408e-bc4a-80dd2dc86e46)
![ГП](https://github.com/space-syndicate/space-station-14/assets/91343598/94415eb5-50ff-4207-8291-0f0f61349bdf)
![ГСБ](https://github.com/space-syndicate/space-station-14/assets/91343598/a3c68442-3646-40e2-b00b-4c075feba9b9)
![ГСБАльт](https://github.com/space-syndicate/space-station-14/assets/91343598/1ed52ed7-3aff-40a8-a7de-d1660da7edbb)
![КМ](https://github.com/space-syndicate/space-station-14/assets/91343598/5c6af950-03da-4d8e-938e-337e00b25c96)
![Кэп](https://github.com/space-syndicate/space-station-14/assets/91343598/9f357e1d-142b-4970-af18-86ca2fa348fe)
![НР](https://github.com/space-syndicate/space-station-14/assets/91343598/7c0339ec-1751-4ba8-b1b3-fb19d4b3c97d)
![РНД](https://github.com/space-syndicate/space-station-14/assets/91343598/ebe6369f-389b-4343-b253-723e3ea95d2e)
![СИ](https://github.com/space-syndicate/space-station-14/assets/91343598/a0adf039-177a-4b80-a1a0-45c2a607abd9)

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [X] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**
:cl: Deenkaide
- add: Водолазки для ГП и Капитана
- add: Чёрный костюм для ГСБ
- add: Фиолетовый костюм для НРа
- tweak: Перенесены и исправлены водолазки ГСБ и НРа
- tweak: Водолазки СИ и ГВ перерисованы
- tweak: Водолазка КМа исправлена в руке

2024-06-17 14:06 UTC, lzk228 commented
по поводу водолазки смо, я бы взял с https://github.com/space-syndicate/space-station-14/pull/2190 , там низ более тёмный
но пусть решает @SonicHDC

2024-06-17 14:06 UTC, Deenkaide commented
Когда-нибудь я научусь нормально пользоваться гитом...
ПР не закончен ещё, но хочу услышать критику, если есть такая)

2024-06-17 19:58 UTC, Deenkaide commented
Добавил новые предметы в папку Корвакса.
Нужно понять какой копирайт прописывать в моём случае...
А также найти где переводить их

2024-06-17 20:06 UTC, lzk228 commented
я трясусь, чтобы не сказать легендарную фразу, но я так люблю водолазки в этой ебучей игре

2024-06-17 20:09 UTC, Deenkaide commented
> я трясусь, чтобы не сказать легендарную фразу, но я так люблю водолазки в этой ебучей игре

Оффы такое не примут, скорее всего, а шакалить до их уровня... у меня руки не поднимутся)

2024-06-17 20:14 UTC, lzk228 requested changes
- для хоса и рд оставь респрайты, а именно отдельные костюмы вынеси в корвакс

- ещё было бы хорошо сделать их в лодауты, можешь попробовать, если не сможешь, то я сделаю

- по поводу копирайта можешь просто написать `Created by Deenkaide (github)`

2024-06-17 20:14 UTC, lzk228 commented on Resources/Prototypes/Corvax/Entities/Clothing/Uniforms/jumpskirts.yml
> +  description: True captain's turtleneck
все описания в конце должны быть с точкой

2024-06-17 20:20 UTC, Deenkaide commented
> - для хоса и рд оставь респрайты, а именно отдельные костюмы вынеси в корвакс
> 
> - ещё было бы хорошо сделать их в лодауты, можешь попробовать, если не сможешь, то я сделаю
> 
> - по поводу копирайта можешь просто написать `Created by Deenkaide (github)`

1) так и сделал
2) я с лодаутами работал и планировал добавить их туда.
Плюс надо в принтер засунуть, наверное 
3) Мне уже отписали по этому поводу. Писать, что я создал мне совесть не позволит, ибо во многом просто перекрасы КМа и ВУ. Но я где возможно восстановлю прошлый копирайт и добавлю себя, а вот с новыми вещами надо подумать

2024-06-17 20:24 UTC, lzk228 commented
> 1. так и сделал

вот эти костюмчики в корвакс
![image](https://github.com/space-syndicate/space-station-14/assets/124214523/2dfc8f6c-a753-47ce-aff5-e19cdd2bb0c6)
чтобы водолазки на месте остались, а костюмы отдельно
![image](https://github.com/space-syndicate/space-station-14/assets/124214523/24887663-74c5-4bca-b32a-759c687d5ad7)


> 2\. Плюс надо в принтер засунуть, наверное

да



> 3\. Мне уже отписали по этому поводу. Писать, что я создал мне совесть не позволит, ибо во многом просто перекрасы КМа и ВУ. Но я где возможно восстановлю прошлый копирайт и добавлю себя, а вот с новыми вещами надо подумать

тогда напиши `Resprited from блаблабла by NAME`

2024-06-17 20:47 UTC, Deenkaide commented
> > 1. так и сделал
> 
> вот эти костюмчики в корвакс

Понял. Я просто увидел у оффов текстурки этих "водолазок" и названия папок (описания предметов я не читал) и подумал, что в нашем репозитории их просто назвали водолазками, тем более респрайты у нас. Поэтому эти костюмчик на их место запихнул.

Сейчас специально проверил и оказалось, что у оффов это тоже водолазки...
Поменяю тогда уж, но мне не нравится нейминг папок у оффов... запутанность создают. Потому что понять, что hos_alt и rnd - это водолазки сложно без чтения кода в другой папке и документе. 

Надо будет запустить к ним в репозиторий руки))

2024-06-18 08:31 UTC, Deenkaide commented
Вроде местами всё поменял, надеюсь ничего не пропустил

2024-06-18 09:15 UTC, lzk228 approved these changes

2024-06-18 09:33 UTC, Deenkaide commented
Чего... мне Аутпост тест завалили?

2024-06-18 09:34 UTC, SonicHDC commented
Шутки за 300

2024-06-18 09:34 UTC, merged

2024-06-18 09:35 UTC, Deenkaide commented
Аээээ, а лодауты и переводы)