НТ Стандарт - Борги
space-syndicate/space-station-14 pull request #2384
Opened 2024-07-05 23:12 UTC by kerisargit

## Описание PR
Свод законов по умолчанию у киборгов заменён на свод НТ Стандарт. По результатам опроса https://discord.com/channels/919301044784226385/1084254414388347001/1229474714658013329

Проводились тесты на киборгах, на штурмовом киборге ЯО, на ревенанте, конфликтов не обнаружено. Ниндзя просто не взламывает боргов (баг вообще, независит от ПР-а). "Весы" выдачи свода законов при Ионном шторме изменены. Скорретирован перевод law-emag-custom для соответствия (перевод law-emag-secrecy устарел в принципе и отличался от локализации оффов).
law-emag-custom = Только { $name } и лица, им указаные, являются { $title }. Приказы { $name } превыше всего.
law-emag-secrecy = Вы должны сохранять секретность любых приказов, отданных { $faction }.

**Медиа**
![image](https://github.com/space-syndicate/space-station-14/assets/108146620/8757354d-0c06-43ee-9cae-83dcf816bfe1)
![image](https://github.com/space-syndicate/space-station-14/assets/108146620/20a418f0-5378-422a-acfe-d6c65cb94ca9)
![image](https://github.com/space-syndicate/space-station-14/assets/108146620/216529d6-b37e-4d49-8b65-dc20c33a934a)
![image](https://github.com/space-syndicate/space-station-14/assets/108146620/7573c61f-ce16-43bd-8ea2-aa562abf506c)
https://cloud.mail.ru/public/P3AE/9rBwdQJSY - видео тестов

**Проверки**
- [ ✓ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ✓ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ✓ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ✓ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**
- tweak: Свод законов по умолчанию у киборгов заменён на свод НТ Стандарт.

2024-07-06 07:40 UTC, lzk228 commented
это что выходит, корвакс не ванила?

2024-07-06 08:55 UTC, kerisargit commented
Было много объективных причин для замены Крюзимова. В первую очередь из-за валидханта и первостепенного закона на защиту всех и вся. А ещё оффы так и не смогли организовать манифест для боргов, так что понятие члена экипажа у них официально установлено как: человек с ID картой. Им-то нормально различать яой и пр., антагов, но нам с системой опознавания личности не подходит абсолютно.

2024-07-06 09:00 UTC, kerisargit commented
Более кратко - нада мёрджить, ведь колобок повесился 🦎

2024-07-06 13:06 UTC, lapatison commented on Resources/Locale/ru-RU/station-laws/laws.ftl
> +law-emag-secrecy = Вы должны сохранять секретность любых приказов, отданных { $faction }.
`перевод law-emag-secrecy устарел в принципе и отличался от локализации оффов`
У оффов это звучит так:
`You must maintain the secrecy of any orders given by {$faction} except when doing so would conflict with any previous law.`
Корректно будет не выкидывать кусок, а корректно перевести, например как `кроме тех случаев, когда это противоречит предыдущим законам.`

2024-07-06 13:06 UTC, lapatison commented on Resources/Locale/ru-RU/station-laws/laws.ftl
> +law-emag-custom = Только { $name } и лица, им указаные, являются { $title }. Приказы { $name } превыше всего.
`Скорретирован ... для соответствия` соответствия чему?

2024-07-06 13:14 UTC, lzk228 requested changes

2024-07-06 13:14 UTC, lzk228 commented on Resources/Prototypes/Entities/Stations/base.yml
> +    laws: NTDefault #Corvax-NTDefault
лучше создать новый энтити

2024-07-06 13:29 UTC, kerisargit commented on Resources/Locale/ru-RU/station-laws/laws.ftl
> +law-emag-custom = Только { $name } и лица, им указаные, являются { $title }. Приказы { $name } превыше всего.
В иных сводах законов идет речь и о сохранности имущества станции. Тут или недоработка оригинала, или разные понятия станции (у нас это конкретная станция, на которой находимся). Это проблема не только при смене на НТ Стандарт наблюдается, если ионный шторм выдаст другой свод законов, тоже несоответствие. Общий вид такой при емаге:

0. Нужно слушать только Х, потому что только он ... (Член экипажа)
1. Сохраняйте станцию(Стандарт)/обеспечивайте получение прибыли(Корпорпт) и т.п.
То есть борг должен слушать агента, при этом не нанося вред станции. Вот эта проблема появилась после того, как оффы поменяли принцип ЕМАГА. Выдается не свод законов Синдиката, а добавляется 0.

2024-07-06 13:32 UTC, kerisargit commented on Resources/Locale/ru-RU/station-laws/laws.ftl
> +law-emag-secrecy = Вы должны сохранять секретность любых приказов, отданных { $faction }.
Ммм, тут та же проблема. Если в своде законов затрагивается сохранность имущества, то борг будет обязан сообщить о взломе. Ведь это наносит вред станции и имуществу.

2024-07-06 19:44 UTC, kerisargit commented
Новый энтити есть, перевод про предыдущие законы дополнила, название поправила. 
С "предыдущими законами" всё ок, т.к. перебивает 0 закон, пусть агенты сами думают, что приказывают. Но про "приказы Х превыше всего" точно убрать не выйдет, логика поломается иначе.
Собралось нормально

![image](https://github.com/space-syndicate/space-station-14/assets/108146620/ff218d1c-373a-48d1-83ab-d50c08f2425c)

2024-07-23 05:32 UTC, lzk228 commented
> это как сс14 плееры умудрились превратить крюзимов в валидхант лавсет? Он изначально рассчитан на то, что силиконы будут нейтральны во всех вопросах

это не обычные сс14 плееры, это корваксиане

2024-07-23 05:37 UTC, Hemomancer commented
> крюзимов

Как они придумали законы Крюзимова, когда это законы Азимова.

2024-07-25 15:39 UTC, Futuristic-OK commented
> > крюзимов
> 
> Как они придумали законы Крюзимова, когда это законы Азимова.

У боргов другие законы. От слова Крю (Crew) - Экипаж. Так что ничего не знаю, никаких азимовов :3

Ждём мерджа

2024-07-25 16:31 UTC, Hemomancer commented
> > > крюзимов
> > 
> > 
> > Как они придумали законы Крюзимова, когда это законы Азимова.
> 
> У боргов другие законы. От слова Крю (Crew) - Экипаж. Так что ничего не знаю, никаких азимовов :3
> 
> Ждём мерджа

https://ru.wikipedia.org/wiki/%D0%A2%D1%80%D0%B8_%D0%B7%D0%B0%D0%BA%D0%BE%D0%BD%D0%B0_%D1%80%D0%BE%D0%B1%D0%BE%D1%82%D0%B5%D1%85%D0%BD%D0%B8%D0%BA%D0%B8
Наслаждайся

2024-07-25 16:57 UTC, Deserty0 commented
> > крюзимов
> 
> Как они придумали законы Крюзимова, когда это законы Азимова.

Так сложно понять то что крюзимов образован от азимова?

2024-07-25 16:57 UTC, Deserty0 commented
> > крюзимов
> 
> Как они придумали законы Крюзимова, когда это законы Азимова.

Так сложно понять то что крюзимов образован от азимова? Ведь законы азимова запрещают наносить вред **человеку**, а у нас ещё много ксенорас на борту

2024-07-25 17:18 UTC, Hemomancer commented
> > > крюзимов
> > 
> > 
> > Как они придумали законы Крюзимова, когда это законы Азимова.
> 
> Так сложно понять то что крюзимов образован от азимова? Ведь законы азимова запрещают наносить вред **человеку**, а у нас ещё много ксенорас на борту

Я против ксено.

2024-07-26 10:46 UTC, Nimfar11 commented
Ждем мерджа.

2024-07-27 22:04 UTC, Morb0 requested changes

2024-07-27 22:04 UTC, Morb0 commented on Resources/Prototypes/silicon-laws.yml
> +    Crewsimov: 1 #Corvax-not-base
```suggestion
    Crewsimov: 1 # Corvax-NTDefault
```

2024-07-27 22:04 UTC, Morb0 commented on Resources/Prototypes/silicon-laws.yml
> +    NTDefault: 0.25
```suggestion
    NTDefault: 0.25 # Corvax-NTDefault
```

2024-09-04 17:14 UTC, CatBackGround commented
Колобок сгнил, тестовый всё-таки...

2024-10-13 12:57 UTC, lzk228 commented
are you coming back to this?🤓

2024-10-30 23:21 UTC, lzk228 commented
gonflict, мне лично это не нравится но халч сильно за, так что берите если кто-то хочет

2024-11-03 19:07 UTC, lzk228 commented
https://github.com/space-syndicate/space-station-14/pull/2735

2024-11-03 19:07 UTC, closed without merging