Add new corvax's pins
space-syndicate/space-station-14 pull request #2385
Opened 2024-07-06 11:41 UTC by MureixloI

## Описание PR

Добавление новых значков серверов Корвакса в игру
**Медиа**

![image](https://github.com/space-syndicate/space-station-14/assets/132683811/41886bcd-aeed-4f73-9b14-0a5d7765d56f)

**Изменения**

:cl: MureixloL
- add: Добавлены аксессуары!

2024-07-06 11:55 UTC, lzk228 commented
это всё таки ООС иконки и в неком смысле являются метой

2024-07-06 11:57 UTC, NotSoDana commented
> это всё таки ООС иконки и в неком смысле являются метой

А в чём мета то?

2024-07-06 11:58 UTC, Morb0 commented
> это всё таки ООС иконки и в неком смысле являются метой

Вспомним про постеры? :trollface:

2024-07-06 12:08 UTC, lzk228 commented
> Вспомним про постеры? :trollface:

а что с ними?

2024-07-06 12:17 UTC, lzk228 requested changes

2024-07-06 12:17 UTC, lzk228 commented on Resources/Prototypes/Corvax/Entities/Clothing/Neck/pins.yml
> +    - state: ath
```suggestion
  - type: Sprite
    sprite: Corvax/Clothing/Neck/Misc/pins.rsi
    state: ath
```
и так во всех в этом файле сделай

2024-07-06 12:17 UTC, lzk228 commented on Resources/Prototypes/Corvax/Entities/Clothing/Neck/pins.yml
> +      - state: ath-equipped
```suggestion
  - type: Clothing
    sprite: Corvax/Clothing/Neck/Misc/pins.rsi
    equippedPrefix: ath
```
при этом сам стейт должен будет называться `ath-equipped-NECK`
и так же сделай для всех остальных значков

2024-07-06 12:17 UTC, lzk228 commented on Resources/Prototypes/Entities/Structures/Furniture/dresser.yml
> +        orGroup: dressermainloot
отделить коментариями `# Corvax-Pins-Start` `# Corvax-Pins-End`

2024-07-06 12:17 UTC, lzk228 commented on Resources/Prototypes/Loadouts/loadout_groups.yml
> +  - ClothingNeckWhiteListPin # Corvax-clothing
```suggestion
  # Corvax-Loadouts-Start
  - ClothingNeckAtharaPin
  - ClothingNeckCorvaxPin
  - ClothingNeckEchoPin
  - ClothingNeckElysiumPin
  - ClothingNeckMainPin
  - ClothingNeckNebulaPin
  - ClothingNeckNovaPin
  - ClothingNeckWhiteListPin
  # Corvax-Loadouts-End
```

2024-07-08 15:01 UTC, NotSoDana commented
А в одном коммите слабо делать?

2024-07-08 15:09 UTC, lzk228 commented
так вебедит же

2024-07-08 15:22 UTC, MureixloI commented
------------23

2024-07-08 15:25 UTC, MureixloI commented
Ой, блять, с этими ошибками я лучше застрелюсь, чем буду продолжать всё исправлять в этом ПРе

2024-07-08 18:16 UTC, lzk228 commented on Resources/Prototypes/Corvax/Entities/Clothing/Neck/pins.yml
> +    equippedPrefix: ath-equipped-NECK
префикс на то и префикс, в нём не пишется фулл имя стейсьа а лишь префикс
глянь как это у свистков работает

2024-07-08 18:18 UTC, lzk228 commented on Resources/Prototypes/Corvax/Entities/Clothing/Neck/pins.yml
> +  name: Cluster pin
если это не название, то с маленькой буквы и для остальных серверных пинов тоже

2024-07-08 18:20 UTC, lzk228 commented on Resources/Prototypes/Entities/Structures/Furniture/dresser.yml
> +        # Corvax-Pins-End
мимо, на строку ниже

2024-07-08 22:33 UTC, lzk228 submitted a review, later dismissed
сами названия пнг сменить `ath-equipped` > `ath-equipped-NECK` и по кодовой части одобрено

2024-07-08 23:30 UTC, MureixloI commented
> сами названия пнг сменить `ath-equipped` > `ath-equipped-NECK` и по кодовой части одобрено

вроде готово

2024-07-09 16:55 UTC, MureixloI commented
🫨

2024-07-09 16:55 UTC, MureixloI commented
Я детей

2024-07-13 13:21 UTC, MureixloI commented
Завтра удалят СС14

2024-07-13 13:27 UTC, Verslebas commented
> Завтра удалят СС14

Наконец-то

2024-07-13 18:06 UTC, MureixloI commented
Сейчас бы скинуть стикер с сервера визардов

2024-07-14 15:56 UTC, MureixloI commented
Кстати Облако Оорта

2024-07-14 16:03 UTC, Verslebas commented
Ты обязательно добьешься мерджа, я в тебя верю!

2024-07-14 16:09 UTC, MureixloI commented
Через час

2024-07-16 10:13 UTC, MureixloI commented
🙂‍↕️

2024-07-16 13:30 UTC, Morb0 approved these changes

2024-07-16 13:38 UTC, merged

2024-07-16 14:00 UTC, MureixloI commented
ПОБЕДА!!!!!!!!!!!!

2024-07-16 14:00 UTC, MureixloI commented
Пойду праздновать