Перевод последнего обновления
space-syndicate/space-station-14 pull request #239
Opened 2022-06-07 02:23 UTC by lapatison

## Описание PR 

**Скриншоты**

**Изменения**

:cl: 
- add: различные переводы

2022-06-07 04:38 UTC, Morb0 requested changes

2022-06-07 04:38 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/back/backpacks.ftl
> +    .desc = Вместительный рюкзак с множеством карманов, который носит клоун отряда быстрого реагирования.
`который носит офицер безопасности` сделать для всех сумок кроме лидера во множественном числе - `который носят офицеры безопасности`

2022-06-07 04:38 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/devices/circuitboards/computer.ftl
> +ent-SurveillanceWirelessCameraMonitorCircuitboard = монитор беспроводной камеры наблюдения (машинная плата)
А не в множеством ли числе? `камеры` -> `камер`

2022-06-07 04:38 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/fun/toys.ftl
> +    .desc = Мягкая игрушка, напоминающая ядерного оперативника Синдиката. На бирке указано, что оперативники полностью вымышлены.
```suggestion
    .desc = Мягкая игрушка, напоминающая ядерного оперативника Синдиката. На бирке указано, что оперативники это полнейшая выдумка.
```

2022-06-07 04:38 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/fun/toys.ftl
> +    .desc = Пластиковая модель взрывного устройства ядерного деления. Урана в комплекте нет... возможно.
```suggestion
    .desc = Пластиковая модель взрывного ядерного устройства. Без урана внутри... скорее всего.
```

2022-06-07 04:38 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/fun/toys.ftl
> +    .desc = Фигурка Мини-Меха!  'Меха номер 5/12' написано на обороте.
Лишний пробел после восклицательного знака.
И лучше не `Меха` а просто `Мех`.

2022-06-07 04:38 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/fun/toys.ftl
> +    .desc = Направляя это на службу безопасности, будьте готовы наполниться свинцом.
```suggestion
    .desc = Целясь этим в офицеров, будьте готовы словить свинца.
```

2022-06-07 04:38 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/fun/toys.ftl
> +    .desc = Полустёртая надпись на нём является непереводимой игрой слов с использованием местных идиоматических выражений.
```suggestion
    .desc = Полустёртая надпись на нём выглядит непонятной игрой слов с использованием местных идиоматических выражений.
```

2022-06-07 04:38 UTC, Morb0 commented on Resources/Locale/ru-RU/surveillance-camera/surveillance-camera-ui.ftl
> +surveillance-camera-setup = Установить
Возможно `Настроить`? Не знаю точно контекст

2022-06-07 04:38 UTC, Morb0 commented on Resources/Locale/ru-RU/weapons/ranged/gun.ftl
> +gun-selected-mode = Выбрать { $mode }
```suggestion
gun-selected-mode = Выбран { $mode }
```

2022-06-07 04:38 UTC, Morb0 commented on Resources/Locale/ru-RU/weapons/ranged/gun.ftl
> +gun-magazine-examine = В нём осталось [color={ $color }]{ $count }[/color] выстрелов.
Консистентно с предложением выше. Можно наоборот добавить в `gun-battery-examine` подобное начало - `В нём ...`.
```suggestion
gun-magazine-examine = Осталось [color={ $color }]{ $count }[/color] выстрелов.
```

2022-06-07 04:45 UTC, lapatison commented on Resources/Locale/ru-RU/examine/examine-system.ftl
> +examinable-unanchored = Это не закреплено на полу
Если 'к полу', то тогда 'не прикреплено'. 
Но не звучит. Вечером ещё подумаю.

2022-06-07 04:53 UTC, lapatison commented on Resources/Locale/ru-RU/surveillance-camera/surveillance-camera-ui.ftl
> +surveillance-camera-setup = Установить
Днём посмотрю на сервере конкретизирую.

2022-06-07 15:29 UTC, lapatison commented on Resources/Locale/ru-RU/devices/device-network.ftl
>  device-address-prefix-scrubber = Скр-
Прости, поднять?

2022-06-07 15:59 UTC, Morb0 commented on Resources/Locale/ru-RU/devices/device-network.ftl
>  device-address-prefix-scrubber = Скр-
рядом их разместить
```
device-address-prefix-vent = Вент-
device-address-prefix-scrubber = Скр-
```

2022-06-08 10:44 UTC, lapatison commented on Resources/Locale/ru-RU/examine/examine-system.ftl
> +examinable-unanchored = Это не закреплено на полу
Хотя нет, `закреплено к` должно быть норм

2022-06-08 15:03 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/fun/toys.ftl
> +    .desc = Фигурка Мини-Меха!  'Меха номер 5/12' написано на обороте.
Тут не все

2022-06-08 15:21 UTC, merged