Элегантная форма горничной в УборШкафу
space-syndicate/space-station-14 pull request #2391
Opened 2024-07-07 21:25 UTC by NotSoDana

## Описание PR

А почему бы собственно и нет? Обычные есть, а наша чем хуже?

**Медиа**

![image](https://github.com/space-syndicate/space-station-14/assets/75203942/8a659ef2-2e71-4cb6-ac5e-33ba3adc0fc9)

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: Dezzzix
- add: Элегантная форма горничной добавлена в ЕМАГнутый УборШкаф

2024-07-07 21:40 UTC, NotSoDana commented
Если здесь наберётся 10 классов я осмелею и вообще перенесу её из емагнутой в обычную 
 <:S_buldiga:1204527633753182258>

2024-07-07 21:45 UTC, Sergan31 commented
Где же лазик, когда он так нужен...

2024-07-07 21:46 UTC, lzk228 commented on Resources/Prototypes/Catalog/VendingMachines/Inventories/janidrobe.yml
> +    ClothingUniformJumpskirtElegantMaid: 2 #Corvax-MRP
```suggestion
    ClothingUniformJumpskirtElegantMaid: 2 #Corvax-ERP
```
:trollface:

2024-07-07 21:47 UTC, NotSoDana commented on Resources/Prototypes/Catalog/VendingMachines/Inventories/janidrobe.yml
> +    ClothingUniformJumpskirtElegantMaid: 2 #Corvax-MRP
Не ну ты конечно. Я такое напишу только если перенесу не в емагнутый <:Cat_gagaga:1163453969616621598>

2024-07-07 21:48 UTC, lzk228 commented
а на самом деле я не знаю какой тег тут нужен поэтому ждите морти

2024-07-07 22:06 UTC, lzk228 commented
> Если здесь наберётся 10 классов я осмелею и вообще перенесу её из емагнутой в обычную <:S_buldiga:1204527633753182258>

ребята даже не пытайтесь, я его закрою если не будет опросника с 75%за :trollface:

2024-07-07 22:07 UTC, NotSoDana commented
> > Если здесь наберётся 10 классов я осмелею и вообще перенесу её из емагнутой в обычную <:S_buldiga:1204527633753182258>
> 
> ребята даже не пытайтесь, я его закрою если не будет опросника с 75%за :trollface:

сделаешь нам опросник за фотки полуголых вульпочек? :trollface:

2024-07-07 23:04 UTC, cfif126 commented
![ApplicationFrameHost_q7Odc6Uh1m](https://github.com/space-syndicate/space-station-14/assets/94059374/d34ef608-2682-46b7-9ad1-eab5dca92a9e)

2024-07-07 23:05 UTC, NotSoDana commented
> ![ApplicationFrameHost_q7Odc6Uh1m](https://private-user-images.githubusercontent.com/94059374/346376683-d34ef608-2682-46b7-9ad1-eab5dca92a9e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzOTM3NjksIm5iZiI6MTcyMDM5MzQ2OSwicGF0aCI6Ii85NDA1OTM3NC8zNDYzNzY2ODMtZDM0ZWY2MDgtMjY4Mi00NmI3LTlhZDEtZWFiNWRjYTkyYTllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA3VDIzMDQyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxMTdkOWZlOTFkODY1ZGQwZDE1YWIzNmU5MzVlYzFmYzgzMDc3MGU0OTdlMWJmYTE0MzdiNDYwMGYxODU5ZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aMsZPBOi_yVz6tXuVCESOWtNeTZMw_wsWmKc9oSsWZ8)

втф кто соль коту оставил......

2024-07-08 10:54 UTC, NotSoDana commented
![image](https://github.com/space-syndicate/space-station-14/assets/75203942/a302dea8-77e1-496d-b3b0-327971ec0e88)
допизделись, потом сделаю

2024-08-02 19:33 UTC, NotSoDana commented
@Morb0

2024-08-09 14:07 UTC, Morb0 requested changes

2024-08-09 14:07 UTC, Morb0 commented on Resources/Prototypes/Catalog/VendingMachines/Inventories/janidrobe.yml
> +    ClothingUniformJumpskirtElegantMaid: 2 #Corvax-MRP
```suggestion
    ClothingUniformJumpskirtElegantMaid: 2 # Corvax
```

2024-08-09 14:09 UTC, merged