Респрайт некоторых шкафов для локализации
space-syndicate/space-station-14 pull request #2393
Opened 2024-07-08 15:59 UTC by chavonadelal

## Описание PR

Респрайт некоторых шкафов с заменой английских букв на русские, чтобы новички понимали контекст. У СБ буква заменена на иконку для узнаваемости, ранее там тоже была английская буква.
**Медиа**

![image](https://github.com/space-syndicate/space-station-14/assets/156101927/c6044c23-4015-4dc5-a209-0aaf5a601042)

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: to4no_fix
- tweak: Респрайт некоторых шкафов для локализации

2024-07-08 18:16 UTC, Decortex commented
Мне нравится идея с иконками на шкафу, которые видно в очках сб

2024-07-08 18:37 UTC, lzk228 commented
а заменить на букву Б для Безопасности?

2024-07-08 18:48 UTC, chavonadelal commented
> а заменить на букву Б для Безопасности?

Будет похоже на цифру 6, возможна путаница, я пробовал

2024-07-08 18:50 UTC, lzk228 commented
ну Б для Безопасности а 6 то что будет значить?

2024-07-08 18:55 UTC, lzk228 commented
![image](https://github.com/space-syndicate/space-station-14/assets/124214523/aab4771e-18ca-4c38-ae71-2486d453a014)

2024-07-08 18:57 UTC, lzk228 commented
![image](https://github.com/space-syndicate/space-station-14/assets/124214523/134ec35b-03f8-414c-9656-22c367887f4c)
![image](https://github.com/space-syndicate/space-station-14/assets/124214523/5758d8e7-75ca-4e96-a0c5-a99de3667641)
![image](https://github.com/space-syndicate/space-station-14/assets/124214523/1b428c9e-1b4f-4845-9304-de99453fd8aa)

2024-07-08 19:00 UTC, chavonadelal commented
> ![image](https://private-user-images.githubusercontent.com/124214523/346691933-aab4771e-18ca-4c38-ae71-2486d453a014.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0NjUzMzksIm5iZiI6MTcyMDQ2NTAzOSwicGF0aCI6Ii8xMjQyMTQ1MjMvMzQ2NjkxOTMzLWFhYjQ3NzFlLTE4Y2EtNGMzOC1hZTcxLTI0ODZkNDUzYTAxNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOFQxODU3MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZjE2MWY3ZWIwODBlYzUzNjk5ZTk4MmEzYTYwODdjZTNmMDUzMGMzOGI4NDkzZjQ4OGYxMmM4ODBiMzEwZGJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hA73kGrsrckVygVhpXLUYh7o0jP9X7lu_6kqFcSf__Q)

Ну если только так, хотя лично для меня как нагромождение какое-то выглядит.... Морти же пр проверяет? или кто?

2024-07-08 19:01 UTC, lzk228 commented
@SonicHDC

2024-07-08 19:01 UTC, chavonadelal commented
Ничего не мешает ящику утилизаторов быть с значком кирки, а не с буквой

2024-07-08 19:06 UTC, chavonadelal commented
> @SonicHDC

Спасибо, подожду ответа

2024-07-08 23:01 UTC, SonicHDC requested changes
Честно говоря, у шкафов сб как-то значёк не смотрится. Слишком массивный.
Могу предложить написать на шкафу офицера О, а на шкафу смотрителя С.

2024-07-08 23:08 UTC, chavonadelal commented
> Честно говоря, у шкафов сб как-то значёк не смотрится. Слишком массивный. Могу предложить написать на шкафу офицера О, а на шкафу смотрителя С.

О и С это кто-то слишком топорно, на мой взгляд. Г и то со скрипом с сердце пришлось нарисовать на ящике ботаника.... Я не понимаю, чем так не нравится, ведь на шкафу утилизатора не буква, а кирка - иконка профессии. Чем же тут хуже? Тем более, что шкафы СБ стилистически отличаются от других.

2024-07-08 23:09 UTC, chavonadelal commented
> Честно говоря, у шкафов сб как-то значёк не смотрится. Слишком массивный. Могу предложить написать на шкафу офицера О, а на шкафу смотрителя С.

Если совсем не нравится, то могу попробовать нарисовать иконку профессии смотрителя на шкафу смотрителя, чтобы логичнее было.

2024-07-09 01:51 UTC, SonicHDC commented
> Если совсем не нравится, то могу попробовать нарисовать иконку профессии смотрителя на шкафу смотрителя, чтобы логичнее было.

Да. Если сделать так, то будет логично. Тогда спокойно одобрю.

2024-07-09 17:49 UTC, chavonadelal commented
> > Если совсем не нравится, то могу попробовать нарисовать иконку профессии смотрителя на шкафу смотрителя, чтобы логичнее было.
> 
> Да. Если сделать так, то будет логично. Тогда спокойно одобрю.

@SonicHDC Перерисовал дверь шкафа смотрителя, теперь там красивая иконка профессии. 😎 Одобряешь?

2024-07-09 21:17 UTC, iAmScienceMan commented
Красотулечка, я точно одобряю

2024-07-09 23:17 UTC, SonicHDC approved these changes
Ну теперь это имеет смысл.

2024-07-09 23:20 UTC, merged