Перевод меню «Бункер паники» и «Детская тюрьма»
space-syndicate/space-station-14 pull request #2394
Opened 2024-07-08 22:08 UTC by chavonadelal

## Описание PR

Последний штрих в переводе меню администратора. 😄 
**Медиа**

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: to4no_fix
- add: Добавлен перевод меню «Бункер паники» и «Детская тюрьма»

2024-07-08 22:30 UTC, lzk228 requested changes
@lapatison

2024-07-08 22:30 UTC, lzk228 commented on Resources/Locale/ru-RU/administration/ui/tabs/babyjail-tab.ftl
> +admin-ui-baby-jail-enabled = Детсад включен
```suggestion
admin-ui-baby-jail-enabled = Детсад включён
```

2024-07-08 22:30 UTC, lzk228 commented on Resources/Locale/ru-RU/administration/ui/tabs/babyjail-tab.ftl
> +admin-ui-baby-jail-enabled-admin-alert = Детсад был включен.
```suggestion
admin-ui-baby-jail-enabled-admin-alert = Детсад был включён.
```

2024-07-08 22:30 UTC, lzk228 commented on Resources/Locale/ru-RU/administration/ui/tabs/panicbunker-tab.ftl
> +admin-ui-panic-bunker-enabled = Бункер включен
```suggestion
admin-ui-panic-bunker-enabled = Бункер включён
```

2024-07-08 22:30 UTC, lzk228 commented on Resources/Locale/ru-RU/administration/ui/tabs/panicbunker-tab.ftl
> +admin-ui-panic-bunker-enabled-admin-alert = Бункер был включен.
```suggestion
admin-ui-panic-bunker-is-enabled = Бункер в данный момент включён.
admin-ui-panic-bunker-enabled-admin-alert = Бункер был включён.
```

2024-07-08 22:33 UTC, chavonadelal commented on Resources/Locale/ru-RU/administration/ui/tabs/babyjail-tab.ftl
> +admin-ui-baby-jail-enabled = Детсад включен
Е Ё? Ну хорошо, поменяю сейчас

2024-07-08 22:50 UTC, chavonadelal commented
@lzk228 исправил

2024-07-09 04:52 UTC, lapatison approved these changes

2024-07-09 06:46 UTC, lzk228 approved these changes

2024-07-09 06:48 UTC, merged