Translate Guidebook
space-syndicate/space-station-14 pull request #2420
Opened 2024-07-17 16:44 UTC by Roudenn

## Описание PR
Переведены следующие статьи руководства:
- Командование
- Словарь терминов
- Радиосвязь
- Таблицы и референсы
- Отделы

Помимо словаря терминов отсебятины почти нигде нет. В словаре терминов всё постарался адаптировать под русский сленг SS14, то есть без сингулузов, AoS и KoS, поскольку у них нет прямых аналогов в нашем сленге (насколько я знаю). В словаре всё пересортировано в алфавитном порядке для русского языка.

**Проверки**

- [X] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [X] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [X] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [X] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**
но кл но фан

2024-07-19 07:37 UTC, lzk228 requested changes
запрос ревью от @lapatison

2024-07-19 07:37 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Command.xml
> +Поздравляем с вашим повышением! Помимо бумажной работы, ваши новые [color=#a4885c]обязанности[/color] включают в себя обеспечение работы отдела, проведение изменений и смены приоритетов, обеспечение
```suggestion
Поздравляем с вашим повышением! Помимо бумажной работы, ваши новые [color=#a4885c]обязанности[/color] включают в себя обеспечение работы отдела, проведение изменений и смены приоритетов, обеспечение безопасности персонала отдела и его экипировки, а также лежать на спинке кресла, пока ваши сотрудники работают.
```
масло масляное

2024-07-19 07:37 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Command.xml
> +Пульт управления влияет на то, где и как могут передвигаться люди. Главы могут закрыть персонал от опасных мест или быстро пустить кого-нибудь в отдел.
```suggestion
Пульт управления влияет на то, где и как могут передвигаться люди. Главы могут закрыть персонал от опасных мест или быстро пустить кого-нибудь в отдел.

```

2024-07-19 07:37 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Command.xml
> +Используйте это для сообщения с другими главами и представляйте желания и нужды своих работников.
```suggestion
Используйте это для общения с другими главами и представляйте желания и нужды своих работников.
```

2024-07-19 07:37 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Glossary.xml
это скопировано с страницы вики?

2024-07-19 07:37 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Jobs.xml
> +В научный отдел входят научные ассистенты, учёные и научный руководитель (НР). Этот отдел отвечает за изучение технологий, артефактов и аномалий, улучшение машин, а также производство полезных для ст
```suggestion
В научный отдел входят научные ассистенты, учёные и научный руководитель (НР). Этот отдел отвечает за изучение технологий и артефактов, улучшение машин, а также производство полезных для станции устройств.
```

2024-07-19 07:37 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/NewPlayer/Controls/Radio.xml
> +Общение это ключевая часть Космической Станции 14. Вы можете нажать [keybind="FocusChatInputWindow"/] чтобы открыть поле ввода для чата.
```suggestion
Общение это ключевая часть Космической Станции 14. Вы можете нажать [keybind="FocusChatInputWindow"/] чтобы активировать поле ввода для чата.
```

2024-07-19 07:37 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/NewPlayer/Controls/Radio.xml
> +"Эмоции" это жесты которые вы показываете. Их могут видеть все, у кого есть зрение. Часто мимы делают много эмоций именно через этот канал.
```suggestion
"Эмоции" это жесты которые вы показываете. Их могут видеть все, у кого есть зрение. Вы часто увидите, как мимы исполняют множество эмоций.
```

2024-07-19 07:37 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/NewPlayer/Controls/Radio.xml
> +Сообщения шёпотом могут быть отправлены при написании ([color=#a4885c],[/color]) перед текстом, а Эмоции могут быть отправлены если вы начнёте своё сообщение с символа ([color=#a4885c]%[/color]).
```suggestion
Сообщения шёпотом могут быть отправлены при написании ([color=#a4885c][keybind="FocusWhisperChatWindow"/][/color]) перед текстом, а Эмоции могут быть отправлены если вы начнёте своё сообщение с символа ([color=#a4885c]%[/color]).
```

2024-07-19 07:37 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/NewPlayer/Controls/Radio.xml
> +Ваша гарнитура позволяет вам общаться через всю станцию и с вашим [color=#a4885c]отделом[/color].
```suggestion
Ваша гарнитура позволяет вам общаться со всей станцией и с вашим конкретным [color=#a4885c]отделом[/color].
```

2024-07-19 07:37 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/NewPlayer/Controls/Radio.xml
> +Осмотр ранее известной нам инженерной гарнитуры покажет нам наличие [color=#32cd32]Общего[/color] и [color=#f37746]Инженерного[/color] канала, потому что гарнитура инженера с самого начала имеет соот
```suggestion
Осмотр ранее известной нам инженерной гарнитуры покажет нам наличие [color=#32cd32]Общего[/color] и [color=#f37746]Инженерного[/color] канала, потому что гарнитура инженера с самого начала имеет эти [color=#a4885c]ключи шифрования[/color].
```

2024-07-19 07:37 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/NewPlayer/Controls/Radio.xml
> +Вы можете извлечь ключи шифрования используя [color=#a4885c]отвёртку[/color] на гарнитуре. Новыеп ключи шифрования могут быть вставлены в гарнитуру при нажатии активной рукой с ключом на гарнитуру.
```suggestion
Вы можете извлечь ключи шифрования используя [color=#a4885c]отвёртку[/color] на гарнитуре. Новые ключи шифрования вставляются в гарнитуры, если нажать на одну из них с ключом шифрования в руке.
```

2024-07-19 07:37 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/NewPlayer/Controls/Radio.xml
> +OOC (чаты вне-персонажа) существуют за пределами игрового мира. Это LOOC, OOC и чат Мёртвых.
```suggestion
OOC (чаты вне-персонажа (от англ. out of character)) существуют за пределами игрового мира. Это LOOC, OOC и чат Мёртвых.
```

2024-07-19 09:32 UTC, Roudenn commented on Resources/ServerInfo/Guidebook/Glossary.xml
Нет, прямой перевод страницы оффов

2024-07-19 09:33 UTC, Roudenn commented on Resources/ServerInfo/Guidebook/NewPlayer/Controls/Radio.xml
> +Сообщения шёпотом могут быть отправлены при написании ([color=#a4885c],[/color]) перед текстом, а Эмоции могут быть отправлены если вы начнёте своё сообщение с символа ([color=#a4885c]%[/color]).
Эта штука сломана, она показывает вроде бы неправильный символ, точно также с эмоциями

2024-07-23 06:31 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/NewPlayer/Controls/Radio.xml
> +Сообщения шёпотом могут быть отправлены при написании ([color=#a4885c],[/color]) перед текстом, а Эмоции могут быть отправлены если вы начнёте своё сообщение с символа ([color=#a4885c]%[/color]).
протестировал, работает нормально

2024-08-08 18:07 UTC, lzk228 commented
@lapatison когда сможет - ревьювнет

2024-08-08 18:20 UTC, Roudenn commented
Опять проверки рандомно поломались...

2024-09-07 13:09 UTC, Roudenn commented
@Izk228 @lapatison ревью будет?

2024-09-07 13:24 UTC, lzk228 commented
ждём ревью от лапатисона

2024-10-13 13:04 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Glossary.xml
> +Отсылает к взламывающему устройству синдиката. "Емагнутый" обычно относится к шлюзам или шкафам которые открыты и заболтированы, но также может относится и к другим устройствам, взломанные при помощи
```suggestion
Отсылает к криптографическому секвенсеру синдиката. "Емагнутый" обычно относится к шлюзам или шкафам которые открыты и заболтированы, но также может относится и к другим устройствам, взломанные при помощи Емага.
```

2024-10-13 13:21 UTC, lzk228 requested changes

2024-10-13 13:21 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Glossary.xml
> +## Заболтировано
```suggestion
## Заболтирован
```

2024-10-13 13:21 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Glossary.xml
> +Сленговое сокращение для Ядерного Оперативника. Аналогично может использоваться абривеатура ЯО.
не может.
```suggestion
Сленговое сокращение для Ядерного Оперативника. Аналогично могут использоваться сокращения опер, нюк, опс.
```

2024-10-13 13:21 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Glossary.xml
> +## РнД
```suggestion
## РнД / НИО
```

2024-10-13 13:21 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Glossary.xml
> +## ССД
```suggestion
## ССД / КРС
```

2024-10-13 13:21 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Glossary.xml
> +Космическое расстройство сна, или же Неожиданное растройство сна. Это ролевой путь для описания игрока, который покинул игру и больше не отвечает.
у нас такого нету
```suggestion
Космическое расстройство сна. Это ролевой путь для описания игрока, который покинул игру и больше не отвечает.
```

2024-10-13 13:21 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Glossary.xml
> +Сокращение для специалиста по утилизации.
```suggestion
Сокращение для утилизатора.
```

2024-10-13 13:21 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Glossary.xml
> +Полный доступ (фулл доступ), или же ID карта которая имеет полный доступ на станции. Обычно таким доступом обладает только капитан.
у нас нет аналога термину AA (all access), говорят просто "полный доступ", поэтому это наверное стоит убрать

2024-10-13 13:21 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Glossary.xml
> +Сокращение для Пермаментного брига. Заключенные в такой камере осуждены за крайне серьёзное преступление и никогда не выйдут на свободу. Большинство станций имеет отдельную область для пермаментного
```suggestion
Сокращение для Перманентного брига. Заключенные в такой камере осуждены за крайне серьёзное преступление и никогда не выйдут на свободу. Большинство станций имеет отдельную область для пермаментного брига.
```

2024-10-13 13:21 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Glossary.xml
> +# Сленг в роли персонажа (IC)
```suggestion
# Сленг в роли персонажа (In Character - IC)
```

2024-10-13 13:21 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Glossary.xml
> +# Сленг НЕ в роли персонажа (OOC)
```suggestion
# Сленг НЕ в роли персонажа (Out Of Character - OOC)
```

2024-10-13 13:21 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Glossary.xml
> +Какое-либо событие, которое было вызвано админом.
этот термин у нас так же не используется

2024-10-13 13:21 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Glossary.xml
> +Локальный чат вне-отыгрыша-персонажа и (глобальный) чат вне-отыгрыша-персонажа. Это текстовые каналы, в которых игроки могут общаться с другими игроками вне отыгрыша. В то время как LOOC включён во в
ну ты мог бы хотя бы постараться подправить после переводчика

2024-10-13 13:21 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Glossary.xml
>  ## LRP
```suggestion
## LRP (Low RolePlay)
```

2024-10-13 13:21 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Glossary.xml
>  ## MRP
как и выше

2024-10-13 13:21 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Glossary.xml
>  ## HRP
как и выше

2024-10-13 13:30 UTC, Roudenn commented on Resources/ServerInfo/Guidebook/Glossary.xml
> +Какое-либо событие, которое было вызвано админом.
Правильнее я так понимаю поменять на Адмем и описать примерно как "Ироничное название для администратора"
Сойдет?

2024-10-13 13:33 UTC, UmnayaSvinka commented on Resources/ServerInfo/Guidebook/Glossary.xml
> +Какое-либо событие, которое было вызвано админом.
> Правильнее я так понимаю поменять на Адмем и описать примерно как "Ироничное название для администратора" Сойдет?

у нас вообще нет такого термина

2024-10-13 13:33 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Glossary.xml
> +Какое-либо событие, которое было вызвано админом.
имо лучше убрать вовсе

2024-10-13 13:39 UTC, Roudenn commented on Resources/ServerInfo/Guidebook/Glossary.xml
> +Какое-либо событие, которое было вызвано админом.
Окей
Если что я отсюда сейчас всё скопирую и сделаю 1 коммитом

2024-10-13 13:40 UTC, Roudenn commented on Resources/ServerInfo/Guidebook/Glossary.xml
> +Локальный чат вне-отыгрыша-персонажа и (глобальный) чат вне-отыгрыша-персонажа. Это текстовые каналы, в которых игроки могут общаться с другими игроками вне отыгрыша. В то время как LOOC включён во в
Я переводил всё сам.... 💀

2024-10-13 13:49 UTC, Roudenn commented on Resources/ServerInfo/Guidebook/Glossary.xml
> +Полный доступ (фулл доступ), или же ID карта которая имеет полный доступ на станции. Обычно таким доступом обладает только капитан.
На форке играю, у нас часто именно термин ФД используют
Довольно странно но так уж и быть уберу

2024-10-23 09:12 UTC, lzk228 approved these changes

2024-10-23 09:12 UTC, merged