Change aghost speed
space-syndicate/space-station-14 pull request #2433
Opened 2024-07-24 14:57 UTC by Ko4ergaPunk

## Описание PR

Изменил скорость шифта агостов с 8 на 50.
Все агосты меняют себе скорость передвижения. У админов на призраке есть потребность в высокой скорости, а не замедленном шаге. Так что, почему бы и не сократить рутинные задачи?

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:

2024-07-24 14:59 UTC, Deserty0 commented
оффам 🤓

2024-07-24 15:03 UTC, Verslebas commented
> ![image](https://private-user-images.githubusercontent.com/124214523/351766452-f1e9ad30-c013-4051-ad20-b7234740db9b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4MzM3MDQsIm5iZiI6MTcyMTgzMzQwNCwicGF0aCI6Ii8xMjQyMTQ1MjMvMzUxNzY2NDUyLWYxZTlhZDMwLWMwMTMtNDA1MS1hZDIwLWI3MjM0NzQwZGI5Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNFQxNTAzMjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MjlmOGQxYmE5MTRhOWZjZjc1MmY4Mzg3OWI5MTU4ZmFlYjU0MDcxZDZhNjFiOWVkYjlhYmZkNDhhNjZmMzAxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mLX-akf7xE30Mq6coFoB-kTod6Yeva4p0uUGWlsfay0)

в каком канале

2024-07-24 15:05 UTC, lzk228 commented
в том самом

2024-07-24 21:58 UTC, NikaVichy commented
![image](https://github.com/user-attachments/assets/a44de2ce-b468-4294-8949-c98fc063d077)

2024-07-25 08:10 UTC, Ko4ergaPunk commented
Не дали :с 
@lzk228 
[#30317](https://github.com/space-wizards/space-station-14/pull/30317)

2024-07-25 08:13 UTC, lzk228 commented
вполне reasonable отказ

2024-07-25 08:15 UTC, Ko4ergaPunk commented
Ну, как бы да, но как бы и паебать агостам на описанные причины. Все-равно скорость выставляют. Мерджнешь, или у вас на мой ПР особые извращённые планы?

2024-07-31 13:29 UTC, Ko4ergaPunk commented
:<

2024-08-13 20:35 UTC, Ko4ergaPunk commented
@lzk228

2024-08-17 15:50 UTC, Ko4ergaPunk commented
@lzk228

2024-08-19 14:22 UTC, lzk228 requested changes
.

2024-08-19 14:24 UTC, lzk228 approved these changes

2024-08-19 14:25 UTC, merged

2024-08-19 14:25 UTC, lzk228 commented
rejoice