plitkorez wtf
space-syndicate/space-station-14 pull request #2453
Opened 2024-08-04 00:09 UTC by NotSoDana

## Описание PR

Йобаный рот этого плиткореза

![image](https://github.com/user-attachments/assets/f01ee309-da38-4b33-9988-5c2a67aa05a5)

**Медиа**

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:
- add: Добавлено веселье!
- remove: Убрано веселье!
- tweak: Изменено веселье!
- fix: Исправлено веселье!

2024-08-04 07:31 UTC, Deserty0 commented
А разве у лапатисона сейчас не перевод апстрима с плиткорезом?

2024-08-04 07:42 UTC, lzk228 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/machines/lathe.ftl
> +    .desc = Это резак. Он режет. Придайте разнообразия полу вашей станции с помощью интересных узоров! Не засовывайте внутрь пальцы!
```suggestion
    .desc = Это резак. Он режет. Придайте разнообразия полу вашей станции с помощью интересных узоров! Не засовывайте внутрь пальцы.
```

2024-08-04 07:42 UTC, lzk228 requested changes
what said above

2024-08-04 16:34 UTC, NotSoDana commented
bruh

2024-08-04 16:35 UTC, lzk228 approved these changes

2024-08-09 11:34 UTC, lapatison approved these changes

2024-08-09 13:12 UTC, merged