[Art] Mining structures retexture
space-syndicate/space-station-14 pull request #2465
Opened 2024-08-07 16:16 UTC by Ko4ergaPunk

## Описание PR

Перерисовал шахтерские стены, окна и плитки. Оригинал очень неплох, но по цветам с корвухом не сходится, да и по форме.

От порушенных версий решил отказаться, так как нахер они и не нужны =)
Но могу сделать, если прям так хочется. Правда, я даже не знал о их существовании. Ну и убого они выглядят, есчесн.

**Медиа**

![pr](https://github.com/user-attachments/assets/ec8d0d95-c3f9-4268-884a-eb4673a9de1f)

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:

2024-08-07 16:31 UTC, lzk228 submitted a review, later dismissed
> От порушенных версий решил отказаться, так как нахер они и не нужны =)

либо делаешь нормально либо никак

2024-08-07 16:38 UTC, Sergan31 commented
то есть стены не сочетались по стилю ровно до момента, пока их не сделали более серыми?

2024-08-07 16:38 UTC, SonicHDC requested changes
Окна слишком светлые, лучше приблизить к матовому варианту.

2024-08-07 16:43 UTC, poeMota commented
окна кайф, предыдущие невозможно было использовать

2024-08-07 23:42 UTC, BolloTea commented
Фу, светлая тема...

2024-08-07 23:57 UTC, NotSoDana commented
Чет по-моему хуета какая-то, особенно стекло

2024-08-08 00:01 UTC, BolloTea commented
Мрачность и темное стекло лучше шли. Теперь это палатка для кемпинга, а не суровых шахтеров

2024-08-08 04:15 UTC, Ko4ergaPunk commented
Взял цвета с матового
@SonicHDC 
![pr](https://github.com/user-attachments/assets/e792341c-1e29-4b47-8b5d-95c87a0ce191)

2024-08-08 05:12 UTC, Ko4ergaPunk commented
![image](https://github.com/user-attachments/assets/c63bea01-e9aa-419e-b369-acbae8e4bacb)
В игре показать сложно, тк они рандомные

2024-08-08 08:09 UTC, BolloTea commented
Матовые стекла хорошо выглядят. Кочерга, ты же делал респрайт чтобы они более к ванильной стене подходили?

2024-08-08 08:19 UTC, Ko4ergaPunk commented
> Матовые стекла хорошо выглядят. Кочерга, ты же делал респрайт чтобы они более к ванильной стене подходили?

Не. Я матовые не трогал

2024-08-09 10:04 UTC, Ko4ergaPunk commented
ПОБЕДА @SonicHDC

2024-08-09 14:35 UTC, SonicHDC approved these changes
Всё хорошо, под вечер сам мёрджну.
Вдруг кто раньше продискутирует или mergeнёт.

2024-08-09 15:11 UTC, lzk228 commented
![image](https://github.com/user-attachments/assets/51cea919-07a6-46b2-9472-383b41944055)
мне кажется сломанные стены не достаточно сломанные по сравнению с предыдущими

2024-08-11 09:48 UTC, Ko4ergaPunk commented
> ![image](https://private-user-images.githubusercontent.com/124214523/356660524-420199cf-b5d3-4196-9b47-310cc0046fd7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzNjk5MjMsIm5iZiI6MTcyMzM2OTYyMywicGF0aCI6Ii8xMjQyMTQ1MjMvMzU2NjYwNTI0LTQyMDE5OWNmLWI1ZDMtNDE5Ni05YjQ3LTMxMGNjMDA0NmZkNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxMVQwOTQ3MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04OWRiNDM2NzQ0MzM2NGI4N2VjYWQzMTlkODI2YmEyZWQ2OWI4YzE4ZGUwNmI1N2RhNDY5Y2Q3MWE5OGY5YTE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OGl0sfP2dbLSexRrOx0KFCKnQTGbPaozIrWxAfO0ZcA)
> 
> мне кажется сломанные стены не достаточно сломанные по сравнению с предыдущими да и обычные слишком гладкие а именно просто полоска одним цветом, когда предыдущие были более потёртые

Полоску лучше не трогать. Выглядит крайне паршиво, ибо паттерн слишком сильно в глаза бросается

2024-08-11 09:51 UTC, SonicHDC commented
> > ![image](https://private-user-images.githubusercontent.com/124214523/356660524-420199cf-b5d3-4196-9b47-310cc0046fd7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzNjk5MjMsIm5iZiI6MTcyMzM2OTYyMywicGF0aCI6Ii8xMjQyMTQ1MjMvMzU2NjYwNTI0LTQyMDE5OWNmLWI1ZDMtNDE5Ni05YjQ3LTMxMGNjMDA0NmZkNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxMVQwOTQ3MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04OWRiNDM2NzQ0MzM2NGI4N2VjYWQzMTlkODI2YmEyZWQ2OWI4YzE4ZGUwNmI1N2RhNDY5Y2Q3MWE5OGY5YTE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OGl0sfP2dbLSexRrOx0KFCKnQTGbPaozIrWxAfO0ZcA)
> > мне кажется сломанные стены не достаточно сломанные по сравнению с предыдущими да и обычные слишком гладкие а именно просто полоска одним цветом, когда предыдущие были более потёртые
> 
> Полоску лучше не трогать. Выглядит крайне паршиво, ибо паттерн слишком сильно в глаза бросается

Будь проще, сделай сломаный вариант в прототипе стенрк. Хитро и смешно :trollface:

2024-08-14 08:37 UTC, Ko4ergaPunk commented
Добавил черкаши на полоску
![image](https://github.com/user-attachments/assets/19d6609b-869b-4141-91e8-943e96fcde22)
@SonicHDC

2024-08-14 10:25 UTC, merged