RandomResprites 01
space-syndicate/space-station-14 pull request #2473
Opened 2024-08-10 02:06 UTC by xKREKSx

## Описание PR

Микро пак из 2 респрайтов
![image](https://github.com/user-attachments/assets/6a1d8495-2964-43ad-b0c0-694ebef34111)

**Медиа**

![image](https://github.com/user-attachments/assets/38e2a68b-0aab-40c3-8044-b329dedf7b84)
![image](https://github.com/user-attachments/assets/19ed1b91-82f0-4b7b-9605-a7ba5da79fbc)

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: .kreks.
- tweak: Респрайт Синдикота!
- tweak: Респрайт **Экстренной Каталки** и **Дешевой Каталки**!

2024-08-10 05:46 UTC, SonicHDC commented
Каталки жирку набрали, слишком широкие.
Тем более дешёвая. Сделай её дешевле :trollface:

2024-08-12 19:10 UTC, CrimeMoot commented
О да, наконец-то моя туша поместиться на каталку.

2024-09-05 02:23 UTC, CatBackGround commented
Котики зачёт.

2024-09-11 00:06 UTC, fqqf commented
миленько

2024-10-13 12:58 UTC, lzk228 commented
мне белая каталка нравилась прежняя, она тоньше чем респрайт

2024-10-15 00:15 UTC, SonicHDC requested changes
Удали каталки отсюда, ПР для меда и так есть выше.
Сделай респрайт чисто синдикека.

2024-10-16 18:33 UTC, xKREKSx commented
> Удали каталки отсюда, ПР для меда и так есть выше. Сделай респрайт чисто синдикека.

вот бы я знал как откатить коммит

2024-10-16 18:42 UTC, xKREKSx commented
> Удали каталки отсюда, ПР для меда и так есть выше. Сделай респрайт чисто синдикека.

вроде сделал

2024-10-18 07:20 UTC, closed without merging

2024-10-18 07:20 UTC, SonicHDC commented
Короче тут всё сломано, просто сделай новый PR чисто с котиком и всё.