Add TTS name examine
space-syndicate/space-station-14 pull request #2535
Opened 2024-08-29 11:54 UTC by lzk228

добавил кнопочку для осмотра названия ттс
кнопочку не видно если у персонажа нет ттс или скрыта личность
работает с голосовой маской

https://github.com/user-attachments/assets/41d1fe27-3d3f-4df7-a753-071c03d9d994

:cl:
- add: При осмотре персонажа можно будет увидеть название его голоса ТТС.

2024-08-29 12:16 UTC, NotSoDana commented
Ахуеть, почему это только щас добавили

2024-08-29 12:22 UTC, NotSoDana commented
Нихуя себе "нехуй делать". Был бы я женщиной  да я бы тебя всю ночь ублажала

2024-08-29 12:35 UTC, YuiFann commented
> Нихуя себе "нехуй делать". Был бы я женщиной да я бы тебя всю ночь ублажала

для такого женщиной быть не обязательно

2024-08-31 16:28 UTC, Morb0 commented
Нельзя ли метаебить с этим? Чекая изменился ли голос или подобное
И отбели иконку

2024-08-31 16:39 UTC, lzk228 commented
вообще по хорошему нужно проводить чек на открытое лицо, потому что это почти спижзено с флавор текста
такую же тему с закрытым лицом нужно засунуть и туда


> И отбели иконку

уже отбелил в апстриме

2024-08-31 16:39 UTC, NotSoDana commented
> Нельзя ли метаебить с этим? Чекая изменился ли голос или подобное И отбели иконку

Это ведь как раз и противодействует метаёбу голосовой маски. Ибо невзирая на то что ты поставил имя человека, тебе не поверят из-за другого ТТС. Теперь получится сразу узнавать что ставить хотя бы.

2024-08-31 16:44 UTC, Morb0 commented
По хорошему если это нужно только для войс маски, дать просто ей фичу по клику на человека или каким-то другим способом копировать его установленный голос в маску

2024-08-31 16:45 UTC, lzk228 commented
ну это не только для маски, а в целом для "ого у него крутой голос! интересно как он называется"

2024-09-04 06:04 UTC, pxc1984 approved these changes
seems good

2024-09-22 21:11 UTC, ficcialfaint requested changes

2024-09-22 21:11 UTC, ficcialfaint commented on Content.Server/Corvax/TTS/TTSExamineSystem.cs
> +namespace Content.Server.Corvax.TTS
File-scoped namespace

2024-10-30 23:23 UTC, lzk228 commented
пр is derelict так что стоит сюда имплементировать систему из DetailedExamine после решения issue https://github.com/space-wizards/space-station-14/issues/31689

2024-10-30 23:23 UTC, closed without merging