Добавление ещё скрытого описания
space-syndicate/space-station-14 pull request #2544
Opened 2024-08-31 19:37 UTC by Nimfar11

## Описание PR

Добавление скрытого описания для синдикатских модулей боргов, и ящика инструментов турели.

**Медиа**

**Проверки**
- [X] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [X] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [X] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

:cl: Nimfar11
- add: Добавлено скрытое описание для синдикатских модулей боргов и инструментального ящика турели.

2024-08-31 19:40 UTC, lzk228 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/specific/robotics/borg_modules.ftl
> +	.suffix = модуль киборга Мученик
вообще, делать их всех с названием модуль киборга это пиздец какой кринж, ну типа я могу видеть название например модуля клоуна, модуля инструментов, модуля продвинутой медицины, но вот этот модуль, хмммм.... это обычный модуль киборга.
кринж.

2024-08-31 19:42 UTC, Nimfar11 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/specific/robotics/borg_modules.ftl
> +	.suffix = модуль киборга Мученик
Так в этом и дело. Неизвестный и нестандартный модуль боргов.

2024-08-31 19:45 UTC, Nimfar11 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/specific/robotics/borg_modules.ftl
> +	.suffix = модуль киборга Мученик
Всё что может сказать обычный человек, это то что это модуль борга, а для чего и от кого неизвестно.

2024-09-11 17:13 UTC, lzk228 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/specific/robotics/borg_modules.ftl
> +	.suffix = модуль киборга Мученик
@Nimfar11 как альтернативу выше сказаному предлагаю назвать их "кроваво-красный модуль киборга"

2024-09-11 23:14 UTC, Nimfar11 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/specific/robotics/borg_modules.ftl
> +	.suffix = модуль киборга Мученик
сделано

2024-10-30 23:24 UTC, lzk228 commented
морбо

2024-11-18 18:32 UTC, Vonsant commented on Resources/Prototypes/Entities/Objects/Specific/Robotics/borg_modules.yml
> +        components:
Поменяй везде
с:
```
          components:
            - TraitorRole
            - NukeOperative
```
на:
```
          mindRoles:
          - TraitorRole
          - NukeopsRole
```

2024-11-18 18:37 UTC, Vonsant requested changes

2024-11-18 18:37 UTC, Vonsant commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/specific/robotics/borg_modules.ftl
> +    .suffix = модуль киборга с L6C ROW
Лучше в суффиксах оставь просто название оружия.
Ну там, L6C ROW, двухклинковый энергомеч и т.д.

2024-11-19 19:31 UTC, Nimfar11 commented on Resources/Prototypes/Entities/Objects/Specific/Robotics/borg_modules.yml
> +        components:
поправил

2024-11-19 19:31 UTC, Nimfar11 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/specific/robotics/borg_modules.ftl
> +    .suffix = модуль киборга с L6C ROW
также поправил

2024-11-20 19:10 UTC, Vonsant commented
А чо по тулбоксу, его никто не может опознать?

2024-11-21 07:05 UTC, Nimfar11 commented
> А чо по тулбоксу, его никто не может опознать?

Думаю делать чтобы его мог опознать инженер или учёный, перебор. Это скорее чтобы сам предатель не потерялся, так как можно спутать с любым тулбоксом.

2024-11-22 12:15 UTC, Vonsant approved these changes

2024-11-22 12:15 UTC, merged