[Art] Conveyor resprite
space-syndicate/space-station-14 pull request #2565
Opened 2024-09-05 12:41 UTC by Ko4ergaPunk

## Описание PR

стрелочки UwU

**Медиа**

![image](https://github.com/user-attachments/assets/1530f738-2b72-4028-b575-e67a93266c1b)

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:

2024-09-05 12:44 UTC, lzk228 commented
это будет полезно в апстриме

2024-09-05 13:01 UTC, Vonsant commented
А що, угловые поворотные добавили?

2024-09-05 13:34 UTC, xKREKSx commented
лучше с ТГ перенести

2024-09-05 14:21 UTC, Ko4ergaPunk commented
> А що, угловые поворотные добавили?

Не. Они там просто мертвым грузом валяются

2024-09-08 04:00 UTC, SonicHDC commented
> это будет полезно в апстриме

А? Что? Не вижу логики.

2024-09-08 04:04 UTC, SonicHDC requested changes
Нужна демонстрация с локалки. А также объяснение, почему где-то изменены направления, а где-то нет. (Тем более они не используются)

2024-09-08 09:17 UTC, lzk228 commented
> > это будет полезно в апстриме
> 
> А? Что? Не вижу логики.

то что такого рода улучшение со стрелками будет полезно в апстриме 
это ведь не простой респрайт под стиль, это неплохое добавление qol

2024-09-08 10:30 UTC, Ko4ergaPunk commented
> > > это будет полезно в апстриме
> > 
> > 
> > А? Что? Не вижу логики.
> 
> то что такого рода улучшение со стрелками будет полезно в апстриме это ведь не простой респрайт под стиль, это неплохое добавление qol

Кинь им сам

2024-09-08 11:39 UTC, BolloTea commented
https://github.com/space-wizards/space-station-14/pull/31967

2024-09-08 11:39 UTC, BolloTea commented
Пиаром промахнулся по началу

2024-09-11 17:11 UTC, lzk228 commented
вообщем, https://github.com/space-wizards/space-station-14/pull/31967 , возможно с ещё немногими измененями (если запросят), но получит мёрж, поэтому я закрою (ещё раз :trollface:)

2024-11-14 16:29 UTC, Ko4ergaPunk commented
Оффы развыебывались, что выглядит как ТГ. Запрашиваю реревью
@SonicHDC

2024-11-14 16:31 UTC, Ko4ergaPunk commented
> объяснение, почему где-то изменены направления, а где-то нет

Нихуя не понял, но на локалке все работает как надо

2024-11-14 17:20 UTC, xKREKSx commented
лучше с ТГ перенести

2024-11-15 08:06 UTC, Ko4ergaPunk commented
> лучше с ТГ перенести

Угловые конвейеры еще не реализовали, так что тгшные будут выглядеть хуево

2024-11-15 08:32 UTC, Ko4ergaPunk commented
https://github.com/user-attachments/assets/047544af-3127-4724-9c2c-b74a4878871b

2024-11-16 06:24 UTC, SonicHDC approved these changes

2024-11-16 06:26 UTC, merged