Частичный перевод Upstream #2580, остальное в др ПРе
space-syndicate/space-station-14 pull request #2586
Opened 2024-09-12 05:15 UTC by lapatison

## Описание PR

## Почему / Баланс

## Технические детали

## Медиа

## Требования

- [ ] Я прочитал(а) и следую [Рекомендациям по оформлению Pull Request и Changelog](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [ ] Я добавил(а) медиафайлы к этому PR или он не требует демонстрации в игре.

## Критические изменения

**Список изменений**

2024-09-12 05:30 UTC, NotSoDana reviewed
Лень прям досконально смотреть, то что первое глаза намозолило

2024-09-12 05:30 UTC, NotSoDana commented on Resources/Locale/ru-RU/job/job-names.ftl
> +job-name-cburn = Офицер карантинной службы Центком
Агент/Боец/Оперативник РХБЗЗ

2024-09-12 05:30 UTC, NotSoDana commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/mobs/player/silicon.ftl
> +ent-AsimovCircuitBoard = плата с законом (Крюзимов)
тогда уж "плата законов". " плата с законом" ужасно звучит, тем более что он там не в ед. числе

2024-09-12 06:39 UTC, lzk228 commented on Resources/Locale/ru-RU/lathe/lathe-categories.ftl
> +lathe-category-food = Продукты
продукты это не совсем food

2024-09-12 06:39 UTC, lzk228 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/misc/books.ftl
> +    .suffix = Руководство
lowercase

2024-09-17 14:46 UTC, lzk228 requested changes

2024-09-17 14:46 UTC, lzk228 commented on Resources/Locale/ru-RU/mass-media/news-ui.ftl
>  news-write-ui-cancel-text = Отмена
```suggestion
news-write-ui-cancel-text = Очистить
```

2024-09-17 14:47 UTC, lzk228 submitted a review, later dismissed

2024-09-17 14:51 UTC, lzk228 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/doors/airlocks/access.ftl
> +ent-AirlockBarGlassLocked = { AirlockServiceGlassLocked }
```suggestion
ent-AirlockBarGlassLocked = { ent-AirlockServiceGlassLocked }
```

2024-09-17 15:09 UTC, merged