Исправленная резиновая свинья
space-syndicate/space-station-14 pull request #2607
Opened 2024-09-20 08:54 UTC by Moryachok136

## Описание PR
Вторая попытка добавить резиновую свинью с исправлением конфликтов

## Почему / Баланс
Станет еще веселее

## Технические детали
Сделано по образцу https://github.com/space-wizards/space-station-14/pull/29637, но всеми любимая резиновая свинья

## Медиа
![image](https://github.com/user-attachments/assets/569a21bb-ab51-4017-ab69-3f58fe737a8b)
![image](https://github.com/user-attachments/assets/020d2b69-fdb8-4cc5-bd4f-9e95f84a6bb8)

https://github.com/user-attachments/assets/9ee90409-401f-4722-bc80-52b25d40a43e

## Требования

- [X] Я прочитал(а) и следую [Рекомендациям по оформлению Pull Request и Changelog](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] Я добавил(а) медиафайлы к этому PR или он не требует демонстрации в игре.

## Критические изменения

Отсутствуют
**Список изменений**

:cl:
- add: добавлена всеми любимая резиновая свинья!

2024-09-20 09:05 UTC, lzk228 commented
webedit ops + не смог пофиксить легчайшие конфлиеты

2024-09-20 11:25 UTC, Moryachok136 commented
> webedit ops + не смог пофиксить легчайшие конфлиеты

Да кто этот ваш webedit ops
Я абсолютно не в курсе как нормально их фиксить

2024-09-20 11:47 UTC, Moryachok136 commented
> webedit ops + не смог пофиксить легчайшие конфлиеты

По-русски будь добр сказать что не так.

2024-11-03 22:58 UTC, lzk228 commented on Resources/Prototypes/Corvax/Entities/Objects/Fun/toys.yml
> +  parent: BasePlushie
резиновая свинья - не плюшка

2024-11-03 22:59 UTC, lzk228 requested changes

2024-11-03 22:59 UTC, lzk228 commented on Resources/Textures/Corvax/Objects/Fun/toys.rsi/meta.json
> +    {
```suggestion
  "states": [
    {
```

2024-11-03 22:59 UTC, lzk228 commented on Resources/Prototypes/Entities/Markers/Spawners/Random/maintenance.yml
> +       # Corvax-Toys-Start
```suggestion
      # Corvax-Toys-Start
```

2024-11-04 10:37 UTC, lzk228 commented on Resources/Prototypes/Corvax/Entities/Objects/Fun/toys.yml
> +  parent: BasePlushie
@Moryachok136 это ещё не решено

2024-11-13 20:06 UTC, Moryachok136 commented on Resources/Prototypes/Corvax/Entities/Objects/Fun/toys.yml
> +  parent: BasePlushie
И я только сейчас узнал как надо review закрывать :)

2024-11-13 20:38 UTC, lzk228 submitted a review, later dismissed
> Пример взят с принятой у оффов резиновой курицы. Раз приняли, не думаю что это проблема.

не досмотрели https://github.com/space-wizards/space-station-14/issues/33152
фикси

2024-12-14 21:54 UTC, Ko4ergaPunk commented
когда мне дадут уже в жопу свинье потыкать

2024-12-15 17:01 UTC, Moryachok136 commented
> когда мне дадут уже в жопу свинье потыкать

![image](https://github.com/user-attachments/assets/54d00e35-3839-41cd-b3ad-2f39517a6258)

2025-01-24 13:07 UTC, lzk228 commented
https://github.com/space-wizards/space-station-14/pull/34543

2025-01-26 08:41 UTC, Moryachok136 commented
> [space-wizards/space-station-14#34543](https://github.com/space-wizards/space-station-14/pull/34543)

Да, видел. Жду когда мерджнут, чтобы стырить

2025-04-06 01:57 UTC, Vonsant commented
"Я, великий контентмейкер оффов, увижу что у оффов проблема, доложу им, но не буду её исправлять, так как знаю, что её никогда не исправят, и я буду тут такой умный сидеть и говорить, что не будет принято пока оффы не починят у себя".

На данный момент ПР полностью соответствует оффовской системе, резиновая игрушка соответствует по паренту со всеми остальными. Локализацию исправила, аттрибьюшены и комментарии поправлены, принимаю.
Если оффы пофиксят у себя - пофикшу и у нас. Мариновать минорный ПР 6+ месяцев из-за этого це бред.

Так как все поправила и привела в стандарты корвакса - принимаю.

2025-04-06 01:57 UTC, merged