Guidebook tweak
space-syndicate/space-station-14 pull request #2676
Opened 2024-10-15 10:34 UTC by NotSoDana

Вырезал то, что перевёл уже как пару месяцев назад. Хз почему оно здесь

2024-10-15 10:38 UTC, lzk228 commented on Resources/ServerInfo/Guidebook/Engineering/Singularity.xml
> -  </Box>
а это поч вырезал

2024-10-15 12:40 UTC, NotSoDana commented on Resources/ServerInfo/Guidebook/Engineering/Singularity.xml
> -  </Box>
а нахуя он тут нужен в части с катушками

2024-10-22 16:56 UTC, lzk228 requested changes
пересмотри что в оригинальном гайдбуке и поправь чтобы они соответсвовали друг другу

2025-02-06 18:26 UTC, NotSoDana commented
мне лень

2025-02-06 18:26 UTC, closed without merging