added station goal system
space-syndicate/space-station-14 pull request #268
Opened 2022-06-20 00:31 UTC by arazdelkin

added station goal system

2022-06-20 01:43 UTC, Morb0 requested changes

2022-06-20 01:43 UTC, Morb0 commented on Content.Server/StationGoal/StationGoalCommand.cs
> +        public string Description => "Send station goal papers codes to the communication console";
Неточности
```suggestion
        public string Description => "Send station goal paper to communication consoles";
```

2022-06-20 01:43 UTC, Morb0 commented on Content.Server/StationGoal/StationGoalCommand.cs
> +        public string Help => "setstationgoal";
Нужно отразить в подсказе команды о том, что она принимает обязательный параметр.
```suggestion
        public string Help => "setstationgoal <id>";
```

2022-06-20 01:43 UTC, Morb0 commented on Content.Server/StationGoal/StationGoalPrototype.cs
> +        [DataField("name")] public string Name { get; set; } = string.Empty;
Точнее будет назвать это `text`, так как встраивается в `Content` листка, хоть и проходит локализацию.

2022-06-20 01:43 UTC, Morb0 commented on Content.Server/StationGoal/StationGoalComponent.cs
> +    public class StationGoalComponent : Component
Кажется он нигде не используется.

2022-06-20 01:43 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/misc/paper.ftl
> +ent-StationGoalPaper = Сообщение ЦК о текущей цели станции
Все названия предметов в локализации с маленький буквы.

2022-06-20 01:43 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/misc/paper.ftl
> +ent-StationGoalPaper = Сообщение ЦК о текущей цели станции
Нужно создать аналог английской версии (иначе она создастся сама когда я буду делать обновление).

2022-06-20 01:43 UTC, Morb0 commented on Resources/Locale/ru-RU/station-goal/station-goal-component.ftl
> +station-goal-singularity=Цель вашей смены построить дополнительный генератор основанный на Сингулярности. Чтобы ее выполнить инженерному отделу понадобится построить сдерживающее поле для Сингулярнос
Так же нужен английский аналог.

2022-06-20 01:43 UTC, Morb0 commented on Content.Server/StationGoal/StationGoalSystem.cs
> +            var random = IoCManager.Resolve<IRobustRandom>();
Возможно стоит вынести как `[Dependency]` в начало класса, что бы лишний раз не резолвить.

2022-06-20 01:43 UTC, Morb0 commented on Content.Server/StationGoal/StationGoalSystem.cs
> +            var goal = availableGoals.ElementAt(goalIndex);
Можно просто через `Pick`
```suggestion
            var goal = random.Pick(goals.ToList());
```

2022-06-28 19:11 UTC, arazdelkin commented on Content.Server/StationGoal/StationGoalCommand.cs
> +        public string Description => "Send station goal papers codes to the communication console";
А почему console а не consoles? Там же foreach по всем консолям.

2022-07-01 13:47 UTC, Morb0 requested changes

2022-07-01 13:47 UTC, Morb0 commented on Resources/Locale/en-US/ss14-ru/prototypes/entities/objects/misc/paper.ftl
> +ent-StationGoalPaper = CentCom station goal message
И в английской тоже с маленькой начинаются названия, поэтому просто `centcom`

2022-07-01 13:47 UTC, Morb0 commented on Content.Server/StationGoal/StationGoalSystem.cs
> +            // var goal = availableGoals.ElementAt(goalIndex);
Лучше удалить код, а не оставлять закомментированным.

2022-07-01 14:07 UTC, arazdelkin commented on Resources/Locale/en-US/ss14-ru/prototypes/entities/objects/misc/paper.ftl
> +ent-StationGoalPaper = CentCom station goal message
Написание взял из того же файла 
ent-RubberStampCentcom = CentCom rubber stamp

2022-07-03 11:20 UTC, Morb0 requested changes

2022-07-03 11:20 UTC, Morb0 commented on Resources/Prototypes/Corvax/Entities/Objects/Misc/paper.yml
> +  desc:
Это можно убрать.

2022-07-03 11:20 UTC, Morb0 commented on Resources/Prototypes/Corvax/Entities/Objects/Misc/paper.yml
> +  components:
Нужно добавить еще печать Centcom на листок.

2022-07-03 11:20 UTC, Morb0 commented on Resources/Prototypes/Entities/Objects/Misc/paper.yml
>  - type: entity
Так как в этом файле ничего не изменяется, лучше вернуть его к оригиналу, что бы не было никаких изменений.

2022-07-20 19:51 UTC, Morb0 approved these changes

2022-07-21 11:46 UTC, merged