Add "shortest" ghost raffle and change xeno
space-syndicate/space-station-14 pull request #2687
Opened 2024-10-17 06:37 UTC by Ko4ergaPunk

## Описание PR

Добавил "shortest" рафл. Это нужно для ксено, чтобы людям не приходилось ждать 30 секунд для игры на презренном Бурильщике. В целом на Ксено не похуй только на Пилигриме, но есть нюанс. Их убивают еще до того, как госты успеют взять роли, а для них как бы оно и создавалось. 

Теперь чтобы взять ксено нужно ждать 5 секунд в лотерее вместо 30-ти. 

## Требования

- [x] Я прочитал(а) и следую [Рекомендациям по оформлению Pull Request и Changelog](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] Я добавил(а) медиафайлы к этому PR или он не требует демонстрации в игре.

## Критические изменения

**Список изменений**

:cl: Ko4erga
- tweak: Время лотереи для ксено уменьшено с 30 до 5 секунд.

2024-10-17 07:21 UTC, lzk228 commented
а возможно как-то изменить это на пилигриме без вторжения в существующие прототипы?

2024-10-17 08:17 UTC, YuiFann commented
> а возможно как-то изменить это на пилигриме без вторжения в существующие прототипы?

возможно, надо просто удалить эту залупу

2024-10-17 14:29 UTC, Ko4ergaPunk commented
> а возможно как-то изменить это на пилигриме без вторжения в существующие прототипы?

Неа. У меня дыра на периодических спавнерах работает, а не обычных

2024-10-17 15:15 UTC, Vonsant commented
> > а возможно как-то изменить это на пилигриме без вторжения в существующие прототипы?
> 
> Неа. У меня дыра на периодических спавнерах работает, а не обычных. Да и рафл нужен короче, а не шорт на 15 секунд

Звучит как диагноз проктолога.

2024-10-19 02:19 UTC, Ko4ergaPunk commented
@lzk228 
![2506133_15c6f](https://github.com/user-attachments/assets/651443c0-ca12-4482-9a1e-a33fde0b0665)

2024-10-20 09:11 UTC, Vonsant commented
@Ko4ergaPunk обычно корваксовские прототипы пихаются в папку Corvax, по тому же маршруту что и оригинал. Типа:
Resources/Prototypes/Corvax/GhostRoleRaffles/settings.yml

2024-10-30 23:34 UTC, lzk228 reviewed
я предлагаю (насколько это хуёвым не было бы, ведь само присутсвие ксено на мапе это залупа) сделать отдельный прототип ксено для пильгрима

2024-11-07 04:50 UTC, Morb0 requested changes

2024-11-07 04:50 UTC, Morb0 commented on Resources/Prototypes/GhostRoleRaffles/settings.yml
> +# Corvax-end
Должно быть в `Prototypes/Corvax/GhostRoleRaffles/settings.yml`

2024-12-10 10:36 UTC, Ko4ergaPunk commented
![merge](https://github.com/user-attachments/assets/a8a4a3d8-040c-48be-bf81-89cbfd651933)

2024-12-10 10:59 UTC, lzk228 requested changes
лучше не менять текущих ксено, потом будет боль дырка задница
лучше новых ксено создай с кратчайшим таймером

2024-12-10 11:03 UTC, Ko4ergaPunk commented
ахуй

2025-01-12 07:59 UTC, closed without merging

2025-01-12 08:02 UTC, cfif126 commented
Эээ куда