Update CODEOWNERS
space-syndicate/space-station-14 pull request #2721
Opened 2024-10-30 20:57 UTC by AwareFoxy

## Описание PR
Добавил Кочергу для ревью карт

## Почему / Баланс
Пусть работает :trollface:

## Технические детали

## Медиа

## Требования

- [x] Я прочитал(а) и следую [Рекомендациям по оформлению Pull Request и Changelog](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] Я добавил(а) медиафайлы к этому PR или он не требует демонстрации в игре.

## Критические изменения

**Список изменений**
no cl no fun

2024-10-30 20:58 UTC, Vonsant commented
**Resources/Prototypes/Maps** попадает туда?

2024-10-30 21:00 UTC, AwareFoxy commented
> **Resources/Prototypes/Maps** попадает туда?

да

2024-10-30 21:01 UTC, AwareFoxy commented
@lzk228 pls speedmerg

2024-10-30 23:19 UTC, lzk228 commented
оставлю это для морти

2024-11-07 04:47 UTC, Morb0 requested changes

2024-11-07 04:47 UTC, Morb0 commented on .github/CODEOWNERS
> +**/Maps/** @Ko4ergaPunk
```suggestion
# Map files
/Resources/Prototypes/Maps/** @Ko4ergaPunk 
/Resources/Maps/** @Ko4ergaPunk 
```

2024-11-07 04:48 UTC, merged

2024-11-07 12:48 UTC, Ko4ergaPunk commented
А зарплата в отсосоинах где моя

2024-11-07 12:55 UTC, cfif126 commented
> А зарплата в отсосоинах где моя

Могу предоставить