Add Ai announcements sound
space-syndicate/space-station-14 pull request #2742
Opened 2024-11-06 17:31 UTC by Zekins3366

## Описание PR
Соответственно добавляет звук оповещению от уведомлений станционного ИИ.
Звук взят из сборки TauSeti, в принципе как и другие звуки используемые в русском дубляже у нас.
Все естественно для улучшения игровой атмосферы добавлением этой мелочи.
Вот и все.

## Почему / Баланс
- **Одно и самое важное, почему нет? Так звучит лучше и приятнее уху.**

## Технические детали
Простое изменение части компонента CommunicationsConsole для ИИ.
Строчка `global: true # Corvax-Announcements` это ебаный щиткод, потому что без нее звук не работает .

**Список изменений**
:cl:
- add: Добавлен звук уведомления для станционного ИИ

2024-11-06 18:38 UTC, Zekins3366 commented
> не Tau**S**eti , а Tau **C**eti

Я знаю как оно пишется, просто чекни лицензию в директории звука

2024-11-06 19:11 UTC, Zekins3366 commented
> > > не Tau**S**eti , а Tau **C**eti
> > 
> > 
> > Я знаю как оно пишется, просто чекни лицензию в директории звука
> 
> Лицензию ты не закомиттил . Поправь название и в описании.

Не

2024-11-18 16:25 UTC, Vonsant requested changes
Мержи пофикси.

2024-11-23 16:18 UTC, Vonsant commented
@Zekins3366 уэээээээ

2024-11-25 10:00 UTC, Zekins3366 commented
@Vonsant Это было сложно

2025-01-02 19:35 UTC, Vonsant approved these changes

2025-01-02 19:37 UTC, merged