Remove MLGBTSQL- & adds new Corvax stuff
space-syndicate/space-station-14 pull request #2766
Opened 2024-11-11 22:48 UTC by Ko4ergaPunk

## Описание PR

[Удалена LGBTQ+атрибутика по результатам опросника](https://discord.com/channels/919301044784226385/1084254414388347001/1253641376533581824)
![image](https://github.com/user-attachments/assets/1cf7878f-c640-4a47-b9a6-c9bed807e00c)

Удалено:
- LGBTQFlag
- LGBTQHandyFlag
- ClothingNeckCloakAce
- ClothingNeckCloakAro
- ClothingNeckCloakBi
- ClothingNeckCloakIntersex
- ClothingNeckCloakLesbian
- ClothingNeckCloakGay
- ClothingNeckCloakEnby
- ClothingNeckCloakPan
- ClothingNeckCloakTrans
- ClothingNeckLGBTPin
- ClothingNeckAsexualPin
- ClothingNeckAromanticPin
- ClothingNeckBisexualPin
- ClothingNeckIntersexPin
- ClothingNeckLesbianPin
- ClothingNeckGayPin
- ClothingNeckNonBinaryPin
- ClothingNeckPansexualPin
- ClothingNeckTransPin

Добавлено:
- RainbowFlag
- RainbowHandyFlag
- ClothingNeckCloakPilot
- ClothingNeckCloakWerewolf
- ClothingNeckCloakPoison
- ClothingNeckCloakCyclope
- ClothingNeckCloakPoet
- ClothingNeckCloakMarketing
- ClothingNeckCloakProspector
- ClothingNeckCloakChief
- ClothingNeckCloakVampire
- ClothingNeckRainbowPin
- ClothingNeckPilotPin
- ClothingNeckWerewolfPin
- ClothingNeckPoisonPin
- ClothingNeckCyclopePin
- ClothingNeckPoetPin
- ClothingNeckMarketingPin
- ClothingNeckProspectorPin
- ClothingNeckChiefPin
- ClothingNeckVampirePin

## Почему / Баланс

- Игра про 2д космонавтиков не место для пропагандирования своей сексуальной ориентации.
- Большинству игроков, исходя из результатов опросника, не нравится наличие подобной атрибутики в игре.
- Нарушение КоАП РФ.

## Медиа

![image](https://github.com/user-attachments/assets/d3f5969b-3682-40ec-a1d4-85c81ba416c5)

## Требования

- [x] Я прочитал(а) и следую [Рекомендациям по оформлению Pull Request и Changelog](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] Я добавил(а) медиафайлы к этому PR или он не требует демонстрации в игре.

## Критические изменения

Я съел сухарики с чесноком.

**Список изменений**

:cl: Ko4erga
- add: Добавлено 9 плащей, 10 значков, флаг с радугой и настенный флаг с радугой!
- remove: Удалена LGBTQ+ атрибутика!

2024-11-11 22:52 UTC, lzk228 commented
я бы оставил названия пинов такими какие они щас и есть, хочу выражать персонажа нагрудным значком а не значком поэта

2024-11-11 22:53 UTC, Ko4ergaPunk commented
> такими какие они щас и есть

хз о чем ты

2024-11-11 22:56 UTC, lzk228 commented
> > такими какие они щас и есть
> 
> хз о чем ты

оставить для всех "нагрудный значок"

2024-11-11 23:00 UTC, Ko4ergaPunk commented
> > > такими какие они щас и есть
> > 
> > 
> > хз о чем ты
> 
> оставить для всех "нагрудный значок"

Неуважение к лору придуманных мной значков, но ладно. Изменил

2024-11-11 23:03 UTC, Vonsant commented
![image](https://github.com/user-attachments/assets/1cc03cff-9eb1-41ad-823f-88173719c72f)
Ну не, это буллшит. Переделывай в фтлки.

2024-11-11 23:04 UTC, Vonsant requested changes
Все названия и дескрипшены перенести в локали.

2024-11-11 23:06 UTC, p0etus commented
Кочерга подставу оформил, я из-за него на лазика низачто наехал. Закрывайте ПР, автор мудло.

2024-11-11 23:07 UTC, Ko4ergaPunk commented
> Все названия и дескрипшены перенести в локали.

да пипец блин хватит душить авторский контент!!

2024-11-11 23:15 UTC, Vonsant commented
![image](https://github.com/user-attachments/assets/62ce5ae3-f74b-4d55-9aa2-551c0d89d124)
У трансов удалён, а остальные закомментированы. Ты шо буйный.

2024-11-11 23:19 UTC, Vonsant commented
И закрою конверсы чтобы с утра не наблюдать такой картины:
![image](https://github.com/user-attachments/assets/bff3dbc6-20c6-4723-9c63-26973c3038c7)

2024-11-11 23:20 UTC, Ko4ergaPunk commented
> ![image](https://private-user-images.githubusercontent.com/118206719/385085020-62ce5ae3-f74b-4d55-9aa2-551c0d89d124.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzNjc0ODcsIm5iZiI6MTczMTM2NzE4NywicGF0aCI6Ii8xMTgyMDY3MTkvMzg1MDg1MDIwLTYyY2U1YWUzLWY3NGItNGQ1NS05YWEyLTU1MWMwZDg5ZDEyNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMVQyMzE5NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYzA5NzYyYjZiZWFiYmZmNjU4N2U0MzQxYTVhOTgyZTBhZDUwZTIzMjY4MTQwM2NjNDhjOTU5NDEzZDUwOTFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.otY-ZT9ReO70GvIkQwCs_QFsLLo686ai15S4KwqlAI0) У трансов удалён, а остальные закомментированы. Ты шо буйный.

Не, прост сдвинул чтоб с комментами не ебаться

2024-11-12 00:25 UTC, Vonsant commented
Конверса разблокирована для сбора фидбека.

2024-11-12 00:27 UTC, YuiFann commented
мне не нравится, закрывайте

2024-11-12 00:36 UTC, AwareFoxy commented
ого нельзя же просто изменить названия и не трогать прототипы
это же потом будет так удобно всё мерджить

2024-11-12 00:50 UTC, Ko4ergaPunk commented
> ого нельзя же просто изменить названия и не трогать прототипы это же потом будет так удобно всё мерджить

Низя. Это вАнИлЬнАя сборка

2024-11-12 00:52 UTC, Ko4ergaPunk commented
> > ого нельзя же просто изменить названия и не трогать прототипы это же потом будет так удобно всё мерджить
> 
> Низя. Это вАнИлЬнАя сборка

Ну и еще эти плащи никакого отношения к удаленным не имеют, да.

2024-11-12 01:21 UTC, mhamsterr commented
> > > ого нельзя же просто изменить названия и не трогать прототипы это же потом будет так удобно всё мерджить
> 
> > 
> 
> > Низя. Это вАнИлЬнАя сборка
> 
> 
> 
> Ну и еще эти плащи никакого отношения к удаленным не имеют, да.

Может тогда стоит прописать миграции на случай если кто-то решит добавить оригинальные версии на какие-то карты?

2024-11-12 01:25 UTC, mhamsterr commented
Имо, лучше бы действительно просто локализацию поменял, чем вот этим всем заниматься

![image](https://github.com/user-attachments/assets/a60e5b07-3e28-4f28-9878-0133f1f7f000)

2024-11-12 08:36 UTC, Hemomancer commented
Почему значёк вампира, тоже плащ ?

2024-11-12 08:49 UTC, Meguneri commented
Ты пины с аутизмом закомментил ещё...Не надо, они мне нравятся

2024-11-14 11:47 UTC, Ko4ergaPunk commented
Никакого голосования не было это миф

2024-11-14 11:49 UTC, Vonsant commented
А я пожалуй вмержу.

2024-11-14 11:50 UTC, Vonsant commented
![O9ol_9](https://github.com/user-attachments/assets/8e28abdb-ebbb-4fbd-9ddc-35e3ca859543)

2024-11-14 11:53 UTC, Ko4ergaPunk commented
А ну кышь

2024-11-14 11:53 UTC, closed without merging

2024-11-14 11:54 UTC, Vonsant commented
![image](https://github.com/user-attachments/assets/77dc1e36-20b4-41d3-8548-635bc47c059d)

2024-11-14 13:38 UTC, Hemomancer commented
Кочерга - это шизофрения.

2024-11-14 16:49 UTC, Ko4ergaPunk commented
> у него в отделе 41% фембоев

Вот это бля не шутка даже