Перевод  Upstream #2785
space-syndicate/space-station-14 pull request #2797
Opened 2024-11-21 22:06 UTC by lapatison

## Описание PR

## Почему / Баланс

## Технические детали

## Медиа

## Требования

- [ ] Я прочитал(а) и следую [Рекомендациям по оформлению Pull Request и Changelog](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [ ] Я добавил(а) медиафайлы к этому PR или он не требует демонстрации в игре.

## Критические изменения

**Список изменений**

2024-11-21 23:16 UTC, cfif126 commented on Resources/Locale/ru-RU/borg/borg.ftl
> +borg-type-generic-name = Обычное
```suggestion
borg-type-generic-name = Обычный
```

2024-11-21 23:20 UTC, cfif126 commented on Resources/Locale/ru-RU/borg/borg.ftl
> +borg-type-generic-name = Обычное
Или обыкновенный/стандартный

2024-11-21 23:24 UTC, cfif126 commented on Resources/Locale/ru-RU/borg/borg.ftl
> +borg-type-generic-desc = Может всё, но одинаково не очень хорошо. Выполняйте различные случайные поручения на станции, или, быть может, окажите помощь научному отделу, который вас построил.
```suggestion
borg-type-generic-desc = Хорош во многом, но ни в чем не мастер. Выполняйте различные поручения на станции или даже окажите помощь научному отделу, который вас построил.
```

2024-11-21 23:37 UTC, lzk228 commented on Resources/Locale/ru-RU/borg/borg.ftl
>  borg-type-generic-transponder = generic cyborg
?

2024-11-21 23:37 UTC, lzk228 commented on Resources/Locale/ru-RU/borg/borg.ftl
> +borg-type-engineering-desc = Помогите команде инженеров в строительстве станции, ликвидации повреждений или устранении проблем с электричеством и атмосферой.
```suggestion
borg-type-engineering-desc = Помогайте команде инженеров в строительстве станции, ликвидации повреждений или исправлении проблем с электричеством и атмосферой.
```
"помогайте" звучит лучше, остальное просто как предложение

2024-11-21 23:37 UTC, lzk228 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/mobs/cyborgs/borg_chassis.ftl
> +    .desc = { ent-BorgChassisSelectable.desc }
а не "Тип выбран"?

2024-11-21 23:37 UTC, lzk228 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/power/lights.ftl
> +ent-DimLightBulb = тусклая лампочка
в названии лампа поставь

2024-11-21 23:37 UTC, lzk228 commented on Resources/Locale/ru-RU/store/spellbook-catalog.ftl
>  spellbook-event-summon-ghosts-description = Who ya gonna call?
это отсылка на гостбастеров?

2024-11-21 23:39 UTC, lapatison commented on Resources/Locale/ru-RU/store/spellbook-catalog.ftl
>  spellbook-event-summon-ghosts-description = Who ya gonna call?
Да

2024-11-21 23:40 UTC, lapatison commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/mobs/cyborgs/borg_chassis.ftl
> +    .desc = { ent-BorgChassisSelectable.desc }
А разница? + суффикс

2024-11-21 23:43 UTC, lzk228 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/mobs/cyborgs/borg_chassis.ftl
> +    .desc = { ent-BorgChassisSelectable.desc }
Выбранный тип и Тип выбран это же вообще два разных понятия

2024-11-22 00:20 UTC, cfif126 requested changes
Мой первый раз в гитхабе, перевод может содержать художественную отсебятину. Оставить или нет, решать вам.

2024-11-22 00:20 UTC, cfif126 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/consumable/food/meat.ftl
> +ent-FoodMeatAnomaly = масса аномального мяса
```suggestion
ent-FoodMeatAnomaly = брусок аномального мяса
```

2024-11-22 00:20 UTC, cfif126 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/consumable/food/meat.ftl
> +    .desc = Гигантская масса приготовленного мяса. Блюдо для вечеринки или для тех, кто по-настоящему голоден.
```suggestion
    .desc = Гигантская масса приготовленного мяса. Закуска для вечеринки или для САМЫХ голодных.
```

2024-11-22 00:20 UTC, cfif126 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/magic/event_spells.ftl
> +    .desc = АК-47 для всех! Размещает перед каждым случайное огнестрельное оружие.
```suggestion
    .desc = АК-47 для всех! Раздаёт каждому случайное огнестрельное оружие.
```

2024-11-22 00:20 UTC, cfif126 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/magic/event_spells.ftl
> +    .desc = Размещает перед каждым случайный магический предмет. Что может пойти не так?
```suggestion
    .desc = Раздаёт каждому случайный магический предмет. Что может пойти не так?
```

2024-11-22 00:20 UTC, cfif126 commented on Resources/Locale/ru-RU/store/spellbook-catalog.ftl
> +spellbook-ethereal-jaunt-name = Эфирная прогулка
```suggestion
spellbook-ethereal-jaunt-name = Эфирный прыжок
```
Можно магический прыжок

2024-11-22 00:20 UTC, cfif126 commented on Resources/Locale/ru-RU/store/spellbook-catalog.ftl
> +spellbook-ethereal-jaunt-description = Перейдите на Эфирный план чтобы ускользнуть от врагов!
```suggestion
spellbook-ethereal-jaunt-description = Растворитесь в эфире, чтобы ускользнуть от врагов!
```

2024-11-22 00:20 UTC, cfif126 commented on Resources/Locale/ru-RU/store/spellbook-catalog.ftl
> +spellbook-event-summon-guns-description = АК-47 для всех! Размещает перед каждым случайное огнестрельное оружие. Отключает возврат средств при покупке!
```suggestion
spellbook-event-summon-guns-description = АК-47 для всех! Раздаёт всем случайное огнестрельное оружие. Отключает возврат средств при покупке!
```

2024-11-22 00:20 UTC, cfif126 commented on Resources/Locale/ru-RU/store/spellbook-catalog.ftl
> +spellbook-event-summon-magic-description = Размещает перед каждым случайный магический предмет. Что может пойти не так? Отключает возврат средств при покупке!
```suggestion
spellbook-event-summon-magic-description = Раздаёт каждому случайный магический предмет. Что может пойти не так? Отключает возврат средств при покупке!
```

2024-11-22 00:20 UTC, cfif126 commented on Resources/Locale/ru-RU/store/spellbook-catalog.ftl
> +spellbook-upgrade-jaunt-name = Улучшение Эфирной прогулки
```suggestion
spellbook-upgrade-jaunt-name = книга улучшения Эфирного прыжка
```

2024-11-22 00:20 UTC, cfif126 commented on Resources/Locale/ru-RU/store/spellbook-catalog.ftl
> +spellbook-upgrade-jaunt-description = Позволяет улучшить Эфирную прогулку до максимального 3-го уровня!
```suggestion
spellbook-upgrade-jaunt-description = Позволяет улучшить Эфирный прыжок до максимального 3-го уровня!
```

2024-11-22 00:27 UTC, cfif126 commented on Resources/Locale/ru-RU/borg/borg.ftl
> +borg-type-mining-name = Утилизаторский
На вики кстати, шахтёр @lapatison

2024-11-22 00:39 UTC, lapatison commented on Resources/Locale/ru-RU/borg/borg.ftl
> +borg-type-engineering-name = Инженерное
Это и далее используется только в меню выбора и не имеет особого значения, были внесены иные изменения

2024-11-22 10:11 UTC, lzk228 approved these changes

2024-11-22 12:11 UTC, merged