Separated walls variants
space-syndicate/space-station-14 pull request #2819
Opened 2024-11-30 11:41 UTC by SonicHDC

## Описание PR

Все стены(многие) теперь соединяются между собой.
Добавлены не соединяемые варианты стен.
## Почему / Баланс

Для маппинга это хорошо смотрится, а также мы не оффы и у нас нет дыр.
## Технические детали

Созданы варианты separate для walls.yml
## Медиа

Скоро...
## Требования

- [x] Я прочитал(а) и следую [Рекомендациям по оформлению Pull Request и Changelog](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [ ] Я добавил(а) медиафайлы к этому PR или он не требует демонстрации в игре.

## Критические изменения

Теперь все старые строения и карты оффов имеют скреплённые стены.
**Список изменений**

2024-11-30 11:57 UTC, lzk228 commented
> у нас нет дыр

каких дыр?

2024-11-30 12:24 UTC, SonicHDC commented
Просто описание smoothа у стен.
Потом допилю нормаль и картинку кину.

2024-12-09 07:46 UTC, SonicHDC commented
@Ko4ergaPunk дай честную ревью для мапперства и (не)мёрджни.
:3

2024-12-09 08:40 UTC, lzk228 requested changes
не трогать оригинальные файлы, ты же можешь сделать просто наоборот всё

2024-12-09 08:41 UTC, lzk228 commented
плюс не вижу смысла не закинуть это в апстрим

2024-12-09 08:44 UTC, SonicHDC commented
Ъуъуъуъуъ

2024-12-09 08:44 UTC, closed without merging

2024-12-09 08:49 UTC, lzk228 commented
ойойойойойойо1ой
ойойойойойойойойойойой