New Year Music
space-syndicate/space-station-14 pull request #2829
Opened 2024-12-04 19:29 UTC by AwareFoxy

# НЕ МЕРДЖИТЬ ДО 10 ДЕКАБРЯ

## Описание PR
Добавил новогоднюю музыку в лобби, закинул сюда по просьбе @ksen0morph 

## Почему / Баланс
Настроние новогоднее :sunglasses:

## Технические детали

## Медиа

## Критические изменения

**Список изменений**
:cl:
- add: В лобби добавлена новогодняя музыка!

2024-12-04 19:40 UTC, cfif126 commented
почему не мерджить до 10?

2024-12-04 19:42 UTC, AwareFoxy commented
> почему не мерджить до 10?

По просьбе ксеноморфа, я думаю из за конкурса и новогодних артов

2024-12-04 23:34 UTC, lzk228 reviewed
я бы сделал новый soundCollection и заменил его в
https://github.com/space-syndicate/space-station-14/blob/890294335022b5bcd5d99d0430a411477026324c/Content.Server/Audio/ContentAudioSystem.cs#L17

2024-12-05 17:41 UTC, AwareFoxy commented on Resources/Audio/Corvax/Lobby/NewYear/attributions.yml
> +  source: "https://studio.youtube.com/"
```suggestion
  source: "https://youtu.be/QGJEGeAtH_8?si=_IhSce8rEzoPEkaC"
```

2024-12-05 17:42 UTC, AwareFoxy commented on Resources/Audio/Corvax/Lobby/NewYear/attributions.yml
> +  source: "https://studio.youtube.com/"
```suggestion
  source: "https://youtu.be/OEMFw6gB_ag"
```

2024-12-05 17:43 UTC, lzk228 commented
да и вообще, я бы просто добавил их в текущий пул, потому что только 5 песен это слишком мало и быстро надоест

2024-12-05 22:51 UTC, AwareFoxy commented
Тесты not relevant to PR, жду перезапуск билда

2024-12-12 12:26 UTC, cfif126 commented
пора

2024-12-12 12:34 UTC, lzk228 requested changes
не нужно убирать старые, 5 песен быстро надоест слушать

2024-12-12 23:46 UTC, AwareFoxy commented on Resources/Prototypes/SoundCollections/lobby.yml
> +    # - /Audio/Corvax/Lobby/service.ogg # Corvax-LobbyMusic # Corvax-NewYearMusic
```suggestion
    - /Audio/Lobby/thunderdome.ogg 
    - /Audio/Lobby/absconditus.ogg 
    - /Audio/Lobby/space_asshole.ogg 
    - /Audio/Lobby/endless_space.ogg 
    - /Audio/Lobby/singuloose.ogg 
    - /Audio/Lobby/comet_haley.ogg 
    - /Audio/Lobby/title2.ogg 
    - /Audio/Lobby/title3.ogg 
    - /Audio/Lobby/mod.flip-flap.ogg 
    - /Audio/Lobby/Spac_Stac.ogg 
    - /Audio/Lobby/pwmur.ogg 
    - /Audio/Lobby/lasers_rip_apart_the_bulkhead.ogg 
    - /Audio/Lobby/every_light_is_blinking_at_once.ogg 
    - /Audio/Corvax/Lobby/title2.ogg # Corvax-LobbyMusic 
    - /Audio/Lobby/atomicamnesiammx.ogg 
    - /Audio/Corvax/Lobby/service.ogg # Corvax-LobbyMusic
```

2024-12-12 23:47 UTC, AwareFoxy commented on Resources/Prototypes/SoundCollections/lobby.yml
> +    - /Audio/Lobby/atomicamnesiammx.ogg
```suggestion
    - /Audio/Lobby/thunderdome.ogg
    - /Audio/Lobby/absconditus.ogg
    - /Audio/Lobby/space_asshole.ogg
    - /Audio/Lobby/endless_space.ogg
    - /Audio/Lobby/singuloose.ogg
    - /Audio/Lobby/comet_haley.ogg
    - /Audio/Lobby/title2.ogg
    - /Audio/Lobby/title3.ogg
    - /Audio/Lobby/mod.flip-flap.ogg
    - /Audio/Lobby/Spac_Stac.ogg
    - /Audio/Lobby/pwmur.ogg
    - /Audio/Lobby/lasers_rip_apart_the_bulkhead.ogg
    - /Audio/Lobby/every_light_is_blinking_at_once.ogg
    - /Audio/Corvax/Lobby/title2.ogg # Corvax-LobbyMusic
    - /Audio/Lobby/atomicamnesiammx.ogg
```

2024-12-16 06:03 UTC, lzk228 approved these changes

2024-12-16 12:41 UTC, merged