Перевод Upstream #2830
space-syndicate/space-station-14 pull request #2836
Opened 2024-12-08 22:16 UTC by lapatison

## Описание PR

## Почему / Баланс

## Технические детали

## Медиа

## Требования

- [ ] Я прочитал(а) и следую [Рекомендациям по оформлению Pull Request и Changelog](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [ ] Я добавил(а) медиафайлы к этому PR или он не требует демонстрации в игре.

## Критические изменения

**Список изменений**

2024-12-08 22:54 UTC, NotSoDana commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/wallmounts/signs/posters.ftl
> +    .desc = Постер давно забытого фильма. В нём рассказывается о группе упорных салаг из сектора Грасхоппер, или Кузнечик, которые противостоят атакам печально известных Ядерных Оперативников. Слоган
```suggestion
    .desc = Постер давно забытого фильма. В нём рассказывается о группе упорных салаг из сектора Грасхоппер, или Кузнечик, которые противостоят атакам печально известных Ядерных Оперативников. Слоган гласит: «Атаки оперативников будут продолжаться, пока робастность не повысится».
```
Масло масляное. Либо "Атаки оперативников" либо "Ядерные операции"

2024-12-08 23:51 UTC, lzk228 requested changes

2024-12-08 23:51 UTC, lzk228 commented on Resources/Locale/ru-RU/construction/ui/construction-menu.ftl
> +construction-menu-grid-view = Показать сетку
это переключает режим отображения со списка в сетку в меню крафта, так что по другому назвать бы как-то

2024-12-08 23:51 UTC, lzk228 commented on Resources/Locale/ru-RU/fire-extinguisher/fire-extinguisher-component.ftl
> +fire-extinguisher-component-safety-on-message = Предохранитель включен.
```suggestion
fire-extinguisher-component-safety-on-message = Предохранитель включён.
```

2024-12-08 23:51 UTC, lzk228 commented on Resources/Locale/ru-RU/ghost/roles/ghost-role-component.ftl
> +ghost-role-information-loneop-rules = Вы [color=red][bold]Соло-антагонист[/bold][/color]. Помощь агентов на станции не гарантируется.
может всё таки "одиночный"?

2024-12-08 23:51 UTC, lzk228 commented on Resources/Locale/ru-RU/singularity/components/generator-component.ftl
> +comp-generator-failsafe-disabled = Что-то внутри { $target }...
```suggestion
comp-generator-failsafe-disabled = Что-то шипит внутри { $target }...
```

2024-12-08 23:51 UTC, lzk228 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/catalog/fills/crates/armory.ftl
> +    .desc = Содержит два комплекта бронежилетов, шлемов, щитов и дробовиков "Силовик", заряженных травматическими патронами. Дополнительные боеприпасы входят в комплект. Чтобы открыть необходим урове
```suggestion
    .desc = Содержит два комплекта противоударной брони, шлемов, щитов и дробовиков "Силовик", заряженных травматическими патронами. Дополнительные боеприпасы входят в комплект. Чтобы открыть необходим уровень доступа Оружейная.
```

2024-12-08 23:51 UTC, lzk228 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/weapons/guns/basic/wands.ftl
> +    .desc = Запихивайте нердов на расстоянии!
"нёрдов" но я бы тут перевёл

2024-12-08 23:51 UTC, lzk228 commented on Resources/Textures/Structures/Wallmounts/posters.rsi/poster53_legit.png
перевод потерял насыщенность

2024-12-09 05:22 UTC, cfif126 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/markers/spawners/mobs.ftl
> +ent-SpawnMobReindeerBuck = спавер северный олень самец
```suggestion
ent-SpawnMobReindeerBuck = спавнер северный олень самец
```

2024-12-09 05:22 UTC, cfif126 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/markers/spawners/mobs.ftl
> +ent-SpawnMobReindeerDoe = спавер северный олень самка
```suggestion
ent-SpawnMobReindeerDoe = спавнер северный олень самка
```

2024-12-09 05:22 UTC, cfif126 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/weapons/guns/basic/wands.ftl
> +    .desc = Запихивайте нердов на расстоянии!
```suggestion
    .desc = Запихивайте варваров на расстоянии!
```

2024-12-09 05:22 UTC, cfif126 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/weapons/guns/projectiles/magic.ftl
> +    .desc = Проклятый магический шкафчик! Сможете ли вы устоять?
```suggestion
    .desc = Проклятый магический шкафчик! Сможете ли вы сопротивляться?
```

2024-12-09 05:22 UTC, cfif126 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/power/cable_terminal.ftl
> +    .suffix = Невозможно перерезать
Это точно нужно переводить? Ничего не сломается?

2024-12-09 10:45 UTC, lapatison commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/power/cable_terminal.ftl
> +    .suffix = Невозможно перерезать
Суффикс, не сломается

2024-12-09 10:51 UTC, lapatison commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/weapons/guns/basic/wands.ftl
> +    .desc = Запихивайте нердов на расстоянии!
"ботаников" мб?

2024-12-09 10:57 UTC, lapatison commented on Resources/Locale/ru-RU/construction/ui/construction-menu.ftl
> +construction-menu-grid-view = Показать сетку
Вид сеткой? Вид плиткой?

2024-12-09 11:09 UTC, lzk228 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/weapons/guns/basic/wands.ftl
> +    .desc = Запихивайте нердов на расстоянии!
задротов?

2024-12-09 11:09 UTC, lzk228 commented on Resources/Locale/ru-RU/construction/ui/construction-menu.ftl
> +construction-menu-grid-view = Показать сетку
плиткой

2024-12-09 18:18 UTC, lzk228 submitted a review, later dismissed

2024-12-10 00:49 UTC, lapatison commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/weapons/guns/basic/wands.ftl
> +    .desc = Запихивайте нердов на расстоянии!
Сделал ботаников, так как это всё же отсылка к старой доброй американской школьной традиции

2024-12-10 15:28 UTC, lzk228 approved these changes

2024-12-10 15:49 UTC, merged