Translate Upstream #2748
space-syndicate/space-station-14 pull request #2837
Opened 2024-12-08 23:39 UTC by lzk228

ура перевод!

2024-12-09 10:44 UTC, lapatison requested changes

2024-12-09 12:31 UTC, cfif126 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/weapons/guns/flare_gun.ftl
> +ent-WeaponFlareGunSecurity = охранный пистолет-дробовик
Сигнально-боевой дробовик
Сигнально-боевой пистолет

2024-12-09 12:34 UTC, cfif126 commented on Resources/Locale/ru-RU/inventory/components/inventory-component.ftl
> +        [1] какой-то предмет!
```suggestion
        [1] предмет!
```

2024-12-09 12:39 UTC, lzk228 commented on Resources/Locale/ru-RU/inventory/components/inventory-component.ftl
> +        [1] какой-то предмет!
an даёт неопределенность и просто "Вы уронили предмет" звучит так себе

2024-12-09 12:52 UTC, cfif126 commented on Resources/Locale/ru-RU/inventory/components/inventory-component.ftl
> +        [1] какой-то предмет!
Ты выронил предмет
Ты обронил что-то
У тебя выпал предмет

2024-12-09 12:56 UTC, Vonsant commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/consumable/food/baked/misc.ftl
> +    .desc = Вкусный и пышный кекс, с ягодами.
Вкусный и пышный кекс с ягодами.

Запятые тут не нужны.

2024-12-09 12:56 UTC, Vonsant commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/weapons/guns/flare_gun.ftl
> +    .desc = Модифицированный сигнальный пистолет, изначально предназначенный для использования службой безопасности для запуска нелетальных дробовых снарядов, однако он также может стрелять и летальн
Модифицированный сигнальный пистолет, изначально предназначенный для использования службой безопасности для запуска нелетальных дробовых снарядов. Однако он также может без риска стрелять и летальными снарядами.

2024-12-09 12:56 UTC, Vonsant commented on Resources/Locale/ru-RU/botany/components/plant-holder-component.ftl
> +plant-holder-component-ligneous-cant-harvest-message = Растение слишком прочное, чтобы собрать его голыми руками.
Звучит как-то тупо при переводе на русский.
Мб чонить в стиле "Растение настолько прочно засело, что голыми руками его не сорвёшь."?

2024-12-09 13:02 UTC, cfif126 commented on Resources/Locale/ru-RU/botany/components/plant-holder-component.ftl
> +plant-holder-component-ligneous-cant-harvest-message = Растение слишком прочное, чтобы собрать его голыми руками.
так это про мутацию (деревянные растения)

2024-12-09 13:10 UTC, cfif126 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/weapons/guns/flare_gun.ftl
> +    .desc = Модифицированный сигнальный пистолет, изначально предназначенный для использования службой безопасности для запуска нелетальных дробовых снарядов, однако он также может стрелять и летальн
```suggestion
    .desc = Модифицированный сигнальный пистолет, изначально предназначенный для использования службой безопасности для отстрела нелетальных дробовых снарядов. Однако из него также можно без риска стрелять и летальными снарядами.
```

2024-12-09 13:59 UTC, cfif126 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/weapons/guns/flare_gun.ftl
> +    .desc = Модифицированный сигнальный пистолет, изначально предназначенный для использования службой безопасности для запуска нелетальных дробовых снарядов, однако он также может стрелять и летальн
> Отстрел это утилизация.

стрельбы

2024-12-09 18:19 UTC, lapatison commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/weapons/guns/flare_gun.ftl
> +    .desc = Модифицированный сигнальный пистолет, изначально предназначенный для использования службой безопасности для запуска нелетальных дробовых снарядов. Однако он также может без риска стрелять
```suggestion
    .desc = Модифицированный сигнальный пистолет, изначально предназначенный для использования службой безопасности для запуска нелетальных ружейных снарядов. Однако он также может без риска стрелять и летальными снарядами.
```

2024-12-10 15:34 UTC, lapatison approved these changes

2024-12-10 15:48 UTC, merged