Гринч похитил безумные рождественские подарки.
space-syndicate/space-station-14 pull request #2881
Opened 2024-12-24 00:45 UTC by Vonsant

## Описание PR

No fun allowed.

**Список изменений**

:cl:
- remove: Безумные подарки больше не выпадают из ёлок. Никаких больше нагибаторов и импульсных пушек.

2024-12-24 00:47 UTC, lzk228 commented
схуёв?

2024-12-24 02:35 UTC, p0etus commented
Так это главный смысл ёлки, пассажир с гиб-палкой

2024-12-24 04:10 UTC, lastPechkin commented
Гринч ухади!

2024-12-24 04:53 UTC, NotSoDana commented
Предлагаю нахуй отключить случайные события, антагонистов, цели, вызов эвака и прочие вещи! У нас же игра про рп посиделочки в баре с кошкоблядями, а не "Симулятор станции на которой обязательно что-то произойдет", так зачем мешать рп процессу этим?

2024-12-24 05:34 UTC, foboscheshir commented
вахтёрят даже не по правилам

2024-12-24 06:01 UTC, 21Melkuu commented
Вы не сможете нарушить мои правила в мания мирке ыы14 если игры не будет

2024-12-24 06:52 UTC, kosticia commented
Оффам, пусть посмеются

2024-12-24 07:49 UTC, Vonsant commented
Никому тут ничего нельзя, один девять восемь четыре

2024-12-24 08:06 UTC, lzk228 commented
запретите педалям вмешиваться в игру по хуйне

2024-12-24 08:34 UTC, Vonsant commented
Не, жди.

2024-12-24 08:42 UTC, lzk228 commented
слы, нахуй иди бля

2024-12-24 08:44 UTC, Vonsant commented
> слы, нахуй иди бля

Там занято

2024-12-24 08:45 UTC, lzk228 commented
кочерга слезай

2024-12-24 09:02 UTC, kosticia commented
Least collaborator dialog on corvax github repo:

2024-12-24 18:39 UTC, cfif126 commented
![Discord_aDG81BPwSF](https://github.com/user-attachments/assets/d3bbef0f-d4db-4e68-a157-b13753a7661a)
 # ↑ ↑ ↑ ↑ ↑ ↑ + skill issue + git gut

2024-12-24 18:41 UTC, cfif126 requested changes
![image](https://github.com/user-attachments/assets/67fb2dd4-1e65-478e-8f3e-3d640be69cf1)
# Democracy 🗳️🦅✊🗣️

2024-12-24 18:42 UTC, 1TALERD commented
гринч делает глок глок, поэтому подарки остаются.

2024-12-26 10:05 UTC, SoulFN commented
Эти люди действительно хотят убрать главное веселье с новогоднего ивента, потому что.. это мешает посиделкам с метадрузьяшками в баре?

2024-12-26 10:08 UTC, Vonsant commented
> Эти люди действительно хотят убрать главное веселье с новогоднего ивента, потому что.. это мешает посиделкам с метадрузьяшками в баре?

Это самая из ниоткуда взятая предъява в мою сторону, поздравляю с получением **топ 1**. _Я ведь даже не играю на сервере._

2024-12-26 23:25 UTC, lzk228 commented
можно мне уже закрыть его?

2024-12-27 02:01 UTC, SonicHDC commented
Закрывай.
Fun is allowed

2024-12-27 05:11 UTC, Hemomancer commented
Закрыть до конца января.

2024-12-28 09:14 UTC, closed without merging

2024-12-28 09:14 UTC, Vonsant commented
Гринча побили х*ем по лбу.

2024-12-28 09:19 UTC, lzk228 commented
тудаааа