Remove shows tongue from chatsan
space-syndicate/space-station-14 pull request #2889
Opened 2024-12-28 12:20 UTC by lzk228

:р используется для рации по умолчанию
был пр который добавляет чатсан не только в конец сообщения (как было с 207 отдаёт честь) а и сканирует всё сообщение (лол мужик - _смеётся_ мужик)

2024-12-28 13:40 UTC, kosticia commented
Альтернатива нужна, иначе игроки попередохнут от сложности написания эмоута

2024-12-28 14:00 UTC, lzk228 commented
1. пусть пальцами работают бля
2. всё ещё могут делать эмоцию с латинской p

2024-12-30 06:26 UTC, Morb0 requested changes

2024-12-30 06:26 UTC, Morb0 commented on Content.Server/Chat/Managers/ChatSanitizationManager.cs
> -        { ":р", "chatsan-stick-out-tongue" }, // cyrillic р
замени на `:R`

2024-12-30 10:33 UTC, lzk228 commented on Content.Server/Chat/Managers/ChatSanitizationManager.cs
> -        { ":р", "chatsan-stick-out-tongue" }, // cyrillic р
ну, что так что с латинской p, придётся переключать раскладку, не вижу смысла

2025-01-24 13:06 UTC, lzk228 commented on Content.Server/Chat/Managers/ChatSanitizationManager.cs
> -        { ":р", "chatsan-stick-out-tongue" }, // cyrillic р
@Morb0

2025-04-06 01:51 UTC, Vonsant commented on Content.Server/Chat/Managers/ChatSanitizationManager.cs
> -        { ":р", "chatsan-stick-out-tongue" }, // cyrillic р
@JerryImMouse решай, хост младший, хост старший не ответит.

2025-04-26 00:34 UTC, JerryImMouse commented on Content.Server/Chat/Managers/ChatSanitizationManager.cs
> -        { ":р", "chatsan-stick-out-tongue" }, // cyrillic р
Здесь буквально похуй как, зависит от того как чел ставит ":", но оставлять в исходниках "р" и "p" это мегахуевая идея. Уж лучше действительно либо R, либо что-то иное

2025-04-26 00:36 UTC, lzk228 commented on Content.Server/Chat/Managers/ChatSanitizationManager.cs
> -        { ":р", "chatsan-stick-out-tongue" }, // cyrillic р
huh?

2025-04-26 00:40 UTC, JerryImMouse commented on Content.Server/Chat/Managers/ChatSanitizationManager.cs
> -        { ":р", "chatsan-stick-out-tongue" }, // cyrillic р
оставлять в исходниках кириллицу, которая похожа на латиницу - кринге, даже с учетом коммента

2025-04-26 00:42 UTC, lzk228 commented on Content.Server/Chat/Managers/ChatSanitizationManager.cs
> -        { ":р", "chatsan-stick-out-tongue" }, // cyrillic р
я не понимаю или я реально тупой?

2025-04-26 00:43 UTC, JerryImMouse commented on Content.Server/Chat/Managers/ChatSanitizationManager.cs
> -        { ":р", "chatsan-stick-out-tongue" }, // cyrillic р
я уже не понимаю чего ты не понимаешь

2025-07-28 05:34 UTC, DIMMoon1 commented
Замени р в эмоутах на Ь(мягкий знак), чтобы разделить и не было кнонфликта вместо удаления, и мёржну. Нашли проблему...

2025-07-30 07:59 UTC, DIMMoon1 commented
перенесено в апстрим для исключения конфликта https://github.com/DIMMoon1/space-station-14-ru/commit/232888822ab5689ea968c1f6c8135f18057714fb (с доп.эмоутами =р)

2025-07-30 07:59 UTC, closed without merging