Перевод последнего обновления
space-syndicate/space-station-14 pull request #309
Opened 2022-07-15 21:49 UTC by lapatison

## Описание PR 

**Скриншоты**

**Изменения**

:cl:
- add: Добавлены переводы последнего обновления
- tweak: Проведены стилистические правки

2022-07-15 22:08 UTC, lapatison commented
Стоит ли заменить `магнитные сапоги` на `магботы` ?

2022-07-16 15:26 UTC, Morb0 requested changes

2022-07-16 15:26 UTC, Morb0 commented on Resources/Locale/ru-RU/forensics/forensics.ftl
> +forensic-pad-sample = Она содержит образец: { $sample }
`Она` это кто?

2022-07-16 15:28 UTC, lapatison commented on Resources/Locale/ru-RU/forensics/forensics.ftl
> +forensic-pad-sample = Она содержит образец: { $sample }
Пластинка, forensic pad

2022-07-16 15:35 UTC, lapatison commented on Resources/Locale/ru-RU/forensics/forensics.ftl
> +forensic-scanner-interface-title = Криминальный сканер
Да, ты прав, я ошибся.
Тогда используем 'криминалистический' ?
Дактилоскопический не подходит по той причине, что кроме отпечатков пальцев он и волокна сканирует.

2022-07-16 15:37 UTC, Morb0 commented on Resources/Locale/ru-RU/forensics/forensics.ftl
> +forensic-scanner-interface-title = Криминальный сканер
`Мед-суд сканер` тоже не подходит, так что получается `Криминалистический`, да.

2022-07-16 17:12 UTC, Morb0 requested changes

2022-07-16 17:12 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/weapons/guns/projectiles/magic.ftl
> +    .desc = Не так уж плох, но вы все равно не хотите попасть под него.
Получается, что можно попасть под заряд так как он `не так уж плох`. Думаю в оригинале речь о том, что он не так сильно вредит но попасть под него не хочется все равно.

2022-07-16 17:16 UTC, Morb0 commented
> Стоит ли заменить `магнитные сапоги` на `магботы` ?
Наверное нет.

2022-07-16 17:56 UTC, lapatison commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/eyes/misc.ftl
> +ent-ClothingEyesEyepatch = пиратская повязка
Вернул `глазную повязку`.
`повязка на глаз` слишком похожа на соседнюю `повязка на глаза`.

2022-07-16 18:11 UTC, Morb0 approved these changes

2022-07-16 18:15 UTC, merged