1984: Изменение времени для получении профессий.
space-syndicate/space-station-14 pull request #370
Opened 2022-08-22 16:36 UTC by LarryRussian

## Описание PR 
Теперь многие профессии требуют больше времени что бы их разблокировать. Так же теперь Атмосферный Техник и Ассистент Инженера могут стать Антагонистами.
**Скриншоты**

**Изменения**

:cl:
- add: Больше 1984
- add: Дольше разблокировать профессии.
- add: Атмосферник и Технический ассистент могут стать антагами.

2022-08-22 16:44 UTC, lapatison commented
1) многие решения кринж
2) нафиг ты плазму вырезал?

2022-08-22 16:57 UTC, LarryRussian commented
Меня Номейд попросил сделать время, все вопросы к нему.

2022-08-22 16:59 UTC, LarryRussian commented
Блять, опять всё напутал, теперь у Капитана вырезал...

2022-08-22 17:10 UTC, Morb0 requested changes

2022-08-22 17:10 UTC, Morb0 commented on Resources/Prototypes/Roles/Jobs/Engineering/technical_assistant.yml
> +  canBeAntag: true
Такое небыло обсуждено. Убирай.

2022-08-22 17:10 UTC, Morb0 commented on Resources/Prototypes/Roles/Jobs/Medical/chief_medical_officer.yml
> +  canBeAntag: true
Такое небыло обсуждено. Убирай.

2022-08-22 17:10 UTC, Morb0 commented on Resources/Prototypes/Roles/Jobs/Engineering/atmospheric_technician.yml
> +  canBeAntag: true
Такое небыло обсуждено. Убирай.

2022-08-22 17:10 UTC, Morb0 commented
И файл с плазмой верни.

2022-08-22 17:12 UTC, LarryRussian commented
Щас.

2022-08-22 17:12 UTC, LarryRussian commented on Resources/Prototypes/Roles/Jobs/Engineering/atmospheric_technician.yml
> +  canBeAntag: true
Ладно.

2022-08-22 17:12 UTC, LarryRussian commented on Resources/Prototypes/Roles/Jobs/Medical/chief_medical_officer.yml
> +  canBeAntag: true
Спалили...

2022-08-22 17:13 UTC, LarryRussian commented on Resources/Prototypes/Roles/Jobs/Engineering/technical_assistant.yml
> +  canBeAntag: true
Ну тут уже немного странно, вроде обычный техник, но спорить не буду.

2022-08-22 17:33 UTC, LarryRussian commented on Resources/Prototypes/Roles/Jobs/Engineering/atmospheric_technician.yml
> +  canBeAntag: true
Изменил.

2022-08-22 17:33 UTC, LarryRussian commented on Resources/Prototypes/Roles/Jobs/Medical/chief_medical_officer.yml
> +  canBeAntag: true
Изменил.

2022-08-22 17:38 UTC, LarryRussian commented on Resources/Prototypes/Roles/Jobs/Engineering/technical_assistant.yml
> +  canBeAntag: true
Изменил.

2022-08-22 17:38 UTC, LarryRussian commented
Плазму вернул.

2022-08-22 17:55 UTC, LarryRussian commented
Я не понимаю что за ошибка.

2022-08-22 17:56 UTC, LarryRussian commented
Помогите.

2022-08-23 04:49 UTC, hazzlo commented
Бред какой-то. Даже у ноулайферов столько времени нет играть

2022-08-23 07:28 UTC, LarryRussian commented
Я потом попробую сделать всё адекватнее и разобраться, а пока лучше закрою ПР.

2022-08-23 07:28 UTC, closed without merging