Перевод Upstream#391
space-syndicate/space-station-14 pull request #392
Opened 2022-09-11 22:27 UTC by lapatison

## Описание PR 

**Скриншоты**

**Изменения**

:cl:
- tweak: Переведено последнее обновление

2022-09-11 22:50 UTC, Morb0 requested changes

2022-09-11 22:50 UTC, Morb0 commented on Resources/Locale/ru-RU/armor/armor-examine.ftl
> +armor-examinable-verb-message = Изучите показатели брони.
```suggestion
armor-examinable-verb-message = Изучить показатели брони.
```

2022-09-11 22:50 UTC, Morb0 commented on Resources/Locale/ru-RU/clothing/clothing-speed.ftl
> +clothing-speed-examinable-verb-message = Изучите показатели скорости одежды.
```suggestion
clothing-speed-examinable-verb-message = Изучить показатели скорости одежды.
```

2022-09-11 22:50 UTC, Morb0 commented on Resources/Locale/ru-RU/damage/damage-examine.ftl
> +damage-examinable-verb-message = Изучите показатели урона.
```suggestion
damage-examinable-verb-message = Изучить показатели урона.
```

2022-09-11 22:50 UTC, Morb0 commented on Resources/Locale/ru-RU/escape-menu/ui/options-menu.ftl
> +    Снижение этого параметра может помочь уменьшить статтеры,
```suggestion
    Снижение этого параметра может помочь уменьшить "захлебывания",
```

2022-09-11 22:50 UTC, Morb0 commented on Resources/Locale/ru-RU/escape-menu/ui/options-menu.ftl
> +    уменьшить статтеры при ходьбе, но иногда может
```suggestion
    уменьшить "захлебывания" при ходьбе, но иногда может 
```

2022-09-11 22:50 UTC, Morb0 commented on Resources/Locale/ru-RU/flavors/flavor-profiles.ftl
> +flavor-complex-memory-leek = как fork-бомба
```suggestion
flavor-complex-memory-leek = как форк-бомба
```

2022-09-11 22:50 UTC, Morb0 commented on Resources/Locale/ru-RU/weapons/ranged/gun.ftl
> +gun-revolver-insert = Заряжен
`Insert` же

2022-09-11 23:02 UTC, lapatison commented on Resources/Locale/ru-RU/weapons/ranged/gun.ftl
> +gun-revolver-insert = Заряжен
`Вставлен` не звучит. Это поп-ап при зарядке патронов в револьвер.

2022-09-11 23:04 UTC, lapatison commented on Resources/Locale/ru-RU/weapons/ranged/gun.ftl
> +gun-revolver-insert = Заряжен
Помещён?

2022-09-12 01:11 UTC, Morb0 commented on Resources/Locale/ru-RU/weapons/ranged/gun.ftl
> +gun-revolver-insert = Заряжен
Если popup, то окей.

2022-09-12 01:12 UTC, Morb0 approved these changes

2022-09-12 01:12 UTC, merged