Барсигни на русском
space-syndicate/space-station-14 pull request #444
Opened 2022-10-06 18:53 UTC by Halalrc

## Описание PR 
Перевод барных вывесок
**Скриншоты**

![image](https://user-images.githubusercontent.com/115177362/194394120-cb366e31-5bab-460d-941d-14133c216df7.png)
![image](https://user-images.githubusercontent.com/115177362/194394146-16e4bf24-5a1d-4d15-ac6b-633c62a7a82b.png)
![image](https://user-images.githubusercontent.com/115177362/194394172-e4326b27-bd23-4630-b624-4f52b6adaa29.png)
![image](https://user-images.githubusercontent.com/115177362/194394193-7e1b0d10-544a-49db-86c3-fe3beed189ca.png)
![image](https://user-images.githubusercontent.com/115177362/194394219-452f1381-f3e3-4d60-9c57-cb525ec5d649.png)
![image](https://user-images.githubusercontent.com/115177362/194394248-dc9b6606-304b-4774-8837-1de8a38805e6.png)
![image](https://user-images.githubusercontent.com/115177362/194394284-deaa2d17-b146-41d1-babd-951b9beebb57.png)
![image](https://user-images.githubusercontent.com/115177362/194394318-15d13cdd-4ec6-4b24-84fe-3d110069fc7c.png)
![image](https://user-images.githubusercontent.com/115177362/194394351-5578e6ad-d16e-440b-86ad-b836e7412ad2.png)
![image](https://user-images.githubusercontent.com/115177362/194394413-a2369d62-840a-4e80-8b5f-b1407d6085e3.png)
![image](https://user-images.githubusercontent.com/115177362/194394447-e1c4ac91-5c8f-4dd1-841b-62353fa0c8ee.png)
![image](https://user-images.githubusercontent.com/115177362/194394486-259d8c77-a3db-4877-97b2-dd94c0ae7146.png)
![image](https://user-images.githubusercontent.com/115177362/194394505-2ca3c12d-8d75-401d-a7ba-4cf983123c2a.png)
![image](https://user-images.githubusercontent.com/115177362/194394528-2f323f42-7de2-432a-b98c-c788a825667a.png)

**Изменения**
Добавлены переводы барных вывесок 

:cl: Halalrc
- add: добавлен перевод барных вывесок.

2022-10-06 20:25 UTC, Halalrc commented
Добавил изменения по Хармбатону, по остальным вроде и так понятно, что это вывеска

2022-10-07 20:49 UTC, Morb0 commented
![image](https://user-images.githubusercontent.com/14136326/194650234-62c5a3d1-8647-4a6d-9b24-ff01875920b9.png)

2022-10-07 21:15 UTC, Halalrc commented
угу, может и стоит убрать немного свечения, ибо правая сторона как будто отрезана.

2022-10-08 13:48 UTC, Halalrc commented
Пошаманил с свечением "Вольер"
![birdcage](https://user-images.githubusercontent.com/115177362/194710764-fa796973-3ad5-4b6b-a78a-12698360cd61.png)

2022-10-08 15:45 UTC, Morb0 requested changes

2022-10-08 15:45 UTC, Morb0 commented on Resources/Prototypes/Corvax/bar_signs.yml
> +  - type: barSign
Убрать отступ в 2 пробела.

2022-10-08 15:50 UTC, Halalrc commented on Resources/Locale/ru-RU/corvax/barsign/barsign-component.ftl
> +barsign-prototype-description-alcoholic = Ранее находилось в Космороссии, но уже не кормят.
ты гений

2022-10-08 21:35 UTC, Halalrc commented
Еще что-то?

2022-10-08 22:07 UTC, Morb0 commented
Новый спрайт для нальют и точка свой не залил.

2022-10-08 23:37 UTC, Morb0 approved these changes

2022-10-08 23:44 UTC, merged