Перевод Upstream #475
space-syndicate/space-station-14 pull request #476
Opened 2022-10-21 21:37 UTC by lapatison

## Описание PR 

**Скриншоты**

**Изменения**

:cl:
- add: Добавлены переводы

2022-10-21 23:05 UTC, Morb0 requested changes

2022-10-21 23:05 UTC, Morb0 commented on Resources/Locale/ru-RU/game-ticking/game-presets/preset-survival.ftl
> +survival-description = Внутренние угрозы отсутствуют, но как долго станция сможет продержаться в обстановке все более хаотичных и частых событий?
Может так?
```suggestion
survival-description = Внутренние угрозы отсутствуют, но как долго станция сможет продержаться в обстановке все более разрушительных и частых событий?
```

2022-10-22 01:23 UTC, lapatison commented on Resources/Locale/ru-RU/actions/actions/dragon.ftl
> +action-description-carp-rift = Призвать карповый разлом, который будет периодически призывать карпов.
Ты прав, так лучше

2022-10-22 01:33 UTC, Morb0 approved these changes

2022-10-22 01:34 UTC, merged