Перевод Upstream #503
space-syndicate/space-station-14 pull request #504
Opened 2022-10-31 14:16 UTC by lapatison

## Описание PR 

**Скриншоты**

**Изменения**

:cl:
- add: Добавлены переводы

2022-10-31 17:10 UTC, Morb0 requested changes

2022-10-31 17:10 UTC, Morb0 commented on Resources/Locale/en-US/ss14-ru/prototypes/corvax/entities/objects/misc/tencodes.ftl
> -    .desc = { ent-Paper.desc }
Нужно изменить еще в прототипе - https://github.com/space-syndicate/space-station-14/blob/master/Resources/Prototypes/Corvax/Entities/Objects/Misc/tencodes.yml

2022-11-01 00:45 UTC, lapatison commented on Resources/Locale/en-US/ss14-ru/prototypes/corvax/entities/objects/misc/tencodes.ftl
> -    .desc = { ent-Paper.desc }
Так?

2022-11-01 00:46 UTC, Morb0 commented on Resources/Locale/en-US/ss14-ru/prototypes/corvax/entities/objects/misc/tencodes.ftl
> -    .desc = { ent-Paper.desc }
Да, и название.

2022-11-01 02:08 UTC, Morb0 approved these changes

2022-11-01 02:08 UTC, merged