Перевод Upstream #564
space-syndicate/space-station-14 pull request #566
Opened 2022-11-19 12:56 UTC by lapatison

## Описание PR 

**Скриншоты**

**Изменения**

:cl:
- add: Добавлены переводы

2022-11-19 15:27 UTC, Morb0 requested changes

2022-11-19 15:27 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/devices/circuitboards/machine/production.ftl
> +    .desc = Печатная плата для исказителя обхода.
Ничего не понятно, даже примерно не имею идеи, что делает машина по названию.
Зачем искажать обход?

2022-11-19 15:27 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/machines/artifact_analyzer.ftl
> +    .desc = Машина, способная влиять на посещение нод артефакта.
`посещение нод` втф

2022-11-19 15:39 UTC, lapatison commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/devices/circuitboards/machine/production.ftl
> +    .desc = Печатная плата для исказителя обхода.
Вообще вся эта система основана на
https://ru.m.wikipedia.org/wiki/%D0%9E%D0%B1%D1%85%D0%BE%D0%B4_%D0%B4%D0%B5%D1%80%D0%B5%D0%B2%D0%B0

Я потом попробую более просто написать.
Я понимаю как это работает, но слова не складываются. Помощь приветствуется.

2022-11-19 23:30 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/devices/circuitboards/machine/production.ftl
> +    .desc = Печатная плата для исказителя обхода.
`поперечный искатель` предложил Google.Translate

2022-11-21 00:26 UTC, lapatison commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/devices/circuitboards/machine/production.ftl
> +    .desc = Печатная плата для исказителя обхода.
`поперечный искатель`
`Прибор, способный влиять на открываемые цепочки эффектов артефактов`

2022-11-21 00:49 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/devices/circuitboards/machine/production.ftl
> +    .desc = Печатная плата для исказителя обхода.
yep, и так же нужно в остальных местах использовать эти термины

2022-11-21 01:05 UTC, lapatison commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/devices/circuitboards/machine/production.ftl
> +    .desc = Печатная плата для исказителя обхода.
Ну допустим

2022-11-21 02:05 UTC, merged