feat: added captain secret goals
space-syndicate/space-station-14 pull request #569
Opened 2022-11-19 23:39 UTC by Gaxeer

## Описание PR 

**Скриншоты**

**Изменения**

:cl:
- add: Добавлены секретные цели для капитана

2022-11-19 23:58 UTC, Morb0 requested changes

2022-11-19 23:58 UTC, Morb0 commented on Content.Server/Corvax/SecretStationGoal/SecretStationGoalPaperSystem.cs
> +        private void OnComponentStartup(EntityUid uid, SecretStationGoalPaperComponent component, ComponentInit args)
Переименовать забыл в Init

2022-11-19 23:58 UTC, Morb0 commented on Content.Server/Corvax/SecretStationGoal/SecretStationGoalPaperSystem.cs
> +            }
Просто `return` делать

2022-11-19 23:58 UTC, Morb0 commented on Content.Server/Corvax/SecretStationGoal/SecretStationGoalPaperSystem.cs
> +        private SecretStationGoalPrototype GenerateSecretGoal()
Я бы назвал `PickSecretGoal`

2022-11-19 23:58 UTC, Morb0 commented on Content.Server/Corvax/SecretStationGoal/SecretStationGoalPaperSystem.cs
> +            var secretGoals = _prototypeManager.EnumeratePrototypes<SecretStationGoalPrototype>();
Вот тут желательна проверка на то что целей больше 0, иначе скорее всего кидать exception

2022-11-19 23:58 UTC, Morb0 commented on Resources/Prototypes/Corvax/Entities/Objects/Misc/paper.yml
> +  description: 'An envelope containing secret goal'
Точка в конце

2022-11-19 23:58 UTC, Morb0 commented on Resources/Prototypes/Corvax/Entities/Objects/Misc/paper.yml
> +  name: secret goal sealed envelope
Думаю лучше назвать просто `sealed envelope`

2022-11-19 23:58 UTC, Morb0 commented on Resources/Prototypes/Corvax/Entities/Objects/Misc/paper.yml
> +  name: secret goal open envelope
И тут соответственно просто `open envalope`

2022-11-19 23:58 UTC, Morb0 commented on Resources/Prototypes/Corvax/Entities/Objects/Misc/paper.yml
> +          prob: 1
Шанс появления не нужен

2022-11-19 23:58 UTC, Morb0 commented on Resources/Textures/Corvax/Objects/Misc/envelope.rsi/meta.json
> +  "size": {
Забыл скинуть копирайты
```suggestion
  "version": 1,
  "license": "CC-BY-SA-3.0",
  "copyright": "Taken from infinitystation at commit https://github.com/infinitystation/Baystation12/commit/034c0be53463a2f889d052e04c688c3ef2acc956",
  "size": {
```

2022-11-19 23:58 UTC, Morb0 commented on Content.Server/Corvax/StationGoal/StationGoalSystem.cs
>          }
Методы событий приоритетнее public методов и должны быть выше.

2022-11-19 23:58 UTC, Morb0 commented on Content.Server/Corvax/StationGoal/StationGoalSystem.cs
> +        private void CreateRandomStationGoal()
Некоторые методы специально делаются публичными, даже если не используются еще никем, что бы если кто-то захочет использовать систему как зависимость сразу мог знать, что ему доступно и будет работать.
Думаю в этом классе кроме дублирования random не нужно ничего менять.

2022-11-20 12:01 UTC, Morb0 requested changes

2022-11-20 12:01 UTC, Morb0 commented on Content.Server/Corvax/SecretStationGoal/SecretStationGoalPaperSystem.cs
> +            return secretGoals.Any() ? _random.Pick(secretGoals) : new SecretStationGoalPrototype();
И какое тут будет ID у прототипа? Скорее всего null, так как мы обещаем `default!` что там точно что-то будет, но на самом деле нет

2022-11-20 16:31 UTC, Morb0 requested changes

2022-11-20 16:31 UTC, Morb0 commented on Resources/Prototypes/Corvax/Objectives/goals.yml
> +  text: secret-goal-capture-zombie
Нужно выделить в отдельный файл рядом `secret-goals.yml` и лучше оставить там одно задание сейчас, просто `Особых поручений на смену нету. Слава НТ!`.
А все задачи обдумаем и добавим отдельным PR'ом.

2022-11-20 21:33 UTC, Morb0 approved these changes

2022-11-28 07:12 UTC, Morb0 requested changes
Нужно исправить ошибки из тестов

2023-04-19 16:14 UTC, PuroSlavKing commented
Предлагаю обратно закрыть, челик или очень усердно кодит уже 2 недели (нет), или ему просто похуй и он забил (да)

2023-04-26 08:46 UTC, closed without merging