MTF resprite
space-syndicate/space-station-14 pull request #619
Opened 2022-12-04 09:51 UTC by nomad0260

## Описание PR 

**Скриншоты**

**Изменения**

:cl: no_mad, SOL
- add: Добавлено форма ОБР
- tweak: Изменены скафандры ОБР

2022-12-08 14:35 UTC, nomad0260 commented
Босс, принимай работу

2022-12-09 06:56 UTC, Morb0 commented
Всё было бы быстрее если бы мне не приходилось заниматься тестированием.
![image](https://user-images.githubusercontent.com/14136326/206643463-75292ec0-6673-43fa-aedc-c26c1754e6ec.png)

2022-12-09 06:58 UTC, Morb0 commented
Скафандры в руке или ещё уменьшить, или сдвинуть хотя бы левее, что бы это не выглядело так...
![image](https://user-images.githubusercontent.com/14136326/206643751-f92251cc-1d83-4ca9-ab70-20d991bbd924.png)

2022-12-09 06:59 UTC, Morb0 commented
Вот эту часть бы вообще убрал из иконки, оно лишнее и только портит вид.
![image](https://user-images.githubusercontent.com/14136326/206643921-eff22c41-4950-4806-a01e-639ea4075d20.png)

Выходил за рамки слота:
![image](https://user-images.githubusercontent.com/14136326/206643985-3cf83706-21b8-47cf-96ef-6a06ce754cb6.png)

2022-12-09 07:00 UTC, Morb0 commented
Цвет у света должен быть соответствующий.
![image](https://user-images.githubusercontent.com/14136326/206644082-2eebe4e6-e1b5-4f96-ae12-a8a5541ab1e7.png)

2022-12-09 07:02 UTC, Morb0 commented
Иконка скафандра уборщика неправильная.
![image](https://user-images.githubusercontent.com/14136326/206644346-b59ac48a-c4e7-42be-b114-33fc5aa10d9b.png)

2022-12-09 07:03 UTC, Morb0 commented
Цвет иконки у скафандра медика отличается от надетого.
![image](https://user-images.githubusercontent.com/14136326/206644490-102e1640-e148-445b-afcb-f1ba5b27f233.png)

2023-01-03 06:49 UTC, nomad0260 commented
Ну теперь то все нормально, только тест рси жалуется что у палочки для рта неправильная лицензия
Но я в душе не ебу как это связано с этим ПРом

2023-01-08 10:07 UTC, ZettaProtocol commented
> Это связано с PR'ом. Лицензии `CC-BY` нет, укажи точнее.

Это относится не к этому ПР'ру. Это из за удаления контента автора которого забанили

2023-01-14 13:50 UTC, Morb0 requested changes
Берет странно отображается в руке при виде сбоку.
![image](https://user-images.githubusercontent.com/14136326/212475265-d763128d-871f-4131-8132-184fa382f150.png)

2023-01-14 14:28 UTC, nomad0260 commented
в душе не ебу из-за чего ошибка вылазит, яж только спрайт заменил

2023-01-15 12:23 UTC, Morb0 approved these changes

2023-01-15 12:24 UTC, merged