Fax and can resprites
space-syndicate/space-station-14 pull request #659
Opened 2022-12-20 14:57 UTC by RomanMinaev

## Описание PR

Перенес спрайты факса и газовых канистр с TauCeti

**Скриншоты**

![SS14 Loader_a8qOGobAXV](https://user-images.githubusercontent.com/22061791/208695269-e50e7a17-9311-418a-811f-362420516123.png)
![SS14 Loader_oFhD0EKE2d](https://user-images.githubusercontent.com/22061791/208695318-d93890e2-5427-4cf3-bfb7-7700c949cf55.png)
![image](https://user-images.githubusercontent.com/22061791/208695795-4cf6b61b-ed23-47b2-af8b-4d9649a47108.png)

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.

**Изменения**

:cl:
- add: Клевые спрайты
- remove: Неклевые спрайты

2022-12-20 15:00 UTC, lapatison commented
> В списке изменений тип значка не является часть предложения, поэтому явно указывайте - Добавлен, Удалён, Изменён.
плохо: - add: Новый инструмент для инженеров
хорошо: - add: Добавлен новый инструмент для инженеров

2022-12-20 15:06 UTC, RomanMinaev commented
> > В списке изменений тип значка не является часть предложения, поэтому явно указывайте - Добавлен, Удалён, Изменён.
> > плохо: - add: Новый инструмент для инженеров
> > хорошо: - add: Добавлен новый инструмент для инженеров

Исправил

2022-12-21 04:48 UTC, Deahaka commented
Я конечно Тау-лоббист, но вот ещё интересный спрайт есть на ТГ, который я думал попробовать портировать. Может, вам тоже понравится такой https://github.com/tgstation/tgstation/pull/69397

2022-12-21 04:56 UTC, Deahaka commented
Ну и ещё на поглядеть подкину спрайтики которые делал автор диров для тележки уборщика (их если что никогда до этого не было, насколько я знаю). https://github.com/TauCetiStation/TauCetiClassic/pull/9176

2022-12-21 08:24 UTC, RomanMinaev commented
> Я конечно Тау-лоббист, но вот ещё интересный спрайт есть на ТГ, который я думал попробовать портировать. Может, вам тоже понравится такой [tgstation/tgstation#69397](https://github.com/tgstation/tgstation/pull/69397)
Мы рассматривали в мемторской и этот вариант, но остановились на том, который вот я сделал.


> Ну и ещё на поглядеть подкину спрайтики которые делал автор диров для тележки уборщика (их если что никогда до этого не было, насколько я знаю). [TauCetiStation/TauCetiClassic#9176](https://github.com/TauCetiStation/TauCetiClassic/pull/9176)
Над этим я тоже думал, но, так как он ПР не прошел, я не знаю даже, можно ли его использовать, на него вроде не распространяется лицензия

2022-12-22 07:20 UTC, Morb0 requested changes
Слишком маленькие тайминги у idle анимации факса.

2022-12-22 07:23 UTC, Morb0 reviewed
Возможно стоит поменять местами цвета открытого и закрытого замка, что бы зелёный был слева.

2022-12-22 10:00 UTC, RomanMinaev commented
> Возможно стоит поменять местами цвета открытого и закрытого замка, чтобы зелёный был слева.

Зеленый же итак слева

2022-12-22 10:39 UTC, Morb0 commented
> > Возможно стоит поменять местами цвета открытого и закрытого замка, чтобы зелёный был слева.
> 
> Зеленый же итак слева

Значит я имел в виду справа

2022-12-22 11:21 UTC, RomanMinaev commented
> > > Возможно стоит поменять местами цвета открытого и закрытого замка, чтобы зелёный был слева.
> > 
> > 
> > Зеленый же итак слева
> 
> Значит я имел в виду справа

поменял местами

2022-12-22 12:06 UTC, Morb0 requested changes
Мне не нравится красные свет у полностью опустошённой канистры, лучше как у ТГ просто серое, можешь оттуда взять, там буквально такие же канистры, только с контуром.

2022-12-22 12:33 UTC, Morb0 requested changes
![image](https://user-images.githubusercontent.com/14136326/209135207-1100dbee-a6a2-4ec7-a26b-50fac07d42e4.png)
Так же у индикатора средней заполненности 2 пикселя зелёных.

2022-12-22 13:41 UTC, RomanMinaev commented
> Мне не нравится красные свет у полностью опустошённой канистры, лучше как у ТГ просто серое, можешь оттуда взять, там буквально такие же канистры, только с контуром. Или сам скропить спрайт из 2 частей, где шкала пустая.

Странно, вообще она моргать должна, в meta.json прописаны дилэи и сам спрайт can-o0 64x32 с двумя кадрами. Не понимаю, почему не моргает.

2022-12-22 14:04 UTC, RomanMinaev commented
![image](https://user-images.githubusercontent.com/22061791/209150980-14c36327-e025-4f66-9d08-3f7da422d4dd.png)
Не знаю в общем, почему не мигает, исправил спрайт, второй кадр теперь красный для мигания, если получится исправить, то будет мигать, сейчас просто выключенным будет

2022-12-22 14:24 UTC, Morb0 approved these changes
LGTM

2022-12-22 15:21 UTC, merged