Rxbzz respraite
space-syndicate/space-station-14 pull request #662
Opened 2022-12-21 05:31 UTC by nomad0260

## Описание PR

**Скриншоты**
 
![imaфывфывфывge](https://user-images.githubusercontent.com/110369449/208828604-10594711-5d4c-4b23-9f3d-10ee0238dd48.png)
![imaфывфывфвge](https://user-images.githubusercontent.com/110369449/208828643-ab211770-7ab4-436b-b12c-2a4916e58228.png)
**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.

**Изменения**

:cl: no_mad 𝘽𝙚𝙡𝙖𝙮
- add: Добавлен костюм лидера рхбзз
- tweak: Изменен спрайт костюма рхбзз

2022-12-21 08:08 UTC, Xeno4 commented
сасненько

2022-12-21 17:44 UTC, Morb0 requested changes

2022-12-21 17:44 UTC, Morb0 commented on Resources/Prototypes/Corvax/Entities/Back/backpacks.yml
> +    sprite:
Весь свой код просмотри, у тебя половина пустые

2022-12-22 10:49 UTC, Morb0 requested changes

2022-12-22 10:49 UTC, Morb0 commented on Resources/Textures/Clothing/Head/Hardsuits/cburn.rsi/meta.json
> +  version 1,
Это не валидный json, кавычке и двоеточие исправились

2022-12-23 01:28 UTC, nomad0260 commented on Resources/Textures/Clothing/Head/Hardsuits/cburn.rsi/meta.json
> +  version 1,
странно, я вроде заменил json, но в превью он все еще такой же

2023-01-03 07:14 UTC, nomad0260 commented
Такая же проблема как у ОБР, при чем тут ватные палочки, только волшебники знают

2023-02-01 03:14 UTC, Morb0 requested changes

2023-02-01 03:25 UTC, nomad0260 commented on Resources/Prototypes/Corvax/Entities/Back/backpacks.yml
> +    capacity: 131
Эти предметы должны были быть ивентовыми и по логике, военные рюкзаки по вместительнее будут обычных

2023-02-01 03:36 UTC, Morb0 commented on Resources/Prototypes/Corvax/Entities/Back/backpacks.yml
> +    capacity: 131
Так почему именно 131 а не 130?

2023-02-01 03:45 UTC, nomad0260 commented on Resources/Prototypes/Corvax/Entities/Back/backpacks.yml
> +    capacity: 131
Чтоб картонная коробка влезала идеально

2023-02-01 12:01 UTC, Morb0 approved these changes

2023-02-01 12:26 UTC, Morb0 requested changes

2023-02-01 12:26 UTC, Morb0 commented on Resources/Prototypes/Corvax/Entities/Back/backpacks.yml
> +- type: entity
Файлы не в той папке, должно быть в `Entities\Clothing`

2023-02-01 14:22 UTC, nomad0260 commented
Ошибок нет

2023-02-02 06:58 UTC, Morb0 approved these changes

2023-02-02 07:07 UTC, merged