Added mandarines
space-syndicate/space-station-14 pull request #683
Opened 2022-12-28 09:31 UTC by mhamsterr

## Описание PR

Специально к новому году, добавлены мандарины, а так же сок из них. Мандарины могут быть заказаны в карго.

**Скриншоты**

<img width="322" alt="Мандариновый сок" src="https://user-images.githubusercontent.com/81412348/209789993-ae067b8f-669e-489c-8c5a-8d31d9b6dbd0.png">
<img width="309" alt="Мандарин" src="https://user-images.githubusercontent.com/81412348/209790107-5652a278-0282-4dc6-9ea3-c2239268553b.png">
<img width="371" alt="Ящик мандаринов" src="https://user-images.githubusercontent.com/81412348/209790177-c0b0b3ba-498c-40f2-984e-fb1239dd36a4.png">

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.

**Изменения**

:cl:
- add: Добавлены мандарины
- add: Добавлен мандариновый сок
- add: Добавлен ящик мандаринов для заказа у карго

2022-12-28 10:46 UTC, LarryRussian commented
Если и добавлять Мандарины, то следовало бы и растение сделать.

2022-12-28 11:10 UTC, Morb0 requested changes
Нужно вынести в папку Corvax, то есть изменения в каждом из файлов должно быть соответственно пути файла вынесено в corvax.
То есть:
`Resources/Locale/ru-RU/flavors/flavor-profiles.ftl` => `Resources/Locale/ru-RU/corvax/flavors/flavor-profiles.ftl`

`Resources/Prototypes/Catalog/Cargo/cargo_food.yml` => `Resources/Prototypes/Corvax/Catalog/Cargo/cargo_food.yml`

Если соответствующего аналога файла не существует в папке Corvax, то нужно создать.

2022-12-28 11:10 UTC, Morb0 requested changes

2022-12-28 11:10 UTC, Morb0 commented on Resources/Locale/ru-RU/prototypes/catalog/fills/crates/food-crates.ftl
> +    .desc = Подарите вашей команде небольшую частицу нового года. Прямо как в СССР.
Who?
```suggestion
    .desc = Подарите вашей команде небольшую частицу нового года.
```

2023-01-15 19:44 UTC, Vaaankas commented
Новый год прошёл, а мандарины остались...

2023-03-16 21:39 UTC, closed without merging