Agent names localization
space-syndicate/space-station-14 pull request #744
Opened 2023-01-14 18:52 UTC by Vaaankas

## Описание PR

Локализованы имена агентов покупаемых за ТК

**Медиа**

**Проверки**

- [+] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [+] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [+] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [+] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

:cl: vanx
- tweak: Локазизованы имена агентов из аплинка

2023-01-14 19:44 UTC, Morb0 requested changes
Лучше вынеси этот файл в `Prototypes/Corvax/Datasets/Names/names_death_commando` а ID измени на `corvax_names_death_commando` и везде в yml где сейчас используется `names_death_commando` замени на `corvax_names_death_commando # Corvax-Localization`

2023-01-18 13:05 UTC, Vaaankas commented on Resources/Prototypes/Datasets/Names/death_commando.yml
> +  - Trunk Slamchest
Не понимаю что тут изменилось

2023-01-18 13:07 UTC, Vaaankas commented on Resources/Prototypes/Datasets/Names/death_commando.yml
> +  - Trunk Slamchest
а, изменилось с прошлого но показывает с изначального, ясно

2023-01-25 18:08 UTC, Vaaankas commented
Я там исправил, конфликт это вроде не по моей части

2023-01-30 02:38 UTC, merged