Перевод speech_emotes
space-syndicate/space-station-14 pull request #785
Opened 2023-01-29 18:15 UTC by lapatison

## Описание PR

**Медиа**

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:
- add: Добавлены переводы

2023-01-29 19:29 UTC, fedKotikeD commented
Я как раз хотел написать чтобы это исправили, но добрые люди меня обогнали

2023-01-30 02:29 UTC, Morb0 requested changes

2023-01-30 02:29 UTC, Morb0 commented on Resources/Prototypes/Voice/speech_emotes.yml
> +  chatMessages: [кричит, орёт]
Отметь изменения строками
```suggestion
  chatMessages: [кричит, орёт] # Corvax-Localization
```

2023-01-30 02:29 UTC, Morb0 commented on Resources/Prototypes/Voice/speech_emotes.yml
> +    - визжит
Отметь изменения блоками
```suggestion
    # Corvax-Localization-Start
    - крик
    - кричит
    - ор
    - орёт
    - визг
    - визжит
    # Corvax-Localization-End
```

2023-01-31 00:25 UTC, Morb0 requested changes
Везде нужно, я показал на примере 2 места только

2023-01-31 01:02 UTC, Morb0 approved these changes

2023-01-31 04:56 UTC, merged