Guidebook localisation
space-syndicate/space-station-14 pull request #787
Opened 2023-01-30 01:15 UTC by lapatison

## Описание PR

**Медиа**

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: lapatison, Vigers_Ray
- add: Частично переведено руководство

2023-01-30 02:37 UTC, Morb0 requested changes

2023-01-30 02:37 UTC, Morb0 commented on Resources/Server Info/Guidebook/Survival.xml
> +</Box>
Лишнее, закрывает несуществующий блок

2023-01-30 02:37 UTC, Morb0 commented on Resources/Server Info/Guidebook/Space Station 14.xml
> +Рекомендуется начать с руководства [color=#a4885c]Управление[/color], а затем прочитать [color=#a4885c]Создание персонажа[/color], [color=#a4885c]Ролевой отыгрыш[/color] и [ color=#a4885c]Должности[/
Возможно невалидное
```suggestion
Рекомендуется начать с руководства [color=#a4885c]Управление[/color], а затем прочитать [color=#a4885c]Создание персонажа[/color], [color=#a4885c]Ролевой отыгрыш[/color] и [color=#a4885c]Должности[/color]. Не для всех должностей или концептов будут руководства, и если вы опытный игрок — очень просим помочь нам написать или перевести их!
```

2023-01-30 14:16 UTC, lapatison commented on Resources/Server Info/Guidebook/Survival.xml
> +</Box>
Закрывает 24 строчку

2023-01-31 01:01 UTC, Morb0 requested changes

2023-01-31 12:28 UTC, Morb0 approved these changes

2023-01-31 12:29 UTC, merged