Перевод Upstream #790
space-syndicate/space-station-14 pull request #792
Opened 2023-01-31 21:25 UTC by lapatison

## Описание PR

**Медиа**

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:
- add: Добавлены переводы

2023-01-31 23:08 UTC, Morb0 requested changes

2023-01-31 23:08 UTC, Morb0 commented on Resources/Locale/ru-RU/headset/headset-component.ftl
> +examine-headset-default-channel = Показывает, что каналом по умолчанию этой гарнитуры выбран канал [color={ $color }]{ $channel }[/color].
```suggestion
examine-headset-default-channel = Отображается, что каналом по умолчанию этой гарнитуры является [color={ $color }]{ $channel }[/color].
```

2023-01-31 23:08 UTC, Morb0 commented on Resources/Locale/ru-RU/headset/headset-component.ftl
> +examine-encryption-key-default-channel = Похоже, каналом по умолчанию выбран канал [color={ $color }]{ $channel }[/color].
```suggestion
examine-encryption-key-default-channel = Похоже, каналом по умолчанию является [color={ $color }]{ $channel }[/color].
```

2023-01-31 23:08 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/ears/headsets_alt.ftl
> +ent-ClothingHeadsetAltCargo = полноразмерная гарнитура КМ
В оригинале это кажется все ещё не привязано к главам.

2023-02-01 00:06 UTC, lapatison commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/ears/headsets_alt.ftl
> +ent-ClothingHeadsetAltCargo = полноразмерная гарнитура КМ
Уже привязано
https://github.com/space-syndicate/space-station-14/blob/master/Resources/Locale/en-US/ss14-ru/prototypes/entities/clothing/ears/headsets_alt.ftl

2023-02-01 00:50 UTC, Morb0 approved these changes

2023-02-01 00:56 UTC, merged