guide entry "ScannersAndVessels" translation
space-syndicate/space-station-14 pull request #799
Opened 2023-02-02 02:23 UTC by lapatison

## Описание PR

**Медиа**

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:
- add: Переведена глава "Аномалии и сосуды" руководства

2023-02-02 10:30 UTC, Morb0 requested changes

2023-02-02 10:30 UTC, Morb0 commented on Resources/Locale/ru-RU/anomaly/anomaly.ftl
> +anomaly-scanner-stability-medium = Текущее состояние аномалии: [color=forestgreen]Стабильность[/color]
Состояние - стабильное
Зачем менять?

2023-02-02 10:30 UTC, Morb0 commented on Resources/Locale/ru-RU/anomaly/anomaly.ftl
> +anomaly-scanner-severity-percentage = Текущая серьёзность: [color=gray]{ $percent }[/color]
Как то не звучит, какая-то недосказанность, серьезность чего?
Чем выше этот параметр тем опаснее эффект.
`severity level` используется и для кодов станции и переведен как `уровень угрозы`.

2023-02-02 13:28 UTC, lapatison commented on Resources/Locale/ru-RU/anomaly/anomaly.ftl
> +anomaly-scanner-severity-percentage = Текущая серьёзность: [color=gray]{ $percent }[/color]
Может `интенсивность`?
`Текущая интенсивность`: х%

`Текущая угроза` мэх, а `текущий уровень угрозы` - длинно.

Или можно вернуться к опасности.

2023-02-02 15:14 UTC, lapatison commented on Resources/Locale/ru-RU/anomaly/anomaly.ftl
> +anomaly-scanner-severity-percentage = Текущая серьёзность: [color=gray]{ $percent }[/color]
Мне кажется `Угроза` это больше случится/не случится.

Ещё есть вариант `критическая масса` из #переводов.

2023-02-02 15:43 UTC, Morb0 commented on Resources/Locale/ru-RU/anomaly/anomaly.ftl
> +anomaly-scanner-severity-percentage = Текущая серьёзность: [color=gray]{ $percent }[/color]
критическая масса - этот как раз показатель случится/не случится
а `Угрока` в связке с параметром `Состояние` мне кажется отображает все понятно:
```
Угроза: 90%
Состояние: Стабильное
```

2023-02-13 18:06 UTC, Morb0 commented on Resources/Locale/ru-RU/anomaly/anomaly.ftl
> +anomaly-scanner-severity-percentage = Текущая серьёзность: [color=gray]{ $percent }[/color]
Хорошо, опасность.

2023-02-13 18:20 UTC, lapatison commented
Готово

2023-02-13 18:25 UTC, merged