Обновление текстур
space-syndicate/space-station-14 pull request #826
Opened 2023-02-14 09:27 UTC by SonicHDC

## Описание PR

Изменяет дискаунтер на стилизованный.

**Медиа**

![off](https://user-images.githubusercontent.com/100022571/218692067-e5206887-8f50-458d-a7bc-bb1d0a7299c1.png)
![normal-unshaded](https://user-images.githubusercontent.com/100022571/218692116-cc2a0119-d53c-4a83-a7f1-e7971963b077.png)
![broken](https://user-images.githubusercontent.com/100022571/218692146-e28692d9-7c70-4c4d-b8e5-1e42e65cc0f9.png)

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: SonicDC
- tweak: Изменена текстура автомата!

2023-02-14 13:08 UTC, Vaaankas commented
> tweak: Изменена текстура автомата!
может уточнить какого?

2023-02-14 19:26 UTC, Morb0 commented
Добавь теней, особенно сверху.
![image](https://user-images.githubusercontent.com/14136326/218837336-b50d0062-acf1-41c8-a0d5-237996131492.png)

2023-02-14 20:47 UTC, SonicHDC commented
Попробую

2023-02-15 03:40 UTC, SonicHDC commented
Текстура улучшена

2023-02-15 14:25 UTC, Morb0 requested changes

2023-02-15 14:25 UTC, Morb0 commented on Resources/Textures/Structures/Machines/VendingMachines/discount.rsi/meta.json
> +  "copyright": "Taken from vgstation at https://github.com/vgstation-coders/vgstation13/commit/7c41613c521b6fab647ae98e1283f86b3cef382a",
Укажи своё авторство, например логин или ид Discord, пример -`Ian#4331`

2023-02-15 20:03 UTC, Morb0 requested changes

2023-02-15 20:03 UTC, Morb0 commented on Ресурсы/Текстуры/Структуры/Машины/Торговые автоматы/скидка.rsi/meta.json
> +	  0.4
```suggestion
          0.4,
	      0.4
```

2023-02-15 20:04 UTC, Morb0 requested changes
Куда ты файл перенёс...
`Ресурсы/Текстуры/Структуры/Машины/Торговые автоматы/скидка.rsi/meta.json`
Верни в `Resources/Textures/Structures/Machines/VendingMachines/discount.rsi/meta.json`

2023-02-16 03:28 UTC, SonicHDC commented
Баг гитхаба исправлен. Надеюсь это была последняя проблема.

2023-02-16 05:24 UTC, Morb0 approved these changes

2023-02-16 08:31 UTC, merged