Минорные переводы
space-syndicate/space-station-14 pull request #828
Opened 2023-02-14 21:37 UTC by ficcialfaint

## Описание PR

Переводит некоторые незначительные блоки текста и исправляет ошибки в переводах.
**Медиа**

**Проверки**

- [X] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [X] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [X] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: ficcialfaint
- add: Добавлены переводы

2023-02-14 21:41 UTC, lapatison commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/effects/explosion_light.ftl
> +ent-ExplosionLight = свет от взрыва
```suggestion
ent-ExplosionLight = вспышка взрыва
```

2023-02-14 21:43 UTC, lapatison commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/weapons/throwable/clusterbang.ftl
> +    .desc = Может быть использовано только со светошумовыми гранатами. Взрывается несколько раз.
задвоилось описание

2023-02-14 21:44 UTC, lapatison commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/weapons/throwable/clusterbang.ftl
> +ent-ClusterBang = кластерный взрыв
Фактически это кластерная светошумовая граната.
другие варианты перевода названия?

2023-02-14 23:11 UTC, Morb0 commented
@lapatison Сделай апрув если все норм

2023-02-14 23:27 UTC, Morb0 requested changes

2023-02-14 23:27 UTC, Morb0 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/debugging/spanisharmyknife.ftl
> +    .desc = Боль от его использования слишком высока, чтобы её вынести.
`almost` утерян
```suggestion
    .desc = Боль от его использования почти невыносима.
```

2023-02-14 23:27 UTC, Morb0 commented on Resources/Locale/ru-RU/decals/decal-window.ftl
> +decal-placer-window-zindex = Нарисовать глубину
```suggestion
decal-placer-window-zindex = С глубиной
```

2023-02-14 23:27 UTC, Morb0 commented on Resources/Locale/ru-RU/decals/decal-window.ftl
> +decal-placer-window-enable-snap = Привязать к плитке
```suggestion
decal-placer-window-enable-snap = Привязка к тайлу
```

2023-02-14 23:27 UTC, Morb0 commented on Resources/Locale/ru-RU/job/department-desc.ftl
> +department-Civilian-description = Выполняйте небольшие полезные задания, чтобы поддерживать станцию в нормальном состоянии.
```suggestion
department-Civilian-description = Выполняйте небольшие полезные задания для поддержания нормальной работы станции.
```

2023-02-14 23:27 UTC, Morb0 commented on Resources/Locale/ru-RU/damage/damage-command.ftl
> +damage-command-description = Добавить или убрат урон сущности.
```suggestion
damage-command-description = Добавить или убрать урон сущности.
```

2023-02-14 23:27 UTC, Morb0 commented on Resources/Locale/ru-RU/damage/damage-command.ftl
> +damage-command-error-type = { $arg } неправильная группа урона или типом.
```suggestion
damage-command-error-type = { $arg } неправильная группа или тип урона.
```

2023-02-14 23:27 UTC, Morb0 commented on Resources/Locale/ru-RU/administration/ui/admin-spawn-explosion-eui.ftl
> +admin-explosion-eui-title = Заспавнить взрывы
```suggestion
admin-explosion-eui-title = Создание взрывов
```

2023-02-14 23:27 UTC, Morb0 commented on Resources/Locale/ru-RU/administration/ui/admin-spawn-explosion-eui.ftl
>  admin-explosion-eui-label-ymap = Y (Map)
```suggestion
admin-explosion-eui-label-xmap = X (Карты)
admin-explosion-eui-label-ymap = Y (Карты)
```

2023-02-14 23:27 UTC, Morb0 commented on Resources/Locale/ru-RU/administration/ui/admin-spawn-explosion-eui.ftl
> +admin-explosion-eui-label-max = Максимальная интенсивность
Уверен такой текст не взлезет в UI
```suggestion
admin-explosion-eui-label-max = Макс интенсивность
```

2023-02-14 23:27 UTC, Morb0 commented on Resources/Locale/ru-RU/administration/commands/play-global-sound-command.ftl
> +play-global-sound-command-description = Проигрывает глобальный звук для выбранного игрока или для каждого подключенного игрока, если игрок не выбран.
```suggestion
play-global-sound-command-description = Проигрывает глобальный звук для выбранного игрока или для каждого подключенного игрока, если не выбран конкретный.
```

2023-02-14 23:40 UTC, lapatison commented
> @lapatison Сделай апрув если все норм

1. как
2. кажется вы тут уже порешали

2023-02-14 23:55 UTC, Morb0 commented
> > @lapatison Сделай апрув если все норм
> 
> 1. как
> 2. кажется вы тут уже порешали

![image](https://user-images.githubusercontent.com/14136326/218890093-cb0816ed-c5f9-4263-a014-998bc7e9f3d3.png)

2023-02-15 00:23 UTC, lapatison commented on Resources/Locale/ru-RU/prototypes/gas-tanks.ftl
>  ent-red-oxygen-tank = { ent-oxygen-tank }
Тут что-то не так
Красный баллон это азот

2023-02-15 06:10 UTC, ficcialfaint commented on Resources/Locale/ru-RU/prototypes/gas-tanks.ftl
>  ent-red-oxygen-tank = { ent-oxygen-tank }
исправил

2023-02-15 17:29 UTC, Morb0 commented on Resources/Locale/ru-RU/prototypes/gas-tanks.ftl
>  ent-red-oxygen-tank = { ent-oxygen-tank }
Он не используется, но существует в англ версии как пример перевода прототипов.
Удалить его нельзя, так как скрипт его вернет.
Просто оставь как в оригинале, то есть `кислородом`, это ни на что не повлияет.

2023-02-15 17:32 UTC, lapatison commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/weapons/throwable/clusterbang.ftl
> +    .desc = Может быть использовано только со светошумовыми гранатами. Взрывается несколько раз.
Длинно
Есть другие варианты?

2023-02-15 18:03 UTC, ficcialfaint commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/weapons/throwable/clusterbang.ftl
> +    .desc = Может быть использовано только со светошумовыми гранатами. Взрывается несколько раз.
`Используется только со светошумовыми гранатами. Взрывается пару раз.` Как насчёт этого?

2023-02-15 23:41 UTC, Morb0 approved these changes

2023-02-16 00:09 UTC, merged