Tips and Fortunes locale
space-syndicate/space-station-14 pull request #829
Opened 2023-02-14 23:31 UTC by lapatison

## Описание PR

**Медиа**

**Проверки**

- [X] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [X] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [X] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [X] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: lapatison, Myakot
- add: Переведены советы
- add: Переведены предсказания из печений

2023-02-14 23:54 UTC, Morb0 requested changes

2023-02-14 23:54 UTC, Morb0 commented on Resources/Prototypes/Datasets/Names/fortunes.yml
> +  - Никогда не доверяй персоне без униформы
Просто униформы или одежды?
```suggestion
  - Никогда не доверяй персоне без униформы.
```

2023-02-14 23:54 UTC, Morb0 commented on Resources/Prototypes/Datasets/Names/fortunes.yml
> +  - Аллан, добавь деталей
```suggestion
  - Алан, пожалуйста добавь деталей.
```

2023-02-14 23:54 UTC, Morb0 commented on Resources/Prototypes/Datasets/Names/fortunes.yml
> +  - На этой смене вы ТАК заробастите, что услышат даже на ЦК.
```suggestion
  - На этой смене вы покажите им всем какой вы робаст.
```

2023-02-15 00:17 UTC, lapatison commented on Resources/Prototypes/Datasets/Names/fortunes.yml
> +  - Аллан, добавь деталей
Одежды, fixed

2023-02-15 00:17 UTC, lapatison commented on Resources/Prototypes/Datasets/Names/fortunes.yml
> +  - Никогда не доверяй персоне без униформы
одежды fixed

2023-02-15 00:18 UTC, lapatison commented on Resources/Prototypes/Datasets/Names/fortunes.yml
> +  - Аллан, добавь деталей
fixed но без точки, неформальная рабочая записка

2023-02-15 00:21 UTC, Morb0 requested changes

2023-02-15 00:21 UTC, Morb0 commented on Resources/Prototypes/Datasets/tips.yml
> +  - "Убирайте лужи и переливайте их в другие ёмкости, чтобы сохранить вещества, находившиеся в луже."
```suggestion
  - "Убирайте лужи и выжимайте их в другие ёмкости, чтобы собрать вещества находившиеся в луже."
```

2023-02-15 00:21 UTC, Morb0 commented on Resources/Prototypes/Datasets/tips.yml
> +  - "Взведенные мышеловки невероятно эффективны для борьбы со всеми видами маленьких мобов — в том числе и с крысиными слугами."
```suggestion
  - "Взведенные мышеловки невероятно эффективны для борьбы со всеми видами маленьких существ — в том числе и с крысиными слугами."
```

2023-02-15 00:21 UTC, Morb0 commented on Resources/Prototypes/Datasets/tips.yml
> +  - "Используйте кнопку Использовать предмет в мире (клавиша Е по умолчанию) чтобы взаимодействовать с объектами, если у вас заняты руки или вам не хочется их в руки брать."
```suggestion
  - "Используйте кнопку Использовать предмет в мире (клавиша Е по умолчанию) чтобы взаимодействовать с объектами, если вам не хочется их брать в руки или у вас они заняты."
```

2023-02-15 00:21 UTC, Morb0 commented on Resources/Prototypes/Datasets/tips.yml
> +  - "В крайнем случае, для перемещения в космосе можно использовать метание предметов и стрельбу из оружия, включая протокинетические ускорители."
```suggestion
  - "В крайнем случае, перемещаться в космосе можно метая предметы или стреляя из оружия, включая протокинетический ускоритель."
```

2023-02-15 00:21 UTC, Morb0 commented on Resources/Prototypes/Datasets/tips.yml
> +  - "Как сотрудник службы безопасности, помните, что После не значит Вследствие. Возможно кто-то просто оказался не в том месте и не в то время!"
Вообще не понятно, даже сейчас
`что После не значит Вследствие`

2023-02-15 00:21 UTC, Morb0 commented on Resources/Prototypes/Datasets/tips.yml
> +  - "Будучи мимом помните, что ваш обет молчания - источник вашей силы. Нарушив его, вы лишитесь своих сил и чести."
М?
```suggestion
  - "Будучи мимом помните, что ваш обет молчания - источник вашей силы. Нарушив его, вы лишитесь своих сил... и чести."
```

2023-02-15 00:21 UTC, Morb0 commented on Resources/Prototypes/Datasets/tips.yml
> +  - "Будучи адвокатом, если наказание кажется вам слишком суровым, попытайтесь обсудить это со смотрителем."
Нужно, что-то более нейтральное из-за отсутствия такового.
```suggestion
  - "Занимаясь судебным делом, если наказание кажется вам слишком суровым, попытайтесь обсудить это со смотрителем."
```

2023-02-15 00:21 UTC, Morb0 commented on Resources/Prototypes/Datasets/tips.yml
> +  - "Будучи капитаном, всегда носите с собой диск ядерной аутентификации и поисковый навигатор. Неплохим вариантом будет передать одно из них другому главе, которому вы можете доверить их сохранность
поисковый навигатор - один - его
```suggestion
  - "Будучи капитаном, всегда носите с собой диск ядерной аутентификации и поисковый навигатор. Неплохим вариантом будет передать один из них другому главе, которому вы можете доверить его сохранность."
```

2023-02-15 00:33 UTC, lapatison commented on Resources/Prototypes/Datasets/tips.yml
> +  - "Как сотрудник службы безопасности, помните, что После не значит Вследствие. Возможно кто-то просто оказался не в том месте и не в то время!"
`Корреляция не означает причинно-следственную связь\следствие` ?

2023-02-15 00:39 UTC, lapatison commented on Resources/Prototypes/Datasets/tips.yml
> +  - "Как сотрудник службы безопасности, помните, что После не значит Вследствие. Возможно кто-то просто оказался не в том месте и не в то время!"
`подозрений мало для обвинений` ?

2023-02-15 00:47 UTC, Morb0 commented on Resources/Prototypes/Datasets/tips.yml
> +  - "Как сотрудник службы безопасности, помните, что После не значит Вследствие. Возможно кто-то просто оказался не в том месте и не в то время!"
Последнее неплохо

2023-02-15 00:57 UTC, Morb0 approved these changes

2023-02-15 01:06 UTC, merged