[Resprite] Ammo machine redisign
space-syndicate/space-station-14 pull request #873
Opened 2023-03-11 08:30 UTC by SonicHDC

## Описание PR

Изменяет автоматы чисто визуально
**Медиа**

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: SonicDC
- tweak: Изменены спрайты автомата с патронами!

2023-03-11 09:55 UTC, lapatison commented on Resources/Textures/Structures/Machines/VendingMachines/ammo.rsi/meta.json
> +  "copyright": "Resprited by SonicDC"
Старый копирайт тоже оставь, чтобы было ясно, респрайт чего это.

2023-03-11 22:54 UTC, SonicHDC commented on Resources/Textures/Structures/Machines/VendingMachines/ammo.rsi/meta.json
> +  "copyright": "Resprited by SonicDC"
Хорошо

2023-03-15 08:12 UTC, Morb0 requested changes
Я бы оставил старый спрайт, можешь просто этот выделить в папку Resources/Textures/Corvax/Structures/Machines/VendingMachines/ammo.rsi?
Если сложно слишком, я сам сделаю.

2023-03-15 21:19 UTC, SonicHDC commented
> Я бы оставил старый спрайт, можешь просто этот выделить в папку Resources/Textures/Corvax/Structures/Machines/VendingMachines/ammo.rsi?
> Если сложно слишком, я сам сделаю.

Не отказался бы от помощи

2023-03-16 22:24 UTC, Morb0 requested changes
Хорошо, теперь нужно поменять путь до спрайта у `VendingMachineAmmo`.
Это в файле `Resources\Prototypes\Entities\Structures\Machines\vending_machines.yml`
изменить у `- type: Sprite` `sprite` на `Corvax\Structures/Machines/VendingMachines/ammo.rsi`

2023-03-16 22:25 UTC, Morb0 requested changes
Опечатка в пути новом со спрайтом, должно быть `Structures` а сейчас `Strucrures`
Нужно переименовать папку

2023-03-17 04:16 UTC, Morb0 requested changes
Переименуй `meta.json.txt` в `meta.json`

2023-03-17 08:12 UTC, SonicHDC commented
Надеюсь это всё

2023-03-17 08:13 UTC, Morb0 approved these changes

2023-03-17 11:43 UTC, merged