[Resprite] аммунация
space-syndicate/space-station-14 pull request #879
Opened 2023-03-15 08:53 UTC by nomad0260

## Описание PR

Добавляет уникальные спрайты каждому патрону а так же уникальную остреленную гильзу под калибр и тип патрона
**Медиа**

![Screenshot_758](https://user-images.githubusercontent.com/110369449/225256005-e51ce0fa-c5fe-41ea-bc68-4c21a8e251c7.png)
![Screenshot_752](https://user-images.githubusercontent.com/110369449/225256039-c53e68e3-cb26-4048-aad5-f7cf71643581.png)

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: no_mad
- add: Добавлены уникальные спрайты каждому типу боеприпаса
- tweak: Изменены спрайты спидлоадеров

2023-03-16 22:21 UTC, Morb0 requested changes
Много файлов с изменениями, хотя там 1 строка изменений.

2023-03-16 22:22 UTC, Morb0 requested changes

2023-03-17 01:37 UTC, nomad0260 commented on Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Cartridges/antimaterial.yml
> +    - state: base
Стейт и не нужно менять, я когда делал, забыл что у 60 калибра и так был свой спрайт патрона и отстреленный его вариант, поэтому просто заменил их в текстурах. А насчёт файла, я просто скопировал их отдельно когда делал ну и закинул с основой когда доделал

2023-03-17 08:57 UTC, LarryRussian commented
Гильзы большие.

2023-03-17 10:30 UTC, Morb0 commented
Мне не нравится такое количество пустых изменений в файлах и нужно вынести эти спрайты в отдельную папку.
Если самому сложно, потом займусь этим.

2023-03-17 10:33 UTC, nomad0260 commented
Спрайты вынести без проблем, вот только а как откатить эти изменения?

2023-03-17 10:53 UTC, nomad0260 commented
Как откатывать я в душе не ебу, но вроде сделал как ты просил, на локалке проверил

2023-05-05 07:45 UTC, ficcialfaint commented
Переоткрой, когда вернешься к ПРу

2023-05-05 07:45 UTC, closed without merging