Переводы и ещё раз переводы
space-syndicate/space-station-14 pull request #886
Opened 2023-03-15 20:46 UTC by ficcialfaint

## Описание PR

**Медиа**

**Проверки**

- [] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [X] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [X] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:
- add: Добавлены переводы

2023-03-15 21:08 UTC, Morb0 requested changes

2023-03-15 21:08 UTC, Morb0 commented on Content.Client/Hands/UI/HandVirtualItemStatus.xaml
> +    <Label StyleClasses="ItemStatus" Text="Занято" />
Выдели во fluent строку по примеру как это сделано в уже существующих интерфейсах
Круто если сделаешь PR в upstream с поддержкой перевода

2023-03-15 21:08 UTC, Morb0 commented on Resources/Locale/ru-RU/escape-menu/ui/options-menu.ftl
> +    приводит к чётким текстурам, это часто означает, что вверху/внизу экрана будут
```suggestion
    приводит к чётким текстурам, это часто означает, что сверху/снизу экрана будут
```

2023-03-15 21:09 UTC, ficcialfaint commented on Content.Client/Hands/UI/HandVirtualItemStatus.xaml
> +    <Label StyleClasses="ItemStatus" Text="Занято" />
А оно в .xaml будет также работать, как и в C#, т.е. Loc.GetString()?
Я изначально, кстати, и хотел сделать PR официалом, но не думал, что так можно будет

2023-03-15 21:17 UTC, Morb0 commented on Content.Client/Hands/UI/HandVirtualItemStatus.xaml
> +    <Label StyleClasses="ItemStatus" Text="Занято" />
Я поэтому и говорю посмотреть как сделано в других UI.
Вот пример атрибута с локализацией `Title="{Loc sandbox-window-title}"`

2023-03-15 21:18 UTC, ficcialfaint commented on Content.Client/Hands/UI/HandVirtualItemStatus.xaml
> +    <Label StyleClasses="ItemStatus" Text="Занято" />
А, спасибо, мне тогда щас отменить это изменение и сделать PR офам?

2023-03-15 21:37 UTC, Morb0 commented on Content.Client/Hands/UI/HandVirtualItemStatus.xaml
> +    <Label StyleClasses="ItemStatus" Text="Занято" />
Да

2023-03-16 21:34 UTC, Morb0 approved these changes

2023-03-16 22:06 UTC, merged