[Jobs] Promote QM
space-syndicate/space-station-14 pull request #910
Opened 2023-03-23 07:15 UTC by nomad0260

## Описание PR

Изменяет supervision квартирмейстера с главы персонала на капитана, ибо КМ в нынешний момент является отдельным главой
**Медиа**

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: no_mad
- tweak: Изменен начальник квартирмейстера с ГП на капитана

2023-03-23 07:18 UTC, Morb0 requested changes

2023-03-23 07:18 UTC, Morb0 commented on Resources/Prototypes/Roles/Jobs/Cargo/quartermaster.yml
> +  supervisors: job-supervisors-captain #corvax-hierarchy
Потом же не найти ничего
```suggestion
  supervisors: job-supervisors-captain # Corvax-Hierarchy
```

И это лучше сделать в апстрим

2023-03-23 07:28 UTC, nomad0260 commented on Resources/Prototypes/Roles/Jobs/Cargo/quartermaster.yml
> +  supervisors: job-supervisors-captain #corvax-hierarchy
У них разве тоже км глава отдельный?

2023-03-26 19:17 UTC, Morb0 commented
В офф

2023-03-26 19:17 UTC, closed without merging