[Clothing] Плащ и маска моли
space-syndicate/space-station-14 pull request #916
Opened 2023-03-24 20:51 UTC by PuroSlavKing

## Описание PR

Добавляет плащ и маску моли, маска надевается при помощи иконки в хотбаре при наличии плаща моли на плечах, или как отдельный энтити маски. Маска моли скрывает личность, при отсутствии ID карты в слоте.

**Медиа**

![MothRep1](https://user-images.githubusercontent.com/103608145/227636758-24529272-a1b1-43d0-a248-de25a28daf9a.png)
![MothRep2](https://user-images.githubusercontent.com/103608145/227636805-e192341f-341e-4fb2-ac4b-bb8434b37dfb.png)

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: PuroSlavKing
- add: Добавлен плащ моли.
- add: Добавлена маска моли.
- add: Добавлено веселье.

2023-03-24 21:13 UTC, PuroSlavKing commented
![image](https://user-images.githubusercontent.com/103608145/227642713-5abc3158-3d64-48c6-add7-51aacbc95b46.png)
![image](https://user-images.githubusercontent.com/103608145/227642731-e206cfc3-1f50-42bc-99fe-cf65d92afc16.png)
![image](https://user-images.githubusercontent.com/103608145/227642749-f37a68c5-13fa-45f3-89af-8721d44f842d.png)

2023-03-25 07:10 UTC, LarryRussian commented
Тебе следует размещать файлы по пути:
/[Resources](https://github.com/space-syndicate/space-station-14/tree/master/Resources)/[Textures](https://github.com/space-syndicate/space-station-14/tree/master/Resources/Textures)/Corvax/
А также:
/[Resources](https://github.com/space-syndicate/space-station-14/tree/master/Resources)/[Prototypes](https://github.com/space-syndicate/space-station-14/tree/master/Resources/Prototypes)/Corvax/

2023-03-25 10:11 UTC, PuroSlavKing commented
> Тебе следует размещать файлы по пути: /[Resources](https://github.com/space-syndicate/space-station-14/tree/master/Resources)/[Textures](https://github.com/space-syndicate/space-station-14/tree/master/Resources/Textures)/Corvax/ А также: /[Resources](https://github.com/space-syndicate/space-station-14/tree/master/Resources)/[Prototypes](https://github.com/space-syndicate/space-station-14/tree/master/Resources/Prototypes)/Corvax/

вроде поменял, проверь правильно ли

2023-03-25 11:02 UTC, ficcialfaint commented on Resources/Prototypes/Corvax/Entities/Clothing/Head/hoods.yml
> +  description: A mask in the form of a moths head is usually made of lightweight materials. It mimics the shape of a moths head with large eyes and long antennae. Such masks are often used in cosplay
```suggestion
  description: A mask in the form of a moth's head is usually made of lightweight materials. It mimics the shape of a moth's head with large eyes and long antennae. Such masks are often used in cosplay, or when shooting movies and videos.
```

2023-03-25 16:56 UTC, LarryRussian commented
Ты будешь большим молодцом, если добавишь файлы локализации сюда.
https://github.com/space-syndicate/space-station-14/tree/master/Resources/Locale

2023-03-25 17:01 UTC, LarryRussian commented on Resources/Textures/Corvax/Clothing/Neck/Cloaks/moth.rsi/meta.json
> +  "copyright": "Created by Puro#7768",
Тоже самое.

2023-03-25 17:01 UTC, LarryRussian commented on Resources/Textures/Corvax/Clothing/Head/hoods/moth.rsi/meta.json
> +  "copyright": "Created by Puro#7768",
Это не твои спрайты, ты их обрезал, но создали их в SS13, вроде как на TG.

2023-03-25 17:04 UTC, LarryRussian requested changes
Это не твои спрайты, ты их обрезал, но создали их в SS13, вроде как на TG.

2023-03-25 17:26 UTC, PuroSlavKing commented on Resources/Textures/Corvax/Clothing/Head/hoods/moth.rsi/meta.json
> +  "copyright": "Created by Puro#7768",
спрайт моли, с которого я срисовывал - вики ss220. Я предал другие оттенки некоторым частям, и поменял их форму, на более приятную по моему мнению, или такое тоже нужно указывать?

2023-03-25 17:44 UTC, ficcialfaint commented
Вроде надо ссылку не на репо писать, а на комит с последним изменением спрайта/текстуры

2023-03-25 18:46 UTC, LarryRussian commented on Resources/Textures/Corvax/Clothing/Head/hoods/moth.rsi/meta.json
> +  "copyright": "Created by Puro#7768",
Если ты имеешь в виду Парадайс, то они взяли из TG. Укажи 2-ого автора.

2023-03-25 20:55 UTC, PuroSlavKing commented on Resources/Textures/Corvax/Clothing/Head/hoods/moth.rsi/meta.json
> +  "copyright": "Created by Puro#7768",
> Если ты имеешь в виду Парадайс, то они взяли из TG. Укажи 2-ого автора.

Второго автора? Мне теперь ещё и на гитхабе ТГ рыться, в поисках того кто последний раз лапал молей?

2023-03-26 19:14 UTC, Morb0 commented
К сожалению это теперь в офф

2023-03-26 19:14 UTC, closed without merging