added words to chat filter
space-syndicate/space-station-14 pull request #923
Opened 2023-03-25 17:16 UTC by Serega1997

## Описание PR
добавлены новые слова 

**Проверки**

- [+] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [+] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [+] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [+] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**
:cl:
- add: Добавлены новые слова в чат фильтр

2023-03-25 17:20 UTC, Morb0 requested changes

2023-03-25 17:20 UTC, Morb0 commented on Content.Server/Corvax/ChatFilter/ChatSystem.cs
> +        { "кепа", "капитана" },
Это приемлемо

2023-03-25 17:20 UTC, Morb0 commented on Content.Server/Corvax/ChatFilter/ChatSystem.cs
> +        { "геник", "генератор" },
Дубликат

2023-03-26 15:53 UTC, Serega1997 commented
Поправил

2023-03-26 19:12 UTC, Morb0 approved these changes

2023-03-26 19:12 UTC, merged