Правки перевода
space-syndicate/space-station-14 pull request #939
Opened 2023-03-30 16:30 UTC by lapatison

## Описание PR

**Медиа**

![image](https://user-images.githubusercontent.com/100279397/228911720-c7cec037-8cc3-4ed1-a5ce-9f40cce54a72.png)

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:
- tweak: Исправлены переводы

2023-03-30 17:51 UTC, Morb0 requested changes

2023-03-30 17:51 UTC, Morb0 commented on Resources/Locale/ru-RU/medical/components/crew-monitoring-component.ftl
> +crew-monitoring-user-interface-location = Коорд.
Возможно лучше расширить интерфейс, вот тут:
https://github.com/space-syndicate/space-station-14/blob/6107f2ce4987c88a9e6a6b349918749c529f6ddc/Content.Client/Medical/CrewMonitoring/CrewMonitoringWindow.xaml#L4

2023-03-30 18:28 UTC, lapatison commented on Resources/Locale/ru-RU/medical/components/crew-monitoring-component.ftl
> +crew-monitoring-user-interface-location = Коорд.
Тут нацеленность на другое, пустое место после координат, его прям оч много
![image](https://user-images.githubusercontent.com/100279397/228929875-106b1030-3e75-4709-aa42-0aca3cb5424a.png)

2023-03-31 05:26 UTC, Morb0 commented on Resources/Locale/ru-RU/medical/components/crew-monitoring-component.ftl
> +crew-monitoring-user-interface-location = Коорд.
Может тогда `Позиция`?

2023-03-31 11:26 UTC, lapatison commented on Resources/Locale/ru-RU/medical/components/crew-monitoring-component.ftl
> +crew-monitoring-user-interface-location = Коорд.
+

2023-03-31 13:09 UTC, Morb0 approved these changes

2023-03-31 13:10 UTC, merged