[Add] Chief Engineer's Bags
space-syndicate/space-station-14 pull request #995
Opened 2023-04-16 11:16 UTC by JerryImMouse

## Описание PR

Добавил рюкзак, вещмешок, сумку для СИ. У них увеличенный объем хранения на 50 единиц.
**Медиа**

![image](https://user-images.githubusercontent.com/48524572/232305575-eebc917d-ca66-44e7-858b-4dbef52cb8f1.png)
![image](https://user-images.githubusercontent.com/48524572/232305580-f5f6250d-4ca7-4bfe-9ed9-c232abfa89e4.png)
![image](https://user-images.githubusercontent.com/48524572/232305582-51311727-1ac5-4040-a662-75e450ba09bf.png)
![image](https://user-images.githubusercontent.com/48524572/232305590-25516654-c942-4f90-8c27-23f1b296bef1.png)
![image](https://user-images.githubusercontent.com/48524572/232305592-888b6b55-ea97-4336-bd87-795a12751bb0.png)

**Проверки**

- [X] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [X] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [X] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [X] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: JerryImMouse
- add: Вещмешок для СИ
- add: Рюкзак для СИ
- add: Сумка для СИ

2023-04-16 11:16 UTC, JerryImMouse commented
УРА! СЛАВА МОРТИ!

2023-04-16 11:17 UTC, SonicHDC commented
Не закрывай ты пр. Лучше код подправь в своём форке в нужной ветке.

2023-04-16 11:24 UTC, lzk228 commented
в вещмешке больше места чем в вещмешке оперативников, это явный имбаланс

2023-04-16 11:42 UTC, Morb0 requested changes
Все новые прототипы, спрайты и переводы нужно вынести в Corvax папки соответственно.
Например:
`Resources/Prototypes/Entities/Clothing/Back/backpacks.yml` => `Resources/Prototypes/Corvax/Entities/Clothing/Back/backpacks.yml`

Статы у всех должны быть стандартные, как инженерский.

2023-04-16 13:19 UTC, Morb0 requested changes

2023-04-16 13:19 UTC, Morb0 commented on Resources/Prototypes/Catalog/Fills/Backpacks/StarterGear/backpack.yml
> -      #- id: TelescopicBaton
То что было убирать не нужно, просто сделай `parent: ClothingBackpackCE # Corvax-Resprite`

2023-04-16 13:22 UTC, JerryImMouse commented on Resources/Prototypes/Catalog/Fills/Backpacks/StarterGear/backpack.yml
> -      #- id: TelescopicBaton
Понял, секунду

2023-04-16 13:22 UTC, JerryImMouse commented on Resources/Prototypes/Catalog/Fills/Backpacks/StarterGear/backpack.yml
> -      #- id: TelescopicBaton
Только в этом файле или по всем так сделать?

2023-04-16 13:32 UTC, Morb0 commented on Resources/Prototypes/Catalog/Fills/Backpacks/StarterGear/backpack.yml
> -      #- id: TelescopicBaton
По всем видам сумок

2023-04-16 13:40 UTC, JerryImMouse commented
Не совсем понял, но вроде это от меня требуется

2023-04-16 14:00 UTC, Morb0 requested changes

2023-04-16 14:00 UTC, Morb0 commented on Resources/Prototypes/Catalog/Fills/Backpacks/StarterGear/backpack.yml
> +  parent: ClothingBackpackCE #Corvax-Resprite
Просто скопируй то как я показал, с **пробелами**
```suggestion
  parent: ClothingBackpackCE # Corvax-Resprite
```

2023-04-16 14:05 UTC, JerryImMouse commented on Resources/Prototypes/Catalog/Fills/Backpacks/StarterGear/backpack.yml
> +  parent: ClothingBackpackCE #Corvax-Resprite
Вроде готово

2023-04-16 14:24 UTC, JerryImMouse commented
Пробелы поставил, строки вернул

2023-04-17 13:34 UTC, ficcialfaint commented
в ченджлоге должен быть глагол, например:
**ПЛОХО:** `add: вещмешок для СИ`
**ХОРОШО:** `add: Добавлен вещмешок для СИ`

2023-04-17 14:00 UTC, lapatison commented on Resources/Textures/Corvax/Back/Backpacks/ce.rsi/meta.json
> +  "copyright": "JerryTheMouse#8561",
```suggestion
  "copyright": "Discord: JerryTheMouse#8561",
```
Неясно о чём именно речь, хотя бы так, и в остальных укажи.

2023-04-17 14:31 UTC, JerryImMouse commented on Resources/Textures/Corvax/Back/Backpacks/ce.rsi/meta.json
> +  "copyright": "JerryTheMouse#8561",
Кхм, да хрен с ним, я уже устал от этого ПРа

2023-04-19 07:21 UTC, Morb0 approved these changes

2023-04-19 07:22 UTC, merged